Repository transmission/transmission, pull requests merged in 2020-07, with the labels that each got.

#1370 chore: fix deprecation warnings of GTK_STOCK_ use.
  gtk/actions.c
  gtk/details.c
  gtk/dialogs.c
  gtk/filter.c
  gtk/main.c
  gtk/makemeta-ui.c
  gtk/msgwin.c
  gtk/open-dialog.c
  gtk/relocate.c
  gtk/stats.c
  gtk/tr-prefs.c
Labels: comp:gtk

#1372 fix: type deduction error introduced in 00be8d0
  qt/Prefs.cc
  qt/Session.cc
  qt/VariantHelpers.h
Labels: comp:qt

#1373 refactor: reuse one QRequestHeader across requests
  qt/RpcClient.cc
  qt/RpcClient.h
Labels: comp:qt

#1374 feat: add 'transfer.complete' notification hint on XDG desktop notifications
  gtk/actions.c
  gtk/notify.c
  qt/Application.cc
Labels: comp:gtk, comp:qt

#922 Allow the operating system to set the size of the listen queue connection backlog.
  libtransmission/net.c
Labels: comp:core, enhancement

#1376 fix: ensure details dialog is updated on selection
  qt/DetailsDialog.cc
  qt/DetailsDialog.h
  qt/RpcQueue.cc
  qt/RpcQueue.h
  qt/Session.cc
  qt/Session.h
Labels: comp:qt

#1378 fix: qt client memory leaks
  qt/MainWindow.cc
  qt/MainWindow.h
  qt/WatchDir.cc
  qt/WatchDir.h
Labels: comp:qt

#1380 Fix or silence gtk warnings
  gtk/CMakeLists.txt
  gtk/actions.c
  gtk/details.c
  gtk/file-list.c
Labels: comp:gtk
