Repository transmission/transmission, pull requests merged in 2021-12, with the labels that each got.

#2253 refactor: getPeersToClose() returns a std::vector
  libtransmission/peer-mgr.cc
Labels: scope:core, type:refactor

#2255 test: add regression tests for transmission-show
  tests/CMakeLists.txt
  tests/utils/CMakeLists.txt
  tests/utils/assets/Inner_Sanctum_movie_archive.show
  tests/utils/assets/Inner_Sanctum_movie_archive.torrent
  tests/utils/assets/Thor_and_the_Amazon_Women.avi.show
  tests/utils/assets/Thor_and_the_Amazon_Women.avi.torrent
  tests/utils/assets/ubuntu-20.04.3-desktop-amd64.iso.show
  tests/utils/assets/ubuntu-20.04.3-desktop-amd64.iso.torrent
  tests/utils/run_transmission_show.cmake
  utils/show.cc
Labels: scope:show, type:fix, type:test

#2258 chore: update caniuse in web/
  web/public_html/transmission-app.js
  web/yarn.lock
Labels: scope:web, type:build

#2259 Refactor/use unchecked version of utf8 replace invalid
  libtransmission/utils.cc
Labels: scope:core, type:refactor

#2260 fix: sonarcloud warnings
  gtk/Actions.cc
  gtk/FreeSpaceLabel.cc
  gtk/Notify.cc
  gtk/Session.cc
  gtk/TorrentCellRenderer.cc
  libtransmission/announcer.cc
  libtransmission/file-piece-map.cc
  libtransmission/file-piece-map.h
  libtransmission/peer-mgr.cc
  libtransmission/peer-mgr.h
  libtransmission/peer-msgs.cc
  libtransmission/quark.cc
  libtransmission/resume.cc
  libtransmission/rpcimpl.cc
  libtransmission/session.h
  libtransmission/utils.cc
  libtransmission/variant-json.cc
Labels: scope:gtk, scope:core, type:refactor

#2263 fixup! fix: sonarcloud warnings (#2260)
  libtransmission/resume.cc
Labels: scope:core, type:fixup

#2264 fixup! refactor: use cpputf for utf8 validation and conversion (#2251)
  libtransmission/utils.cc
Labels: scope:core, type:fixup

#2267 refactor: add tr_saveFile()
  cli/cli.cc
  gtk/Session.cc
  libtransmission/torrent-ctor.cc
  libtransmission/torrent.cc
  libtransmission/torrent.h
  libtransmission/transmission.h
  libtransmission/utils.cc
  libtransmission/utils.h
  libtransmission/variant.cc
  tests/libtransmission/metainfo-test.cc
  tests/libtransmission/rename-test.cc
  tests/libtransmission/test-fixtures.h
  tests/libtransmission/utils-test.cc
Labels: scope:core, type:refactor

#2268 Squash consecutive path separators on Windows
  libtransmission/file-win32.cc
Labels: os:windows, scope:core, type:fix

#2270 fix: new warnings
  libtransmission/block-info.h
  libtransmission/torrent.h
  libtransmission/tr-utp.cc
  libtransmission/utils.cc
  libtransmission/variant.cc
  tests/libtransmission/metainfo-test.cc
Labels: scope:core, type:refactor, type:test

#2273 refactor: add tr_torrent::fileCount()
  libtransmission/inout.cc
  libtransmission/resume.cc
  libtransmission/rpcimpl.cc
  libtransmission/torrent.cc
  libtransmission/torrent.h
  libtransmission/transmission.h
  libtransmission/webseed.cc
Labels: scope:core, type:refactor

#2274 refactor: add tr_torrent::file()
  libtransmission/inout.cc
  libtransmission/resume.cc
  libtransmission/torrent.cc
  libtransmission/torrent.h
  libtransmission/transmission.h
  libtransmission/verify.cc
  libtransmission/webseed.cc
Labels: scope:core, type:refactor

#2276 refactor: remove assigned-but-unused tr_info.originalName
  libtransmission/metainfo.cc
  libtransmission/transmission.h
Labels: scope:core, type:refactor

#2277 refactor: add tr_torrentWebseed(), tr_torrentWebseedCount()
  gtk/DetailsDialog.cc
  libtransmission/peer-mgr.cc
  libtransmission/peer-mgr.h
  libtransmission/torrent.cc
  libtransmission/torrent.h
  libtransmission/transmission.h
  libtransmission/webseed.cc
  libtransmission/webseed.h
  macosx/Torrent.mm
Labels: scope:gtk, scope:mac, scope:core, type:refactor

#2275 Reject cancels when fast extension enabled
  libtransmission/peer-msgs.cc
Labels: scope:core, type:fix

#2281 fixup! refactor: make parts of tr file private (#2241)
  gtk/FileList.cc
  libtransmission/resume.cc
Labels: scope:gtk, type:fixup

#2282 refactor: add tr_torrentTrackers()
  gtk/DetailsDialog.cc
  gtk/FilterBar.cc
  gtk/Session.cc
  gtk/TorrentCellRenderer.cc
  libtransmission/announcer.cc
  libtransmission/announcer.h
  libtransmission/file-piece-map.cc
  libtransmission/rpcimpl.cc
  libtransmission/torrent.cc
  libtransmission/torrent.h
  libtransmission/transmission.h
  macosx/Torrent.mm
  macosx/TrackerNode.h
  macosx/TrackerNode.mm
Labels: scope:gtk, scope:mac, scope:core, type:refactor

#2288 Adjust theme icons lookup logic to resemble that of GTK (Qt client)
  qt/DetailsDialog.cc
  qt/DetailsDialog.h
  qt/FilterBar.cc
  qt/IconCache.cc
  qt/IconCache.h
  qt/MainWindow.cc
  qt/MainWindow.h
  qt/TorrentDelegate.cc
Labels: enhancement, scope:qt

#2289 fixup! fix: env var leak in tr_spawn_async() (#2212)
  libtransmission/torrent.cc
Labels: scope:core, type:fixup

#2290 fix: non-portable strftime() fmt string
  libtransmission/torrent.cc
  utils/remote.cc
Labels: scope:remote, scope:core, type:fix

#2291 fix: crash in tr_file_priorities::filePriority()
  libtransmission/torrent.cc
Labels: scope:core, type:fixup

#2292 Fix unbound (and unnecessary) icon cache recursion on theme icon lookup (Qt client)
  qt/IconCache.cc
  qt/MainWindow.cc
Labels: scope:qt, type:fixup

#2293 fix: memleak regressions
  libtransmission/resume.cc
  libtransmission/variant.cc
  libtransmission/webseed.cc
Labels: scope:core, type:fixup

#2294 fixup! refactor: add tr_torrentTrackers() (#2282)
  libtransmission/announcer.cc
  libtransmission/announcer.h
  libtransmission/torrent.cc
  libtransmission/torrent.h
Labels: scope:core, type:fixup

#2296 refactor: remove unused tr torrent.dnd pieces
  libtransmission/torrent.cc
  libtransmission/torrent.h
Labels: scope:core, type:refactor

#2278 Change accent color to match macOS red choice
  macosx/Images/Images.xcassets/Accent Color.colorset/Contents.json
Labels: scope:mac, type:refactor

#2269 [macOS] Update Info window.
  Transmission.xcodeproj/project.pbxproj
  macosx/CMakeLists.txt
  macosx/InfoTabButtonBack.h
  macosx/InfoTabButtonBack.mm
  macosx/InfoTabButtonCell.h
  macosx/InfoTabButtonCell.mm
  macosx/InfoTabMatrix.h
  macosx/InfoTabMatrix.mm
  macosx/InfoWindow.xib
  macosx/InfoWindowController.h
  macosx/InfoWindowController.mm
  macosx/NSImageAdditions.h
  macosx/NSImageAdditions.mm
  macosx/TrackerCell.mm
  macosx/da.lproj/InfoOptionsView.xib
  macosx/de.lproj/InfoOptionsView.xib
  macosx/en.lproj/InfoOptionsView.xib
  macosx/es.lproj/InfoOptionsView.xib
  macosx/fr.lproj/InfoOptionsView.xib
  macosx/it.lproj/InfoOptionsView.xib
  macosx/nl.lproj/InfoOptionsView.xib
  macosx/pt_PT.lproj/InfoOptionsView.xib
  macosx/ru.lproj/InfoOptionsView.xib
  macosx/tr.lproj/InfoOptionsView.xib
Labels: scope:mac, type:refactor

#2304 refactor: tweak qt client about dialog text
  qt/AboutDialog.cc
Labels: scope:qt, type:fix

#2308 refactor: add tr_announce_list
  Transmission.xcodeproj/project.pbxproj
  gtk/DetailsDialog.cc
  libtransmission/CMakeLists.txt
  libtransmission/announce-list.cc
  libtransmission/announce-list.h
  libtransmission/announcer.cc
  libtransmission/announcer.h
  libtransmission/magnet-metainfo.cc
  libtransmission/magnet-metainfo.h
  libtransmission/makemeta.h
  libtransmission/metainfo.cc
  libtransmission/rpcimpl.cc
  libtransmission/torrent-magnet.cc
  libtransmission/torrent.cc
  libtransmission/torrent.h
  libtransmission/transmission.h
  libtransmission/variant.h
  macosx/QuickLookPlugin/GeneratePreviewForURL.mm
  macosx/Torrent.mm
  tests/libtransmission/CMakeLists.txt
  tests/libtransmission/announce-list-test.cc
  tests/libtransmission/magnet-metainfo-test.cc
  tests/libtransmission/makemeta-test.cc
  tests/libtransmission/metainfo-test.cc
  utils/show.cc
Labels: scope:gtk, scope:mac, scope:core, type:refactor

#2285 refactor: make tr_torrentInfo() private
  gtk/DetailsDialog.cc
  gtk/Session.cc
  gtk/TorrentCellRenderer.cc
  libtransmission/rpcimpl.cc
  libtransmission/torrent-magnet.cc
  libtransmission/torrent.cc
  libtransmission/torrent.h
  libtransmission/transmission.h
  macosx/Controller.mm
  macosx/Torrent.mm
Labels: scope:gtk, scope:mac, scope:core, type:refactor

#2312 refactor: make some tr_torrentFoo() methods member functions
  libtransmission/peer-mgr.cc
  libtransmission/peer-msgs.cc
  libtransmission/rpcimpl.cc
  libtransmission/torrent.cc
  libtransmission/torrent.h
  libtransmission/tr-dht.cc
  libtransmission/tr-lpd.cc
Labels: scope:core, type:refactor

#2313 refactor: replace tr_torrentIsSeed() with tr_torrent::isDone()
  libtransmission/announcer.cc
  libtransmission/completion.h
  libtransmission/handshake.cc
  libtransmission/peer-mgr.cc
  libtransmission/peer-msgs.cc
  libtransmission/session.cc
  libtransmission/torrent.cc
  libtransmission/torrent.h
  libtransmission/webseed.cc
  tests/libtransmission/completion-test.cc
Labels: scope:core, type:refactor

#2314 refactor: add tr_info accessors to tr_torrent
  libtransmission/announcer.cc
  libtransmission/completion.h
  libtransmission/inout.cc
  libtransmission/peer-mgr.cc
  libtransmission/peer-msgs.cc
  libtransmission/rpcimpl.cc
  libtransmission/session.cc
  libtransmission/torrent-magnet.cc
  libtransmission/torrent.cc
  libtransmission/torrent.h
  libtransmission/tr-lpd.cc
  libtransmission/verify.cc
  libtransmission/webseed.cc
  tests/libtransmission/move-test.cc
  tests/libtransmission/rename-test.cc
  tests/libtransmission/test-fixtures.h
Labels: scope:core, type:refactor

#2317 refactor: prefer tr_strv*() funcs
  libtransmission/announcer-udp.cc
  libtransmission/error.cc
  libtransmission/error.h
  libtransmission/magnet-metainfo.cc
  libtransmission/makemeta.cc
  libtransmission/metainfo.cc
  libtransmission/rpc-server.cc
  libtransmission/rpcimpl.cc
  libtransmission/rpcimpl.h
  libtransmission/torrent.cc
  libtransmission/tr-macros.h
  libtransmission/utils.cc
  tests/libtransmission/error-test.cc
  tests/libtransmission/file-test.cc
  tests/libtransmission/move-test.cc
  tests/libtransmission/test-fixtures.h
  utils/create.cc
  utils/remote.cc
Labels: scope:core, type:refactor

#2318 refactor: more prefer tr_strv*()
  libtransmission/announcer-udp.cc
  libtransmission/metainfo.cc
  libtransmission/platform.cc
  libtransmission/quark.cc
  libtransmission/torrent.cc
  libtransmission/utils.cc
  tests/libtransmission/rename-test.cc
  tests/libtransmission/test-fixtures.h
Labels: scope:core, type:refactor

#2319 refactor: tr_torrent housekeeping
  libtransmission/announcer.cc
  libtransmission/error.cc
  libtransmission/metainfo.cc
  libtransmission/metainfo.h
  libtransmission/peer-mgr.cc
  libtransmission/peer-msgs.cc
  libtransmission/resume.cc
  libtransmission/rpcimpl.cc
  libtransmission/session.cc
  libtransmission/torrent-magnet.cc
  libtransmission/torrent.cc
  libtransmission/torrent.h
  libtransmission/verify.cc
  libtransmission/webseed.cc
Labels: scope:core, type:refactor

#2320 refactor: more torrent housekeeping
  libtransmission/crypto.h
  libtransmission/file.h
  libtransmission/peer-io.h
  libtransmission/peer-mgr.cc
  libtransmission/peer-msgs.h
  libtransmission/resume.cc
  libtransmission/rpcimpl.cc
  libtransmission/session.h
  libtransmission/torrent-magnet.h
  libtransmission/torrent.cc
  libtransmission/torrent.h
  libtransmission/tr-udp.h
  libtransmission/transmission.h
  libtransmission/verify.cc
  macosx/Torrent.mm
Labels: scope:core, type:refactor

#2322 fix: sonarcloud
  gtk/FileList.cc
  gtk/MainWindow.cc
  gtk/Session.cc
  gtk/TorrentCellRenderer.cc
  gtk/Utils.cc
  libtransmission/announcer-udp.cc
  libtransmission/announcer.cc
  libtransmission/bandwidth.cc
  libtransmission/block-info.cc
  libtransmission/file-win32.cc
  libtransmission/handshake.cc
  libtransmission/inout.cc
  libtransmission/metainfo.cc
  libtransmission/metainfo.h
  libtransmission/net.cc
  libtransmission/peer-mgr.cc
  libtransmission/platform-quota.cc
  libtransmission/platform.cc
  libtransmission/quark.cc
  libtransmission/rpcimpl.cc
  libtransmission/session-id.cc
  libtransmission/session.cc
  libtransmission/torrent.cc
  libtransmission/torrent.h
  libtransmission/utils.h
  libtransmission/verify.cc
  libtransmission/web-utils.h
  libtransmission/web.cc
  libtransmission/webseed.cc
  utils/edit.cc
Labels: scope:gtk, scope:core, type:refactor

#2323 refactor: even more torrent housekeeping
  libtransmission/announcer.cc
  libtransmission/crypto-utils.h
  libtransmission/handshake.cc
  libtransmission/peer-mgr.cc
  libtransmission/peer-msgs.cc
  libtransmission/resume.cc
  libtransmission/rpcimpl.cc
  libtransmission/session.h
  libtransmission/torrent-magnet.cc
  libtransmission/torrent.cc
  libtransmission/torrent.h
  libtransmission/tr-dht.cc
  libtransmission/tr-lpd.cc
Labels: scope:core, type:refactor

#2324 fix: more sonarcloud warnings
  libtransmission/bitfield.cc
  libtransmission/completion.cc
  libtransmission/crypto-utils.cc
  libtransmission/crypto.cc
  libtransmission/error.cc
  libtransmission/fdlimit.cc
  libtransmission/log.cc
  libtransmission/makemeta.cc
  libtransmission/rpcimpl.cc
  libtransmission/session.cc
  libtransmission/subprocess-win32.cc
  libtransmission/torrent.cc
  libtransmission/transmission.h
  libtransmission/utils.cc
  libtransmission/utils.h
  libtransmission/variant-benc.cc
  libtransmission/variant.cc
  libtransmission/web-utils.cc
  libtransmission/web.cc
Labels: scope:core, type:refactor

#2327 fix: sonarcloud
  cli/cli.cc
  daemon/daemon.cc
  utils/create.cc
  utils/edit.cc
  utils/remote.cc
  utils/show.cc
Labels: scope:cli, scope:remote, scope:create, scope:edit, scope:show, type:refactor, type:fixup

#2330 refactor: use tr_sha1_digest_t everywhere
  libtransmission/announcer.cc
  libtransmission/clients.cc
  libtransmission/crypto-utils-ccrypto.cc
  libtransmission/crypto-utils-cyassl.cc
  libtransmission/crypto-utils-fallback.cc
  libtransmission/crypto-utils-openssl.cc
  libtransmission/crypto-utils-polarssl.cc
  libtransmission/crypto-utils.cc
  libtransmission/crypto-utils.h
  libtransmission/crypto.cc
  libtransmission/crypto.h
  libtransmission/handshake.cc
  libtransmission/inout.cc
  libtransmission/magnet-metainfo.cc
  libtransmission/makemeta.cc
  libtransmission/metainfo.cc
  libtransmission/peer-io.cc
  libtransmission/peer-io.h
  libtransmission/peer-mgr.cc
  libtransmission/rpc-server.cc
  libtransmission/session.h
  libtransmission/torrent-magnet.cc
  libtransmission/torrent.cc
  libtransmission/torrent.h
  libtransmission/tr-dht.cc
  libtransmission/tr-macros.h
  libtransmission/transmission.h
  libtransmission/web-utils.cc
  qt/Torrent.h
  tests/libtransmission/crypto-test-ref.h
  tests/libtransmission/crypto-test.cc
  tests/libtransmission/makemeta-test.cc
  tests/libtransmission/peer-msgs-test.cc
  tests/libtransmission/session-test.cc
  utils/show.cc
Labels: scope:qt, scope:core, type:refactor

#2332 refactor: add tr_interned_string
  Transmission.xcodeproj/project.pbxproj
  libtransmission/announce-list.cc
  libtransmission/announce-list.h
  libtransmission/announcer-common.h
  libtransmission/announcer-http.cc
  libtransmission/announcer-udp.cc
  libtransmission/announcer.cc
  libtransmission/announcer.h
  libtransmission/foo
  libtransmission/inout.cc
  libtransmission/interned-string.h
  libtransmission/magnet-metainfo.cc
  libtransmission/peer-common.h
  libtransmission/peer-mgr.cc
  libtransmission/peer-msgs.cc
  libtransmission/quark.h
  libtransmission/resume.cc
  libtransmission/rpcimpl.cc
  libtransmission/torrent-magnet.cc
  libtransmission/torrent.cc
  libtransmission/torrent.h
  libtransmission/transmission.h
  macosx/QuickLookPlugin/GeneratePreviewForURL.mm
  tests/libtransmission/announce-list-test.cc
  tests/libtransmission/rename-test.cc
  tests/libtransmission/test-fixtures.h
  utils/show.cc
Labels: scope:core, type:refactor

#2334 refactor: move tr_ioFindFileLocation() to tr_file_piece_manager
  libtransmission/file-piece-map.cc
  libtransmission/file-piece-map.h
  libtransmission/inout.cc
  libtransmission/inout.h
  libtransmission/torrent.h
  libtransmission/transmission.h
  libtransmission/webseed.cc
  tests/libtransmission/file-piece-map-test.cc
Labels: scope:core, type:refactor

#2335 refactor: take string_view in tr_loadFile(), tr_saveFile()
  libtransmission/announce-list.cc
  libtransmission/announce-list.h
  libtransmission/platform.cc
  libtransmission/resume.cc
  libtransmission/torrent-ctor.cc
  libtransmission/torrent.h
  libtransmission/utils.cc
  libtransmission/utils.h
  libtransmission/variant.cc
  libtransmission/variant.h
Labels: scope:core, type:refactor

#2336 refactor: further decouple tr_torrent and tr_info
  libtransmission/announcer.cc
  libtransmission/handshake.cc
  libtransmission/peer-mgr.cc
  libtransmission/peer-msgs.cc
  libtransmission/resume.cc
  libtransmission/rpcimpl.cc
  libtransmission/session.cc
  libtransmission/torrent-magnet.cc
  libtransmission/torrent.cc
  libtransmission/torrent.h
  libtransmission/tr-dht.cc
  libtransmission/tr-lpd.cc
  tests/libtransmission/rename-test.cc
Labels: scope:core, type:refactor

#2337 refactor: change tr torrent new() args
  cli/cli.cc
  daemon/daemon.cc
  gtk/OptionsDialog.cc
  gtk/Session.cc
  gtk/Utils.cc
  gtk/Utils.h
  libtransmission/rpcimpl.cc
  libtransmission/session.cc
  libtransmission/torrent.cc
  libtransmission/transmission.h
  macosx/Torrent.mm
  tests/libtransmission/rename-test.cc
  tests/libtransmission/test-fixtures.h
Labels: scope:cli, scope:daemon, scope:gtk, scope:qt, scope:mac, type:refactor

#2338 fix: exit time dtor warnings
  libtransmission/announcer.cc
  libtransmission/interned-string.h
  qt/IconCache.cc
  utils/remote.cc
Labels: scope:remote, scope:qt, type:fixup

#2339 fix: clang warnings
  libtransmission/crypto.cc
  libtransmission/crypto.h
  libtransmission/interned-string.h
  libtransmission/peer-io.cc
  libtransmission/peer-io.h
  tests/libtransmission/crypto-test.cc
Labels: scope:core, type:fixup

#2340 refactor: tr_torrent_metainfo
  Transmission.xcodeproj/project.pbxproj
  libtransmission/CMakeLists.txt
  libtransmission/magnet-metainfo.cc
  libtransmission/magnet-metainfo.h
  libtransmission/torrent-metainfo.cc
  libtransmission/torrent-metainfo.h
  libtransmission/torrent.cc
  libtransmission/tr-dht.cc
  tests/libtransmission/CMakeLists.txt
  tests/libtransmission/magnet-metainfo-test.cc
  tests/libtransmission/torrent-metainfo-test.cc
Labels: scope:core, type:refactor

#2341 refactor: use tr_torrent_metainfo in transmission-show
  libtransmission/block-info.h
  libtransmission/magnet-metainfo.h
  utils/show.cc
Labels: scope:show, type:refactor

#2342 refactor: use tr_torrent_metainfo in transmission-qt
  qt/AddData.cc
  qt/OptionsDialog.cc
  qt/OptionsDialog.h
  qt/Torrent.h
  qt/WatchDir.cc
Labels: scope:qt, type:refactor

#2343 refactor: use tr_torrent_metainfo in mac client
  libtransmission/torrent.cc
  libtransmission/transmission.h
  macosx/Controller.mm
  macosx/DragOverlayWindow.mm
  macosx/QuickLookPlugin/GeneratePreviewForURL.mm
Labels: scope:mac, type:refactor

#2344 refactor: use tr_torrent_metainfo in makemeta tests
  tests/libtransmission/makemeta-test.cc
Labels: type:test

#2345 refactor: use tr_torrent_metainfo in tr ctor
  cli/cli.cc
  daemon/daemon.cc
  gtk/MakeDialog.cc
  gtk/OptionsDialog.cc
  gtk/Session.cc
  libtransmission/metainfo.h
  libtransmission/rpcimpl.cc
  libtransmission/session.cc
  libtransmission/torrent-ctor.cc
  libtransmission/torrent.cc
  libtransmission/torrent.h
  libtransmission/transmission.h
  macosx/Torrent.mm
  tests/libtransmission/metainfo-test.cc
  tests/libtransmission/rename-test.cc
  tests/libtransmission/test-fixtures.h
  tests/libtransmission/torrent-metainfo-test.cc
Labels: scope:cli, scope:daemon, scope:gtk, scope:mac, scope:core, type:refactor

#2346 refactor: remove tr_pieceOffset()
  libtransmission/torrent.cc
  libtransmission/torrent.h
  libtransmission/webseed.cc
Labels: scope:core, type:refactor

#2347 refactor: remove tr_file.offset
  libtransmission/completion.cc
  libtransmission/completion.h
  libtransmission/file-piece-map.h
  libtransmission/torrent.cc
  libtransmission/transmission.h
  tests/libtransmission/completion-test.cc
Labels: scope:core, type:refactor

#2349 refactor: remove tr_file.priv
  libtransmission/metainfo.cc
  libtransmission/metainfo.h
  libtransmission/resume.cc
  libtransmission/torrent.cc
  libtransmission/torrent.h
  libtransmission/transmission.h
  tests/libtransmission/metainfo-test.cc
  tests/libtransmission/rename-test.cc
  tests/libtransmission/torrent-metainfo-test.cc
Labels: scope:core, type:refactor

#2350 fix: sonarcloud warnings
  libtransmission/session.cc
  libtransmission/torrent-metainfo.cc
  libtransmission/torrent.cc
  qt/AddData.cc
  qt/OptionsDialog.cc
  utils/show.cc
Labels: scope:show, scope:qt, type:refactor

#2351 refactor: use std::string in tr_variantToStr()
  daemon/daemon.cc
  gtk/Application.cc
  libtransmission/announce-list.cc
  libtransmission/announcer-http.cc
  libtransmission/announcer.cc
  libtransmission/file.cc
  libtransmission/file.h
  libtransmission/log.cc
  libtransmission/metainfo.cc
  libtransmission/peer-msgs.cc
  libtransmission/torrent-magnet.cc
  libtransmission/torrent-metainfo.cc
  libtransmission/utils.cc
  libtransmission/utils.h
  libtransmission/variant.cc
  libtransmission/variant.h
  qt/RpcClient.cc
  tests/libtransmission/json-test.cc
  tests/libtransmission/variant-test.cc
  utils/remote.cc
Labels: scope:remote, scope:gtk, scope:qt, scope:core, type:refactor

#2352 refactor: don't use varargs in tr_error
  daemon/daemon-posix.cc
  daemon/daemon-win32.cc
  gtk/Utils.cc
  libtransmission/crypto-utils.cc
  libtransmission/error.cc
  libtransmission/error.h
  libtransmission/file-posix.cc
  libtransmission/file-win32.cc
  libtransmission/file.cc
  libtransmission/log.cc
  libtransmission/magnet-metainfo.cc
  libtransmission/metainfo.cc
  libtransmission/subprocess-posix.cc
  libtransmission/subprocess-win32.cc
  libtransmission/torrent-ctor.cc
  libtransmission/torrent-metainfo.cc
  libtransmission/utils.cc
  libtransmission/variant.cc
  macosx/Torrent.mm
  tests/libtransmission/error-test.cc
Labels: scope:remote, scope:qt, scope:core, type:refactor

#2353 fix: sonarcloud warnings
  gtk/Session.cc
  libtransmission/resume.cc
  libtransmission/torrent.cc
  qt/OptionsDialog.cc
  utils/show.cc
Labels: scope:show, scope:gtk, scope:qt, scope:core, type:refactor

#2354 refactor: remove varargs code in tr_sys_file
  daemon/daemon.cc
  libtransmission/announcer-http.cc
  libtransmission/file.cc
  libtransmission/file.h
  libtransmission/log.cc
  libtransmission/utils.cc
  libtransmission/utils.h
  tests/libtransmission/file-test.cc
  tests/libtransmission/utils-test.cc
Labels: scope:daemon, scope:core, type:refactor

#2356 fix: sonarcloud
  cli/cli.cc
  daemon/daemon.cc
  libtransmission/peer-mgr.cc
  libtransmission/peer-mgr.h
  libtransmission/rpcimpl.cc
  utils/create.cc
  utils/remote.cc
  utils/show.cc
  utils/units.h
Labels: scope:cli, scope:daemon, scope:remote, scope:core, type:refactor

#2359 refactor: prefer std::from_chars over strtoul
  libtransmission/utils.cc
  libtransmission/utils.h
  libtransmission/variant-benc.cc
  libtransmission/web-utils.cc
Labels: scope:core, type:fixup

#2360 fix: clear verify_thread before releasing verify mutex lock
  libtransmission/verify.cc
Labels: scope:core, type:fixup

#2364 fix: out-of-bound memory acess sonarcloud warning
  libtransmission/clients.cc
Labels: scope:core, type:fixup
