Repository transmission/transmission, pull requests merged in 2021-11, with the labels that each got.

#2076 fix: crash in capitalizing trackername when no trackername
  qt/FaviconCache.cc
Labels: bug, scope:qt, type:fix

#2077 refactor: add util tr_strvstrip() to strip string_views
  libtransmission/utils.cc
  libtransmission/utils.h
  tests/libtransmission/utils-test.cc
Labels: scope:core, type:refactor

#2078 refactor: tr_urlIsValid*() now takes a std::string_view
  libtransmission/metainfo.cc
  libtransmission/rpc-server.cc
  libtransmission/utils.cc
  libtransmission/utils.h
  tests/libtransmission/utils-test.cc
Labels: scope:core, type:refactor

#2079 feat: new function tr_variantGetStrView()
  libtransmission/variant.cc
  libtransmission/variant.h
  tests/libtransmission/variant-test.cc
Labels: dependencies, type:refactor

#2081 refactor: tr_quark_lookup() takes a std::string_view
  libtransmission/quark.cc
  libtransmission/quark.h
  libtransmission/rpcimpl.cc
  tests/libtransmission/quark-test.cc
Labels: scope:core, type:refactor

#2082 refactor: tr_torrentFindFromHashString() takes a std::string_view
  libtransmission/rpcimpl.cc
  libtransmission/session.h
  libtransmission/torrent.cc
  libtransmission/torrent.h
Labels: scope:core, type:refactor

#2083 feat: add tr_quark_get_string_view()
  gtk/Application.cc
  libtransmission/announcer-http.cc
  libtransmission/peer-mgr.cc
  libtransmission/peer-msgs.cc
  libtransmission/quark.cc
  libtransmission/quark.h
  libtransmission/rpc-server.cc
  libtransmission/variant.cc
  utils/show.cc
Labels: scope:core, type:refactor

#2085 perf: intern the announcer module's URL strings
  libtransmission/announcer-common.h
  libtransmission/announcer-http.cc
  libtransmission/announcer-udp.cc
  libtransmission/announcer.cc
  libtransmission/announcer.h
  libtransmission/torrent.cc
  libtransmission/torrent.h
  libtransmission/transmission.h
  libtransmission/utils.cc
  libtransmission/utils.h
Labels: scope:core, type:perf

#2086 fixup! refactor: remove tr_piece struct (#2059)
  libtransmission/resume.cc
  libtransmission/torrent.cc
  libtransmission/torrent.h
Labels: scope:core, type:perf

#2087 refactor: cppcoreguidelines-init-variables pt. 16
  libtransmission/.clang-tidy
  libtransmission/blocklist.cc
Labels: scope:core, type:refactor

#2088 build: enable more .clang-tidy checks
  libtransmission/.clang-tidy
Labels: scope:core, type:build

#2090 Fix deprecated NSURL to NSString conversion.
  macosx/Controller.mm
Labels: scope:mac, type:refactor

#2069 Qt 6 support
  CMakeLists.txt
  cmake/TrMacros.cmake
  dist/msi/CMakeLists.txt
  dist/msi/components/QtClient.wxs
  qt/Application.cc
  qt/DetailsDialog.cc
  qt/FaviconCache.cc
  qt/FileTreeDelegate.cc
  qt/FileTreeItem.cc
  qt/FileTreeModel.cc
  qt/FilterBarComboBox.cc
  qt/IconCache.cc
  qt/MainWindow.cc
  qt/MainWindow.h
  qt/MakeDialog.cc
  qt/OptionsDialog.cc
  qt/OptionsDialog.h
  qt/PathButton.cc
  qt/Prefs.cc
  qt/RpcQueue.cc
  qt/RpcQueue.h
  qt/Torrent.cc
  qt/Torrent.h
  qt/TorrentDelegate.cc
  qt/TorrentDelegateMin.cc
  qt/TorrentModel.cc
  qt/TorrentModel.h
  qt/TrackerModel.cc
  qt/TrackerModel.h
  qt/Utils.cc
  qt/VariantHelpers.h
Labels: scope:qt, type:feat

#2091 refactor: increase use of tr sha1 digest t
  libtransmission/announcer-common.h
  libtransmission/announcer-http.cc
  libtransmission/announcer-udp.cc
  libtransmission/announcer.cc
  libtransmission/crypto-utils.h
  libtransmission/crypto.cc
  libtransmission/inout.cc
  libtransmission/torrent.cc
  libtransmission/torrent.h
  libtransmission/tr-macros.h
  libtransmission/verify.cc
  libtransmission/web.cc
  libtransmission/web.h
Labels: scope:core, type:refactor

#2096 perf: minor perf improvements
  libtransmission/log.cc
  libtransmission/metainfo.cc
  libtransmission/metainfo.h
  tests/libtransmission/metainfo-test.cc
Labels: scope:core, type:perf

#2098 refactor: c++ify torrent ctor
  libtransmission/torrent-ctor.cc
  tests/libtransmission/metainfo-test.cc
Labels: scope:core, type:refactor

#2099 fix: another piece priority fix
  libtransmission/resume.cc
  libtransmission/torrent.cc
Labels: scope:core, type:fixup

#2097 refactor: prefer string_view over raw char*
  libtransmission/announcer-http.cc
  libtransmission/metainfo.cc
  libtransmission/resume.cc
  libtransmission/rpc-server.cc
  libtransmission/rpcimpl.cc
  libtransmission/torrent.cc
  libtransmission/utils.cc
  libtransmission/utils.h
  libtransmission/variant-benc.cc
  libtransmission/variant-json.cc
Labels: scope:core, type:refactor

#2100 perf: recycle variant tree walking helpers
  libtransmission/variant.cc
Labels: scope:core, type:perf

#2114 fixup! refactor: c++ify torrent ctor (#2098)
  libtransmission/torrent-ctor.cc
Labels: scope:core, type:fixup

#2115 fixup! refactor: remove tr_piece struct (#2059)
  libtransmission/bitfield.cc
  libtransmission/bitfield.h
  libtransmission/peer-msgs.cc
  libtransmission/resume.cc
  tests/libtransmission/bitfield-test.cc
Labels: scope:core, type:fixup

#2116 refactor: remove tr_ctorSetMetainfoFromHash()
  libtransmission/session.cc
  libtransmission/session.h
  libtransmission/torrent-ctor.cc
  libtransmission/torrent-magnet.cc
  libtransmission/torrent.cc
  libtransmission/transmission.h
  macosx/Torrent.mm
Labels: scope:mac, scope:core, type:refactor

#849 Add a "Start Now" action for newly added torrent notifications in the GTK client
  gtk/Notify.cc
  gtk/Notify.h
  gtk/Session.cc
  gtk/Session.h
Labels: enhancement, scope:gtk, needs update

#2121 refactor: web_utils
  Transmission.xcodeproj/project.pbxproj
  gtk/DetailsDialog.cc
  gtk/FilterBar.cc
  gtk/PrefsDialog.cc
  gtk/Utils.cc
  libtransmission/CMakeLists.txt
  libtransmission/announcer-common.h
  libtransmission/announcer-http.cc
  libtransmission/announcer.cc
  libtransmission/bandwidth.cc
  libtransmission/bandwidth.h
  libtransmission/clients.cc
  libtransmission/completion.cc
  libtransmission/completion.h
  libtransmission/crypto-utils.h
  libtransmission/crypto.h
  libtransmission/inout.cc
  libtransmission/log.h
  libtransmission/magnet.cc
  libtransmission/magnet.h
  libtransmission/makemeta.cc
  libtransmission/metainfo.cc
  libtransmission/metainfo.h
  libtransmission/peer-io.h
  libtransmission/peer-msgs.cc
  libtransmission/platform.cc
  libtransmission/ptrarray.cc
  libtransmission/ptrarray.h
  libtransmission/resume.cc
  libtransmission/rpc-server.cc
  libtransmission/rpc-server.h
  libtransmission/rpcimpl.cc
  libtransmission/rpcimpl.h
  libtransmission/session.cc
  libtransmission/session.h
  libtransmission/torrent-ctor.cc
  libtransmission/torrent-magnet.cc
  libtransmission/torrent.cc
  libtransmission/torrent.h
  libtransmission/transmission.h
  libtransmission/utils.cc
  libtransmission/utils.h
  libtransmission/web-utils.cc
  libtransmission/web-utils.h
  libtransmission/web.cc
  libtransmission/web.h
  libtransmission/webseed.cc
  macosx/CreatorWindowController.mm
  macosx/TrackerCell.mm
  tests/libtransmission/CMakeLists.txt
  tests/libtransmission/magnet-test.cc
  tests/libtransmission/utils-test.cc
  tests/libtransmission/web-utils-test.cc
  utils/show.cc
Labels: scope:core, type:refactor, type:perf, type:test, type:feat

#2123 refactor: tr_strv*() util functions
  libtransmission/announcer-http.cc
  libtransmission/announcer.cc
  libtransmission/crypto-utils.cc
  libtransmission/crypto-utils.h
  libtransmission/magnet.cc
  libtransmission/makemeta.cc
  libtransmission/metainfo.cc
  libtransmission/peer-io.h
  libtransmission/resume.cc
  libtransmission/rpc-server.cc
  libtransmission/rpcimpl.cc
  libtransmission/torrent.cc
  libtransmission/utils.cc
  libtransmission/utils.h
  libtransmission/web-utils.cc
  qt/AddData.cc
  tests/libtransmission/utils-test.cc
  utils/remote.cc
Labels: scope:core, type:refactor

#2124 refactor: magnet metainfo
  Transmission.xcodeproj/project.pbxproj
  libtransmission/CMakeLists.txt
  libtransmission/announcer.cc
  libtransmission/magnet-metainfo.cc
  libtransmission/magnet-metainfo.h
  libtransmission/magnet.cc
  libtransmission/magnet.h
  libtransmission/torrent-ctor.cc
  libtransmission/torrent-magnet.cc
  libtransmission/torrent.cc
  libtransmission/tr-macros.h
  libtransmission/transmission.h
  libtransmission/utils.h
  libtransmission/web-utils.cc
  libtransmission/web-utils.h
  tests/libtransmission/CMakeLists.txt
  tests/libtransmission/magnet-metainfo-test.cc
  tests/libtransmission/magnet-test.cc
  tests/libtransmission/utils-test.cc
Labels: scope:core, type:refactor

#2089 Replace C rand() with uniform_int_distribution and mt19937.
  libtransmission/crypto-utils.cc
Labels: scope:core, type:refactor

#2130 refactor: make piece checksums private
  libtransmission/inout.cc
  libtransmission/metainfo.cc
  libtransmission/metainfo.h
  libtransmission/torrent-magnet.cc
  libtransmission/torrent.cc
  libtransmission/torrent.h
  libtransmission/transmission.h
  libtransmission/verify.cc
  qt/OptionsDialog.cc
  qt/OptionsDialog.h
Labels: scope:core, type:refactor

#2132 refactor: prefer tr_variantDictFindStrView() in tests
  tests/libtransmission/json-test.cc
  tests/libtransmission/test-fixtures.h
  tests/libtransmission/variant-test.cc
Labels: type:refactor, type:test

#2134 feat: add tr_strvPath()
  daemon/daemon.cc
  libtransmission/inout.cc
  libtransmission/makemeta.cc
  libtransmission/platform.cc
  libtransmission/platform.h
  libtransmission/resume.cc
  libtransmission/rpcimpl.cc
  libtransmission/session-id.cc
  libtransmission/session.cc
  libtransmission/stats.cc
  libtransmission/torrent.cc
  libtransmission/tr-dht.cc
  libtransmission/tr-macros.h
  libtransmission/utils.h
  libtransmission/variant.cc
  libtransmission/watchdir.cc
  libtransmission/web.cc
  tests/libtransmission/blocklist-test.cc
  tests/libtransmission/copy-test.cc
  tests/libtransmission/file-test.cc
  tests/libtransmission/makemeta-test.cc
  tests/libtransmission/move-test.cc
  tests/libtransmission/rename-test.cc
  tests/libtransmission/test-fixtures.h
  tests/libtransmission/utils-test.cc
Labels: scope:core, type:refactor

#2136 fixup! refactor: make piece checksums private (#2130)
  libtransmission/torrent.cc
Labels: scope:core, type:fixup

#2138 Null-initialize MainWindow::Impl::popup_menu_ (GTK client)
  gtk/MainWindow.cc
Labels: scope:gtk, type:fixup

#2139 Fix pending_request_data memleak in Session (GTK client)
  gtk/Session.cc
Labels: scope:gtk, type:fixup

#2142 refactor: tr_sys_path_is_relative() takes a string_view
  libtransmission/file-posix.cc
  libtransmission/file-win32.cc
  libtransmission/file.h
Labels: scope:core, type:refactor

#2143 refactor: tr_dirSpace()
  gtk/FreeSpaceLabel.cc
  libtransmission/platform-quota.cc
  libtransmission/platform-quota.h
  libtransmission/rpcimpl.cc
  libtransmission/session.cc
  libtransmission/session.h
  libtransmission/transmission.h
  libtransmission/utils.cc
  libtransmission/utils.h
Labels: scope:core, type:refactor

#2145 refactor: tr_session.incomplete_dir
  libtransmission/rpcimpl.cc
  libtransmission/session.cc
  libtransmission/session.h
  tests/libtransmission/session-test.cc
Labels: scope:core, type:refactor

#2146 refactor: tr_session.scripts
  libtransmission/rpcimpl.cc
  libtransmission/session.cc
  libtransmission/session.h
  tests/libtransmission/session-test.cc
Labels: scope:core, type:refactor

#2147 refactor: tr session.blocklist
  libtransmission/rpcimpl.cc
  libtransmission/session.cc
  libtransmission/session.h
  tests/libtransmission/session-test.cc
Labels: scope:core, type:refactor

#2148 refactor: tr_ssha1(), tr_ssha1_matches()
  libtransmission/crypto-utils.cc
  libtransmission/crypto-utils.h
  libtransmission/rpc-server.cc
  tests/libtransmission/crypto-test.cc
Labels: scope:core, type:refactor

#2149 refactor: tr session.tos
  libtransmission/session.cc
  libtransmission/utils.h
  tests/libtransmission/utils-test.cc
Labels: scope:core, type:refactor

#2150 refactor: rpc whitelist
  libtransmission/rpc-server.cc
  libtransmission/rpc-server.h
  libtransmission/session.cc
  libtransmission/session.h
Labels: scope:core, type:refactor

#2151 refactor: tr_session.congestion
  libtransmission/peer-io.cc
  libtransmission/session.cc
  libtransmission/session.h
  libtransmission/tr-udp.cc
Labels: scope:core, type:refactor

#2144 Fix torrent counts in tracker filter bar combo (GTK client)
  gtk/FilterBar.cc
Labels: scope:gtk, type:fixup

#2153 fixup! refactor: remove tr_piece struct (#2059)
  libtransmission/torrent.h
Labels: scope:core, type:fixup

#2154 build: disable exit-time-destructor warnings in GTK client
  gtk/CMakeLists.txt
Labels: scope:gtk, type:build

#2155 refactor: remove tr_variantDictFindStr() from transmission remote
  utils/remote.cc
Labels: scope:remote, type:refactor

#2157 refactor: remove tr_variantDictFindStr() from transmission-edit
  utils/edit.cc
Labels: scope:edit, type:refactor

#2158 refactor: remove tr_variantDictFindstr() from transmission-gtk
  gtk/Prefs.cc
Labels: scope:gtk, type:refactor

#2156 fixup! feat: add tr_strvPath() (#2134)
  libtransmission/utils.h
Labels: scope:core, type:fixup

#2152 refactor: rpc-server.cc
  libtransmission/rpc-server.cc
  libtransmission/rpc-server.h
  libtransmission/session.cc
  libtransmission/session.h
  tests/libtransmission/session-test.cc
Labels: scope:core, type:refactor

#2159 refactor: remove tr_variantDictFindStr() from rpc-server.cc
  libtransmission/rpc-server.cc
Labels: scope:core, type:refactor

#2160 refactor: remove tr_variantGetStr()
  gtk/Prefs.cc
  libtransmission/variant.cc
  libtransmission/variant.h
  qt/TorrentModel.cc
  qt/VariantHelpers.h
  tests/libtransmission/rpc-test.cc
Labels: scope:gtk, scope:qt, scope:core, type:refactor, type:test

#2162 refactor: tr_webRun() now takes std::string_view args
  libtransmission/rpcimpl.cc
  libtransmission/web.cc
  libtransmission/web.h
Labels: scope:core, type:refactor

#2164 fix: rpc-authorization regression from earlier today
  libtransmission/crypto-utils.cc
  libtransmission/crypto-utils.h
  libtransmission/rpc-server.cc
  libtransmission/rpc-server.h
  libtransmission/transmission.h
  tests/libtransmission/session-test.cc
Labels: scope:core, type:fixup

#2165 refactor: remove tr_variantDictFindStr() from transmission-daemon
  daemon/daemon.cc
  libtransmission/watchdir.cc
  libtransmission/watchdir.h
Labels: scope:daemon, type:refactor

#2166 refactor: remove unused pieces of str to variant
  libtransmission/announcer-http.cc
  libtransmission/peer-msgs.cc
  libtransmission/rpc-server.cc
  libtransmission/torrent-ctor.cc
  libtransmission/torrent-magnet.cc
  libtransmission/variant.cc
  libtransmission/variant.h
  qt/RpcClient.cc
  tests/libtransmission/json-test.cc
  tests/libtransmission/variant-test.cc
  utils/remote.cc
  utils/show.cc
Labels: scope:core, type:refactor

#2167 Fix inconsistent message log action state (GTK client)
  gtk/Application.cc
  gtk/MessageLogWindow.cc
  gtk/MessageLogWindow.h
Labels: scope:gtk, type:fixup

#2169 Fix activity filter combo size (GTK client)
  gtk/FilterBar.cc
Labels: scope:gtk, type:fixup

#2071 web: preferences: add option to alter the download queue
  web/src/prefs-dialog.js
Labels: scope:web, feature disparity, type:feat

#2170 Fix torrent cells rendering in RTL mode (GTK client)
  gtk/TorrentCellRenderer.cc
Labels: scope:gtk, type:fix

#2172 refactor: tr_web's callback now uses std::string_view
  cli/cli.cc
  gtk/FaviconCache.cc
  libtransmission/announcer-http.cc
  libtransmission/rpcimpl.cc
  libtransmission/web.cc
  libtransmission/web.h
  libtransmission/webseed.cc
Labels: scope:core, type:refactor

#2173 Fix tracker cells rendering in RTL mode (GTK client)
  gtk/DetailsDialog.cc
Labels: scope:gtk, type:fix

#2175 refactor: tr_torrent.setLocation
  libtransmission/rpcimpl.cc
  libtransmission/torrent.cc
  libtransmission/torrent.h
Labels: scope:core, type:refactor

#2176 refactor: tr_address_from_string() is now std::string_view-friendly
  libtransmission/announcer-http.cc
  libtransmission/net.cc
  libtransmission/net.h
  libtransmission/rpcimpl.cc
  libtransmission/session.cc
Labels: scope:core, type:refactor

#2177 refactor: tr_sys_path_dirname(), tr_sys_path_basename() now take std::string_view parameters
  libtransmission/file-posix.cc
  libtransmission/file-win32.cc
  libtransmission/file.h
  libtransmission/platform.cc
  tests/libtransmission/file-test.cc
Labels: scope:core, type:refactor

#2178 refactor: add tr_torrent::renamePath()
  libtransmission/rpcimpl.cc
  libtransmission/session.cc
  libtransmission/torrent.cc
  libtransmission/torrent.h
Labels: scope:core, type:refactor

#2180 refactor: remove tr_variantDictFindStr()
  cli/cli.cc
  daemon/daemon.cc
  libtransmission/rpcimpl.cc
  libtransmission/variant.cc
  libtransmission/variant.h
Labels: scope:core, type:refactor

#2181 refactor: add a tr_loadFile() variant with reusable buffer
  libtransmission/torrent-ctor.cc
  libtransmission/utils.cc
  libtransmission/utils.h
Labels: scope:core, type:refactor

#2184 refactor: fix a -Wshadow warning for a variable named optarg
  cli/cli.cc
Labels: scope:cli, type:refactor

#2185 refactor: fix some msvc compiler warnings
  libtransmission/announcer.cc
  libtransmission/utils.cc
  tests/libtransmission/rename-test.cc
Labels: scope:core, type:refactor, type:test

#2182 refactor: use std::string_view in benc parser
  libtransmission/magnet-metainfo.cc
  libtransmission/peer-msgs.cc
  libtransmission/variant-benc.cc
  libtransmission/variant-common.h
  libtransmission/variant-json.cc
  libtransmission/variant.cc
  libtransmission/variant.h
  tests/libtransmission/variant-test.cc
Labels: scope:core, type:refactor

#2186 fix: coverity warnings
  gtk/Prefs.cc
  libtransmission/rpc-server.cc
  libtransmission/rpcimpl.cc
  libtransmission/session.cc
  tests/libtransmission/metainfo-test.cc
  tests/libtransmission/subprocess-test.cc
Labels: scope:gtk, scope:core, type:fix, type:test

#2189 fix: some sonarcloud warnings
  cli/cli.cc
  libtransmission/announcer.cc
  libtransmission/magnet-metainfo.cc
  libtransmission/magnet-metainfo.h
  libtransmission/metainfo.cc
  libtransmission/metainfo.h
  libtransmission/platform-quota.cc
  libtransmission/platform.cc
  libtransmission/rpc-server.cc
  libtransmission/rpc-server.h
  libtransmission/session.cc
Labels: scope:cli, scope:core, type:fix

#2190 fixup! refactor: make piece checksums private (#2130)
  libtransmission/torrent-magnet.cc
Labels: scope:core, type:fixup

#2187 refactor: make tr_variantFromBuf() public
  gtk/Application.cc
  gtk/DetailsDialog.cc
  gtk/Session.cc
  libtransmission/announcer-http.cc
  libtransmission/makemeta.cc
  libtransmission/peer-msgs.cc
  libtransmission/resume.cc
  libtransmission/rpc-server.cc
  libtransmission/rpcimpl.cc
  libtransmission/session.cc
  libtransmission/stats.cc
  libtransmission/torrent-ctor.cc
  libtransmission/torrent-magnet.cc
  libtransmission/torrent.cc
  libtransmission/tr-dht.cc
  libtransmission/variant-benc.cc
  libtransmission/variant-common.h
  libtransmission/variant-json.cc
  libtransmission/variant.cc
  libtransmission/variant.h
  qt/Prefs.cc
  qt/RpcClient.cc
  tests/libtransmission/json-test.cc
  tests/libtransmission/rpc-test.cc
  tests/libtransmission/variant-test.cc
  utils/edit.cc
  utils/remote.cc
  utils/show.cc
Labels: scope:create, scope:edit, scope:show, scope:gtk, scope:core, type:refactor

#2192 Fix building for XFS
  libtransmission/platform-quota.cc
Labels: scope:core, type:fixup

#2193 perf: faster shutdown
  libtransmission/session.cc
  libtransmission/session.h
  libtransmission/torrent.cc
  libtransmission/web.cc
Labels: type:refactor, type:perf

#2103 refactor: swarm
  Transmission.xcodeproj/project.pbxproj
  libtransmission/CMakeLists.txt
  libtransmission/clients.cc
  libtransmission/crypto-utils-ccrypto.cc
  libtransmission/crypto-utils-cyassl.cc
  libtransmission/crypto-utils-openssl.cc
  libtransmission/crypto-utils-polarssl.cc
  libtransmission/peer-common.h
  libtransmission/peer-mgr-active-requests.cc
  libtransmission/peer-mgr-active-requests.h
  libtransmission/peer-mgr-wishlist.cc
  libtransmission/peer-mgr-wishlist.h
  libtransmission/peer-mgr.cc
  libtransmission/peer-mgr.h
  libtransmission/peer-msgs.cc
  libtransmission/torrent.cc
  libtransmission/torrent.h
  libtransmission/transmission.h
  libtransmission/webseed.cc
  tests/libtransmission/CMakeLists.txt
  tests/libtransmission/peer-mgr-active-requests-test.cc
  tests/libtransmission/peer-mgr-wishlist-test.cc
Labels: scope:core, type:refactor

#2196 refactor: add tr_buildTorrentFilename()
  libtransmission/metainfo.cc
  libtransmission/metainfo.h
  libtransmission/resume.cc
Labels: scope:core, type:refactor

#2197 refactor: make Bandwidth.children a std::vector
  libtransmission/bandwidth.cc
  libtransmission/bandwidth.h
Labels: scope:core, type:refactor

#2194 refactor: use std mutex/lock intead of bespoke
  libtransmission/announcer.cc
  libtransmission/crypto-utils-cyassl.cc
  libtransmission/crypto-utils-polarssl.cc
  libtransmission/fdlimit.cc
  libtransmission/log.cc
  libtransmission/makemeta.cc
  libtransmission/peer-io.cc
  libtransmission/peer-mgr.cc
  libtransmission/platform.cc
  libtransmission/platform.h
  libtransmission/session.cc
  libtransmission/session.h
  libtransmission/torrent.cc
  libtransmission/torrent.h
  libtransmission/tr-dht.cc
  libtransmission/trevent.cc
  libtransmission/utils.cc
  libtransmission/verify.cc
  libtransmission/web.cc
  libtransmission/webseed.cc
Labels: scope:core, type:refactor

#2200 Use stock options and statistics icons in statusbar (GTK client)
  gtk/MainWindow.cc
  gtk/transmission.gresource.xml
Labels: scope:gtk, type:fix

#2204 man pages: remove commas in option listings
  cli/transmission-cli.1
  gtk/transmission-gtk.1
  qt/transmission-qt.1
Labels: scope:cli, scope:gtk, scope:qt, scope:docs

#2210 refactor: tr_block_info class
  Transmission.xcodeproj/project.pbxproj
  libtransmission/CMakeLists.txt
  libtransmission/block-info.cc
  libtransmission/block-info.h
  libtransmission/cache.cc
  libtransmission/completion.cc
  libtransmission/inout.cc
  libtransmission/peer-mgr.cc
  libtransmission/peer-msgs.cc
  libtransmission/resume.cc
  libtransmission/torrent.cc
  libtransmission/torrent.h
  libtransmission/verify.cc
  libtransmission/webseed.cc
  tests/libtransmission/CMakeLists.txt
  tests/libtransmission/block-info-test.cc
  tests/libtransmission/move-test.cc
Labels: scope:core, type:refactor, type:test

#2211 fixup! refactor: use std mutex/lock intead of bespoke (#2194)
  libtransmission/trevent.cc
Labels: scope:core, type:fixup

#2212 fix: env var leak in tr_spawn_async()
  libtransmission/subprocess-posix.cc
  libtransmission/subprocess-win32.cc
  libtransmission/subprocess.h
  libtransmission/torrent.cc
  tests/libtransmission/subprocess-test.cc
Labels: scope:core, type:fix

#2215 fixup: crash after completing magnet link metainfo
  libtransmission/cache.cc
  libtransmission/torrent-magnet.cc
  libtransmission/torrent.cc
  libtransmission/torrent.h
Labels: bug, scope:core, type:fixup

#2216 fixup: benc parse string view
  libtransmission/tr-dht.cc
Labels: scope:core, type:fixup

#2218 fix: GTK client's log window should honor dark mode
  gtk/MessageLogWindow.cc
Labels: scope:gtk, type:fix

#2223 fix: crash on corrupt dht.dat file
  libtransmission/tr-dht.cc
Labels: bug, scope:core

#2220 refactor: tr_completion
  libtransmission/announcer.cc
  libtransmission/bitfield.cc
  libtransmission/bitfield.h
  libtransmission/block-info.h
  libtransmission/cache.cc
  libtransmission/completion.cc
  libtransmission/completion.h
  libtransmission/peer-mgr-wishlist.cc
  libtransmission/peer-mgr-wishlist.h
  libtransmission/peer-mgr.cc
  libtransmission/peer-mgr.h
  libtransmission/peer-msgs.cc
  libtransmission/resume.cc
  libtransmission/rpcimpl.cc
  libtransmission/torrent-magnet.cc
  libtransmission/torrent.cc
  libtransmission/torrent.h
  libtransmission/transmission.h
  libtransmission/verify.cc
  libtransmission/webseed.cc
  tests/libtransmission/CMakeLists.txt
  tests/libtransmission/bitfield-test.cc
  tests/libtransmission/block-info-test.cc
  tests/libtransmission/completion-test.cc
  tests/libtransmission/move-test.cc
  tests/libtransmission/peer-mgr-wishlist-test.cc
Labels: scope:core, type:refactor, type:test

#2226 test: improve tr_bitfield and tr_block_info coverage
  libtransmission/bitfield.cc
  libtransmission/block-info.cc
  tests/libtransmission/bitfield-test.cc
  tests/libtransmission/block-info-test.cc
Labels: type:test

#2228 fixup! refactor: tr_completion (#2220)
  libtransmission/torrent.cc
Labels: scope:core, type:fixup

#2227 fix: sonarcloud
  libtransmission/announcer-http.cc
  libtransmission/announcer.cc
  libtransmission/handshake.cc
  libtransmission/inout.cc
  libtransmission/magnet-metainfo.cc
  libtransmission/peer-mgr-active-requests.cc
Labels: scope:core, type:refactor

#2229 fix: coverity warnings
  libtransmission/rpcimpl.cc
  libtransmission/torrent.cc
  libtransmission/torrent.h
  libtransmission/variant-json.cc
  libtransmission/web.cc
Labels: scope:core, type:refactor

#2230 fix: crash when renaming top-level folder in qt
  qt/FileTreeModel.cc
Labels: scope:qt, type:fix

#2233 refactor: minor naming change in block_info
  libtransmission/block-info.h
  libtransmission/completion.cc
  libtransmission/inout.cc
  libtransmission/peer-mgr.cc
  libtransmission/peer-msgs.cc
  libtransmission/torrent.cc
  libtransmission/verify.cc
  libtransmission/webseed.cc
  tests/libtransmission/block-info-test.cc
  tests/libtransmission/completion-test.cc
Labels: scope:core, type:refactor

#2242 fix: sonarcloud warnings / code smells
  gtk/Application.cc
  libtransmission/completion.cc
  libtransmission/completion.h
  libtransmission/peer-io.cc
  libtransmission/peer-mgr-wishlist.cc
  libtransmission/peer-mgr-wishlist.h
  libtransmission/peer-mgr.cc
  libtransmission/peer-msgs.cc
  libtransmission/torrent-ctor.cc
  libtransmission/torrent.cc
  libtransmission/torrent.h
  libtransmission/tr-dht.cc
  libtransmission/variant-benc.cc
  qt/FileTreeModel.cc
  qt/FileTreeModel.h
  qt/VariantHelpers.h
Labels: scope:gtk, scope:qt, scope:core, type:refactor

#2241 refactor: make parts of tr file private
  gtk/FileList.cc
  gtk/FilterBar.cc
  gtk/Notify.cc
  gtk/Session.cc
  gtk/TorrentCellRenderer.cc
  libtransmission/inout.cc
  libtransmission/metainfo.cc
  libtransmission/resume.cc
  libtransmission/rpcimpl.cc
  libtransmission/torrent.cc
  libtransmission/torrent.h
  libtransmission/transmission.h
  libtransmission/verify.cc
  libtransmission/webseed.cc
  macosx/Torrent.mm
  tests/libtransmission/move-test.cc
  tests/libtransmission/rename-test.cc
Labels: scope:show, scope:gtk, scope:qt, scope:mac, scope:core, type:refactor

#2246 refactor: add file-piece-map
  Transmission.xcodeproj/project.pbxproj
  libtransmission/CMakeLists.txt
  libtransmission/completion.cc
  libtransmission/completion.h
  libtransmission/file-piece-map.cc
  libtransmission/file-piece-map.h
  libtransmission/inout.cc
  libtransmission/peer-mgr.cc
  libtransmission/resume.cc
  libtransmission/rpcimpl.cc
  libtransmission/torrent-ctor.cc
  libtransmission/torrent.cc
  libtransmission/torrent.h
  libtransmission/transmission.h
  tests/libtransmission/CMakeLists.txt
  tests/libtransmission/completion-test.cc
  tests/libtransmission/file-piece-map-test.cc
Labels: scope:core, type:refactor
