Repository transmission/transmission, pull requests merged in 2021-10, with the labels that each got.

#1893 Don't set the path attribute when setting a cookie.
  web/src/prefs.js
Labels: comp:web

#1901 fix: minor dead store assignment warning in buildHandshakeMessage()
  libtransmission/handshake.cc
Labels: comp:core

#1950 fix runtime with wolfSSL and fastmath
  libtransmission/crypto-utils-cyassl.cc
Labels: bug, comp:core

#1960 refactor: use C++'s [[noreturn]] atrribute
  libtransmission/tr-assert.cc
  libtransmission/tr-assert.h
  libtransmission/tr-macros.h
Labels: comp:core

#1961 refactor: tr_quark_new() now takes a std::string_view
  daemon/daemon.cc
  gtk/actions.cc
  gtk/open-dialog.cc
  libtransmission/metainfo.cc
  libtransmission/peer-mgr.cc
  libtransmission/peer-msgs.cc
  libtransmission/quark.cc
  libtransmission/quark.h
  libtransmission/rpcimpl.cc
  libtransmission/session.cc
  libtransmission/torrent.cc
  libtransmission/variant-benc.cc
  libtransmission/variant-json.cc
  qt/TorrentModel.cc
  tests/libtransmission/json-test.cc
  tests/libtransmission/quark-test.cc
  tests/libtransmission/variant-test.cc
Labels: comp:core

#1965 fix: cppcoreguidelines-init-variables pt. 4
  libtransmission/.clang-tidy
  libtransmission/resume.cc
Labels: comp:core, code:refactor

#1980 refactor: clang-tidy --fix modernize-deprecated-headers
  libtransmission/.clang-tidy
  libtransmission/announcer-http.cc
  libtransmission/announcer-udp.cc
  libtransmission/blocklist.cc
  libtransmission/cache.cc
  libtransmission/clients.cc
  libtransmission/crypto-utils.cc
  libtransmission/crypto.cc
  libtransmission/handshake.cc
  libtransmission/log.cc
  libtransmission/magnet.cc
  libtransmission/metainfo.cc
  libtransmission/natpmp.cc
  libtransmission/net.cc
  libtransmission/platform-quota.cc
  libtransmission/session-id.cc
  libtransmission/subprocess-posix.cc
  libtransmission/torrent-ctor.cc
  libtransmission/torrent-magnet.cc
  libtransmission/tr-assert.cc
  libtransmission/tr-udp.cc
  libtransmission/tr-utp.cc
  libtransmission/trevent.cc
  libtransmission/upnp.cc
  libtransmission/variant-benc.cc
  libtransmission/variant-json.cc
  libtransmission/variant.cc
  libtransmission/watchdir-generic.cc
  libtransmission/watchdir-inotify.cc
  libtransmission/watchdir.cc
Labels: comp:core, code:refactor

#1981 refactor: add performance-* to libt .clang-tidy
  libtransmission/.clang-tidy
  libtransmission/file-posix.cc
  libtransmission/subprocess-posix.cc
  libtransmission/utils.cc
  libtransmission/webseed.cc
Labels: comp:core, code:refactor

#1982 build: silence new clang-tidy 13 warnings
  qt/.clang-tidy
  tests/libtransmission/.clang-tidy
Labels: code:fix

#1983 refactor: fixup! tr_quark_new() now takes a std::string_view (#1961)
  libtransmission/quark.cc
Labels: comp:core, code:refactor

#1984 fixup! Add total disk space to free-space RPC request (#1682)
  libtransmission/rpcimpl.cc
Labels: comp:core, code:refactor

#1979 refactor: cppcoreguidelines-init-variables pt. 6
  libtransmission/completion.cc
  libtransmission/magnet.cc
  libtransmission/session.cc
Labels: comp:core, code:refactor

#1999 fixup! refactor: tr_variant*Str() functions now take a std::string_view
  macosx/Controller.mm
Labels: comp:core

#1997 refactor: cppcoreguidelines-init-variables pt. 9
  libtransmission/peer-msgs.cc
  libtransmission/torrent-magnet.cc
  libtransmission/tr-getopt.cc
Labels: comp:core, code:refactor

#2059 refactor: remove tr_piece struct
  libtransmission/completion.cc
  libtransmission/inout.cc
  libtransmission/metainfo.cc
  libtransmission/peer-mgr.cc
  libtransmission/peer-msgs.cc
  libtransmission/resume.cc
  libtransmission/torrent.cc
  libtransmission/torrent.h
  libtransmission/tr-macros.h
  libtransmission/transmission.h
  libtransmission/verify.cc
  qt/OptionsDialog.cc
Labels: scope:core, type:perf

#2055 refactor: cppcoreguidelines-init-variables pt. 15
  libtransmission/file-posix.cc
  libtransmission/handshake.cc
  libtransmission/platform-quota.cc
  libtransmission/subprocess-posix.cc
Labels: scope:core, type:refactor

#2062 refactor: use a std::vector for tr_session.removed_torrents
  libtransmission/rpcimpl.cc
  libtransmission/session.cc
  libtransmission/session.h
  libtransmission/torrent.cc
Labels: scope:core, type:refactor

#2064 perf: omit extra std::map in tr_torrentPrimaryMimeType()
  libtransmission/torrent.cc
Labels: scope:core, type:perf

#2060 Fix clang warning in VDKQueue.m
  macosx/VDKQueue/VDKQueue.m
Labels: scope:mac, type:refactor

#2066 Fix pointer `return false` in file-win32.cc
  libtransmission/file-win32.cc
Labels: scope:core, type:fix

#2038 [macos] Replace Deprecated constants.
  macosx/AddMagnetWindowController.mm
  macosx/AddWindowController.mm
  macosx/BadgeView.mm
  macosx/BlocklistDownloaderViewController.mm
  macosx/Controller.mm
  macosx/CreatorWindowController.mm
  macosx/DragOverlayView.mm
  macosx/DragOverlayWindow.mm
  macosx/FileNameCell.mm
  macosx/FileOutlineController.mm
  macosx/FilePriorityCell.mm
  macosx/FileRenameSheetController.mm
  macosx/FilterBarController.mm
  macosx/GroupsPrefsController.mm
  macosx/InfoFileViewController.mm
  macosx/InfoOptionsViewController.mm
  macosx/InfoTabButtonCell.mm
  macosx/InfoTrackersViewController.mm
  macosx/MessageWindowController.mm
  macosx/NSImageAdditions.mm
  macosx/PeerProgressIndicatorCell.mm
  macosx/PrefsController.mm
  macosx/QuickLookPlugin/GeneratePreviewForURL.mm
  macosx/StatsWindowController.mm
  macosx/StatusBarController.mm
  macosx/ToolbarSegmentedCell.mm
  macosx/Torrent.mm
  macosx/TorrentCell.mm
  macosx/TorrentTableView.mm
  macosx/TrackerCell.mm
Labels: scope:mac, type:refactor

#2068 perf: add tr_buildBuf()
  libtransmission/fdlimit.cc
  libtransmission/fdlimit.h
  libtransmission/session.cc
  libtransmission/torrent.cc
  libtransmission/torrent.h
  libtransmission/utils.h
Labels: scope:core, type:perf

#2070 refactor: tr_urlParse()
  libtransmission/utils.cc
  libtransmission/utils.h
  tests/libtransmission/utils-test.cc
Labels: scope:core, type:refactor

#2072 Move Application class to a separate file
  gtk/CMakeLists.txt
  gtk/application.cc
  gtk/application.h
  gtk/main.cc
Labels: scope:gtk, type:refactor
