Repository transmission/transmission, pull requests merged in 2022-02, with the labels that each got.

#2554 refactor: use std::chrono not OS-specific syscalls
  libtransmission/log.cc
  libtransmission/session.cc
  libtransmission/tr-dht.cc
  libtransmission/utils.cc
  libtransmission/utils.h
Labels: scope:core, type:refactor

#2556 refactor: remove raw ptr variant of tr_peerMgrCompactToPex()
  libtransmission/peer-mgr.cc
  libtransmission/peer-mgr.h
  libtransmission/peer-msgs.cc
  libtransmission/tr-dht.cc
Labels: scope:core, type:refactor

#2558 fix: sonarcloud
  gtk/Actions.cc
  gtk/FileList.cc
  gtk/IconCache.cc
  gtk/MessageLogWindow.cc
  gtk/Prefs.cc
  gtk/PrefsDialog.cc
  gtk/Session.cc
  gtk/SystemTrayIcon.cc
  gtk/Utils.cc
  libtransmission/announce-list.cc
  libtransmission/announcer-http.cc
  libtransmission/announcer.cc
  libtransmission/blocklist.cc
  libtransmission/blocklist.h
  libtransmission/cache.cc
  libtransmission/file-posix.cc
  libtransmission/handshake.cc
  libtransmission/net.cc
  libtransmission/peer-mgr.cc
  libtransmission/peer-msgs.cc
  libtransmission/peer-msgs.h
  libtransmission/quark.cc
  libtransmission/resume.cc
  libtransmission/rpc-server.cc
  libtransmission/rpcimpl.cc
  libtransmission/session.cc
  libtransmission/torrent-magnet.cc
  libtransmission/torrent.cc
  libtransmission/tr-dht.cc
  libtransmission/tr-dht.h
  libtransmission/tr-getopt.cc
  libtransmission/tr-lpd.cc
  libtransmission/transmission.h
  libtransmission/utils.h
  libtransmission/variant-benc.cc
  libtransmission/variant-json.cc
  libtransmission/variant.cc
  libtransmission/web-utils.cc
  libtransmission/web.cc
  libtransmission/webseed.cc
  qt/Application.cc
  qt/DBusInteropHelper.cc
  qt/DetailsDialog.cc
  qt/FaviconCache.cc
  qt/FileTreeItem.cc
  qt/FileTreeView.cc
  qt/FilterBarComboBox.cc
  qt/FreeSpaceLabel.cc
  qt/InteropObject.cc
  qt/MainWindow.cc
  qt/MakeDialog.cc
  qt/PathButton.cc
  qt/Prefs.cc
  qt/PrefsDialog.cc
  qt/RpcClient.cc
  qt/Session.cc
  qt/VariantHelpers.h
  utils/remote.cc
Labels: scope:remote, scope:gtk, scope:qt, scope:core, type:refactor

#2559 refactor: static allocation of formatter units
  libtransmission/utils.cc
Labels: scope:core, type:fix

#2560 fix: edge case file leak if error while making torrent
  libtransmission/makemeta.cc
Labels: scope:core, type:fixup

#2563 fix: some use-init-statement sonarcloud warnings
  gtk/FileList.cc
  gtk/MessageLogWindow.cc
  gtk/Prefs.cc
  gtk/Session.cc
  gtk/SystemTrayIcon.cc
  gtk/Utils.cc
  libtransmission/announce-list.cc
  libtransmission/announcer-http.cc
  libtransmission/announcer.cc
  libtransmission/file-posix.cc
  libtransmission/handshake.cc
  libtransmission/net.cc
  libtransmission/peer-msgs.cc
  libtransmission/resume.cc
Labels: scope:gtk, scope:core, type:refactor

#2566 refactor: sonarcloud
  qt/Application.cc
  qt/FaviconCache.cc
  qt/FileTreeItem.cc
  qt/FilterBarComboBox.cc
  qt/FreeSpaceLabel.cc
  qt/InteropObject.cc
  qt/MainWindow.cc
  qt/MakeDialog.cc
  qt/PathButton.cc
  qt/Prefs.cc
  qt/PrefsDialog.cc
  qt/RpcClient.cc
  qt/Session.cc
  qt/VariantHelpers.h
  qt/WatchDir.cc
Labels: scope:qt, type:refactor

#2578 refactor: clang-tidy in libtransmission
  libtransmission/.clang-tidy
  libtransmission/announcer-http.cc
  libtransmission/announcer-udp.cc
  libtransmission/announcer.cc
  libtransmission/block-info.cc
  libtransmission/clients.cc
  libtransmission/crypto-utils-ccrypto.cc
  libtransmission/crypto-utils-cyassl.cc
  libtransmission/crypto-utils-openssl.cc
  libtransmission/crypto-utils-polarssl.cc
  libtransmission/file-posix.cc
  libtransmission/log.cc
  libtransmission/peer-mgr-active-requests.cc
  libtransmission/peer-mgr.cc
  libtransmission/peer-msgs.cc
  libtransmission/platform-quota.cc
  libtransmission/platform.cc
  libtransmission/resume.cc
  libtransmission/rpc-server.cc
  libtransmission/rpcimpl.cc
  libtransmission/session.cc
  libtransmission/subprocess-posix.cc
  libtransmission/torrent-ctor.cc
  libtransmission/torrent-metainfo.cc
  libtransmission/torrent.cc
  libtransmission/tr-dht.cc
  libtransmission/tr-lpd.cc
  libtransmission/tr-udp.cc
  libtransmission/tr-utp.cc
  libtransmission/tr-utp.h
  libtransmission/trevent.cc
  libtransmission/utils.cc
  libtransmission/variant-benc.cc
  libtransmission/variant-json.cc
  libtransmission/variant.cc
  libtransmission/verify.cc
  libtransmission/watchdir.cc
  libtransmission/web-utils.cc
  libtransmission/web.cc
  libtransmission/webseed.cc
Labels: scope:core, type:refactor

#2585 refactor: re-enable some clang-tidy checks in qt/
  qt/.clang-tidy
  qt/Application.cc
  qt/Application.h
  qt/DetailsDialog.cc
  qt/FaviconCache.cc
  qt/FileTreeModel.cc
  qt/FilterBarComboBoxDelegate.cc
  qt/MainWindow.cc
  qt/PathButton.cc
  qt/Prefs.cc
  qt/PrefsDialog.cc
  qt/RpcClient.cc
  qt/RpcClient.h
  qt/Session.cc
  qt/Torrent.cc
  qt/Torrent.h
  qt/TorrentDelegate.cc
  qt/TorrentDelegateMin.cc
  qt/TorrentModel.cc
  qt/TorrentView.cc
  qt/Utils.cc
  qt/VariantHelpers.cc
Labels: scope:qt, type:refactor

#2587 refactor: sonarcloud "use if init" statements
  gtk/FileList.cc
  gtk/PrefsDialog.cc
  gtk/Session.cc
  gtk/TorrentCellRenderer.cc
  libtransmission/announce-list.cc
  libtransmission/blocklist.cc
  libtransmission/cache.cc
  libtransmission/handshake.cc
  libtransmission/peer-mgr.cc
  libtransmission/peer-msgs.cc
  libtransmission/platform.cc
  libtransmission/resume.cc
  libtransmission/rpc-server.cc
  libtransmission/rpcimpl.cc
  libtransmission/session.cc
  libtransmission/torrent-magnet.cc
  libtransmission/torrent.cc
  libtransmission/tr-dht.cc
  libtransmission/tr-getopt.cc
  libtransmission/variant-benc.cc
  libtransmission/variant-json.cc
  libtransmission/variant.cc
  libtransmission/web-utils.cc
  qt/DetailsDialog.cc
  qt/FileTreeModel.cc
  qt/FileTreeView.cc
Labels: scope:gtk, scope:qt, scope:core, type:refactor

#2588 refactor: fix a pair of win32 msvc warnings in libtransmission
  libtransmission/log.cc
  libtransmission/verify.cc
Labels: scope:core, type:refactor

#2589 fixup! add labels to torrent-add rpc method (#2539)
  libtransmission/rpcimpl.cc
Labels: scope:core, type:fixup

#2590 refactor: fix sonarcloud "use enum class" code smells
  gtk/Application.cc
  gtk/HigWorkarea.h
  gtk/MainWindow.cc
  gtk/MakeDialog.cc
  gtk/PrefsDialog.h
  gtk/StatsDialog.cc
  gtk/TorrentCellRenderer.cc
  gtk/Utils.cc
  gtk/Utils.h
  libtransmission/announce-list.h
  libtransmission/makemeta.cc
  libtransmission/makemeta.h
  libtransmission/peer-msgs.cc
  libtransmission/resume.cc
  libtransmission/resume.h
  libtransmission/rpcimpl.cc
  libtransmission/torrent.cc
  macosx/CreatorWindowController.mm
  qt/Application.cc
  qt/FileTreeItem.cc
  qt/FileTreeItem.h
  qt/FileTreeModel.cc
  qt/MakeDialog.cc
  tests/libtransmission/rename-test.cc
  utils/create.cc
Labels: scope:gtk, scope:qt, scope:core, type:refactor

#2591 fix: make DNS queries lowercase
  libtransmission/announcer-udp.cc
Labels: scope:core, type:fix

#2586 [Web] Magnet link, Main window toolbar accessibility, ARM build fix, Dependencies update
  .gitignore
  web/.nvmrc
  web/package.json
  web/public_html/index.html
  web/public_html/transmission-app.js
  web/src/inspector.js
  web/src/torrent.js
  web/style/images/README.md
  web/style/images/magnet.svg
  web/style/transmission-app.scss
  web/yarn.lock
Labels: scope:web, feature disparity, type:feat

#1406 Add labels support into web client.
  web/public_html/transmission-app.js
  web/src/action-manager.js
  web/src/context-menu.js
  web/src/inspector.js
  web/src/remote.js
  web/src/torrent-row.js
  web/src/torrent.js
  web/src/transmission.js
  web/style/transmission-app.scss
Labels: enhancement, scope:web, feature disparity

#2595 fix: deprecated sass division warning in web client
  web/public_html/transmission-app.js
  web/public_html/transmission-app.js.LICENSE.txt
  web/style/transmission-app.scss
Labels: scope:web, dependencies

#2601 feat: add 'ok' shortcut in web client open dialog
  web/public_html/transmission-app.js
  web/src/open-dialog.js
Labels: enhancement, scope:web, feature disparity

#2605 fix: rename 'corrupt' label for understandability
  gtk/DetailsDialog.cc
  qt/DetailsDialog.cc
  utils/remote.cc
  web/public_html/transmission-app.js
  web/src/inspector.js
Labels: scope:remote, scope:gtk, scope:qt, scope:web, type:fix

#2606 docs: move rpc-spec document from txt to markdown
  CMakeLists.txt
  extras/rpc-spec.md
  extras/rpc-spec.txt
  libtransmission/transmission.h
Labels: scope:docs, type:docs

#2613 refactor: tr_webseed simplification
  libtransmission/peer-mgr-wishlist.cc
  libtransmission/web.cc
  libtransmission/web.h
  libtransmission/webseed.cc
Labels: scope:core, type:refactor

#2608 feat: add support for adding torrents by raw hash values
  cli/cli.cc
  gtk/OptionsDialog.cc
  gtk/Session.cc
  gtk/Utils.cc
  gtk/Utils.h
  libtransmission/crypto-utils.cc
  libtransmission/crypto-utils.h
  libtransmission/magnet-metainfo.cc
  libtransmission/magnet-metainfo.h
  libtransmission/rpcimpl.cc
  libtransmission/session.cc
  qt/AddData.cc
  qt/MainWindow.cc
  qt/Torrent.h
  qt/Utils.h
  tests/libtransmission/crypto-test.cc
  tests/libtransmission/magnet-metainfo-test.cc
Labels: scope:cli, scope:gtk, scope:qt, scope:core, type:feat

#2615 Add support for torrent-get calls with the key percentComplete
  extras/rpc-spec.md
  libtransmission/quark.cc
  libtransmission/quark.h
  libtransmission/rpcimpl.cc
Labels: scope:core, type:feat

#2618 feat: allow decimal values in seedRatioLimit input
  web/public_html/transmission-app.js
  web/src/prefs-dialog.js
Labels: enhancement, scope:web, type:feat

#2619 feat: expose downloaded byte count to done script
  libtransmission/torrent.cc
Labels: scope:core, type:feat

#1452 Add ProtectSystem and PrivateTmp to systemd service
  daemon/transmission-daemon.service
Labels: enhancement, scope:daemon

#2620 refactor: add fetch options object to tr_webRun()
  cli/cli.cc
  gtk/FaviconCache.cc
  libtransmission/announcer-http.cc
  libtransmission/rpcimpl.cc
  libtransmission/web.cc
  libtransmission/web.h
  libtransmission/webseed.cc
Labels: scope:core, type:refactor

#2621 feat: run script when done seeding
  extras/rpc-spec.md
  gtk/Application.cc
  gtk/PrefsDialog.cc
  libtransmission/quark.cc
  libtransmission/quark.h
  libtransmission/rpcimpl.cc
  libtransmission/session.cc
  libtransmission/session.h
  libtransmission/torrent.cc
  libtransmission/transmission.h
  qt/Prefs.cc
  qt/Prefs.h
  qt/PrefsDialog.cc
  qt/PrefsDialog.h
  qt/PrefsDialog.ui
  qt/Session.cc
  tests/libtransmission/rpc-test.cc
  utils/remote.cc
Labels: scope:remote, scope:gtk, scope:qt, scope:core, type:feat

#2622 feat: use new envvar TR_CURL_PROXY_SSL_NO_VERIFY
  libtransmission/web.cc
Labels: scope:core, type:feat

#2623 fix: sonarcloud code smells
  gtk/OptionsDialog.cc
  libtransmission/magnet-metainfo.cc
  libtransmission/session.h
  libtransmission/web-utils.cc
  libtransmission/web.cc
  qt/FaviconCache.cc
  utils/create.cc
  web/src/torrent.js
Labels: scope:create, scope:gtk, scope:qt, scope:core, type:refactor

#2624 use metainfo folder instead of appdata
  gtk/CMakeLists.txt
  gtk/transmission-gtk.metainfo.xml.in
  po/POTFILES.in
Labels: scope:gtk, type:build

#2627 fix: crash when evdns_base_new() fails
  libtransmission/session.cc
  libtransmission/trevent.cc
Labels: scope:core, type:fix

#2628 refactor: remove tr_webGetTaskResponseCode()
  libtransmission/web.cc
  libtransmission/web.h
  libtransmission/webseed.cc
Labels: scope:core, type:refactor

#2629 build: use -DHAVE_FLOCK in the macOS Xcode build
  Transmission.xcodeproj/project.pbxproj
Labels: scope:mac, type:fix, type:build

#2634 fix: set torrent.doneDate when adding a new seed
  libtransmission/torrent.cc
Labels: scope:core, type:fix

#2635 revert da855a72 "Set stock icon for speed, options and statistics buttons in qt"
  qt/MainWindow.cc
Labels: scope:qt, type:fixup

#2640 refactor: tr_web
  cli/cli.cc
  gtk/FaviconCache.cc
  libtransmission/announcer-http.cc
  libtransmission/rpcimpl.cc
  libtransmission/session.cc
  libtransmission/session.h
  libtransmission/web.cc
  libtransmission/web.h
  libtransmission/webseed.cc
Labels: scope:core, type:fixup

#2641 fix: do not hammer dns servers re-requesting udp trackernames
  libtransmission/announcer-udp.cc
Labels: scope:core, type:perf

#2649 Feat: add tr_block_info::Location
  libtransmission/block-info.h
  libtransmission/cache.cc
  libtransmission/completion.cc
  libtransmission/file-piece-map.cc
  libtransmission/peer-mgr.cc
  libtransmission/peer-msgs.cc
  libtransmission/peer-msgs.h
  libtransmission/torrent-metainfo.h
  libtransmission/torrent.cc
  libtransmission/torrent.h
  libtransmission/webseed.cc
  tests/libtransmission/block-info-test.cc
Labels: scope:core, type:refactor

#2650 refactor/remove-unused-utp-includes
  libtransmission/session.cc
  libtransmission/tr-udp.cc
Labels: scope:core, type:refactor

#2652 refactor: use tr_block_info::Location in cache.cc
  libtransmission/cache.cc
  libtransmission/cache.h
  libtransmission/inout.cc
  libtransmission/peer-msgs.cc
  libtransmission/tr-utp.h
  libtransmission/webseed.cc
  tests/libtransmission/move-test.cc
Labels: scope:core, type:refactor

#2654 magnet links always pause after they get metainfo
  libtransmission/torrent-magnet.cc
Labels: scope:core, type:fix

#2658 refactor: use tr_block_info::Location in inout.cc
  libtransmission/cache.cc
  libtransmission/inout.cc
  libtransmission/inout.h
  libtransmission/torrent-metainfo.h
  libtransmission/torrent.h
  libtransmission/webseed.cc
Labels: scope:core, type:refactor

#2659 refactor: move tr_netClosePeerSocket() impl to net.cc
  libtransmission/net.cc
  libtransmission/peer-mgr.cc
  libtransmission/peer-socket.h
  libtransmission/utils.cc
Labels: scope:core, type:refactor

#2661 fix implicit conversion
  libtransmission/file-posix.cc
Labels: scope:core, type:fixup

#2666 fixup! fix: sonarcloud code smells (#2623)
  web/src/torrent.js
Labels: scope:web, type:fixup

#2668 feat: default public trackers
  daemon/daemon.cc
  extras/rpc-spec.md
  gtk/Application.cc
  gtk/DetailsDialog.cc
  gtk/PrefsDialog.cc
  libtransmission/announce-list.cc
  libtransmission/announce-list.h
  libtransmission/announcer.cc
  libtransmission/quark.cc
  libtransmission/quark.h
  libtransmission/rpcimpl.cc
  libtransmission/session.cc
  libtransmission/session.h
  libtransmission/transmission.h
  qt/Prefs.cc
  qt/Prefs.h
  qt/PrefsDialog.cc
  qt/PrefsDialog.h
  qt/PrefsDialog.ui
  qt/Session.cc
  qt/TrackersDialog.ui
  tests/libtransmission/announce-list-test.cc
  tests/libtransmission/rpc-test.cc
  web/public_html/transmission-app.js
  web/src/prefs-dialog.js
  web/style/transmission-app.scss
Labels: enhancement, scope:daemon, scope:gtk, scope:qt, scope:web, scope:core

#2675 fix: recent memory leak regressions
  libtransmission/makemeta.cc
  libtransmission/trevent.cc
Labels: scope:core, type:fixup

#2673 docs: move the wiki into `transmission/transmission`
  CMakeLists.txt
  README.md
  docs/Blocked-Traffic.md
  docs/Blocklists.md
  docs/Bug-Submission.md
  docs/Building-Transmission.md
  docs/Can-I-sequence-the-files-I-download.md
  docs/Configuration-Files.md
  docs/Editing-Configuration-Files.md
  docs/Environment-Variables.md
  docs/Peer-ID-and-User-Agent.md
  docs/Peer-Status-Text.md
  docs/Previous-Releases.md
  docs/README.md
  docs/RPC-Protocol-Specification.md
  docs/Release-Notes.md
  docs/Translating.md
  docs/Transmission-Architecture.md
  docs/Transmission-Resume-Files.md
  docs/Transmission-is-Downloading-Files-I-Asked-It-To-Not-Download.md
  docs/Web-Interface.md
  docs/Why-Are-My-Speeds-So-Slow.md
  docs/Why-is-my-port-closed.md
  docs/rpc-spec.md
  libtransmission/transmission.h
Labels: scope:docs, scope:wiki

#2676 fix: bitfield assertion failure on zero-byte file
  libtransmission/torrent.cc
Labels: scope:core, type:fixup

#2677 fix: unreleased regression in makemeta pieces hashes
  libtransmission/makemeta.cc
Labels: scope:create, scope:core, type:fixup

#2678 docs: misc fixes in the docs/ directory
  docs/Configuration-Files.md
  docs/Editing-Configuration-Files.md
  docs/Environment-Variables.md
  docs/README.md
  docs/RPC-Protocol-Specification.md
Labels: scope:docs

#2681 refactor: rename mediator classes
  libtransmission/peer-mgr-wishlist.cc
  libtransmission/peer-mgr-wishlist.h
  libtransmission/peer-mgr.cc
  libtransmission/session.cc
  libtransmission/session.h
  libtransmission/web.cc
  libtransmission/web.h
  tests/libtransmission/peer-mgr-wishlist-test.cc
Labels: scope:core, type:refactor

#2682 fix: ensure all bytes used in file io read/writes
  libtransmission/inout.cc
Labels: scope:core, type:fix

#2683 docs: misc fixes
  docs/Bug-Submission.md
  docs/Building-Transmission.md
  docs/Can-I-sequence-the-files-I-download.md
  docs/Configuration-Files.md
  docs/Editing-Configuration-Files.md
  docs/Environment-Variables.md
  docs/Previous-Releases.md
  docs/README.md
  docs/Release-Notes.md
  docs/Scripts.md
  docs/Transmission-Architecture.md
  docs/Web-Interface.md
  docs/Why-is-my-port-closed.md
Labels: scope:docs, type:docs

#2685 docs: restore the Port Forwarding Guide
  docs/Port-Forwarding-Guide.md
  docs/Why-Are-My-Speeds-So-Slow.md
Labels: scope:docs

#2687 fix: unsupported peer socket type 0 assertion failure
  libtransmission/peer-io.cc
Labels: scope:core, type:fix

#2689 refactor: webseed
  libtransmission/block-info.h
  libtransmission/cache.cc
  libtransmission/peer-msgs.cc
  libtransmission/torrent.cc
  libtransmission/torrent.h
  libtransmission/web.cc
  libtransmission/webseed.cc
Labels: scope:core, type:fix, type:refactor, type:perf

#2693 fixup! refactor: tr_web (#2633)
  libtransmission/web.cc
Labels: scope:core, type:fixup

#2692 docs: convert some wiki markup to markdown
  docs/Blocklists.md
  docs/Bug-Submission.md
  docs/Building-Transmission.md
  docs/Configuration-Files.md
  docs/Editing-Configuration-Files.md
  docs/Environment-Variables.md
  docs/Transmission-Architecture.md
  docs/Web-Interface.md
  docs/Why-Are-My-Speeds-So-Slow.md
  docs/Why-is-my-port-closed.md
  docs/rpc-spec.md
Labels: scope:docs

#2694 fix: always use a block size of 16 KB
  libtransmission/block-info.cc
  libtransmission/block-info.h
  libtransmission/completion.cc
  libtransmission/inout.cc
  libtransmission/peer-mgr.cc
  libtransmission/peer-msgs.cc
  libtransmission/torrent-metainfo.h
  libtransmission/torrent.h
  tests/libtransmission/block-info-test.cc
  tests/libtransmission/completion-test.cc
  tests/libtransmission/file-piece-map-test.cc
  tests/libtransmission/move-test.cc
Labels: scope:core, type:fix

#2695 feat: warn when creating torrents with nonportable filenames
  Transmission.xcodeproj/project.pbxproj
  libtransmission/CMakeLists.txt
  libtransmission/file-info.cc
  libtransmission/file-info.h
  libtransmission/makemeta.cc
  libtransmission/makemeta.h
  libtransmission/torrent-metainfo.cc
  utils/create.cc
Labels: scope:create, type:feat

#2697 feat: update built-in speed limit settings
  gtk/MainWindow.cc
  macosx/TorrentTableView.mm
  qt/MainWindow.cc
  web/public_html/transmission-app.js
  web/src/overflow-menu.js
Labels: scope:gtk, scope:qt, scope:mac, scope:web, type:feat

#2698 fix: allow 0-byte files when creating torrents
  libtransmission/makemeta.cc
Labels: scope:core, type:fix

#2699 docs: rpc password, systemd privs
  docs/Editing-Configuration-Files.md
  docs/Scripts.md
Labels: scope:docs, type:docs

#2701 fixup: handle unhandled scrape/announce responses
  libtransmission/announcer-common.h
  libtransmission/announcer-http.cc
  libtransmission/announcer.cc
  libtransmission/net.cc
  libtransmission/net.h
  libtransmission/session.h
  tests/libtransmission/announcer-test.cc
Labels: scope:core, type:refactor

#2704 refactor: remove unused tr_block_info.n_blocks_in_piece
  libtransmission/block-info.cc
  libtransmission/block-info.h
  tests/libtransmission/block-info-test.cc
  tests/libtransmission/completion-test.cc
Labels: scope:core, type:refactor, type:fixup

#2706 refactor: use std string in tr net strerror
  libtransmission/fdlimit.cc
  libtransmission/net.cc
  libtransmission/net.h
  libtransmission/peer-io.cc
  libtransmission/tr-udp.cc
Labels: scope:core, type:refactor

#2708 feat: stop announcing on not-registered tracker error
  libtransmission/announcer.cc
Labels: scope:core, type:perf

#2709 feat: better dialog when adding duplicate magnet
  qt/AddData.cc
Labels: scope:qt, type:feat

#2712 fixup: webseed
  libtransmission/web.cc
  libtransmission/webseed.cc
Labels: scope:core, type:fixup

#2714 perf: do not block on upnpDiscover() call during startup
  libtransmission/upnp.cc
Labels: scope:core, type:perf

#2717 chore: exploratory change for #2571
  libtransmission/announcer.cc
Labels: scope:core

#2719 refactor: remove utils dependency from peer-io
  libtransmission/peer-io.cc
  libtransmission/peer-io.h
  libtransmission/peer-mgr.cc
  libtransmission/peer-msgs.cc
  libtransmission/peer-msgs.h
  libtransmission/web-utils.h
  tests/libtransmission/benc-test.cc
Labels: scope:core
