Repository transmission/transmission, pull requests merged in 2022-12, with the labels that each got.

#4235 Fix tr_rand_int modulo bias and fix tr_rand_int for values larger than INT_MAX
  libtransmission/bandwidth.cc
  libtransmission/crypto-utils.cc
  libtransmission/crypto-utils.h
Labels: scope:core, type:refactor, notes:none

#4252 docs: add a draft of 4.0.0-beta.2 notes
  news/news-4.0.0-beta-2.md
Labels: notes:none

#4300 refactor: stop tracking peerIo creation time
  libtransmission/peer-io.cc
  libtransmission/peer-io.h
  libtransmission/peer-mgr.cc
  libtransmission/peer-msgs.cc
  libtransmission/peer-msgs.h
  tests/libtransmission/handshake-test.cc
Labels: scope:core, type:refactor

#4306 Simplify widget initialization in preferences dialog
  gtk/PrefsDialog.cc
Labels: scope:gtk, type:refactor

#4322 refactor: only need a single handshake mediator
  libtransmission/handshake.cc
  libtransmission/handshake.h
  libtransmission/peer-mgr.cc
  tests/libtransmission/handshake-test.cc
Labels: scope:core, type:refactor, notes:none

#4325 refactor: tr_peer_socket
  Transmission.xcodeproj/project.pbxproj
  libtransmission/CMakeLists.txt
  libtransmission/handshake.cc
  libtransmission/net.cc
  libtransmission/peer-io.cc
  libtransmission/peer-io.h
  libtransmission/peer-mgr.cc
  libtransmission/peer-msgs.cc
  libtransmission/peer-socket.cc
  libtransmission/peer-socket.h
  libtransmission/session.cc
  libtransmission/tr-utp.cc
  tests/libtransmission/handshake-test.cc
Labels: scope:core, type:refactor, notes:none

#4326 refactor: peer-socket pt 2
  libtransmission/net.cc
  libtransmission/peer-io.cc
  libtransmission/peer-io.h
  libtransmission/peer-mgr.cc
  libtransmission/peer-mgr.h
  libtransmission/peer-socket.cc
  libtransmission/peer-socket.h
  libtransmission/session.cc
  libtransmission/session.h
  libtransmission/tr-utp.cc
  tests/libtransmission/handshake-test.cc
Labels: scope:core, type:refactor, notes:none

#4331 refactor: fix shutdown order of utp
  libtransmission/session.cc
  libtransmission/session.h
Labels: scope:core, type:fix

#4324 ignoring /tests/**/*.out
  .gitignore
Labels: notes:none

#4334 fix: broken detection of peer udp port
  libtransmission/peer-msgs.cc
Labels: scope:core, type:fix

#4337 Detect changes against branch off point, not origin/main
  .github/workflows/actions.yml
Labels: type:build

#4335 refactor: tr_address::display_name()
  libtransmission/handshake.cc
  libtransmission/net.cc
  libtransmission/net.h
  libtransmission/peer-common.h
  libtransmission/peer-io.cc
  libtransmission/peer-io.h
  libtransmission/peer-mgr.cc
  libtransmission/peer-mgr.h
  libtransmission/peer-msgs.cc
  libtransmission/peer-socket.cc
  libtransmission/peer-socket.h
  libtransmission/port-forwarding.cc
  libtransmission/session.cc
  libtransmission/tr-udp.cc
  libtransmission/webseed.cc
  tests/libtransmission/announcer-test.cc
  tests/libtransmission/dht-test.cc
  tests/libtransmission/net-test.cc
Labels: scope:core, type:refactor, notes:none

#4339 Don't include MSVC redist MSM in Windows MSI package
  .github/workflows/actions.yml
  dist/msi/CMakeLists.txt
  dist/msi/Transmission.wxs
  dist/msi/TransmissionConfig.wxi.in
  dist/msi/UtilityFunctions.cmake
Labels: os:windows, type:build

#4333 MacOS empty tableview rows fix
  Transmission.xcodeproj/project.pbxproj
  macosx/CMakeLists.txt
  macosx/Controller.mm
  macosx/GroupTextCell.h
  macosx/GroupTextCell.mm
  macosx/TorrentTableView.mm
Labels: scope:mac, type:ui

#4346 fix: remove invalid assertion from bitfield code
  libtransmission/bitfield.cc
Labels: scope:core, type:fix

#4349 Show "Enable uTP" checkbox in preferences if supported (GTK client)
  gtk/CMakeLists.txt
Labels: bug, scope:gtk, type:ui

#4351 Fixed crash in tr_bitfield::operator|= range
  libtransmission/bitfield.cc
Labels: scope:core, type:fixup

#4354 Simplify `PrefsDialog`'s `PageBase` further by passing builder via ctor
  gtk/PrefsDialog.cc
Labels: scope:gtk, type:refactor

#4309 Fixed memory leak in BlocklistDownloader
  macosx/BlocklistDownloader.mm
Labels: scope:mac, type:fix

#4355 Improve error handling upon watch directory setup
  gtk/Session.cc
Labels: scope:gtk, type:fix, bug:regression

#4353 Fixed logic in tr_wildmat
  libtransmission/utils.cc
Labels: scope:core, type:fix, bug:regression

#4348 Fixed crash on exit in tr_utpPacket
  libtransmission/tr-udp.cc
Labels: bug, scope:core

#4362 refactor: tr_handshake
  libtransmission/handshake.cc
  libtransmission/handshake.h
  libtransmission/peer-mgr.cc
  libtransmission/tr-udp.cc
  tests/libtransmission/handshake-test.cc
Labels: scope:core, type:refactor

#4310 Fixed `archivedDataWithRootObject:` is deprecated
  macosx/Controller.mm
  macosx/GroupsController.mm
  macosx/GroupsPrefsController.mm
  macosx/TorrentTableView.mm
Labels: scope:mac

#4323 Moving CMAKE_OSX_DEPLOYMENT_TARGET FATAL_ERROR next to its default setting
  CMakeLists.txt
  macosx/CMakeLists.txt
Labels: type:build, notes:none

#4365 Sorting by size should be instead by sizeWhenDone
  macosx/Controller.mm
Labels: scope:mac

#4271 Dropped tr_rand_int_weak (where possible).
  libtransmission/announcer.cc
  libtransmission/bandwidth.cc
  libtransmission/crypto-utils-polarssl.cc
  libtransmission/peer-mgr.cc
  libtransmission/session.cc
  libtransmission/tr-dht.cc
  libtransmission/tr-utp.cc
  tests/libtransmission/bitfield-test.cc
  tests/libtransmission/crypto-test.cc
  tests/libtransmission/makemeta-test.cc
  tests/libtransmission/utils-test.cc
Labels: scope:core

#4308 Replaced deprecated NSURLDownload with NSURLSessionDownloadTask
  macosx/Controller.h
  macosx/Controller.mm
Labels: scope:mac

#4374 removed redunant code from AddMagnetWindow
  macosx/AddMagnetWindowController.mm
  macosx/Base.lproj/AddMagnetWindow.xib
Labels: scope:mac, type:refactor

#4372 refactor: tr_peerIo
  libtransmission/announcer.cc
  libtransmission/bandwidth.cc
  libtransmission/handshake.cc
  libtransmission/handshake.h
  libtransmission/net.cc
  libtransmission/peer-io.cc
  libtransmission/peer-io.h
  libtransmission/peer-mgr.cc
  libtransmission/peer-msgs.cc
  libtransmission/peer-socket.cc
  libtransmission/peer-socket.h
  libtransmission/tr-buffer.h
  libtransmission/tr-utp.cc
  tests/libtransmission/handshake-test.cc
Labels: scope:core, type:refactor, notes:none

#4379 Disconnect some more signals on widgets destruction
  gtk/Application.cc
  gtk/DetailsDialog.cc
  gtk/FileList.cc
  gtk/PrefsDialog.cc
  gtk/Session.cc
Labels: scope:gtk, type:fix

#4366 macOS fix some layout issues in torrent inspector window
  macosx/Base.lproj/InfoActivityView.xib
  macosx/Base.lproj/InfoGeneralView.xib
  macosx/Base.lproj/InfoOptionsView.xib
  macosx/InfoActivityViewController.h
  macosx/InfoActivityViewController.mm
  macosx/InfoGeneralViewController.mm
  macosx/InfoOptionsViewController.h
  macosx/InfoOptionsViewController.mm
  macosx/InfoWindowController.mm
Labels: scope:mac, type:ui

#4363 Add Qt dependencies for Windows build instructions and minor fixes
  docs/Building-Transmission.md
Labels: scope:qt, type:docs

#4381 Add `ENABLE_WERROR` option for use on CI
  .github/workflows/actions.yml
  CMakeLists.txt
  gtk/CMakeLists.txt
  gtk/PathButton.cc
Labels: scope:infra, type:build

#4380 refactor: group related tr_peerIo methods together
  libtransmission/peer-io.cc
  libtransmission/peer-io.h
  libtransmission/peer-mgr.cc
Labels: scope:core, type:refactor, notes:none

#4383 fix: tear down utp _after_ peer-mgr
  libtransmission/session.cc
  libtransmission/session.h
Labels: scope:core, type:fix

#4391 Make preferences dialog non-modal
  gtk/ui/gtk3/PrefsDialog.ui
  gtk/ui/gtk4/PrefsDialog.ui
Labels: scope:gtk, type:fix, bug:regression

#4392 Don't use message dialog to display blocklist update status
  gtk/PrefsDialog.cc
  gtk/Session.cc
  gtk/Session.h
Labels: scope:gtk, type:ui

#4395 Use C++ (not C) flags for GTK client
  CMakeLists.txt
  cli/CMakeLists.txt
  daemon/CMakeLists.txt
  gtk/CMakeLists.txt
  libtransmission/CMakeLists.txt
  qt/CMakeLists.txt
  tests/libtransmission/CMakeLists.txt
  utils/CMakeLists.txt
Labels: type:fix, type:build

#4397 Fixed implicit conversion warning: __LINE__ is a long
  daemon/daemon.cc
  libtransmission/crypto-utils-ccrypto.cc
  libtransmission/log.cc
  libtransmission/log.h
  libtransmission/tr-assert.cc
  libtransmission/tr-assert.h
  libtransmission/tr-assert.mm
Labels: notes:none

#4394 fixup: 3899255
  libtransmission/handshake.cc
  libtransmission/peer-io.cc
  libtransmission/session.cc
  libtransmission/session.h
Labels: scope:core, type:fix, notes:none

#4401 perf: remove libtransmission::Buffer.vecs()
  libtransmission/peer-socket.cc
  libtransmission/tr-buffer.h
Labels: scope:core, type:perf

#4402 Move jsonsl and wildmat to third-party
  .clang-format-ignore
  CMakeLists.txt
  Transmission.xcodeproj/project.pbxproj
  libtransmission/CMakeLists.txt
  libtransmission/utils.cc
  libtransmission/variant-json.cc
  third-party/jsonsl/CMakeLists.txt
  third-party/jsonsl/jsonsl.c
  third-party/jsonsl/jsonsl.h
  third-party/wildmat/CMakeLists.txt
  third-party/wildmat/wildmat.c
  third-party/wildmat/wildmat.h
Labels: scope:core, type:refactor, notes:none

#4404 perf: reduce excess rand() calls in tr_bandwidth::phaseOne()
  libtransmission/bandwidth.cc
Labels: scope:core, type:perf

#4393 perf: lazy-calculate torrent seconds-seeding stat
  libtransmission/resume.cc
  libtransmission/session.cc
  libtransmission/torrent.cc
  libtransmission/torrent.h
Labels: scope:core, type:perf

#4408 perf: recycle Diffie-Hellman keys iff peer was unreachable
  libtransmission/handshake.cc
  libtransmission/handshake.h
  libtransmission/peer-mse.h
Labels: scope:core, type:perf

#4409 Remove unused UTP Socket code.
  libtransmission/peer-socket.cc
  libtransmission/peer-socket.h
Labels: scope:core, type:refactor, notes:none

#4412 perf: recycle DH MSE keys iff peer was unreachable
  libtransmission/handshake.cc
  libtransmission/handshake.h
  libtransmission/peer-mse.h
Labels: scope:core, type:perf

#4411 fixup! perf: reduce rand() calls in tr_bandwidth::phaseOne() (#4404)
  libtransmission/bandwidth.cc
  libtransmission/bandwidth.h
  libtransmission/crypto-utils.h
  tests/libtransmission/crypto-test-ref.h
Labels: scope:core, type:refactor

#4422 build: fix utils tests on win32 CI
  .github/workflows/actions.yml
Labels: type:build, notes:none

#4424 perf: make bandwidth.allocate() bidirectional
  libtransmission/bandwidth.cc
  libtransmission/bandwidth.h
  libtransmission/peer-mgr.cc
Labels: scope:core, type:perf

#4425 perf: cache the result of thread_current_id()
  libtransmission/session-thread.cc
Labels: scope:core, type:perf

#4416 refactor: xunused
  gtk/Utils.cc
  gtk/Utils.h
  libtransmission/log.cc
  libtransmission/log.h
  libtransmission/peer-mgr.cc
  libtransmission/session.cc
  libtransmission/transmission.h
Labels: scope:gtk, scope:qt, scope:core, type:refactor

#4415 refactor: tr_rand_buffer(), tr_rand_int() again
  libtransmission/announcer.cc
  libtransmission/crypto-utils-ccrypto.cc
  libtransmission/crypto-utils-cyassl.cc
  libtransmission/crypto-utils-openssl.cc
  libtransmission/crypto-utils-polarssl.cc
  libtransmission/crypto-utils.cc
  libtransmission/crypto-utils.h
  libtransmission/file-win32.cc
  libtransmission/session.cc
  libtransmission/tr-dht.cc
  libtransmission/tr-utp.cc
  tests/libtransmission/bitfield-test.cc
  tests/libtransmission/crypto-test-ref.h
  tests/libtransmission/crypto-test.cc
  tests/libtransmission/magnet-metainfo-test.cc
  tests/libtransmission/torrent-metainfo-test.cc
  tests/libtransmission/utils-test.cc
  tests/libtransmission/variant-test.cc
  tests/libtransmission/web-utils-test.cc
Labels: scope:core, type:refactor

#4418 Removed ToolbarSegmentedCell
  Transmission.xcodeproj/project.pbxproj
  macosx/CMakeLists.txt
  macosx/Controller.mm
  macosx/ToolbarSegmentedCell.h
  macosx/ToolbarSegmentedCell.mm
Labels: scope:mac, type:refactor

#4431 perf: cache peer and atom counts instead of always recomputing them
  libtransmission/peer-common.h
  libtransmission/peer-mgr.cc
Labels: scope:core, type:perf

#4414 refactor: Addressed various warnings
  Transmission.xcodeproj/project.pbxproj
  daemon/daemon.cc
  daemon/daemon.h
  macosx/BadgeView.h
  macosx/BadgeView.mm
  macosx/Badger.h
  macosx/Badger.mm
  macosx/BlocklistDownloaderViewController.h
  macosx/BlocklistDownloaderViewController.mm
  macosx/CMakeLists.txt
  macosx/Controller.mm
  macosx/CreatorWindowController.mm
  macosx/DragOverlayWindow.h
  macosx/DragOverlayWindow.mm
  macosx/FileListNode.mm
  macosx/FileOutlineController.mm
  macosx/GroupsController.mm
  macosx/InfoActivityViewController.mm
  macosx/InfoOptionsViewController.mm
  macosx/InfoPeersViewController.mm
  macosx/InfoWindowController.mm
  macosx/MessageWindowController.mm
  macosx/NSStringAdditions.mm
  macosx/PiecesView.mm
  macosx/QuickLookPlugin/GenerateThumbnailForURL.mm
  macosx/QuickLookPlugin/main.cc
  macosx/SparkleProxy.mm
  macosx/StatsWindowController.h
  macosx/StatsWindowController.mm
  macosx/Torrent.mm
  macosx/TorrentTableView.h
  macosx/TrackerCell.mm
  macosx/WebSeedTableView.mm
Labels: type:refactor, notes:none

#4430 Use `Gio::List{Model,Store}` for torrents
  gtk/Application.cc
  gtk/CMakeLists.txt
  gtk/FilterBar.cc
  gtk/FilterBar.h
  gtk/Flags.h
  gtk/ListModelAdapter.cc
  gtk/ListModelAdapter.h
  gtk/MainWindow.cc
  gtk/MainWindow.h
  gtk/OptionsDialog.cc
  gtk/Session.cc
  gtk/Session.h
  gtk/Torrent.cc
  gtk/Torrent.h
  gtk/TorrentCellRenderer.cc
  gtk/TorrentCellRenderer.h
  gtk/TorrentFilter.cc
  gtk/TorrentFilter.h
  gtk/TorrentSorter.cc
  gtk/TorrentSorter.h
  gtk/Utils.cc
  gtk/Utils.h
Labels: scope:gtk, type:refactor

#4434 refactor: add tr_torrent::do_idle_work()
  libtransmission/peer-mgr.cc
  libtransmission/torrent.cc
  libtransmission/torrent.h
Labels: scope:core, type:refactor, notes:none

#4417 Add missing GroupPopUpButtonCell and PriorityPopUpButtonCell to CMakeLists.txt
  macosx/CMakeLists.txt
  macosx/GroupPopUpButtonCell.h
  macosx/GroupPopUpButtonCell.mm
  macosx/PriorityPopUpButtonCell.h
  macosx/PriorityPopUpButtonCell.mm
Labels: scope:mac, type:build

#4444 Removing WebSeedTableView.mm and InfoViewController.h from libtransmission
  Transmission.xcodeproj/project.pbxproj
Labels: type:build, notes:none

#4440 macOS remove defunct share code
  macosx/Base.lproj/MainMenu.xib
  macosx/Controller.mm
Labels: scope:mac, type:refactor

#4441 Addressed lockFocus is deprecated
  macosx/PiecesView.mm
Labels: scope:mac, needs code review

#4445 fixup: peer counts
  libtransmission/peer-common.h
  libtransmission/peer-mgr.cc
  libtransmission/peer-msgs.cc
  libtransmission/peer-msgs.h
Labels: scope:core, type:fixup

#4447 fix: 4.0.0-beta.2 regression transmission-show --scrape did not exit cleanly
  libtransmission/session.cc
  libtransmission/session.h
  libtransmission/web.cc
  libtransmission/web.h
  utils/show.cc
Labels: scope:show, type:fix

#4453 fix: sonarcloud
  libtransmission/announcer.cc
  libtransmission/net.h
  libtransmission/peer-mgr.cc
  libtransmission/peer-socket.cc
  libtransmission/peer-socket.h
  libtransmission/web.cc
Labels: scope:core, type:refactor

#4451 Fixed crash on exit while downloading from webseed
  libtransmission/webseed.cc
Labels: scope:core

#4454 Fix tr_torrent_view incorrectly returning is_folder false for single files in a single folder
  libtransmission/torrent.cc
Labels: scope:core

#4457 refactor: add TR_CONSTEXPR20 to make future C++20 migration easier
  libtransmission/announce-list.h
  libtransmission/bitfield.h
  libtransmission/file-piece-map.h
  libtransmission/magnet-metainfo.h
  libtransmission/makemeta.h
  libtransmission/peer-io.h
  libtransmission/peer-mgr.cc
  libtransmission/session.h
  libtransmission/torrent-files.h
  libtransmission/torrent-metainfo.h
  libtransmission/torrent.h
  libtransmission/torrents.cc
  libtransmission/torrents.h
  libtransmission/tr-buffer.h
  libtransmission/tr-macros.h
  libtransmission/tr-popcount.h
  qt/FileTreeItem.h
  qt/Torrent.h
Labels: scope:qt, scope:core, type:refactor, notes:none

#4455 Add missing GroupTextCell.h
  macosx/CMakeLists.txt
Labels: scope:mac, type:build

#4460 macOS - use autolayout in statistics view
  macosx/StatsWindow.xib
  macosx/StatsWindowController.mm
Labels: scope:mac, type:fix, type:refactor, type:ui

#4448 refactor ActivityView
  macosx/InfoActivityViewController.mm
  macosx/InfoOptionsViewController.mm
Labels: scope:mac, type:refactor, type:fixup

#4458 set selected torrentTableView backgroundstyle
  macosx/TorrentTableView.mm
Labels: scope:mac, type:fix, type:ui

#4462 refactor: add tr_address.is_global_unicast_address()
  libtransmission/net.cc
  libtransmission/net.h
  tests/libtransmission/net-test.cc
Labels: scope:core, type:refactor, type:test

#4464 refactor: tr_globalIPv6() returns a std::optional<tr_address>
  libtransmission/announcer-http.cc
  libtransmission/net.cc
  libtransmission/net.h
  libtransmission/peer-msgs.cc
  libtransmission/session.h
  libtransmission/tr-udp.cc
  tests/libtransmission/net-test.cc
Labels: scope:core, type:refactor

#4477 Include individual headers (GTK client)
  gtk/Actions.cc
  gtk/Actions.h
  gtk/Application.cc
  gtk/Application.h
  gtk/DetailsDialog.cc
  gtk/DetailsDialog.h
  gtk/Dialogs.cc
  gtk/Dialogs.h
  gtk/FaviconCache.cc
  gtk/FaviconCache.h
  gtk/FileList.cc
  gtk/FileList.h
  gtk/FilterBar.cc
  gtk/FilterBar.h
  gtk/FreeSpaceLabel.cc
  gtk/FreeSpaceLabel.h
  gtk/IconCache.cc
  gtk/IconCache.h
  gtk/ListModelAdapter.h
  gtk/MainWindow.cc
  gtk/MainWindow.h
  gtk/MakeDialog.cc
  gtk/MakeDialog.h
  gtk/MessageLogWindow.cc
  gtk/MessageLogWindow.h
  gtk/Notify.cc
  gtk/Notify.h
  gtk/OptionsDialog.cc
  gtk/OptionsDialog.h
  gtk/PathButton.cc
  gtk/PathButton.h
  gtk/Prefs.cc
  gtk/PrefsDialog.cc
  gtk/PrefsDialog.h
  gtk/RelocateDialog.cc
  gtk/RelocateDialog.h
  gtk/Session.cc
  gtk/Session.h
  gtk/StatsDialog.cc
  gtk/StatsDialog.h
  gtk/SystemTrayIcon.cc
  gtk/SystemTrayIcon.h
  gtk/Torrent.cc
  gtk/Torrent.h
  gtk/TorrentCellRenderer.cc
  gtk/TorrentCellRenderer.h
  gtk/TorrentFilter.h
  gtk/TorrentSorter.h
  gtk/Utils.cc
  gtk/Utils.h
  gtk/main.cc
Labels: scope:gtk, type:refactor, notes:none

#4437 Update qt cmakelists to include support for building svg
  .github/workflows/actions.yml
  CMakeLists.txt
  dist/msi/CMakeLists.txt
Labels: type:build

#4473 Fix BlockListDownloader unzipFrom
  macosx/BlocklistDownloader.mm
Labels: scope:mac

#4489 Fix progress bars positioning in Qt client on Mac
  qt/FileTreeDelegate.cc
  qt/StyleHelper.cc
  qt/StyleHelper.h
  qt/TorrentDelegate.cc
  qt/TorrentDelegateMin.cc
Labels: scope:qt, os:mac, type:ui

#4485 Fix/suppress clang-tidy issues in recently-added code (GTK client)
  gtk/FilterBar.cc
  gtk/ListModelAdapter.cc
  gtk/ListModelAdapter.h
  gtk/MainWindow.cc
  gtk/MainWindow.h
  gtk/Session.cc
  gtk/Torrent.cc
  gtk/TorrentFilter.cc
  gtk/TorrentSorter.cc
  gtk/Utils.cc
Labels: scope:gtk, type:refactor, notes:none

#4493 Move GTK compatibility definitions into a separate header
  gtk/.clang-format
  gtk/Actions.h
  gtk/Application.cc
  gtk/CMakeLists.txt
  gtk/DetailsDialog.cc
  gtk/Dialogs.cc
  gtk/FileList.cc
  gtk/FilterBar.h
  gtk/GtkCompat.h
  gtk/IconCache.cc
  gtk/ListModelAdapter.cc
  gtk/ListModelAdapter.h
  gtk/MainWindow.cc
  gtk/MakeDialog.cc
  gtk/MessageLogWindow.cc
  gtk/Notify.cc
  gtk/OptionsDialog.cc
  gtk/PathButton.cc
  gtk/PathButton.h
  gtk/Prefs.cc
  gtk/PrefsDialog.cc
  gtk/RelocateDialog.cc
  gtk/Session.h
  gtk/StatsDialog.cc
  gtk/TorrentCellRenderer.cc
  gtk/TorrentCellRenderer.h
  gtk/TorrentFilter.cc
  gtk/TorrentFilter.h
  gtk/TorrentSorter.cc
  gtk/TorrentSorter.h
  gtk/Utils.h
  gtk/main.cc
Labels: scope:gtk, type:refactor, notes:none

#4495 Drop obsolete CyaSSL and PolarSSL crypto backends
  CMakeLists.txt
  cmake/FindCyaSSL.cmake
  cmake/FindMbedTLS.cmake
  cmake/FindPolarSSL.cmake
  cmake/FindWolfSSL.cmake
  libtransmission/CMakeLists.txt
  libtransmission/crypto-utils-mbedtls.cc
  libtransmission/crypto-utils-wolfssl.cc
Labels: scope:core, type:feat

#4494 fix: fix omitted fmt call
  libtransmission/tr-udp.cc
Labels: type:fixup

#4461 Fixed dead code in "Open Torrent Address"
  macosx/URLSheetWindowController.mm
Labels: scope:mac

#4502 fix: remove announce ipv4 ipv6 query params
  libtransmission/announcer-http.cc
  libtransmission/session.h
Labels: scope:core, type:refactor, bep-compliance
