Repository transmission/transmission, pull requests merged in 2022-03, with the labels that each got.

#2721 Delay start of daemon systemd service until network is configured
  daemon/transmission-daemon.service
Labels: scope:daemon, type:fix

#2722 refactor: tr_torrents
  Transmission.xcodeproj/project.pbxproj
  libtransmission/CMakeLists.txt
  libtransmission/announcer.cc
  libtransmission/handshake.cc
  libtransmission/peer-mgr.cc
  libtransmission/rpcimpl.cc
  libtransmission/session.cc
  libtransmission/session.h
  libtransmission/torrent.cc
  libtransmission/torrents.cc
  libtransmission/torrents.h
  libtransmission/tr-dht.cc
  libtransmission/tr-lpd.cc
  tests/libtransmission/CMakeLists.txt
  tests/libtransmission/assets/debian-11.2.0-amd64-DVD-1.iso.torrent
  tests/libtransmission/assets/ubuntu-18.04.6-desktop-amd64.iso.torrent
  tests/libtransmission/assets/ubuntu-20.04.4-desktop-amd64.iso.torrent
  tests/libtransmission/torrents-test.cc
Labels: scope:core, type:perf

#2735 fix: webseed assertion failures
  libtransmission/torrent.cc
  libtransmission/torrents.cc
  libtransmission/webseed.cc
Labels: scope:core, type:fixup

#2737 perf: use condition variables during tr thread startup
  libtransmission/announcer-udp.cc
  libtransmission/session.cc
  libtransmission/session.h
  libtransmission/trevent.cc
Labels: scope:core, type:perf

#2739 feat: tr_runInEventThread() now takes std::function, typesafe args
  libtransmission/announcer-http.cc
  libtransmission/peer-io.cc
  libtransmission/rpc-server.cc
  libtransmission/session.cc
  libtransmission/torrent.cc
  libtransmission/tr-dht.cc
  libtransmission/trevent.cc
  libtransmission/trevent.h
  libtransmission/webseed.cc
Labels: scope:core, type:feat

#2740 refactor: remove redundant MAX_BLOCK_SIZE constant
  libtransmission/cache.cc
  libtransmission/peer-common.h
  libtransmission/peer-io.cc
  libtransmission/torrent.cc
Labels: scope:core, type:refactor

#19 Added ability to filter on error status.
  macosx/Controller.mm
  macosx/FilterBar.xib
  macosx/FilterBarController.h
  macosx/FilterBarController.mm
Labels: scope:mac, feature disparity, needs update, type:feat

#2747 fix: rpc-server shutdown assertion failure
  libtransmission/rpc-server.cc
Labels: scope:core, type:fixup

#2748 chore: add more descriptive assertion in bitfield
  libtransmission/bitfield.cc
  libtransmission/bitfield.h
Labels: scope:core, type:refactor

#2749 refactor: remove deep logging
  daemon/daemon.cc
  gtk/MessageLogWindow.cc
  libtransmission/announcer-common.h
  libtransmission/announcer-http.cc
  libtransmission/announcer-udp.cc
  libtransmission/announcer.cc
  libtransmission/bandwidth.cc
  libtransmission/cache.cc
  libtransmission/fdlimit.cc
  libtransmission/handshake.cc
  libtransmission/log.cc
  libtransmission/log.h
  libtransmission/net.cc
  libtransmission/peer-io.cc
  libtransmission/peer-mgr.cc
  libtransmission/peer-msgs.cc
  libtransmission/port-forwarding.cc
  libtransmission/rpc-server.cc
  libtransmission/rpcimpl.cc
  libtransmission/session.cc
  libtransmission/stats.cc
  libtransmission/torrent-magnet.cc
  libtransmission/torrent.cc
  libtransmission/tr-lpd.cc
  libtransmission/tr-udp.cc
  libtransmission/tr-utp.cc
  libtransmission/transmission.h
  libtransmission/trevent.cc
  libtransmission/utils.cc
  libtransmission/web.cc
  tests/libtransmission/announcer-test.cc
  tests/libtransmission/torrent-metainfo-test.cc
Labels: scope:core, type:refactor

#2755 refactor: set logging levels
  daemon/daemon.cc
  libtransmission/announcer-http.cc
  libtransmission/announcer.cc
  libtransmission/bandwidth.cc
  libtransmission/benc.h
  libtransmission/blocklist.cc
  libtransmission/cache.cc
  libtransmission/fdlimit.cc
  libtransmission/handshake.cc
  libtransmission/inout.cc
  libtransmission/log.cc
  libtransmission/log.h
  libtransmission/makemeta.cc
  libtransmission/natpmp.cc
  libtransmission/net.cc
  libtransmission/net.h
  libtransmission/peer-io.cc
  libtransmission/peer-io.h
  libtransmission/peer-mgr.cc
  libtransmission/platform.cc
  libtransmission/resume.cc
  libtransmission/session-id.cc
  libtransmission/session.cc
  libtransmission/torrent-metainfo.cc
  libtransmission/torrent.h
  libtransmission/tr-dht.cc
  libtransmission/upnp.cc
  libtransmission/utils.cc
  libtransmission/verify.cc
  macosx/Torrent.mm
  utils/remote.cc
Labels: scope:core, type:refactor

#2756 refactor: stop logging repetitive warnings
  libtransmission/log.cc
Labels: scope:core, type:feat

#2762 fix: memory corruption in RPC when fetching torrent piece info
  libtransmission/rpcimpl.cc
Labels: scope:core, type:fixup

#2764 fixup: macos log error
  Transmission.xcodeproj/project.pbxproj
  gtk/MessageLogWindow.cc
  macosx/MessageWindow.xib
  macosx/MessageWindowController.mm
Labels: scope:mac, type:fixup

#2773 refactor: fmt part 3
  daemon/daemon.cc
  gtk/Application.cc
  gtk/FileList.cc
  gtk/MakeDialog.cc
  gtk/MessageLogWindow.cc
  gtk/Session.cc
  libtransmission/announcer-http.cc
  libtransmission/announcer-udp.cc
  libtransmission/announcer.cc
  libtransmission/blocklist.cc
  libtransmission/crypto-utils-ccrypto.cc
  libtransmission/crypto-utils-cyassl.cc
  libtransmission/crypto-utils-openssl.cc
  libtransmission/crypto-utils-polarssl.cc
  libtransmission/fdlimit.cc
  libtransmission/file-posix.cc
  libtransmission/inout.cc
  libtransmission/makemeta.cc
  libtransmission/natpmp.cc
  libtransmission/net.cc
  libtransmission/peer-mgr.h
  libtransmission/port-forwarding.cc
  libtransmission/resume.cc
  libtransmission/rpc-server.cc
  libtransmission/rpcimpl.cc
  libtransmission/session-id.cc
  libtransmission/torrent-metainfo.cc
  libtransmission/torrent.cc
  libtransmission/tr-dht.cc
  libtransmission/tr-lpd.cc
  libtransmission/utils.cc
  libtransmission/variant-json.cc
  libtransmission/variant.cc
Labels: scope:gtk, scope:core, i18n, type:refactor

#2774 refactor: fmt pt 4
  daemon/daemon.cc
  gtk/Session.cc
  libtransmission/rpc-server.cc
  libtransmission/torrent.cc
  libtransmission/tr-udp.cc
  libtransmission/tr-utp.cc
  libtransmission/variant-json.cc
  libtransmission/watchdir-generic.cc
  libtransmission/watchdir-inotify.cc
  libtransmission/watchdir-kqueue.cc
  libtransmission/watchdir-win32.cc
  libtransmission/watchdir.cc
  macosx/Controller.mm
Labels: scope:core, i18n, type:refactor

#2780 fixup! fix: ensure all bytes read / written to file (#2682)
  libtransmission/file-posix.cc
Labels: scope:core, type:fixup

#2770 fix: calculate ratio as uploaded / total size
  gtk/DetailsDialog.cc
  libtransmission/torrent.cc
  libtransmission/torrent.h
  libtransmission/transmission.h
  macosx/TorrentGroup.mm
  qt/DetailsDialog.cc
  utils/remote.cc
  web/src/inspector.js
Labels: scope:gtk, scope:qt, scope:mac, scope:web, type:fix

#2776 refactor: remove remaining vararg log messages
  daemon/daemon.cc
  gtk/Application.cc
  gtk/MessageLogWindow.cc
  gtk/Session.cc
  libtransmission/announcer-http.cc
  libtransmission/announcer-udp.cc
  libtransmission/announcer.cc
  libtransmission/cache.cc
  libtransmission/crypto-utils-ccrypto.cc
  libtransmission/crypto-utils-cyassl.cc
  libtransmission/crypto-utils-openssl.cc
  libtransmission/crypto-utils-polarssl.cc
  libtransmission/foo
  libtransmission/handshake.cc
  libtransmission/log.cc
  libtransmission/log.h
  libtransmission/natpmp.cc
  libtransmission/net.cc
  libtransmission/peer-io.cc
  libtransmission/peer-mgr.cc
  libtransmission/port-forwarding.cc
  libtransmission/rpc-server.cc
  libtransmission/rpcimpl.cc
  libtransmission/torrent-magnet.cc
  libtransmission/torrent-metainfo.cc
  libtransmission/torrent.h
  libtransmission/tr-dht.cc
  libtransmission/tr-lpd.cc
  libtransmission/tr-udp.cc
  libtransmission/tr-utp.cc
  libtransmission/transmission.h
  libtransmission/trevent.cc
  libtransmission/upnp.cc
  libtransmission/watchdir-generic.cc
  libtransmission/watchdir-inotify.cc
  libtransmission/watchdir-kqueue.cc
  libtransmission/watchdir-win32.cc
  libtransmission/watchdir.cc
  libtransmission/web.cc
  macosx/Torrent.mm
  utils/create.cc
  utils/edit.cc
  utils/remote.cc
  utils/show.cc
Labels: scope:daemon, scope:create, scope:edit, scope:show, scope:core, type:refactor

#2778 fix: don't crash when processing multiple errors
  libtransmission/announcer-http.cc
Labels: scope:core, type:fixup

#2783 refactor: aggregate bandwidth objects
  libtransmission/bandwidth.cc
  libtransmission/bandwidth.h
  libtransmission/interned-string.h
  libtransmission/peer-mgr.cc
  libtransmission/rpcimpl.cc
  libtransmission/session.cc
  libtransmission/session.h
  libtransmission/torrent.cc
  libtransmission/torrent.h
  libtransmission/webseed.cc
Labels: scope:core, type:refactor

#2784 docs: add pid-file to transmission-daemon manpage
  daemon/transmission-daemon.1
Labels: scope:daemon, type:docs

#2785 feat: handle new log levels in transmission-daemon's cli invocation
  daemon/daemon.cc
  libtransmission/log.cc
  libtransmission/log.h
Labels: scope:daemon, type:feat

#2786 perf: avoid excess filesystem checks
  libtransmission/net.cc
  libtransmission/torrent-metainfo.h
  libtransmission/torrent.cc
  libtransmission/torrent.h
Labels: scope:core, type:perf

#2788 refactor: use fmt to build the GTK client's user-visible strings
  daemon/daemon.cc
  gtk/Application.cc
  gtk/DetailsDialog.cc
  gtk/FileList.cc
  gtk/FilterBar.cc
  gtk/FreeSpaceLabel.cc
  gtk/MainWindow.cc
  gtk/MakeDialog.cc
  gtk/MessageLogWindow.cc
  gtk/OptionsDialog.cc
  gtk/PrefsDialog.cc
  gtk/RelocateDialog.cc
  gtk/Session.cc
  gtk/StatsDialog.cc
  gtk/TorrentCellRenderer.cc
  gtk/Utils.cc
  gtk/Utils.h
  libtransmission/announce-list.cc
  libtransmission/makemeta.h
  libtransmission/platform.h
  libtransmission/torrent-magnet.cc
  libtransmission/transmission.h
  libtransmission/watchdir.cc
  qt/WatchDir.cc
  tests/libtransmission/announce-list-test.cc
  tests/libtransmission/makemeta-test.cc
  tests/libtransmission/move-test.cc
  tests/libtransmission/rename-test.cc
  utils/show.cc
Labels: scope:gtk, type:refactor

#2792 refactor: tr_sys_path_dirname returns a std::string
  libtransmission/announce-list.cc
  libtransmission/blocklist.cc
  libtransmission/fdlimit.cc
  libtransmission/file-posix.cc
  libtransmission/file-win32.cc
  libtransmission/file.h
  libtransmission/log.cc
  libtransmission/makemeta.cc
  libtransmission/platform.cc
  libtransmission/rpcimpl.cc
  libtransmission/session.cc
  libtransmission/torrent.cc
  libtransmission/trevent.cc
  libtransmission/utils.cc
  tests/libtransmission/announce-list-test.cc
  tests/libtransmission/blocklist-test.cc
  tests/libtransmission/copy-test.cc
  tests/libtransmission/error-test.cc
  tests/libtransmission/file-test.cc
  tests/libtransmission/makemeta-test.cc
  tests/libtransmission/move-test.cc
  tests/libtransmission/rename-test.cc
  tests/libtransmission/subprocess-test.cc
  tests/libtransmission/test-fixtures.h
  tests/libtransmission/torrent-metainfo-test.cc
  tests/libtransmission/utils-test.cc
  utils/create.cc
Labels: scope:create, scope:core, type:refactor

#2802 perf: tell curl_share to share everything
  libtransmission/web.cc
Labels: scope:core, type:perf

#2804 fix: sonarcloud warnings
  gtk/TorrentCellRenderer.cc
  libtransmission/cache.cc
  libtransmission/log.cc
  libtransmission/peer-mgr.cc
  libtransmission/rpcimpl.cc
  libtransmission/torrent.cc
  libtransmission/torrents.cc
  libtransmission/torrents.h
  libtransmission/webseed.cc
Labels: scope:gtk, scope:core, type:fix

#2809 fix: set the utp state change log level to trace
  libtransmission/peer-io.cc
Labels: scope:core, type:fixup

#2810 feat: add tr_strbuf
  CMakeLists.txt
  Transmission.xcodeproj/project.pbxproj
  daemon/CMakeLists.txt
  gtk/CMakeLists.txt
  libtransmission/CMakeLists.txt
  libtransmission/tr-strbuf.h
  tests/libtransmission/CMakeLists.txt
  tests/libtransmission/strbuf-test.cc
  utils/CMakeLists.txt
Labels: scope:core, type:refactor

#2811 test: fix file-info test edge case
  tests/libtransmission/file-test.cc
Labels: type:test

#2805 Add ability to change piece size during torrent creation in MacOS GUI…
  .gitignore
  macosx/CreatorWindowController.h
  macosx/CreatorWindowController.mm
  macosx/da.lproj/Creator.xib
  macosx/de.lproj/Creator.xib
  macosx/en.lproj/Creator.xib
  macosx/es.lproj/Creator.xib
  macosx/fr.lproj/Creator.xib
  macosx/it.lproj/Creator.xib
  macosx/nl.lproj/Creator.xib
  macosx/pt_PT.lproj/Creator.xib
  macosx/ru.lproj/Creator.xib
  macosx/tr.lproj/Creator.xib
Labels: enhancement, scope:mac

#2815 fix: sonarcloud warnings
  gtk/MessageLogWindow.cc
  gtk/PrefsDialog.cc
  gtk/TorrentCellRenderer.cc
  libtransmission/file-posix.cc
  libtransmission/log.cc
  libtransmission/peer-mgr.cc
  libtransmission/rpcimpl.cc
  libtransmission/webseed.cc
Labels: scope:gtk, scope:core, type:fix

#2819 fix: missing fmt::arg calls in GTK client
  gtk/TorrentCellRenderer.cc
Labels: scope:gtk, type:fixup

#2820 fix: set peer-io destructor log level to trace
  libtransmission/peer-io.cc
Labels: scope:core, type:fixup

#2821 feat: strbuf features
  libtransmission/tr-strbuf.h
  tests/libtransmission/strbuf-test.cc
Labels: scope:core, type:refactor, type:perf

#2822 refactor: tr_loadFile() tr_saveFile() take a std::string_view filename arg
  libtransmission/file.h
  libtransmission/platform.cc
  libtransmission/resume.cc
  libtransmission/rpc-server.cc
  libtransmission/rpcimpl.cc
  libtransmission/session.cc
  libtransmission/torrent-ctor.cc
  libtransmission/torrent-metainfo.cc
  libtransmission/utils.cc
  libtransmission/utils.h
  libtransmission/variant.cc
  tests/libtransmission/announce-list-test.cc
  tests/libtransmission/torrent-metainfo-test.cc
  tests/libtransmission/utils-test.cc
  utils/remote.cc
Labels: scope:core, type:refactor, type:perf

#2824 refactor: tr_variantToFile() takes a string_view filename
  libtransmission/announce-list.cc
  libtransmission/block-info.h
  libtransmission/session.cc
  libtransmission/stats.cc
  libtransmission/tr-dht.cc
  libtransmission/variant.cc
  libtransmission/variant.h
  qt/Prefs.cc
  utils/edit.cc
Labels: scope:edit, scope:qt, scope:core, type:perf

#2827 refactor: make err arg optional in tr_sys_* funcs
  cli/cli.cc
  daemon/daemon.cc
  gtk/OptionsDialog.cc
  libtransmission/blocklist.cc
  libtransmission/fdlimit.cc
  libtransmission/file-posix.cc
  libtransmission/file.h
  libtransmission/inout.cc
  libtransmission/log.cc
  libtransmission/makemeta.cc
  libtransmission/platform.cc
  libtransmission/rpcimpl.cc
  libtransmission/session-id.cc
  libtransmission/session.cc
  libtransmission/torrent-magnet.cc
  libtransmission/torrent-metainfo.cc
  libtransmission/torrent.cc
  libtransmission/utils.cc
  libtransmission/verify.cc
  libtransmission/watchdir.cc
  tests/libtransmission/blocklist-test.cc
  tests/libtransmission/copy-test.cc
  tests/libtransmission/file-test.cc
  tests/libtransmission/makemeta-test.cc
  tests/libtransmission/rename-test.cc
  tests/libtransmission/subprocess-test-program.cc
  tests/libtransmission/subprocess-test.cc
  tests/libtransmission/test-fixtures.h
  tests/libtransmission/watchdir-test.cc
Labels: scope:cli, scope:daemon, scope:gtk, scope:core, type:test

#2829 refactor: add fmt::formatters
  Transmission.xcodeproj/project.pbxproj
  libtransmission/announcer-udp.cc
  libtransmission/interned-string.h
  libtransmission/rpcimpl.cc
  libtransmission/torrent.cc
  libtransmission/tr-strbuf.h
  libtransmission/utils.cc
  tests/libtransmission/peer-mgr-active-requests-test.cc
  tests/libtransmission/quark-test.cc
  tests/libtransmission/strbuf-test.cc
Labels: scope:core, type:refactor

#2833 refactor: strbuf for metainfo files
  libtransmission/announce-list.cc
  libtransmission/announce-list.h
  libtransmission/announcer-http.cc
  libtransmission/announcer.cc
  libtransmission/magnet-metainfo.cc
  libtransmission/magnet-metainfo.h
  libtransmission/resume.cc
  libtransmission/rpcimpl.cc
  libtransmission/session.cc
  libtransmission/torrent-ctor.cc
  libtransmission/torrent-magnet.cc
  libtransmission/torrent-metainfo.cc
  libtransmission/torrent-metainfo.h
  libtransmission/torrent.cc
  libtransmission/torrent.h
  libtransmission/utils.cc
  libtransmission/web-utils.cc
  libtransmission/web-utils.h
  libtransmission/webseed.cc
  tests/libtransmission/torrent-metainfo-test.cc
  tests/libtransmission/torrents-test.cc
  utils/show.cc
Labels: scope:core, type:refactor, type:perf

#2836 refactor: add tracer assertions or bug #2727
  libtransmission/announcer.cc
  libtransmission/completion.h
  libtransmission/peer-mgr.cc
  libtransmission/peer-msgs.cc
  libtransmission/resume.cc
  libtransmission/rpcimpl.cc
  libtransmission/torrent-magnet.cc
  libtransmission/torrent.cc
  libtransmission/torrent.h
Labels: scope:core, type:refactor

#2837 fix: sonarcloud
  CMakeLists.txt
  libtransmission/interned-string.h
  libtransmission/log.cc
  libtransmission/peer-io.cc
  libtransmission/resume.cc
  libtransmission/session.cc
  libtransmission/tr-dht.cc
  libtransmission/tr-strbuf.h
  libtransmission/trevent.cc
  libtransmission/web-utils.h
  utils/remote.cc
Labels: scope:core, type:fix

#2838 fix: file progress in GTK Details dialog
  gtk/FileList.cc
Labels: scope:gtk, type:fix

#2841 test: fix race condition in move-test
  libtransmission/torrent-metainfo.h
  tests/libtransmission/move-test.cc
  tests/libtransmission/rename-test.cc
  tests/libtransmission/rpc-test.cc
  tests/libtransmission/test-fixtures.h
Labels: type:fix, type:test

#2843 fix: tr_strbuf move op loses zero-termination
  libtransmission/tr-strbuf.h
  tests/libtransmission/strbuf-test.cc
Labels: scope:core, type:fixup

#2839 perf: replace tr_torrentFindFile2() with tr_torrrent.findFile()
  libtransmission/inout.cc
  libtransmission/torrent.cc
  libtransmission/torrent.h
  libtransmission/verify.cc
Labels: scope:core, type:perf

#2845 refactor: prefer FMT_STRING
  gtk/Application.cc
  gtk/DetailsDialog.cc
  gtk/FileList.cc
  gtk/FreeSpaceLabel.cc
  gtk/MakeDialog.cc
  gtk/PrefsDialog.cc
  gtk/TorrentCellRenderer.cc
  gtk/Utils.cc
  libtransmission/announcer-http.cc
  libtransmission/error.cc
  libtransmission/file-posix.cc
  libtransmission/inout.cc
  libtransmission/log.cc
  libtransmission/makemeta.cc
  libtransmission/peer-msgs.cc
  libtransmission/resume.cc
  libtransmission/subprocess-posix.cc
  libtransmission/torrent-metainfo.cc
  libtransmission/webseed.cc
Labels: scope:gtk, scope:core, type:refactor

#2851 fix: three asan issues
  libtransmission/magnet-metainfo.cc
  tests/libtransmission/completion-test.cc
  tests/libtransmission/torrents-test.cc
Labels: scope:core, type:test, type:fixup

#2852 Bandwidth group are written to a dict, not to a list.
  libtransmission/session.cc
Labels: scope:core, type:fixup

#2853 fix: getBandwidthGroup() uses the wrong Bandwidth group
  libtransmission/session.cc
Labels: scope:core, type:fixup
