Repository transmission/transmission, pull requests merged in 2022-07, with the labels that each got.

#3380 Add basic support for v2 hashes in transmission-show
  CMakeLists.txt
  libtransmission/crypto-utils-ccrypto.cc
  libtransmission/crypto-utils-cyassl.cc
  libtransmission/crypto-utils-openssl.cc
  libtransmission/crypto-utils-polarssl.cc
  libtransmission/crypto-utils.cc
  libtransmission/crypto-utils.h
  libtransmission/magnet-metainfo.cc
  libtransmission/magnet-metainfo.h
  libtransmission/torrent-metainfo.cc
  libtransmission/torrent-metainfo.h
  libtransmission/tr-macros.h
  tests/libtransmission/crypto-test-ref.h
  tests/libtransmission/crypto-test.cc
  tests/utils/CMakeLists.txt
  tests/utils/assets/Inner_Sanctum_movie_archive.show
  tests/utils/assets/Thor_and_the_Amazon_Women.avi.show
  tests/utils/assets/bittorrent-v2-hybrid-test.show
  tests/utils/assets/bittorrent-v2-hybrid-test.torrent
  tests/utils/assets/bittorrent-v2-test.show
  tests/utils/assets/ubuntu-20.04.3-desktop-amd64.iso.show
  utils/show.cc
Labels: enhancement, scope:show, scope:core

#3382 Fix Warn -> Warning
  macosx/MessageWindowController.mm
  macosx/da.lproj/Localizable.strings
  macosx/de.lproj/Localizable.strings
  macosx/en.lproj/Localizable.strings
  macosx/es.lproj/Localizable.strings
  macosx/fr.lproj/Localizable.strings
  macosx/it.lproj/Localizable.strings
  macosx/nl.lproj/Localizable.strings
  macosx/pt_PT.lproj/Localizable.strings
  macosx/ru.lproj/Localizable.strings
  macosx/tr.lproj/Localizable.strings
Labels: scope:mac, i18n

#3272 docs: draft 4.0.0-beta.1 news
  news/news-2.42-and-older.md
  news/news-2.50.md
  news/news-2.51.md
  news/news-2.52.md
  news/news-2.60.md
  news/news-2.61.md
  news/news-2.70.md
  news/news-2.71.md
  news/news-2.72.md
  news/news-2.73.md
  news/news-2.74.md
  news/news-2.75.md
  news/news-2.76.md
  news/news-2.77.md
  news/news-2.80.md
  news/news-2.81.md
  news/news-2.82.md
  news/news-2.83.md
  news/news-2.84.md
  news/news-2.90.md
  news/news-2.91.md
  news/news-2.92.md
  news/news-2.93.md
  news/news-2.94.md
  news/news-3.00.md
  news/news-4.0.0-beta-1.md
Labels: type:docs

#3390 docs: fix installation of release notes
  CMakeLists.txt
Labels: type:fix, type:build

#3384 refactor: add tr_peer.requestBlocks()
  libtransmission/peer-common.h
  libtransmission/peer-msgs.cc
  libtransmission/webseed.cc
Labels: scope:core, type:refactor

#3360 [macOS] Use NSAlert APIs to show alert suppression checkbox
  macosx/Controller.mm
Labels: enhancement, scope:mac, type:ui

#3399 fixup! feat: use jimmac ratio icon in qt client
  dist/msi/CMakeLists.txt
  dist/msi/ConvertTo-Icon.ps1
  dist/msi/Transmission.wxs
  dist/msi/UtilityFunctions.cmake
  qt/icons/SOURCES.md
  qt/icons/transmission.ico
Labels: scope:qt, os:windows, type:build, type:fixup

#3404 fix: Instantiate `tr_parseNum()` template using basic types
  libtransmission/utils.cc
Labels: scope:core, type:fixup

#3406 fix: assertion failed "s->leftUntilDone <= s->sizeWhenDone"
  libtransmission/block-info.h
  libtransmission/completion.cc
  libtransmission/completion.h
  tests/libtransmission/completion-test.cc
Labels: scope:core, type:fixup

#3408 refactor: add tr_peer.canRequest()
  libtransmission/peer-common.h
  libtransmission/peer-msgs.cc
  libtransmission/webseed.cc
Labels: scope:core, type:refactor

#3413 fix: minor warnings
  libtransmission/torrent-magnet.cc
  tests/libtransmission/blocklist-test.cc
  tests/libtransmission/torrent-metainfo-test.cc
Labels: scope:core, type:fixup, scope:test

#3422 refactor: tr_address cleanup
  libtransmission/announcer-http.cc
  libtransmission/blocklist.cc
  libtransmission/net.cc
  libtransmission/net.h
  libtransmission/peer-io.cc
  libtransmission/peer-io.h
  libtransmission/peer-mgr.cc
  libtransmission/peer-mgr.h
  libtransmission/peer-msgs.cc
  libtransmission/peer-msgs.h
  libtransmission/peer-socket.h
  libtransmission/port-forwarding.cc
  libtransmission/session.cc
  libtransmission/session.h
  libtransmission/tr-dht.cc
  libtransmission/tr-dht.h
  libtransmission/tr-udp.cc
  libtransmission/tr-utp.cc
  libtransmission/upnp.cc
  libtransmission/upnp.h
  libtransmission/web-utils.cc
  tests/libtransmission/blocklist-test.cc
  tests/libtransmission/peer-msgs-test.cc
Labels: scope:core, type:refactor

#3427 refactor: remove tr_address_to_string()
  libtransmission/net.cc
  libtransmission/net.h
  libtransmission/peer-mgr.cc
  libtransmission/port-forwarding.cc
  libtransmission/session.cc
  libtransmission/upnp.cc
  libtransmission/upnp.h
Labels: scope:core, type:refactor

#3428 refactor: use std::deque for tr_peerIo.outbuf_info
  libtransmission/peer-io.cc
  libtransmission/peer-io.h
Labels: scope:core, type:refactor

#3430 refactor: migrate tr_crypto C functions to members
  libtransmission/crypto.cc
  libtransmission/crypto.h
  libtransmission/handshake.cc
  libtransmission/peer-io.cc
  libtransmission/peer-io.h
  libtransmission/peer-mgr.cc
  tests/libtransmission/crypto-test-ref.h
  tests/libtransmission/crypto-test.cc
Labels: scope:core, type:refactor

#3435 refactor: decouple tr_handshake
  libtransmission/handshake.cc
  libtransmission/handshake.h
  libtransmission/peer-mgr.cc
  libtransmission/peer-mgr.h
Labels: scope:core, type:refactor

#3433 use the default toolbar button size on macOS 11+
  macosx/Controller.mm
Labels: scope:mac, needs UI review, type:ui

#3455 test: add plaintext & encrypted handshake tests
  libtransmission/handshake.cc
  libtransmission/log.h
  libtransmission/peer-io.cc
  libtransmission/peer-io.h
  libtransmission/peer-mse.cc
  libtransmission/peer-msgs.cc
  tests/libtransmission/CMakeLists.txt
  tests/libtransmission/handshake-test.cc
Labels: scope:core, type:test

#3469 fixup! refactor: use fmt to build the GTK client's user-visible strings (#2788)
  gtk/TorrentCellRenderer.cc
Labels: scope:gtk, type:fixup

#3471 fix: limit pad search during encrypted handshake
  libtransmission/handshake.cc
  tests/libtransmission/handshake-test.cc
Labels: scope:core, type:fix

#3452 tr_makeMetaInfo: new anonymize option (closes #3420)
  gtk/MakeDialog.cc
  libtransmission/makemeta.cc
  libtransmission/makemeta.h
  macosx/CreatorWindowController.mm
  qt/MakeDialog.cc
  tests/libtransmission/makemeta-test.cc
  utils/create.cc
  utils/transmission-create.1
Labels: enhancement, scope:create, scope:gtk, scope:qt, scope:core

#3480 Update Web-Interface.md
  docs/Web-Interface.md
Labels: type:docs

#3461 Add announce-ip and announce-ip-enabled parameters.
  docs/Editing-Configuration-Files.md
  libtransmission/announcer-http.cc
  libtransmission/announcer-udp.cc
  libtransmission/quark.cc
  libtransmission/quark.h
  libtransmission/session.cc
  libtransmission/session.h
Labels: scope:core, type:feat, needs code review

#3473 macOS fix clipping and crashing on the Info Inspector Options tab
  macosx/Base.lproj/InfoOptionsView.xib
Labels: scope:mac, type:fix, needs UI review, type:ui

#3493 refactor: remove unused tr_stat fields
  libtransmission/rpcimpl.cc
  libtransmission/torrent.cc
  libtransmission/transmission.h
Labels: scope:core, type:refactor

#3497 macOS fix some autolayout issues in Info window
  macosx/Base.lproj/InfoActivityView.xib
  macosx/Base.lproj/InfoOptionsView.xib
Labels: scope:mac, type:fix, needs UI review, type:ui

#3501 fix: silence "couldn't read file" warnings
  libtransmission/platform.cc
  libtransmission/session.cc
Labels: scope:core, type:fixup

#3472 macOS preference window localization autolayout fixes
  macosx/Base.lproj/PrefsWindow.xib
  macosx/da.lproj/Localizable.strings
  macosx/en.lproj/Localizable.strings
  macosx/es.lproj/Localizable.strings
  macosx/it.lproj/Localizable.strings
  macosx/nl.lproj/Localizable.strings
  macosx/ru.lproj/Localizable.strings
  macosx/tr.lproj/Localizable.strings
Labels: scope:mac, type:fix, type:ui

#3502 fix: do not leak in tr_getWebClientDir()
  libtransmission/platform.cc
  libtransmission/platform.h
  libtransmission/rpc-server.cc
  libtransmission/rpc-server.h
Labels: scope:core, type:fix

#3506 refactor: remove tr_sessionGetConfigDir()
  daemon/daemon.cc
  gtk/Application.cc
  gtk/Session.cc
  gtk/Session.h
  libtransmission/platform.cc
  libtransmission/platform.h
  libtransmission/resume.cc
  libtransmission/rpcimpl.cc
  libtransmission/session.cc
  libtransmission/session.h
  libtransmission/stats.cc
  libtransmission/torrent.cc
  libtransmission/torrent.h
  libtransmission/tr-dht.cc
  libtransmission/transmission.h
  tests/libtransmission/blocklist-test.cc
  tests/libtransmission/file-test.cc
  tests/libtransmission/move-test.cc
Labels: scope:daemon, scope:gtk, scope:core, type:refactor

#3511 fix: 3508 location invalidation
  daemon/daemon.cc
  gtk/Application.cc
  gtk/Session.cc
  gtk/Session.h
  libtransmission/platform.cc
  libtransmission/platform.h
  libtransmission/resume.cc
  libtransmission/rpc-server.cc
  libtransmission/rpc-server.h
  libtransmission/rpcimpl.cc
  libtransmission/session.cc
  libtransmission/session.h
  libtransmission/stats.cc
  libtransmission/torrent.cc
  libtransmission/torrent.h
  libtransmission/tr-dht.cc
  libtransmission/transmission.h
  tests/libtransmission/blocklist-test.cc
  tests/libtransmission/file-test.cc
  tests/libtransmission/move-test.cc
Labels: scope:core, type:fix, bug:regression

#3509 refactor: remove tr_strvPath()
  libtransmission/platform.cc
  libtransmission/torrent.cc
  libtransmission/utils.h
  tests/libtransmission/test-fixtures.h
  tests/libtransmission/utils-test.cc
Labels: scope:core, type:refactor, scope:test

#3514 test: add platform tests
  cli/cli.cc
  gtk/Prefs.cc
  gtk/main.cc
  libtransmission/platform.cc
  libtransmission/platform.h
  libtransmission/rpc-server.cc
  libtransmission/rpc-server.h
  libtransmission/session.cc
  libtransmission/transmission.h
  macosx/Controller.mm
  qt/Application.cc
  qt/Prefs.cc
  tests/libtransmission/CMakeLists.txt
  tests/libtransmission/assets/user-dirs.dirs
  tests/libtransmission/platform-test.cc
Labels: scope:core, type:refactor, type:test

#3495 refactor: replace per-torrent callbacks with per-session ones.
  gtk/Session.cc
  libtransmission/crypto-utils-ccrypto.cc
  libtransmission/peer-mgr.cc
  libtransmission/session.cc
  libtransmission/session.h
  libtransmission/torrent.cc
  libtransmission/torrent.h
  libtransmission/transmission.h
  macosx/Controller.mm
  macosx/Torrent.h
  macosx/Torrent.mm
  tests/libtransmission/move-test.cc
Labels: scope:gtk, scope:mac, type:refactor

#3516 refactor: make tr_session's directory fields private
  libtransmission/platform.cc
  libtransmission/platform.h
  libtransmission/resume.cc
  libtransmission/rpcimpl.cc
  libtransmission/session.cc
  libtransmission/session.h
  libtransmission/stats.cc
  libtransmission/torrent.cc
  libtransmission/torrent.h
  libtransmission/tr-dht.cc
  libtransmission/transmission.h
  tests/libtransmission/blocklist-test.cc
  tests/libtransmission/file-test.cc
  tests/libtransmission/move-test.cc
  tests/libtransmission/open-files-test.cc
  tests/libtransmission/remove-test.cc
Labels: scope:core, type:refactor

#3492 Update Web-Interface.md
  docs/Web-Interface.md
Labels: type:docs

#3512 [macOS] Revamp Toolbar Segments
  macosx/Controller.mm
  macosx/GroupToolbarItem.h
  macosx/GroupToolbarItem.mm
Labels: scope:mac, type:ui

#3518 Update Scripts.md
  docs/Scripts.md
Labels: type:docs

#3524 refactor: remove tr_address_from_string()
  libtransmission/announcer-http.cc
  libtransmission/announcer-udp.cc
  libtransmission/blocklist.cc
  libtransmission/net.cc
  libtransmission/net.h
  libtransmission/peer-msgs.cc
  libtransmission/session.cc
  libtransmission/tr-dht.cc
  libtransmission/web-utils.cc
  tests/libtransmission/blocklist-test.cc
  tests/libtransmission/peer-msgs-test.cc
Labels: scope:core, type:refactor

#3525 refactor: iwyu
  gtk/Dialogs.cc
  gtk/FaviconCache.cc
  gtk/FileList.cc
  gtk/FilterBar.cc
  gtk/FreeSpaceLabel.cc
  gtk/IconCache.cc
  gtk/MakeDialog.cc
  gtk/Notify.cc
  gtk/OptionsDialog.cc
  gtk/RelocateDialog.cc
  gtk/TorrentCellRenderer.cc
  gtk/Utils.cc
  libtransmission/announcer-http.cc
  libtransmission/announcer-udp.cc
  libtransmission/blocklist.cc
  libtransmission/cache.cc
  libtransmission/cache.h
  libtransmission/crypto-utils.cc
  libtransmission/open-files.cc
  libtransmission/open-files.h
  libtransmission/peer-mgr-active-requests.cc
  libtransmission/peer-mgr-wishlist.cc
  libtransmission/peer-mgr.h
  libtransmission/peer-mse.h
  libtransmission/rpc-server.cc
  libtransmission/session.cc
  libtransmission/torrent-files.cc
  libtransmission/torrent-files.h
  libtransmission/torrent-metainfo.cc
  libtransmission/tr-assert.cc
  libtransmission/tr-lpd.cc
  libtransmission/variant-json.cc
  libtransmission/web.cc
  libtransmission/webseed.cc
  qt/Application.cc
  qt/MainWindow.cc
  qt/Prefs.cc
  qt/Torrent.cc
  qt/TorrentFilter.cc
  qt/TorrentModel.cc
  tests/libtransmission/clients-test.cc
  tests/libtransmission/completion-test.cc
  tests/libtransmission/crypto-test.cc
  tests/libtransmission/handshake-test.cc
Labels: scope:gtk, scope:qt, scope:core

#3526 chore: update web client build-dependencies
  web/package.json
  web/public_html/transmission-app.js
  web/yarn.lock
Labels: scope:web, dependencies

#3527 refactor: tr_env_get_string() now returns a std::string
  libtransmission/platform.cc
  libtransmission/utils.cc
  libtransmission/utils.h
  libtransmission/web.cc
  tests/libtransmission/subprocess-test-program.cc
  tests/libtransmission/utils-test.cc
  utils/remote.cc
Labels: scope:core, type:refactor

#3528 refactor: remove tr_runInEventThread() temp data structs
  libtransmission/session.cc
  libtransmission/torrent.cc
Labels: scope:core, type:refactor

#3530 refactor: reimplement tr_strlcpy() using fmt::format_to_n()
  libtransmission/utils.cc
Labels: scope:core, type:refactor

#3531 refactor: use STL containers in torrent-magnet.cc
  libtransmission/torrent-magnet.cc
Labels: scope:core, type:refactor

#3532 chore: iwyu cstring, cstdlib, optional, unordered_set
  cli/cli.cc
  gtk/FileList.cc
  libtransmission/announcer-common.h
  libtransmission/announcer-http.cc
  libtransmission/announcer.cc
  libtransmission/bitfield.cc
  libtransmission/blocklist.cc
  libtransmission/clients.cc
  libtransmission/platform-quota.cc
  libtransmission/session.cc
  libtransmission/session.h
  libtransmission/variant-json.cc
  libtransmission/watchdir-win32.cc
  libtransmission/watchdir.cc
  libtransmission/web-utils.cc
  qt/DetailsDialog.h
Labels: scope:cli, scope:gtk, scope:qt, scope:core, type:fix

#3533 refactor: use std::sort() in rechokeDownloads()
  libtransmission/peer-mgr.cc
Labels: scope:core, type:refactor

#3522 macOS small layout fixes to Info Window
  macosx/Base.lproj/InfoActivityView.xib
  macosx/Base.lproj/InfoOptionsView.xib
Labels: scope:mac, needs UI review, type:ui

#3534 refactor: avoid unnecessary heap alloc when reading PadC
  libtransmission/handshake.cc
Labels: scope:core, type:refactor

#3535 refactor: avoid unnecessary heap alloc when sending magnet link over RPC
  libtransmission/rpcimpl.cc
Labels: scope:core, type:refactor

#3537 perf: batch up calls to the RNG
  libtransmission/crypto-utils.h
  libtransmission/peer-mgr-wishlist.cc
  libtransmission/peer-mgr.cc
  libtransmission/rpcimpl.cc
  tests/libtransmission/crypto-test-ref.h
Labels: scope:core, type:perf

#3540 refactor: remove tr_loadFile()
  libtransmission/rpc-server.cc
  libtransmission/utils.cc
  libtransmission/utils.h
  tests/libtransmission/rename-test.cc
Labels: scope:core, type:refactor, scope:test

#3542 refactor: tr_stats
  gtk/MainWindow.cc
  gtk/StatsDialog.cc
  libtransmission/inout.cc
  libtransmission/peer-mgr.cc
  libtransmission/rpcimpl.cc
  libtransmission/session.cc
  libtransmission/session.h
  libtransmission/stats.cc
  libtransmission/stats.h
  libtransmission/transmission.h
  macosx/Controller.mm
  macosx/StatsWindowController.mm
  macosx/StatusBarController.mm
Labels: scope:gtk, scope:mac, scope:core, type:refactor

#3545 refactor: aggregate bindinfo in tr_session
  libtransmission/port-forwarding.cc
  libtransmission/session.cc
  libtransmission/session.h
Labels: scope:core, type:refactor

#3549 refactor: remove unused GET handler in rpc-server.cc
  libtransmission/rpc-server.cc
  libtransmission/rpcimpl.cc
  libtransmission/rpcimpl.h
Labels: scope:core, type:refactor

#3550 refactor: remove closure struct in tr-dht
  libtransmission/tr-dht.cc
  libtransmission/utils.cc
  libtransmission/utils.h
Labels: scope:core, type:refactor

#3551 refactor: use fmt::format() in tr-getopt
  libtransmission/tr-getopt.cc
  libtransmission/verify.cc
Labels: scope:core, type:refactor
