Repository transmission/transmission, pull requests merged in 2022-08, with the labels that each got.

#3559 macOS autolayout fixes on Inspector - Options tab
  macosx/Base.lproj/InfoOptionsView.xib
Labels: scope:mac, type:ui

#3563 macOS disable green maximize button on Inspector window
  macosx/InfoWindowController.mm
Labels: scope:mac, type:fix, type:ui

#3566 refactor: tr_sys_path_get_info() now returns a tr_sys_path_info
  libtransmission/blocklist.cc
  libtransmission/crypto-utils-openssl.cc
  libtransmission/file-posix.cc
  libtransmission/file-win32.cc
  libtransmission/file.h
  libtransmission/makemeta.cc
  libtransmission/open-files.cc
  libtransmission/session.cc
  libtransmission/torrent-files.cc
  libtransmission/utils.cc
  libtransmission/watchdir.cc
  tests/libtransmission/copy-test.cc
  tests/libtransmission/file-test.cc
  tests/libtransmission/test-fixtures.h
Labels: scope:core, type:refactor, scope:test

#3565 refactor: tr_metainfo_builder()
  gtk/MakeDialog.cc
  libtransmission/makemeta.cc
  libtransmission/makemeta.h
  libtransmission/session.cc
  libtransmission/torrent-metainfo.h
  macosx/CreatorWindowController.mm
  qt/MakeDialog.cc
  qt/MakeDialog.h
  tests/libtransmission/crypto-test.cc
  tests/libtransmission/makemeta-test.cc
  tests/libtransmission/test-fixtures.h
  utils/create.cc
Labels: scope:create, scope:gtk, scope:qt, os:mac, scope:core, type:refactor

#3570 fix: clang-tidy-15 warnings
  libtransmission/bitfield.cc
  libtransmission/block-info.h
  libtransmission/completion.cc
  libtransmission/torrent.cc
  libtransmission/upnp.cc
  libtransmission/variant.cc
  libtransmission/watchdir-generic.cc
  libtransmission/watchdir-inotify.cc
  qt/AboutDialog.cc
  qt/Session.cc
  qt/TrackerDelegate.cc
  qt/Utils.h
Labels: scope:qt, scope:core, type:fix

#3568 refactor: in sendPex(), reuse the temporary buffer
  libtransmission/peer-msgs.cc
Labels: scope:core, type:refactor

#3572 fix: readability-inconsistent-declaration-parameter-name warnings in libtransmission
  libtransmission/.clang-tidy
  libtransmission/announce-list.h
  libtransmission/announcer-common.h
  libtransmission/announcer.h
  libtransmission/bandwidth.cc
  libtransmission/bandwidth.h
  libtransmission/bitfield.h
  libtransmission/cache.cc
  libtransmission/completion.h
  libtransmission/crypto-utils.h
  libtransmission/handshake.cc
  libtransmission/handshake.h
  libtransmission/inout.cc
  libtransmission/log.cc
  libtransmission/log.h
  libtransmission/makemeta.cc
  libtransmission/makemeta.h
  libtransmission/natpmp_local.h
  libtransmission/net.h
  libtransmission/open-files.h
  libtransmission/peer-io.cc
  libtransmission/peer-io.h
  libtransmission/peer-mgr-wishlist.h
  libtransmission/peer-mgr.cc
  libtransmission/peer-mgr.h
  libtransmission/peer-mse.h
  libtransmission/peer-msgs.cc
  libtransmission/peer-socket.h
  libtransmission/port-forwarding.cc
  libtransmission/port-forwarding.h
  libtransmission/rpc-server.cc
  libtransmission/rpc-server.h
  libtransmission/session.cc
  libtransmission/session.h
  libtransmission/torrent-files.h
  libtransmission/torrent-metainfo.h
  libtransmission/torrent.cc
  libtransmission/torrent.h
  libtransmission/torrents.cc
  libtransmission/tr-dht.cc
  libtransmission/tr-dht.h
  libtransmission/tr-getopt.cc
  libtransmission/tr-getopt.h
  libtransmission/transmission.h
  libtransmission/utils.cc
  libtransmission/utils.h
  libtransmission/variant-json.cc
  libtransmission/variant.cc
  libtransmission/variant.h
  libtransmission/verify.h
  libtransmission/web-utils.cc
Labels: scope:core, type:refactor

#3575 fix: cppcoreguidelines-special-member-functions in libtransmission
  libtransmission/.clang-tidy
  libtransmission/announcer.cc
  libtransmission/crypto-utils-openssl.cc
  libtransmission/handshake.cc
  libtransmission/peer-mgr.cc
  libtransmission/peer-msgs.cc
  libtransmission/session.cc
  libtransmission/upnp.cc
  libtransmission/variant-benc.cc
  libtransmission/watchdir.cc
  libtransmission/web.cc
  libtransmission/webseed.cc
Labels: scope:core, type:fix

#3581 refactor: tr_sys_dir_get_current() returns a std::string
  libtransmission/file-posix.cc
  libtransmission/file-win32.cc
  libtransmission/file.h
  tests/libtransmission/subprocess-test-program.cc
  tests/libtransmission/subprocess-test.cc
  tests/libtransmission/test-fixtures.h
  utils/create.cc
Labels: scope:core, type:refactor

#3583 refactor: iwyu utils.h
  gtk/FilterBar.cc
  gtk/PrefsDialog.cc
  gtk/Session.cc
  libtransmission/announcer-udp.cc
  libtransmission/cache.cc
  libtransmission/file-posix.cc
  libtransmission/file.h
  libtransmission/magnet-metainfo.cc
  libtransmission/makemeta.h
  libtransmission/rpc-server.cc
  libtransmission/stats.cc
  libtransmission/stats.h
  libtransmission/torrent-ctor.cc
  libtransmission/torrent.cc
  libtransmission/tr-dht.cc
  libtransmission/verify.cc
  libtransmission/web-utils.h
  qt/AddData.cc
  qt/Application.cc
  qt/FaviconCache.cc
  qt/MakeDialog.cc
  qt/OptionsDialog.cc
  qt/RpcClient.h
  qt/Session.cc
  qt/Torrent.cc
  qt/TorrentDelegateMin.cc
  qt/TrackerDelegate.cc
  tests/libtransmission/announce-list-test.cc
  tests/libtransmission/announcer-test.cc
  tests/libtransmission/benc-test.cc
  tests/libtransmission/bitfield-test.cc
  tests/libtransmission/blocklist-test.cc
  tests/libtransmission/clients-test.cc
  tests/libtransmission/completion-test.cc
  tests/libtransmission/copy-test.cc
  tests/libtransmission/json-test.cc
  tests/libtransmission/magnet-metainfo-test.cc
  tests/libtransmission/makemeta-test.cc
  tests/libtransmission/move-test.cc
  tests/libtransmission/peer-msgs-test.cc
  tests/libtransmission/rename-test.cc
  tests/libtransmission/rpc-test.cc
  tests/libtransmission/session-test.cc
  tests/libtransmission/subprocess-test-program.cc
  tests/libtransmission/subprocess-test.cc
  tests/libtransmission/torrents-test.cc
  tests/libtransmission/variant-test.cc
  tests/libtransmission/watchdir-test.cc
Labels: scope:gtk, scope:qt, scope:core, type:refactor

#3587 refactor: tr_sys_path_resolve() returns a std::string
  CMakeLists.txt
  libtransmission/file-posix.cc
  libtransmission/file-win32.cc
  libtransmission/file.h
  libtransmission/utils.cc
  libtransmission/utils.h
  libtransmission/variant-benc.cc
  tests/libtransmission/file-test.cc
  tests/libtransmission/subprocess-test.cc
Labels: scope:core, type:refactor, type:test

#3590 refactor: remove tr_win32_utf8_to_native_ex()
  libtransmission/file-win32.cc
  libtransmission/subprocess-posix.cc
  libtransmission/subprocess-win32.cc
  libtransmission/subprocess.h
  libtransmission/utils.cc
  libtransmission/utils.h
  libtransmission/variant-benc.cc
  tests/libtransmission/subprocess-test.cc
Labels: scope:core, type:refactor

#3593 refactor: fix recent sonarcloud warnings
  gtk/Session.cc
  libtransmission/announce-list.cc
  libtransmission/announce-list.h
  libtransmission/announcer-common.h
  libtransmission/announcer-udp.cc
  libtransmission/clients.cc
  libtransmission/crypto-utils-openssl.cc
  libtransmission/file-posix.cc
  libtransmission/file.h
  libtransmission/makemeta.h
  libtransmission/net.cc
  libtransmission/rpc-server.cc
  libtransmission/session.cc
  libtransmission/session.h
  libtransmission/torrent.h
  libtransmission/web-utils.h
Labels: scope:core, type:refactor

#3598 refactor: make tr_session_id a class
  libtransmission/rpc-server.cc
  libtransmission/rpcimpl.cc
  libtransmission/session-id.cc
  libtransmission/session-id.h
  libtransmission/session.cc
  libtransmission/session.h
  libtransmission/utils.cc
  qt/Prefs.cc
  qt/Prefs.h
  qt/Session.cc
  tests/libtransmission/session-test.cc
Labels: scope:qt, scope:core, type:refactor, scope:test

#3603 refactor: add timer class
  Transmission.xcodeproj/project.pbxproj
  libtransmission/CMakeLists.txt
  libtransmission/announcer.cc
  libtransmission/handshake.cc
  libtransmission/handshake.h
  libtransmission/peer-io.cc
  libtransmission/peer-mgr.cc
  libtransmission/peer-msgs.cc
  libtransmission/port-forwarding.cc
  libtransmission/rpc-server.cc
  libtransmission/session.cc
  libtransmission/session.h
  libtransmission/timer-ev.cc
  libtransmission/timer-ev.h
  libtransmission/timer.h
  libtransmission/tr-dht.cc
  libtransmission/tr-lpd.cc
  libtransmission/tr-udp.cc
  libtransmission/tr-utp.cc
  libtransmission/trevent.cc
  libtransmission/webseed.cc
  tests/libtransmission/handshake-test.cc
Labels: scope:core, type:refactor

#3571 Increase font size of TrackerCell from 9 to 9.5
  macosx/TrackerCell.mm
Labels: scope:mac, needs UI review, type:ui

#3606 refactor: watchdir
  daemon/daemon.cc
  libtransmission/CMakeLists.txt
  libtransmission/announcer.cc
  libtransmission/cache.cc
  libtransmission/cache.h
  libtransmission/log.cc
  libtransmission/peer-io.cc
  libtransmission/utils.cc
  libtransmission/utils.h
  libtransmission/watchdir-base.h
  libtransmission/watchdir-common.h
  libtransmission/watchdir-generic.cc
  libtransmission/watchdir-inotify.cc
  libtransmission/watchdir-kqueue.cc
  libtransmission/watchdir-win32.cc
  libtransmission/watchdir.cc
  libtransmission/watchdir.h
  tests/libtransmission/subprocess-test.cc
  tests/libtransmission/test-fixtures.h
  tests/libtransmission/watchdir-test.cc
  utils/edit.cc
Labels: scope:daemon, scope:core, type:refactor

#3604 macOS convert message window to autolayout
  macosx/MessageWindow.xib
Labels: scope:mac, type:fixup, type:ui

#3615 docs: update Web-Interface.md
  docs/Web-Interface.md
  docs/resources/WI-torrent-inspector-trackers-tab.png
Labels: type:docs

#3617 refactor: timer pt 2
  .github/workflows/actions.yml
  libtransmission/peer-mgr.cc
  libtransmission/peer-msgs.cc
  libtransmission/port-forwarding.cc
  libtransmission/rpc-server.cc
  libtransmission/rpc-server.h
  libtransmission/session.cc
  libtransmission/session.h
  libtransmission/timer.h
  libtransmission/tr-dht.cc
  libtransmission/tr-lpd.cc
  libtransmission/tr-utp.cc
  libtransmission/utils.cc
  libtransmission/utils.h
  libtransmission/webseed.cc
Labels: scope:core, type:refactor

#3626 refactor: remove tr_new, tr_free pt. 1
  daemon/daemon.cc
  gtk/MessageLogWindow.cc
  libtransmission/file-posix.cc
  libtransmission/file-win32.cc
  libtransmission/log.cc
  libtransmission/log.h
  libtransmission/natpmp.cc
  libtransmission/natpmp_local.h
  libtransmission/peer-mgr.cc
  libtransmission/peer-msgs.cc
  libtransmission/port-forwarding.cc
  libtransmission/port-forwarding.h
  libtransmission/session.cc
  libtransmission/session.h
  libtransmission/torrent-magnet.cc
  libtransmission/torrent-magnet.h
  libtransmission/torrent.cc
  macosx/MessageWindowController.mm
Labels: scope:core, type:refactor

#3630 fix: tr_session field order
  libtransmission/session.cc
  libtransmission/session.h
Labels: scope:core, type:fixup

#3632 fix: coverity warnings
  gtk/Application.cc
  gtk/FaviconCache.cc
  libtransmission/.clang-tidy
  libtransmission/bandwidth.cc
  libtransmission/file-posix.cc
  libtransmission/handshake.cc
  libtransmission/makemeta.cc
  libtransmission/natpmp_local.h
  libtransmission/peer-mgr.cc
  libtransmission/port-forwarding.cc
  libtransmission/rpc-server.cc
  libtransmission/session-id.h
  libtransmission/session.h
  libtransmission/timer-ev.cc
  libtransmission/utils.cc
  tests/libtransmission/announce-list-test.cc
  tests/libtransmission/test-fixtures.h
  tests/libtransmission/watchdir-test.cc
  utils/create.cc
Labels: scope:gtk, scope:core, type:fix, scope:test

#3633 refactor: make tr_session.web_mediator_ private
  libtransmission/session.cc
  libtransmission/session.h
Labels: scope:core, type:refactor

#3634 refactor: make tr_session.queue fields private
  libtransmission/peer-mgr.cc
  libtransmission/rpcimpl.cc
  libtransmission/session.cc
  libtransmission/session.h
  libtransmission/torrent.cc
Labels: scope:core, type:refactor

#3635 refactor: make tr_session.peer_count private
  libtransmission/peer-mgr.cc
  libtransmission/rpcimpl.cc
  libtransmission/session.cc
  libtransmission/session.h
  libtransmission/torrent-ctor.cc
Labels: scope:core, type:refactor

#3637 refactor: make tr_session.is_closing_private_
  libtransmission/announcer-http.cc
  libtransmission/announcer.cc
  libtransmission/inout.cc
  libtransmission/peer-mgr.cc
  libtransmission/peer-msgs.cc
  libtransmission/rpcimpl.cc
  libtransmission/session.cc
  libtransmission/session.h
  libtransmission/torrent-ctor.cc
  libtransmission/torrent-magnet.cc
  libtransmission/tr-utp.cc
  libtransmission/transmission.h
Labels: scope:core, type:refactor

#3638 refactor: remove tr_isSession()
  libtransmission/announcer.cc
  libtransmission/net.cc
  libtransmission/peer-mgr.cc
  libtransmission/session.cc
  libtransmission/session.h
  libtransmission/torrent.cc
  libtransmission/torrent.h
  libtransmission/tr-dht.cc
  libtransmission/tr-lpd.cc
  libtransmission/tr-udp.cc
  libtransmission/tr-utp.cc
  libtransmission/trevent.cc
Labels: scope:core, type:refactor

#3640 refactor: make tr_session.rpc_func_ private
  libtransmission/rpcimpl.cc
  libtransmission/session.cc
  libtransmission/session.h
Labels: scope:core, type:refactor

#3641 refactor: remove tr_session nonmember functions
  libtransmission/net.cc
  libtransmission/peer-mgr.cc
  libtransmission/peer-msgs.cc
  libtransmission/rpcimpl.cc
  libtransmission/session.cc
  libtransmission/session.h
  libtransmission/torrent-magnet.cc
  libtransmission/torrent-magnet.h
  libtransmission/torrent.cc
  libtransmission/torrent.h
  libtransmission/tr-lpd.cc
  libtransmission/tr-udp.cc
  libtransmission/transmission.h
  tests/libtransmission/blocklist-test.cc
  tests/libtransmission/rename-test.cc
Labels: scope:core, type:refactor

#3642 refactor: make tr_session.is_incomplete_file_naming_enabled_ private
  libtransmission/inout.cc
  libtransmission/rpcimpl.cc
  libtransmission/session.cc
  libtransmission/session.h
  libtransmission/torrent.cc
  libtransmission/torrent.h
  libtransmission/transmission.h
Labels: scope:core, type:refactor

#3645 refactor: make tr_session.speed_limit_Bps_ private
  libtransmission/announcer-udp.cc
  libtransmission/peer-mgr.cc
  libtransmission/peer-msgs.cc
  libtransmission/rpc-server.cc
  libtransmission/rpcimpl.cc
  libtransmission/session.cc
  libtransmission/session.h
  libtransmission/torrent.cc
  libtransmission/tr-udp.cc
  libtransmission/tr-utp.cc
  libtransmission/transmission.h
  libtransmission/trevent.cc
Labels: scope:core, type:refactor

#3646 refactor: make tr_session.rpc_server_private_
  libtransmission/handshake.h
  libtransmission/rpc-server.h
  libtransmission/session.cc
  libtransmission/session.h
  libtransmission/utils.h
  libtransmission/web-utils.h
Labels: scope:core, type:refactor

#3648 refactor: avoid tr_malloc / tr_free in subprocess-win32
  libtransmission/subprocess-win32.cc
Labels: scope:core, type:refactor

#3649 refactor: fix sonarcloud warnings
  libtransmission/bandwidth.cc
  libtransmission/bandwidth.h
  qt/FileTreeModel.cc
  qt/FileTreeModel.h
Labels: scope:qt, scope:core, type:fix

#3652 refactor: reduce use of tr_malloc / tr_free
  macosx/PiecesView.mm
  macosx/Torrent.mm
  qt/RpcClient.cc
Labels: scope:qt, scope:mac, type:refactor

#3653 test: possibly fix rename-test flakes
  .github/workflows/actions.yml
  tests/libtransmission/rename-test.cc
  tests/libtransmission/test-fixtures.h
Labels: type:fix, scope:test

#3657 feat: add tr_strvToBuf()
  cli/cli.cc
  daemon/daemon.cc
  gtk/Application.cc
  gtk/DetailsDialog.cc
  gtk/Prefs.cc
  gtk/main.cc
  libtransmission/platform.cc
  libtransmission/session.cc
  libtransmission/torrent-magnet.cc
  libtransmission/torrent-metainfo.cc
  libtransmission/torrent.cc
  libtransmission/transmission.h
  libtransmission/utils.cc
  libtransmission/utils.h
  macosx/Controller.mm
  macosx/Torrent.mm
  qt/Application.cc
  qt/Prefs.cc
  tests/libtransmission/move-test.cc
  tests/libtransmission/platform-test.cc
  tests/libtransmission/rename-test.cc
  tests/libtransmission/subprocess-test.cc
  tests/libtransmission/test-fixtures.h
  utils/remote.cc
Labels: scope:cli, scope:daemon, scope:remote, scope:gtk, scope:qt, scope:mac, scope:core

#3658 refactor: don't use tr_free in tr_strvUtf8Clean()
  libtransmission/torrent-metainfo.cc
  libtransmission/utils.cc
  libtransmission/utils.h
  tests/libtransmission/utils-test.cc
Labels: scope:core, type:refactor

#3662 refactor: avoid tr_new in rpcimpl
  libtransmission/rpcimpl.cc
Labels: scope:core, type:refactor

#3663 refactor: avoid tr_new(), tr_free() in tr_variant
  libtransmission/quark.cc
  libtransmission/utils.cc
  libtransmission/utils.h
  libtransmission/variant.cc
Labels: scope:core, type:refactor

#3664 refactor: avoid tr_new() in tr_main()
  libtransmission/utils.cc
Labels: scope:core, type:refactor

#3665 refactor: avoid tr_new() in transmission-remote
  cli/cli.cc
  daemon/daemon.cc
  gtk/Application.cc
  gtk/DetailsDialog.cc
  gtk/Session.cc
  libtransmission/announce-list.cc
  libtransmission/file.cc
  libtransmission/makemeta.cc
  libtransmission/peer-msgs.cc
  libtransmission/quark.cc
  libtransmission/resume.cc
  libtransmission/rpc-server.cc
  libtransmission/rpcimpl.cc
  libtransmission/session.cc
  libtransmission/stats.cc
  libtransmission/torrent-magnet.cc
  libtransmission/tr-dht.cc
  libtransmission/transmission.h
  libtransmission/utils.h
  libtransmission/variant.cc
  libtransmission/variant.h
  macosx/Controller.mm
  qt/Prefs.cc
  qt/RpcClient.cc
  qt/Session.cc
  tests/libtransmission/json-test.cc
  tests/libtransmission/rpc-test.cc
  tests/libtransmission/test-fixtures.h
  tests/libtransmission/variant-test.cc
  utils/edit.cc
  utils/remote.cc
  utils/show.cc
Labels: scope:remote, scope:core, type:refactor

#3666 refactor: remove tr_strvDup()
  libtransmission/error.cc
  libtransmission/utils.cc
  libtransmission/utils.h
  tests/libtransmission/utils-test.cc
  utils/remote.cc
Labels: scope:remote, scope:core, type:refactor

#3668 refactor: remove tr_free()
  daemon/daemon.cc
  gtk/Session.cc
  libtransmission/cache.cc
  libtransmission/error.cc
  libtransmission/makemeta.cc
  libtransmission/session.cc
  libtransmission/tr-macros.h
  libtransmission/transmission.h
  libtransmission/utils.cc
  libtransmission/utils.h
  macosx/Controller.mm
  qt/Session.cc
Labels: scope:daemon, scope:gtk, scope:qt, scope:mac, scope:core, type:refactor

#3671 refactor: remove tr_utf8_validate() from public API
  libtransmission/utils.cc
  libtransmission/utils.h
  tests/libtransmission/utils-test.cc
Labels: scope:core, type:refactor

#3672 refactor: use OutputIterator for url-escaped info hash strings
  libtransmission/announcer-http.cc
  libtransmission/web-utils.cc
  libtransmission/web-utils.h
  utils/show.cc
Labels: scope:core, type:refactor

#3552 Add a new flag in remote for connecting through a Unix domain socket.
  utils/remote.cc
  utils/transmission-remote.1
Labels: scope:remote, type:feat, needs code review

#3674 refactor: remove TR_N_ELEMENTS macro
  libtransmission/platform.cc
  libtransmission/utils.cc
  libtransmission/utils.h
  libtransmission/web.cc
  utils/remote.cc
Labels: scope:remote, scope:core, type:refactor

#3675 refactor: remove unused
  libtransmission/file-win32.cc
  libtransmission/session.cc
  libtransmission/session.h
  libtransmission/tr-macros.h
  libtransmission/transmission.h
  tests/libtransmission/session-test.cc
Labels: scope:core, type:refactor

#3678 refactor: replace tr_http_escape() with tr_urlEscape()
  libtransmission/announcer-http.cc
  libtransmission/magnet-metainfo.cc
  libtransmission/web-utils.cc
  libtransmission/web-utils.h
  libtransmission/webseed.cc
  utils/show.cc
Labels: scope:core, type:refactor

#3679 fix: close all timers before destroying the event loop
  libtransmission/session.h
Labels: scope:core, type:fixup

#3682 refactor: make blockinfo methods constexpr
  libtransmission/block-info.cc
  libtransmission/block-info.h
Labels: scope:core, type:refactor

#3683 fix: 3579 assertion when RPC client asks for torrent-id 0
  libtransmission/torrents.cc
Labels: scope:core, type:fixup

#3685 chore: re-enable readability-redundant-access-specifiers warning
  libtransmission/.clang-tidy
  libtransmission/watchdir-inotify.cc
  libtransmission/web.cc
Labels: scope:core, type:build

#3686 perf: sonarcloud warnings about temp objects
  libtransmission/crypto-utils-ccrypto.cc
  libtransmission/crypto-utils-cyassl.cc
  libtransmission/crypto-utils-openssl.cc
  libtransmission/crypto-utils-polarssl.cc
  libtransmission/crypto-utils.h
  libtransmission/inout.cc
  libtransmission/makemeta.cc
  libtransmission/quark.cc
  libtransmission/torrent-ctor.cc
  libtransmission/verify.cc
  libtransmission/watchdir-base.h
  libtransmission/watchdir.cc
  libtransmission/webseed.cc
Labels: scope:core, type:perf

#3688 refactor: tr_urlPercentEncode()
  libtransmission/announcer-http.cc
  libtransmission/magnet-metainfo.cc
  libtransmission/web-utils.h
  libtransmission/webseed.cc
  tests/libtransmission/torrent-metainfo-test.cc
  utils/show.cc
Labels: scope:core, type:refactor

#3690 docs: update 4.0.0-beta.1 release notes
  news/news-4.0.0-beta-1.md
Labels: type:docs

#2201 gtk: Disable torrent actions that override text entry field actions
  gtk/Actions.cc
  gtk/Actions.h
  gtk/Application.cc
  gtk/MainWindow.cc
  gtk/MainWindow.h
  gtk/transmission-ui.xml
Labels: enhancement, scope:gtk, type:ui

#3692 Fix IPv6 announce socket binding interface.
  libtransmission/session.cc
  libtransmission/session.h
  libtransmission/web.cc
  libtransmission/web.h
Labels: scope:core, type:fix

#3699 fixup! perf: sonarcloud warnings about temp objects (#3686)
  libtransmission/quark.cc
Labels: scope:core, type:fixup

#3696 refactor: local peer discovery
  CMakeLists.txt
  libtransmission/.clang-tidy
  libtransmission/CMakeLists.txt
  libtransmission/crypto-utils.h
  libtransmission/session.cc
  libtransmission/session.h
  libtransmission/stats.cc
  libtransmission/tr-lpd.cc
  libtransmission/tr-lpd.h
  libtransmission/utils.cc
  tests/libtransmission/CMakeLists.txt
  tests/libtransmission/lpd-test.cc
  tests/libtransmission/rename-test.cc
  tests/libtransmission/test-fixtures.h
Labels: scope:core, type:perf, type:test, type:feat

#3702 refactor: modernize-avoid-c-arrays pt. 1
  libtransmission/blocklist.cc
  libtransmission/crypto-utils-openssl.cc
  libtransmission/crypto-utils.cc
  libtransmission/handshake.cc
  libtransmission/log.cc
  libtransmission/natpmp.cc
  libtransmission/net.cc
  libtransmission/peer-io.cc
  libtransmission/peer-io.h
  libtransmission/peer-mgr.cc
  libtransmission/platform.cc
  libtransmission/resume.cc
  libtransmission/rpc-server.cc
  libtransmission/torrent-ctor.cc
  libtransmission/tr-udp.cc
  libtransmission/variant-json.cc
Labels: scope:core, type:refactor

#3704 fix: lpd fixup
  libtransmission/tr-lpd.cc
  libtransmission/tr-lpd.h
Labels: scope:core, type:fixup

#3447 option to disable TCP
  libtransmission/handshake.cc
  libtransmission/handshake.h
  libtransmission/net.cc
  libtransmission/peer-io.cc
  libtransmission/peer-mgr.cc
  libtransmission/quark.cc
  libtransmission/quark.h
  libtransmission/rpcimpl.cc
  libtransmission/session.cc
  libtransmission/session.h
  tests/libtransmission/handshake-test.cc
  tests/libtransmission/rpc-test.cc
Labels: needs clarification, scope:mac, scope:core, type:feat

#3713 refactor: modernize-avoid-c-arrays pt. 2
  libtransmission/.clang-tidy
  libtransmission/announcer-common.h
  libtransmission/announcer-http.cc
  libtransmission/completion.cc
  libtransmission/net.cc
  libtransmission/peer-msgs.cc
  libtransmission/rpc-server.cc
  libtransmission/subprocess-posix.cc
  libtransmission/tr-dht.cc
  libtransmission/tr-getopt.cc
  libtransmission/upnp.cc
  libtransmission/utils.cc
Labels: scope:core, type:refactor

#3715 fixup! refactor: modernize cache.cc (#3108)
  libtransmission/cache.cc
Labels: scope:core, type:fixup

#3717 fix: when renaming local data files fails, set torrent error and pause it
  libtransmission/inout.cc
  libtransmission/peer-io.cc
  libtransmission/torrent.cc
Labels: scope:core, type:fix

#3723 refactor: remove tr_sys file_map_for_reading()
  libtransmission/blocklist.cc
  libtransmission/blocklist.h
  libtransmission/file-posix.cc
  libtransmission/file-win32.cc
  libtransmission/file.cc
  libtransmission/file.h
  libtransmission/natpmp_local.h
  libtransmission/session.cc
  tests/libtransmission/file-test.cc
  tests/libtransmission/subprocess-test.cc
Labels: scope:core, type:refactor

#3725 test: add torrent-magnet tests
  libtransmission/torrent-magnet.cc
  tests/libtransmission/torrent-magnet-test.cc
Labels: type:test, scope:test

#3726 refactor: use std::ifstream in torrent-magnet
  libtransmission/torrent-magnet.cc
  tests/libtransmission/CMakeLists.txt
Labels: scope:core, type:refactor

#3727 refactor: remove unused function tr_sys_file_seek()
  libtransmission/file-posix.cc
  libtransmission/file-win32.cc
  libtransmission/file.h
  tests/libtransmission/file-test.cc
Labels: scope:core, type:refactor

#3728 refactor: remove tr_quark_get_string()
  gtk/Application.cc
  libtransmission/interned-string.h
  libtransmission/quark.cc
  libtransmission/quark.h
  libtransmission/rpc-server.cc
  libtransmission/rpcimpl.cc
  libtransmission/variant.cc
  qt/RpcClient.cc
  qt/Session.cc
  tests/libtransmission/quark-test.cc
Labels: scope:core, type:refactor

#3730 refactor: remove tr_ctorSetBandwidthPriority() from public API
  libtransmission/torrent.h
  libtransmission/transmission.h
Labels: scope:core, type:refactor

#3731 refactor: remove tr_removeElementFromArray()
  libtransmission/peer-msgs.cc
  libtransmission/utils.cc
  libtransmission/utils.h
  libtransmission/variant.cc
  tests/libtransmission/utils-test.cc
Labels: scope:core, type:refactor

#3732 refactor: tr_peerIo read buffer
  libtransmission/handshake.cc
  libtransmission/peer-io.cc
  libtransmission/peer-io.h
  libtransmission/peer-msgs.cc
Labels: scope:core, type:refactor

#3734 Refactor/tr peer io member funcs
  libtransmission/bandwidth.cc
  libtransmission/handshake.cc
  libtransmission/peer-io.cc
  libtransmission/peer-io.h
  libtransmission/peer-mgr.cc
  libtransmission/peer-msgs.cc
  libtransmission/tr-utp.cc
  tests/libtransmission/handshake-test.cc
Labels: scope:core, type:refactor

#3735 refactor: tr_peerIo ref, unref
  libtransmission/bandwidth.cc
  libtransmission/bandwidth.h
  libtransmission/cache.cc
  libtransmission/handshake.cc
  libtransmission/handshake.h
  libtransmission/peer-io.cc
  libtransmission/peer-io.h
  libtransmission/peer-mgr.cc
  libtransmission/peer-msgs.cc
  libtransmission/peer-msgs.h
  tests/libtransmission/handshake-test.cc
Labels: scope:core, type:refactor

#3740 refactor: remove unnecessary default destructors
  libtransmission/peer-msgs.h
  libtransmission/session.h
  libtransmission/timer-ev.h
  libtransmission/torrent.h
  libtransmission/tr-strbuf.h
  libtransmission/watchdir-base.h
Labels: scope:core, type:refactor, type:perf

#3741 refactor: prefer std::unique_ptr over std::shared_ptr
  libtransmission/handshake.cc
  libtransmission/handshake.h
  libtransmission/peer-mgr.cc
  libtransmission/rpc-server.h
  libtransmission/rpcimpl.cc
  libtransmission/session.cc
  libtransmission/session.h
  libtransmission/web.cc
  libtransmission/webseed.cc
  tests/libtransmission/handshake-test.cc
Labels: scope:core, type:refactor

#3742 perf: make methods constexpr
  libtransmission/benc.h
  libtransmission/bitfield.h
  libtransmission/completion.cc
  libtransmission/completion.h
  libtransmission/file-piece-map.cc
  libtransmission/file-piece-map.h
  libtransmission/lru-cache.h
  libtransmission/peer-io.cc
  libtransmission/peer-mse.cc
  libtransmission/peer-mse.h
  libtransmission/torrent-metainfo.h
  libtransmission/torrent.h
Labels: scope:core, type:perf

#3744 refactor: more constexpr
  libtransmission/handshake.cc
  libtransmission/session.h
  libtransmission/stats.h
  libtransmission/torrent-metainfo.h
  libtransmission/torrent.cc
  libtransmission/torrent.h
Labels: scope:core, type:refactor
