Repository transmission/transmission, pull requests merged in 2022-04, with the labels that each got.

#2854 refactor: remove tr_strdup_printf()
  daemon/daemon-win32.cc
  libtransmission/subprocess-win32.cc
  libtransmission/utils.cc
  libtransmission/utils.h
  tests/libtransmission/utils-test.cc
Labels: scope:core, type:refactor

#2856 fix: incorrect magnet size calcuation in tr_completion
  libtransmission/completion.cc
  libtransmission/torrent.h
Labels: scope:core, type:fixup

#2860 fix: sonarcloud
  cli/cli.cc
  gtk/Application.cc
  gtk/DetailsDialog.cc
  gtk/FreeSpaceLabel.cc
  gtk/FreeSpaceLabel.h
  gtk/IconCache.cc
  gtk/MainWindow.cc
  gtk/Prefs.cc
  gtk/Prefs.h
  gtk/PrefsDialog.cc
  gtk/Session.cc
  gtk/Utils.cc
  qt/DetailsDialog.cc
  qt/FileTreeModel.cc
  qt/TorrentModel.cc
  tests/libtransmission/crypto-test.cc
  tests/libtransmission/test-fixtures.h
Labels: scope:gtk, scope:core, type:fix

#2861 refactor: remove varargs from TR_ASSERT_MSG()
  libtransmission/bitfield.cc
  libtransmission/file-posix.cc
  libtransmission/file-win32.cc
  libtransmission/handshake.cc
  libtransmission/net.cc
  libtransmission/peer-io.cc
  libtransmission/peer-mgr.cc
  libtransmission/peer-msgs.cc
  libtransmission/subprocess-win32.cc
  libtransmission/tr-assert.cc
  libtransmission/tr-assert.h
  libtransmission/tr-assert.mm
Labels: scope:core, type:refactor

#2862 refactor: annotate nodiscard, constexpr, noexcept methods
  libtransmission/benc.h
  libtransmission/bitfield.cc
  libtransmission/bitfield.h
  libtransmission/block-info.h
  libtransmission/completion.h
  libtransmission/magnet-metainfo.h
  libtransmission/net.cc
  libtransmission/net.h
  libtransmission/session.h
  libtransmission/torrent-metainfo.h
  libtransmission/torrent.h
  libtransmission/torrents.h
Labels: scope:core, type:refactor

#2863 refactor: remove unused functions
  libtransmission/blocklist.cc
  libtransmission/blocklist.h
  libtransmission/crypto-utils.cc
  libtransmission/crypto-utils.h
  libtransmission/error.cc
  libtransmission/error.h
  libtransmission/handshake.cc
  libtransmission/handshake.h
  libtransmission/peer-mgr.cc
  libtransmission/ptrarray.cc
  libtransmission/ptrarray.h
  libtransmission/session.h
  libtransmission/torrent-ctor.cc
  libtransmission/torrent.cc
  libtransmission/torrent.h
  libtransmission/torrents.cc
  libtransmission/torrents.h
  libtransmission/tr-lpd.cc
  libtransmission/tr-lpd.h
  libtransmission/transmission.h
  libtransmission/web-utils.cc
  libtransmission/web-utils.h
  qt/Session.cc
  qt/Session.h
  qt/VariantHelpers.cc
  qt/VariantHelpers.h
Labels: scope:qt, scope:core, type:refactor

#2865 fix: sonarcloud
  gtk/Application.cc
  gtk/FaviconCache.cc
  libtransmission/announcer-udp.cc
  libtransmission/blocklist.cc
  libtransmission/handshake.cc
  libtransmission/log.cc
  libtransmission/magnet-metainfo.h
  libtransmission/peer-io.cc
  libtransmission/peer-io.h
  libtransmission/peer-msgs.cc
  libtransmission/rpcimpl.cc
  libtransmission/session.cc
  libtransmission/torrent.cc
  libtransmission/torrent.h
  libtransmission/trevent.h
  qt/FileTreeItem.cc
  qt/FileTreeItem.h
  qt/InteropHelper.cc
  qt/Prefs.cc
  qt/Torrent.cc
  tests/libtransmission/announce-list-test.cc
  tests/libtransmission/announcer-test.cc
  tests/libtransmission/assets/alice_in_wonderland_librivox_archive.torrent
  tests/libtransmission/assets/debian-11.2.0-amd64-DVD-1.iso.torrent.added
  tests/libtransmission/bitfield-test.cc
  tests/libtransmission/block-info-test.cc
  tests/libtransmission/completion-test.cc
  tests/libtransmission/file-piece-map-test.cc
  tests/libtransmission/history-test.cc
  tests/libtransmission/json-test.cc
  tests/libtransmission/magnet-metainfo-test.cc
  tests/libtransmission/peer-mgr-active-requests-test.cc
  tests/libtransmission/peer-mgr-wishlist-test.cc
  tests/libtransmission/rename-test.cc
  tests/libtransmission/rpc-test.cc
  tests/libtransmission/session-test.cc
  tests/libtransmission/strbuf-test.cc
  tests/libtransmission/test-fixtures.h
  tests/libtransmission/torrent-metainfo-test.cc
  tests/libtransmission/utils-test.cc
  utils/remote.cc
  utils/show.cc
Labels: scope:show, scope:gtk, scope:qt, scope:core, type:fix

#2867 refactor: remove tr_snprintf() pt 1
  cli/cli.cc
  daemon/daemon.cc
  utils/remote.cc
Labels: scope:cli, scope:daemon, scope:remote, type:refactor

#2868 fix: sonarcloud
  gtk/Application.cc
  gtk/DetailsDialog.cc
  gtk/FileList.cc
  gtk/IconCache.cc
  gtk/OptionsDialog.cc
  gtk/PrefsDialog.cc
  gtk/Utils.cc
  libtransmission/announcer.cc
  libtransmission/peer-mgr-active-requests.cc
  libtransmission/peer-mgr.cc
  libtransmission/rpcimpl.cc
  libtransmission/utils.cc
  libtransmission/variant-json.cc
  qt/DetailsDialog.cc
  qt/FilterBar.cc
  qt/FilterBarComboBox.cc
  qt/FilterBarComboBoxDelegate.cc
  qt/MainWindow.cc
  qt/TorrentModel.cc
  tests/libtransmission/copy-test.cc
  tests/libtransmission/makemeta-test.cc
  tests/libtransmission/move-test.cc
  tests/libtransmission/test-fixtures.h
  tests/libtransmission/utils-test.cc
  tests/libtransmission/web-utils-test.cc
  utils/edit.cc
  utils/remote.cc
Labels: scope:remote, scope:edit, scope:gtk, scope:qt, scope:core, type:refactor

#2871 refactor: remove tr_snprintf() pt 2
  libtransmission/announcer.cc
  libtransmission/makemeta.cc
  libtransmission/net.cc
  libtransmission/rpcimpl.cc
  libtransmission/tr-dht.cc
  libtransmission/tr-strbuf.h
  libtransmission/upnp.cc
  libtransmission/utils.cc
  libtransmission/utils.h
  libtransmission/variant-benc.cc
  libtransmission/variant-json.cc
  tests/libtransmission/makemeta-test.cc
  tests/libtransmission/test-fixtures.h
  tests/libtransmission/utils-test.cc
Labels: scope:core, type:refactor

#1328 watch: can use .magnet files
  daemon/daemon.cc
Labels: enhancement, scope:daemon, needs update

#2872 refactor: remove tr_snprintf()
  libtransmission/blocklist.cc
  libtransmission/clients.cc
  libtransmission/file-win32.cc
  libtransmission/tr-dht.cc
  libtransmission/tr-lpd.cc
  libtransmission/utils.cc
  libtransmission/utils.h
  libtransmission/web-utils.cc
  tests/libtransmission/utils-test.cc
Labels: scope:core, type:refactor

#2879 refactor: annotate nodiscard, constexpr, noexcept methods
  libtransmission/announce-list.h
  libtransmission/announcer.cc
  libtransmission/bandwidth.h
  libtransmission/completion.cc
  libtransmission/completion.h
  libtransmission/peer-msgs.cc
  libtransmission/peer-msgs.h
  libtransmission/quark.h
  libtransmission/torrent-metainfo.h
  libtransmission/torrent.h
  libtransmission/utils.h
  libtransmission/web.cc
  libtransmission/web.h
  libtransmission/webseed.cc
Labels: scope:core, type:refactor

#2882 refactor: remove tr_strcmp0()
  libtransmission/platform-quota.cc
  libtransmission/session.cc
  libtransmission/utils.cc
  libtransmission/utils.h
  utils/remote.cc
Labels: scope:remote, scope:core, type:refactor

#2887 fix: tr_clientForId()
  libtransmission/clients.cc
  tests/libtransmission/clients-test.cc
Labels: scope:core, type:fixup

#2890 test: fuzz test tr_magnet_metainfo.parseMagnet()
  libtransmission/magnet-metainfo.cc
  tests/libtransmission/magnet-metainfo-test.cc
Labels: scope:core, type:test, type:fixup

#2891 test: fuzz test tr_torrent_metainfo.parseBenc()
  libtransmission/variant-benc.cc
  tests/libtransmission/torrent-metainfo-test.cc
  tests/libtransmission/web-utils-test.cc
Labels: scope:core, type:test, type:fixup

#2892 test: fuzz test tr_variantFromBuf()
  libtransmission/benc.h
  libtransmission/variant-benc.cc
  libtransmission/variant-common.h
  libtransmission/variant-json.cc
  libtransmission/variant.cc
  tests/libtransmission/variant-test.cc
Labels: scope:core, type:test, type:fixup

#2889 Fix typographical errors in the documentation.
  docs/Bug-Submission.md
  docs/Building-Transmission.md
  docs/Editing-Configuration-Files.md
  docs/Environment-Variables.md
  docs/Peer-ID-and-User-Agent.md
  docs/Port-Forwarding-Guide.md
  docs/Release-Notes.md
  docs/Scripts.md
  docs/Why-Are-My-Speeds-So-Slow.md
  docs/Why-is-my-port-closed.md
  docs/rpc-spec.md
Labels: scope:docs

#2896 refactor: remove tr_strvJoin()
  daemon/daemon-posix.cc
  daemon/daemon.cc
  libtransmission/announce-list.cc
  libtransmission/crypto-utils.cc
  libtransmission/magnet-metainfo.cc
  libtransmission/platform.cc
  libtransmission/rpc-server.cc
  libtransmission/rpcimpl.cc
  libtransmission/session-id.cc
  libtransmission/session.cc
  libtransmission/subprocess-win32.cc
  libtransmission/torrent.cc
  libtransmission/utils.h
  macosx/Torrent.mm
  tests/libtransmission/announce-list-test.cc
  tests/libtransmission/benc-test.cc
  tests/libtransmission/move-test.cc
  tests/libtransmission/torrent-metainfo-test.cc
  tests/libtransmission/torrents-test.cc
  tests/libtransmission/utils-test.cc
  utils/create.cc
  utils/remote.cc
  utils/show.cc
Labels: scope:daemon, scope:remote, scope:create, scope:show, scope:mac, scope:core, type:refactor

#2897 refactor: remove unused macros
  libtransmission/announcer.cc
  libtransmission/handshake.cc
  libtransmission/peer-mgr.cc
  libtransmission/peer-msgs.cc
  libtransmission/port-forwarding.cc
  libtransmission/ptrarray.cc
  libtransmission/ptrarray.h
  libtransmission/rpc-server.cc
  libtransmission/session.cc
  libtransmission/torrent.cc
  libtransmission/tr-dht.cc
  libtransmission/tr-lpd.cc
  libtransmission/tr-macros.h
  libtransmission/tr-utp.cc
  libtransmission/utils.cc
  libtransmission/utils.h
  libtransmission/webseed.cc
  tests/libtransmission/utils-test.cc
Labels: scope:core, type:refactor

#2899 refactor: convert watchdir to C++
  libtransmission/watchdir.cc
Labels: scope:core, type:refactor

#2906 refactor: extract some file management into tr_files class
  Transmission.xcodeproj/project.pbxproj
  libtransmission/CMakeLists.txt
  libtransmission/files.cc
  libtransmission/files.h
  libtransmission/inout.cc
  libtransmission/torrent-metainfo.cc
  libtransmission/torrent-metainfo.h
  libtransmission/torrent.cc
  libtransmission/torrent.h
  libtransmission/verify.cc
  tests/libtransmission/CMakeLists.txt
  tests/libtransmission/files-test.cc
Labels: scope:core, type:refactor

#2908 refactor: tr_block_info
  libtransmission/block-info.cc
  libtransmission/block-info.h
  libtransmission/completion.cc
  libtransmission/completion.h
  libtransmission/files.h
  libtransmission/inout.cc
  libtransmission/torrent-metainfo.cc
  libtransmission/torrent-metainfo.h
  libtransmission/torrent.cc
  libtransmission/torrent.h
  tests/libtransmission/block-info-test.cc
  tests/libtransmission/completion-test.cc
  tests/libtransmission/file-piece-map-test.cc
Labels: scope:core, type:refactor

#2911 refactor: tr_files::hasAnyLocalData()
  libtransmission/files.cc
  libtransmission/files.h
  libtransmission/torrent.cc
  libtransmission/torrent.h
  tests/libtransmission/files-test.cc
Labels: scope:core, type:refactor

#2913 fixup: minor log string formatting changes
  daemon/daemon.cc
  libtransmission/log.cc
  libtransmission/port-forwarding.cc
  libtransmission/upnp.cc
Labels: scope:core, type:fixup

#2903 Addressing red links in the Xcode project
  Transmission.xcodeproj/project.pbxproj
Labels: scope:mac, type:build

#2919 refactor: add tr_torrent_files::move() and remove()
  Transmission.xcodeproj/project.pbxproj
  libtransmission/CMakeLists.txt
  libtransmission/files.cc
  libtransmission/inout.cc
  libtransmission/torrent-files.cc
  libtransmission/torrent-files.h
  libtransmission/torrent-metainfo.cc
  libtransmission/torrent-metainfo.h
  libtransmission/torrent.cc
  libtransmission/torrent.h
  libtransmission/utils.h
  tests/libtransmission/CMakeLists.txt
  tests/libtransmission/files-test.cc
  tests/libtransmission/move-test.cc
  tests/libtransmission/remove-test.cc
  tests/libtransmission/test-fixtures.h
  tests/libtransmission/variant-test.cc
Labels: scope:core, type:refactor, type:test

#2924 fixup: more libfmt usage regressions
  gtk/DetailsDialog.cc
  libtransmission/peer-msgs.cc
Labels: scope:gtk, scope:core, type:fixup

#2927 refactor: remove tr_torrent.magicNumber
  libtransmission/torrent.h
Labels: scope:core, type:refactor

#2928 test: use uniform naming scheme for fuzz tests.
  tests/libtransmission/clients-test.cc
Labels: type:refactor, scope:test

#2929 refactor: remove tr_url_parsed_t.portstr
  libtransmission/announcer.cc
  libtransmission/utils.h
  libtransmission/web-utils.cc
  libtransmission/web-utils.h
  tests/libtransmission/web-utils-test.cc
Labels: scope:core, type:refactor

#2930 refactor: remove tr_announce_list.tracker_info.scrape
  libtransmission/announce-list.cc
  libtransmission/announce-list.h
  tests/libtransmission/announce-list-test.cc
  tests/libtransmission/magnet-metainfo-test.cc
  utils/show.cc
Labels: scope:core, type:refactor

#2931 refactor: remove tr_announce_list::tracker info.announce
  libtransmission/announce-list.cc
  libtransmission/announce-list.h
  libtransmission/announcer.cc
  libtransmission/magnet-metainfo.cc
  libtransmission/rpcimpl.cc
  libtransmission/torrent-magnet.cc
  libtransmission/torrent.cc
  macosx/QuickLookPlugin/GeneratePreviewForURL.mm
  tests/libtransmission/announce-list-test.cc
  tests/libtransmission/magnet-metainfo-test.cc
  utils/show.cc
Labels: scope:core, type:refactor

#2934 build: pass cmake compiler values to submodules
  cmake/TrMacros.cmake
Labels: type:build

#2935 build: try clang-format-12 in code_style
  code_style.sh
Labels: type:build

#2936 fix: new MSVC warning in file-piece-map-test.cc
  tests/libtransmission/file-piece-map-test.cc
Labels: type:fix, scope:test

#2933 perf: fix misc inefficiencies in bitfield.cc
  libtransmission/bitfield.cc
Labels: scope:core, type:perf

#2937 refactor: make tr_peerMgr.webseeds a std::vector
  libtransmission/peer-mgr.cc
Labels: scope:core, type:refactor

#2940 fix: do not load magnet file resume files
  libtransmission/torrent.cc
Labels: scope:core, type:fixup

#2941 fix: uninintialized field tr_torrent_files.total_size_
  libtransmission/torrent-files.h
Labels: scope:core, type:fixup

#2942 refactor: use std::vector<tr_quark> for torrent labels
  libtransmission/resume.cc
  libtransmission/rpcimpl.cc
  libtransmission/torrent-ctor.cc
  libtransmission/torrent.cc
  libtransmission/torrent.h
Labels: scope:core, type:perf

#2943 refactor: use std::vector for tr_torrents.removed_
  libtransmission/rpcimpl.cc
  libtransmission/session.cc
  libtransmission/session.h
  libtransmission/torrent.cc
  libtransmission/torrents.cc
  libtransmission/torrents.h
Labels: scope:core, type:refactor

#2946 build: re-enable cert str34 c clang tidy
  libtransmission/.clang-tidy
Labels: scope:core, type:build

#2952 refactor: add a tr_port safety class
  libtransmission/announcer-common.h
  libtransmission/announcer-http.cc
  libtransmission/announcer-udp.cc
  libtransmission/announcer.cc
  libtransmission/natpmp.cc
  libtransmission/natpmp_local.h
  libtransmission/net.cc
  libtransmission/net.h
  libtransmission/peer-common.h
  libtransmission/peer-mgr.cc
  libtransmission/peer-msgs.cc
  libtransmission/port-forwarding.cc
  libtransmission/port-forwarding.h
  libtransmission/rpc-server.cc
  libtransmission/rpc-server.h
  libtransmission/rpcimpl.cc
  libtransmission/session.cc
  libtransmission/session.h
  libtransmission/torrent.cc
  libtransmission/tr-dht.cc
  libtransmission/tr-lpd.cc
  libtransmission/tr-udp.cc
  libtransmission/tr-utp.cc
  libtransmission/transmission.h
  libtransmission/upnp.cc
  libtransmission/web-utils.cc
  macosx/PrefsController.mm
  qt/Session.cc
Labels: scope:core, type:refactor

#2958 fix: when loading resume state, load filenames before mtimes
  libtransmission/resume.cc
Labels: scope:core, type:fixup

#2960 refactor: remove tr_announce_list.tiers
  libtransmission/announce-list.cc
  libtransmission/announce-list.h
  libtransmission/torrent.h
  tests/libtransmission/announce-list-test.cc
Labels: scope:core, type:refactor

#2961 refactor: add tr_address::fromCompact()
  libtransmission/announcer-http.cc
  libtransmission/net.cc
  libtransmission/net.h
  libtransmission/peer-mgr.cc
  libtransmission/tr-dht.cc
Labels: scope:core, type:refactor

#2962 refactor: add tr_address.readable()
  libtransmission/net.cc
  libtransmission/net.h
  libtransmission/peer-io.cc
  libtransmission/peer-mgr.h
  libtransmission/session.cc
  libtransmission/tr-lpd.cc
  libtransmission/tr-udp.cc
  tests/libtransmission/announcer-test.cc
Labels: scope:core, type:refactor

#2963 fix: heap-buffer-overflow in variant-json
  libtransmission/variant-json.cc
Labels: scope:core, type:fix

#2950 perf: use popcnt in tr_bitfield
  libtransmission/bitfield.cc
  libtransmission/tr-popcount.h
Labels: scope:core, type:perf

#2964 refactor: prefer std::vector as the default container
  libtransmission/bitfield.cc
  libtransmission/rpc-server.cc
  libtransmission/rpc-server.h
  libtransmission/session.cc
  libtransmission/session.h
  libtransmission/torrents.cc
  libtransmission/torrents.h
  tests/libtransmission/torrents-test.cc
Labels: scope:core, type:refactor

#2965 refactor: partially c++ifiy tr_rpc_server
  libtransmission/rpc-server.cc
  libtransmission/rpc-server.h
  libtransmission/session.cc
  libtransmission/session.h
  libtransmission/transmission.h
Labels: scope:core, type:refactor

#2966 refactor: prefer tr_pathbuf over tr_strvPath()
  libtransmission/inout.cc
  libtransmission/makemeta.cc
  libtransmission/rpc-server.h
  libtransmission/session.cc
  libtransmission/tr-dht.cc
  tests/libtransmission/blocklist-test.cc
  tests/libtransmission/copy-test.cc
  tests/libtransmission/file-test.cc
  tests/libtransmission/move-test.cc
  tests/libtransmission/rename-test.cc
  tests/libtransmission/test-fixtures.h
Labels: scope:core, type:refactor, scope:test

#2967 refactor: remove evbuffer_free_to_str()
  libtransmission/announcer.cc
  libtransmission/utils.cc
  libtransmission/utils.h
  libtransmission/variant.cc
Labels: scope:core, type:refactor

#2968 build: re-enable cert-err33-c clang-tidy warning
  CMakeLists.txt
  gtk/DetailsDialog.cc
  libtransmission/.clang-tidy
  libtransmission/rpc-server.cc
  libtransmission/session.cc
  libtransmission/torrent.cc
  libtransmission/trevent.cc
  libtransmission/utils.cc
  libtransmission/utils.h
  utils/remote.cc
  utils/show.cc
Labels: scope:remote, scope:show, scope:core, type:refactor

#2970 fix: cell-renderer up/down ui layout order
  gtk/MainWindow.cc
  gtk/TorrentCellRenderer.cc
Labels: scope:gtk, type:fixup

#2975 Balancing HTML opening-closing tags
  macosx/TransmissionHelp/html/FAQ.html
  macosx/TransmissionHelp/html/Index2.html
  macosx/TransmissionHelp/html/Speed.html
  macosx/TransmissionHelp/html/check.html
  macosx/TransmissionHelp/html/gettingstarted.html
  macosx/TransmissionHelp/html/network.html
  macosx/TransmissionHelp/html/peers.html
  macosx/TransmissionHelp/html/pffirewall.html
  macosx/TransmissionHelp/html/pfrouter.html
  macosx/TransmissionHelp/html/portforward.html
  macosx/TransmissionHelp/html/remote.html
  macosx/TransmissionHelp/html/scripts.html
  macosx/TransmissionHelp/html/speed.html
  macosx/TransmissionHelp/html/tracker.html
  macosx/TransmissionHelp/html/troubleshoot.html
  macosx/TransmissionHelp/html/usingt.html
  macosx/TransmissionHelp/index.html
Labels: scope:docs

#2978 fix: corruption when downloading webseeds
  libtransmission/webseed.cc
Labels: scope:core, type:fixup

#2981 chore: iwyu cleanup
  gtk/Session.h
  gtk/Utils.h
  libtransmission/announce-list.h
  libtransmission/announcer-common.h
  libtransmission/fdlimit.h
  libtransmission/handshake.h
  libtransmission/log.h
  libtransmission/magnet-metainfo.h
  libtransmission/natpmp_local.h
  libtransmission/peer-io.h
  libtransmission/ptrarray.h
  libtransmission/rpcimpl.cc
  libtransmission/rpcimpl.h
  libtransmission/session.h
  libtransmission/torrent-files.h
  libtransmission/tr-dht.h
  libtransmission/tr-strbuf.h
  libtransmission/upnp.h
  libtransmission/utils.h
  libtransmission/web.h
  qt/MainWindow.h
  qt/Torrent.h
  qt/Utils.h
  qt/VariantHelpers.h
Labels: scope:gtk, scope:qt, scope:core, type:refactor

#2982 refactor: make tr_torrent::verify_state_ private
  libtransmission/rpcimpl.cc
  libtransmission/torrent.cc
  libtransmission/torrent.h
  libtransmission/verify.cc
Labels: scope:core, type:refactor

#2992 perf: faster file priorities
  libtransmission/file-piece-map.cc
Labels: scope:core, type:perf

#2993 perf: faster file-lists in the GTK client's details dialog
  gtk/FileList.cc
  gtk/IconCache.cc
  gtk/IconCache.h
  gtk/TorrentCellRenderer.cc
Labels: scope:gtk, type:perf

#2994 perf: limit the scope of bitfield assertions
  libtransmission/bitfield.cc
Labels: scope:core, type:perf

#3002 refactor: add Handshakes helper class in peer-mgr
  libtransmission/peer-mgr.cc
Labels: scope:core, type:refactor

#3005 refactor: use smaller integral types in some structs
  gtk/FileList.cc
  libtransmission/peer-common.h
  libtransmission/peer-mgr.cc
  libtransmission/resume.cc
  libtransmission/rpcimpl.cc
  libtransmission/torrent.cc
  libtransmission/torrent.h
  libtransmission/transmission.h
Labels: scope:core, type:refactor

#3006 refactor: reduce field padding in some structs
  libtransmission/announcer.cc
  libtransmission/bandwidth.cc
  libtransmission/bandwidth.h
  libtransmission/torrent.cc
  libtransmission/torrent.h
Labels: scope:core, type:refactor

#3013 refactor: remove unused tr_torrent fields
  libtransmission/bandwidth.h
  libtransmission/bitfield.h
  libtransmission/torrent.cc
  libtransmission/torrent.h
  libtransmission/tr-dht.cc
Labels: scope:core, type:refactor

#3016 refactor: replace tr_fdlimit with tr_open_files
  Transmission.xcodeproj/project.pbxproj
  libtransmission/CMakeLists.txt
  libtransmission/fdlimit.cc
  libtransmission/inout.cc
  libtransmission/lru-cache.h
  libtransmission/open-files.cc
  libtransmission/open-files.h
  libtransmission/session.cc
  libtransmission/session.h
  libtransmission/torrent.cc
  libtransmission/transmission.h
  tests/libtransmission/CMakeLists.txt
  tests/libtransmission/open-files-test.cc
  tests/libtransmission/test-fixtures.h
Labels: scope:core, type:refactor

#3017 refactor: make tr_swarm.peers a std::vector
  libtransmission/peer-mgr.cc
Labels: scope:core, type:refactor

#3024 fix: invalid tr_peerMsgsImpl::prefetchCount value
  libtransmission/peer-common.h
  libtransmission/peer-mgr.cc
  libtransmission/peer-msgs.cc
  libtransmission/peer-msgs.h
Labels: scope:core, type:fix

#3033 fixup! fix: ensure all bytes read / written to file
  libtransmission/file-posix.cc
Labels: scope:core, type:fixup

#3035 fixup! fix: ensure all bytes read / written to file (#2682)
  libtransmission/inout.cc
Labels: scope:core, type:fixup
