Repository transmission/transmission, pull requests merged in 2022-01, with the labels that each got.

#2370 Fixup construction of temp dir path in `deleteLocalData`
  libtransmission/torrent.cc
Labels: scope:core, type:fixup

#2373 refactor: avoid referencing tr_file struct directly
  libtransmission/inout.cc
  libtransmission/resume.cc
  libtransmission/torrent.cc
  libtransmission/torrent.h
  libtransmission/transmission.h
  libtransmission/verify.cc
  libtransmission/webseed.cc
Labels: scope:core, type:refactor

#2374 refactor: make tr_buildPath() private
  libtransmission/platform.cc
  libtransmission/platform.h
  libtransmission/session.cc
  libtransmission/session.h
  libtransmission/torrent.h
  libtransmission/tr-dht.cc
  libtransmission/utils.cc
  libtransmission/utils.h
  libtransmission/web.cc
  tests/libtransmission/utils-test.cc
  utils/create.cc
Labels: scope:core, type:refactor

#2378 Fix integer overflow when calculating `sizeWhenDone`
  libtransmission/completion.cc
Labels: scope:core, type:fixup

#2376 refactor: make tr_torrent aggregates tr_block_info instead of subclassing
  libtransmission/block-info.h
  libtransmission/inout.cc
  libtransmission/peer-mgr.cc
  libtransmission/peer-msgs.cc
  libtransmission/resume.cc
  libtransmission/torrent-metainfo.h
  libtransmission/torrent.cc
  libtransmission/torrent.h
  libtransmission/webseed.cc
  tests/libtransmission/move-test.cc
  tests/libtransmission/rename-test.cc
Labels: scope:core, type:refactor

#2381 refactor: base64 utils
  libtransmission/crypto-utils.cc
  libtransmission/crypto-utils.h
  libtransmission/rpc-server.cc
  libtransmission/rpcimpl.cc
  qt/AddData.cc
  tests/libtransmission/crypto-test-ref.h
  tests/libtransmission/crypto-test.cc
  tests/libtransmission/rename-test.cc
  tests/libtransmission/test-fixtures.h
  utils/remote.cc
Labels: scope:remote, scope:qt, scope:core, type:refactor

#2382 refactor: use std::string in tr_file
  libtransmission/file-piece-map.cc
  libtransmission/inout.cc
  libtransmission/metainfo.cc
  libtransmission/torrent-ctor.cc
  libtransmission/torrent-magnet.cc
  libtransmission/torrent-metainfo.h
  libtransmission/torrent.cc
  libtransmission/torrent.h
  libtransmission/transmission.h
  macosx/Controller.mm
  macosx/DragOverlayWindow.mm
  macosx/QuickLookPlugin/GeneratePreviewForURL.mm
  qt/OptionsDialog.cc
  tests/libtransmission/announce-list-test.cc
  tests/libtransmission/makemeta-test.cc
  tests/libtransmission/rename-test.cc
  tests/libtransmission/torrent-metainfo-test.cc
  utils/show.cc
Labels: scope:core, type:refactor

#2383 refactor: rename tr_torrent.infoDictSize()
  libtransmission/metainfo.cc
  libtransmission/metainfo.h
  libtransmission/peer-msgs.cc
  libtransmission/torrent-magnet.cc
  libtransmission/torrent.cc
  libtransmission/torrent.h
Labels: scope:core, type:refactor

#2384 refactor: use std::string in tr_info
  libtransmission/metainfo.cc
  libtransmission/rpcimpl.cc
  libtransmission/torrent-magnet.cc
  libtransmission/torrent.cc
  libtransmission/torrent.h
  libtransmission/tr-lpd.cc
  libtransmission/transmission.h
  libtransmission/utils.cc
  libtransmission/utils.h
  tests/libtransmission/announce-list-test.cc
  tests/libtransmission/rename-test.cc
  tests/libtransmission/utils-test.cc
Labels: scope:core, type:refactor

#2385 refactor: migrate makeFilename() to tr_magnet_metainfo
  libtransmission/magnet-metainfo.cc
  libtransmission/magnet-metainfo.h
  libtransmission/metainfo.cc
  libtransmission/metainfo.h
  libtransmission/resume.cc
  libtransmission/torrent-metainfo.cc
  libtransmission/torrent.cc
Labels: scope:core, type:refactor

#2386 refactor: use std::vector in tr_info
  libtransmission/announcer.h
  libtransmission/file-piece-map.cc
  libtransmission/magnet-metainfo.cc
  libtransmission/magnet-metainfo.h
  libtransmission/metainfo.cc
  libtransmission/peer-common.h
  libtransmission/torrent-magnet.cc
  libtransmission/torrent.cc
  libtransmission/torrent.h
  libtransmission/transmission.h
  macosx/QuickLookPlugin/GeneratePreviewForURL.mm
  tests/libtransmission/magnet-metainfo-test.cc
  utils/show.cc
Labels: scope:core, type:refactor

#2387 refactor: unstack nested code in tr_torrentSetMetadataPiece()
  libtransmission/torrent-magnet.cc
Labels: scope:core, type:refactor

#2389 fix: potential infinite loop when parsing benc
  libtransmission/variant-benc.cc
  tests/libtransmission/variant-test.cc
Labels: scope:core, type:fixup

#2390 fix: magnet link regression
  libtransmission/torrent-ctor.cc
  libtransmission/torrent-magnet.cc
  libtransmission/torrent-magnet.h
  libtransmission/torrent.cc
  libtransmission/transmission.h
Labels: scope:core, type:fixup

#2391 Fix another integer overflow bug on 32-bit platforms with torrents > 4GB
  libtransmission/completion.cc
  tests/libtransmission/completion-test.cc
Labels: scope:core, type:fixup

#2397 refactor: replace tr_info with tr_torrent_metainfo
  Transmission.xcodeproj/project.pbxproj
  libtransmission/CMakeLists.txt
  libtransmission/announce-list.cc
  libtransmission/announce-list.h
  libtransmission/file-piece-map.cc
  libtransmission/file-piece-map.h
  libtransmission/magnet-metainfo.cc
  libtransmission/magnet-metainfo.h
  libtransmission/metainfo.cc
  libtransmission/metainfo.h
  libtransmission/mime-types.h
  libtransmission/quark.cc
  libtransmission/quark.h
  libtransmission/resume.cc
  libtransmission/session.cc
  libtransmission/stats.cc
  libtransmission/torrent-ctor.cc
  libtransmission/torrent-magnet.cc
  libtransmission/torrent-metainfo.cc
  libtransmission/torrent-metainfo.h
  libtransmission/torrent.cc
  libtransmission/torrent.h
  libtransmission/transmission.h
  libtransmission/utils.cc
  libtransmission/utils.h
  libtransmission/variant.cc
  libtransmission/variant.h
  tests/libtransmission/CMakeLists.txt
  tests/libtransmission/announce-list-test.cc
  tests/libtransmission/metainfo-test.cc
  tests/libtransmission/torrent-metainfo-test.cc
  tests/libtransmission/utils-test.cc
Labels: scope:core, type:refactor

#2409 fix: broken tooltiop in GTK client peer flag tooltip
  gtk/DetailsDialog.cc
Labels: scope:gtk, type:fixup

#2410 fix: allow malformed magnet links to be added
  libtransmission/web-utils.cc
Labels: scope:core, type:fixup

#2411 fix: parse utorrent peer-id version components as hex
  libtransmission/clients.cc
  tests/libtransmission/clients-test.cc
Labels: scope:core, type:fixup

#2413 fix: potential out-of-range error in io's readOrWritePiece()
  libtransmission/inout.cc
  libtransmission/torrent-metainfo.cc
  libtransmission/torrent-metainfo.h
Labels: scope:core, type:fixup

#2415 fixup! refactor: replace tr_info with tr_torrent_metainfo (#2397)
  libtransmission/torrent-metainfo.cc
Labels: scope:core, type:fixup

#2421 fix: sonarcloud code smells
  gtk/Application.cc
  gtk/DetailsDialog.cc
  gtk/FileList.cc
  gtk/IconCache.cc
  gtk/Notify.cc
  gtk/Session.cc
  gtk/Utils.cc
  libtransmission/announce-list.cc
  libtransmission/announcer-http.cc
  libtransmission/announcer.cc
  libtransmission/cache.cc
  libtransmission/crypto-utils-ccrypto.cc
  libtransmission/crypto-utils-cyassl.cc
  libtransmission/crypto-utils-openssl.cc
  libtransmission/crypto-utils-polarssl.cc
  libtransmission/crypto.cc
  libtransmission/handshake.cc
  libtransmission/natpmp.cc
  libtransmission/net.cc
  libtransmission/peer-mgr.cc
  libtransmission/peer-msgs.cc
  libtransmission/platform.cc
  libtransmission/port-forwarding.cc
  libtransmission/ptrarray.cc
  libtransmission/rpc-server.cc
  libtransmission/rpcimpl.cc
  libtransmission/session-id.cc
  libtransmission/session.cc
  libtransmission/stats.cc
  libtransmission/torrent-magnet.cc
  libtransmission/torrent-magnet.h
  libtransmission/torrent.cc
  libtransmission/tr-utp.cc
  libtransmission/upnp.cc
  libtransmission/utils.cc
  libtransmission/variant-json.cc
  libtransmission/watchdir-generic.cc
  libtransmission/watchdir-inotify.cc
  qt/DetailsDialog.cc
  utils/remote.cc
  utils/show.cc
Labels: scope:remote, scope:show, scope:gtk, scope:qt, scope:core, type:fix

#2423 fix: assertion failed on non-English symbols
  libtransmission/torrent-metainfo.cc
Labels: scope:core, type:fixup

#2424 fix: calculate seed ratio by torrent size.
  libtransmission/torrent.cc
  libtransmission/transmission.h
  macosx/NSStringAdditions.mm
Labels: type:fix

#2435 fix: empty torrent filename
  libtransmission/resume.cc
  libtransmission/torrent-ctor.cc
  libtransmission/torrent-magnet.cc
  libtransmission/torrent-metainfo.h
  libtransmission/torrent.cc
  libtransmission/torrent.h
  libtransmission/transmission.h
  libtransmission/utils.cc
  macosx/Torrent.mm
  tests/libtransmission/rename-test.cc
Labels: scope:core, type:fixup

#2440 fix: string leak regression when udp announces fail
  libtransmission/announcer-udp.cc
Labels: scope:core, type:fixup

#2442 fix: remove assert() that shouldn't always be true
  libtransmission/cache.cc
Labels: scope:core, type:fixup

#2443 fix: make add-torrent dialogs modal in GTK client
  gtk/OptionsDialog.cc
  gtk/PrefsDialog.cc
  gtk/transmission-ui.xml
Labels: scope:gtk, type:fix

#2444 fix: explicitly use unsigned char when checking isprint()
  libtransmission/variant-json.cc
Labels: scope:core, type:fixup

#265 Wrong IPv6 address used in announces
  libtransmission/announcer-http.cc
  libtransmission/net.cc
  libtransmission/net.h
  libtransmission/peer-msgs.cc
  libtransmission/tr-udp.cc
Labels: scope:core, type:fix

#2464 fixup: unused variable warnings
  libtransmission/net.cc
  libtransmission/tr-udp.cc
Labels: scope:core, type:fixup

#2465 fix: long error string truncated in GTK client
  gtk/DetailsDialog.cc
Labels: scope:gtk, type:fix

#1638 fix: don't follow symlinks when removing junk files
  libtransmission/torrent.cc
Labels: scope:core, needs update, type:fix

#2470 fixup! fix: don't follow symlinks when removing junk files (#1638)
  libtransmission/torrent.cc
Labels: scope:core, type:fixup

#2468 fix: in check input before calling tr_sha1_from_string()
  libtransmission/session.cc
Labels: scope:core, type:fixup

#1602 NAT-PMP private/public port and lifetime fix
  libtransmission/natpmp.cc
  libtransmission/natpmp_local.h
  libtransmission/port-forwarding.cc
  libtransmission/session.cc
Labels: scope:core, needs update, type:fix

#1633 Add the option of automatically picking up URLs from the clipboard on window focus
  libtransmission/quark.cc
  libtransmission/quark.h
  qt/MainWindow.cc
  qt/MainWindow.h
  qt/Prefs.cc
  qt/Prefs.h
  qt/PrefsDialog.cc
  qt/PrefsDialog.ui
Labels: enhancement, scope:qt

#2481 fix: memory leak in upnp
  libtransmission/upnp.cc
Labels: scope:core, type:fix, type:perf

#2482 fixup! NAT-PMP private/public port and lifetime fix (#1602)
  libtransmission/port-forwarding.cc
Labels: scope:core, type:fixup

#726 Fix icon install location
  gtk/CMakeLists.txt
Labels: needs clarification, scope:gtk

#2483 test: magnet links with junk values
  tests/libtransmission/magnet-metainfo-test.cc
Labels: scope:core, type:fix

#715 allow stopping torrents in verification states
  libtransmission/rpcimpl.cc
Labels: enhancement, scope:core

#1487 Add content_rating to appdata
  gtk/transmission-gtk.appdata.xml.in
Labels: enhancement, scope:gtk

#2485 refactor: re-enable clang-tidy warnings
  libtransmission/.clang-tidy
  libtransmission/announce-list.h
  libtransmission/announcer.cc
  libtransmission/cache.cc
  libtransmission/file-posix.cc
  libtransmission/peer-mgr-active-requests.cc
  libtransmission/peer-mgr-wishlist.cc
  libtransmission/peer-mgr-wishlist.h
  libtransmission/peer-mgr.cc
  libtransmission/peer-msgs.cc
  libtransmission/quark.cc
  libtransmission/subprocess-posix.cc
  libtransmission/torrent-metainfo.cc
  libtransmission/torrent-metainfo.h
  libtransmission/tr-dht.cc
  libtransmission/utils.cc
  libtransmission/variant.cc
  libtransmission/verify.cc
  libtransmission/webseed.cc
Labels: scope:core, type:refactor

#2486 fix: sonarcloud code smells
  gtk/Application.cc
  gtk/FileList.cc
  gtk/MainWindow.cc
  gtk/MakeDialog.cc
  gtk/Utils.cc
  libtransmission/announcer-http.cc
  libtransmission/announcer.cc
  libtransmission/handshake.cc
  libtransmission/torrent.h
  libtransmission/utils.cc
  libtransmission/variant.cc
  qt/MainWindow.cc
  qt/RpcQueue.h
  qt/Session.cc
  qt/TorrentModel.cc
  qt/VariantHelpers.h
  utils/show.cc
Labels: scope:show, scope:gtk, scope:qt, scope:core, type:fix

#932 Move private interfaces to interface extensions
  macosx/AddMagnetWindowController.mm
  macosx/AddWindowController.mm
  macosx/BadgeView.mm
  macosx/BlocklistDownloader.mm
  macosx/BlocklistDownloaderViewController.mm
  macosx/BlocklistScheduler.mm
  macosx/CreatorWindowController.mm
  macosx/DragOverlayWindow.mm
  macosx/FileListNode.mm
  macosx/FileNameCell.mm
  macosx/FileOutlineController.mm
  macosx/FilterBarController.mm
  macosx/GroupsController.mm
  macosx/GroupsPrefsController.mm
  macosx/InfoActivityViewController.mm
  macosx/InfoFileViewController.mm
  macosx/InfoGeneralViewController.mm
  macosx/InfoPeersViewController.mm
  macosx/InfoTrackersViewController.mm
  macosx/MessageWindowController.mm
  macosx/PortChecker.mm
  macosx/PrefsController.mm
  macosx/StatsWindowController.mm
  macosx/StatusBarController.mm
  macosx/StatusBarView.mm
  macosx/Torrent.mm
  macosx/TorrentCell.mm
  macosx/TorrentTableView.mm
  macosx/TrackerCell.mm
  macosx/URLSheetWindowController.mm
Labels: scope:mac, needs update, type:refactor

#2487 refactor: clang-tidy 14
  libtransmission/.clang-tidy
  libtransmission/utils.cc
  qt/.clang-tidy
  tests/libtransmission/.clang-tidy
Labels: scope:qt, scope:core, type:refactor

#585 Use Android logger when building on Android
  libtransmission/log.cc
Labels: scope:core

#2488 fixup! [android] Use android logger (#585)
  libtransmission/log.cc
Labels: scope:core, type:fixup

#2489 refactor: quark's static_assert formatting
  libtransmission/quark.cc
Labels: scope:core, type:refactor

#2490 refactor: SAX-like benc parser pt. 1
  Transmission.xcodeproj/project.pbxproj
  libtransmission/CMakeLists.txt
  libtransmission/benc.h
  libtransmission/variant-benc.cc
  libtransmission/variant-common.h
  libtransmission/variant.cc
  tests/libtransmission/variant-test.cc
Labels: scope:core, type:perf

#2500 fix: sonarcloud warnings in new code
  libtransmission/announcer.cc
  libtransmission/benc.h
  libtransmission/net.cc
  libtransmission/peer-mgr.cc
  libtransmission/resume.cc
  libtransmission/torrent.cc
  libtransmission/variant-benc.cc
Labels: scope:core, type:fixup

#2502 fixup! refactor: use C++ objects in announcer (#2474)
  libtransmission/peer-mgr.cc
Labels: scope:core, type:fixup

#2505 refactor: saxlike benc pt. 2: add announce response parsing tests
  extras/libtransmission-valgrind.supp
  libtransmission/announcer-common.h
  libtransmission/announcer-http.cc
  libtransmission/peer-mgr.h
  tests/libtransmission/CMakeLists.txt
  tests/libtransmission/announcer-test.cc
Labels: scope:core, type:test

#2506 feat: remember tab selection in Details dialog
  gtk/DetailsDialog.cc
  qt/DetailsDialog.cc
  qt/DetailsDialog.h
Labels: scope:gtk, scope:qt, type:feat

#2507 fix: use libdeflate_gzip_compress in rpc-server.cc
  libtransmission/rpc-server.cc
Labels: scope:core, type:fixup

#2183 web: preferences: incomplete-dir
  web/src/prefs-dialog.js
Labels: enhancement, scope:web, feature disparity

#2527 test: add tests for parsing http tracker scrape responses
  libtransmission/announcer-common.h
  libtransmission/announcer-http.cc
  tests/libtransmission/announcer-test.cc
Labels: scope:core, type:test

#2528 fix: paused torrents not scraped when scrape-paused-torrents-enabled is set
  libtransmission/announcer.cc
  libtransmission/trevent.cc
  libtransmission/utils.cc
Labels: scope:core, type:fixup

#2529 refactor: use the new benc parser in announcer-http
  libtransmission/announcer-http.cc
  libtransmission/benc.h
  libtransmission/quark.cc
  libtransmission/quark.h
Labels: scope:core, type:perf

#2531 refactor: add benc::Handler::Context
  libtransmission/announcer-http.cc
  libtransmission/benc.h
  libtransmission/error.cc
  libtransmission/error.h
  libtransmission/variant-benc.cc
  tests/libtransmission/CMakeLists.txt
  tests/libtransmission/announcer-test.cc
  tests/libtransmission/benc-test.cc
Labels: scope:core, type:refactor

#2535 test: add tr_torrent_metainfo.infoDictSize() tests
  libtransmission/announce-list.cc
  libtransmission/announce-list.h
  libtransmission/magnet-metainfo.cc
  libtransmission/rpcimpl.cc
  libtransmission/torrent-metainfo.cc
  libtransmission/torrent-metainfo.h
  tests/libtransmission/announce-list-test.cc
  tests/libtransmission/makemeta-test.cc
  tests/libtransmission/torrent-metainfo-test.cc
Labels: scope:core, type:test

#2536 fix: sonarcloud use-init-statement warnings in new code
  libtransmission/announcer-http.cc
Labels: scope:core, type:fixup

#2544 fixup! refactor: SAX-like benc parser pt. 1 (#2490)
  libtransmission/benc.h
  tests/libtransmission/benc-test.cc
Labels: scope:core, type:fixup

#2545 fixup! refactor: base64 utils (#2381)
  utils/remote.cc
Labels: scope:remote, type:fixup

#2548 refactor: replace tr_thread with std::thread
  libtransmission/crypto-utils-cyassl.cc
  libtransmission/crypto-utils-polarssl.cc
  libtransmission/file-posix.cc
  libtransmission/makemeta.cc
  libtransmission/platform.cc
  libtransmission/platform.h
  libtransmission/resume.cc
  libtransmission/stats.cc
  libtransmission/torrent.cc
  libtransmission/tr-dht.cc
  libtransmission/trevent.cc
  libtransmission/verify.cc
  libtransmission/web.cc
Labels: scope:core, type:refactor

#2550 chore: remove /upload endpoint from rpc-server
  CMakeLists.txt
  extras/rpc-spec.txt
  libtransmission/rpc-server.cc
  libtransmission/utils.cc
  libtransmission/utils.h
  tests/libtransmission/utils-test.cc
Labels: scope:core, type:refactor

#2552 chore: remove unused function tr_strcasestr()
  CMakeLists.txt
  Transmission.xcodeproj/project.pbxproj
  libtransmission/utils.cc
  libtransmission/utils.h
Labels: scope:core, type:refactor

#2553 chore: iwyu
  gtk/Application.cc
  gtk/Prefs.cc
  gtk/PrefsDialog.cc
  gtk/Session.cc
  libtransmission/announcer-common.h
  libtransmission/benc.h
  libtransmission/handshake.cc
  libtransmission/peer-mgr.h
  libtransmission/platform.cc
  libtransmission/torrent-metainfo.cc
  libtransmission/utils.cc
Labels: scope:gtk, scope:core, type:refactor
