Repository transmission/transmission, pull requests merged in 2022-09, with the labels that each got.

#3745 refactor: reduce http announce timeout interval to 45 seconds
  libtransmission/announcer-http.cc
Labels: scope:core, type:refactor

#3746 refactor: tr_peer_event
  libtransmission/peer-common.h
  libtransmission/peer-mgr.cc
  libtransmission/peer-msgs.cc
  libtransmission/webseed.cc
Labels: scope:core, type:refactor

#3747 perf: check torrrent seed ratio less frequently
  libtransmission/peer-mgr.cc
Labels: scope:core, type:perf

#3748 build: re-enable cert-err34-c checks in clang-tidy
  libtransmission/.clang-tidy
  libtransmission/clients.cc
  libtransmission/rpc-server.cc
  libtransmission/session.cc
  libtransmission/tr-lpd.cc
  libtransmission/utils.cc
  libtransmission/utils.h
  libtransmission/variant-benc.cc
Labels: scope:core, type:refactor, type:build

#3751 refactor: simplify tr_clientForId()
  libtransmission/clients.cc
  libtransmission/clients.h
Labels: scope:core, type:refactor

#3757 Don't crash when hiding top-level windows
  gtk/Utils.cc
Labels: bug, scope:gtk

#3761 test: improve file-win32, file-posix test coverage
  libtransmission/file-posix.cc
  libtransmission/file-win32.cc
  libtransmission/file.h
  tests/libtransmission/file-test.cc
  tests/libtransmission/test-fixtures.h
Labels: scope:core, type:refactor, type:test

#3764 chore: remove dead "fast set" code
  libtransmission/handshake.cc
  libtransmission/peer-msgs.cc
  libtransmission/tr-lpd.cc
  libtransmission/tr-macros.h
Labels: scope:core, type:refactor

#3766 refactor: fix warning issued during LTO build
  libtransmission/announcer-http.cc
Labels: scope:core, type:refactor

#3775 refactor: move the verify worker thread into a wrapper class
  libtransmission/session.cc
  libtransmission/session.h
  libtransmission/torrent.cc
  libtransmission/torrent.h
  libtransmission/verify.cc
  libtransmission/verify.h
  tests/libtransmission/file-test.cc
  tests/libtransmission/rename-test.cc
  tests/libtransmission/test-fixtures.h
Labels: scope:core, type:refactor

#3771 GTK: increase torrent piece size limit as per #3402
  gtk/MakeDialog.cc
Labels: scope:gtk, feature disparity, type:feat, type:ui

#3768 Qt: Allow piece size selection on torrent creation
  qt/MakeDialog.cc
  qt/MakeDialog.h
  qt/MakeDialog.ui
Labels: scope:qt, feature disparity, type:feat

#3780 refactor: constify
  libtransmission/announcer-common.h
  libtransmission/announcer-http.cc
  libtransmission/cache.cc
  libtransmission/cache.h
  libtransmission/handshake.cc
  libtransmission/peer-mgr.cc
  libtransmission/peer-msgs.h
  libtransmission/resume.cc
  libtransmission/rpc-server.cc
  libtransmission/torrent.cc
  libtransmission/tr-dht.cc
  libtransmission/tr-dht.h
  libtransmission/tr-udp.cc
  libtransmission/tr-udp.h
  libtransmission/tr-utp.cc
  libtransmission/transmission.h
  libtransmission/upnp.cc
  libtransmission/webseed.cc
Labels: scope:core, type:refactor

#3784 refactor: use readability-identifier-naming in clang-tidy
  libtransmission/.clang-tidy
  libtransmission/announcer.cc
  libtransmission/announcer.h
  libtransmission/bitfield.cc
  libtransmission/file-posix.cc
  libtransmission/handshake.cc
  libtransmission/log.cc
  libtransmission/log.h
  libtransmission/net.cc
  libtransmission/net.h
  libtransmission/open-files.cc
  libtransmission/peer-common.h
  libtransmission/peer-io.cc
  libtransmission/peer-io.h
  libtransmission/peer-mgr.cc
  libtransmission/peer-mgr.h
  libtransmission/peer-mse.cc
  libtransmission/peer-msgs.cc
  libtransmission/quark.cc
  libtransmission/resume.cc
  libtransmission/rpc-server.cc
  libtransmission/rpcimpl.cc
  libtransmission/session.cc
  libtransmission/torrent-ctor.cc
  libtransmission/torrent-files.cc
  libtransmission/torrent.cc
  libtransmission/torrent.h
  libtransmission/tr-dht.cc
  libtransmission/tr-getopt.cc
  libtransmission/tr-getopt.h
  libtransmission/tr-lpd.cc
  libtransmission/transmission.h
  libtransmission/trevent.cc
  libtransmission/upnp.cc
  libtransmission/upnp.h
  libtransmission/utils.cc
  libtransmission/utils.h
  libtransmission/variant-common.h
  libtransmission/variant-json.cc
  libtransmission/variant.cc
  libtransmission/webseed.cc
Labels: scope:core, type:refactor

#3786 fixup new minor warnings
  libtransmission/file-posix.cc
  libtransmission/session.h
  libtransmission/transmission.h
Labels: scope:core, type:fixup

#3787 fix: qt open magnet dialog munges magnet url
  qt/AddData.h
  qt/MainWindow.cc
  qt/MainWindow.h
  qt/OptionsDialog.cc
  qt/Session.cc
  qt/Session.h
Labels: scope:qt, type:fix, bug:regression

#3788 fix: recent coverity warnings
  libtransmission/peer-msgs.cc
  libtransmission/verify.cc
  tests/libtransmission/file-test.cc
Labels: scope:core, type:fixup

#3782 daemon: use evsignal-based signal handling on POSIX systems
  daemon/daemon-posix.cc
Labels: scope:daemon, needs update, type:feat

#3789 Switch from `Gtk::Menu` to `Gio::Menu` for status bar menus
  gtk/MainWindow.cc
  gtk/MainWindow.ui
Labels: scope:gtk, type:refactor

#3792 refactor: inline short Formatter utils
  qt/Formatter.cc
  qt/Formatter.h
Labels: scope:qt, type:refactor

#3793 refactor: add [[nodiscard]]
  libtransmission/crypto-utils.h
  libtransmission/makemeta.h
  libtransmission/net.h
  libtransmission/peer-mgr.h
  libtransmission/variant-common.h
  libtransmission/variant.h
  libtransmission/watchdir.h
  libtransmission/web-utils.h
  tests/libtransmission/web-utils-test.cc
Labels: scope:core, type:refactor

#3798 refactor: add tr_peerIo::peek()
  libtransmission/handshake.cc
  libtransmission/peer-io.h
  tests/libtransmission/file-test.cc
Labels: scope:core, type:refactor

#3794 refactor: fold session UDP innards into C++ class
  Transmission.xcodeproj/project.pbxproj
  libtransmission/CMakeLists.txt
  libtransmission/announcer-udp.cc
  libtransmission/net.h
  libtransmission/session.cc
  libtransmission/session.h
  libtransmission/tr-dht.cc
  libtransmission/tr-udp.cc
  libtransmission/tr-udp.h
  libtransmission/tr-utp.cc
Labels: scope:core, type:refactor

#3833 chore: iwyu headers
  libtransmission/announcer-http.cc
  libtransmission/bandwidth.h
  libtransmission/file-posix.cc
  libtransmission/file-win32.cc
  libtransmission/handshake.cc
  libtransmission/log.cc
  libtransmission/peer-msgs.cc
  libtransmission/rpc-server.cc
  libtransmission/torrent-files.cc
  libtransmission/torrent-metainfo.cc
  libtransmission/transmission.h
  libtransmission/trevent.cc
  libtransmission/upnp.cc
  libtransmission/utils.cc
  libtransmission/variant.cc
  libtransmission/watchdir.cc
  libtransmission/watchdir.h
  libtransmission/webseed.cc
  qt/Session.cc
Labels: scope:core, type:build

#3836 refactor: tr_globalIPv6() returns a std::optional<in6_addr>
  libtransmission/.clang-tidy
  libtransmission/announcer-http.cc
  libtransmission/net.cc
  libtransmission/net.h
  libtransmission/peer-msgs.cc
  libtransmission/session.h
  libtransmission/tr-udp.cc
Labels: scope:core, type:refactor

#3839 test: fix watchdir CI flake
  tests/libtransmission/watchdir-test.cc
Labels: type:fix, scope:test

#3840 chore: add cppcoreguidelines-pro-type-member-init to .clang-tidy
  libtransmission/.clang-tidy
  libtransmission/announcer-http.cc
  libtransmission/announcer-udp.cc
  libtransmission/announcer.cc
  libtransmission/file-piece-map.cc
  libtransmission/file-piece-map.h
  libtransmission/file-posix.cc
  libtransmission/net.cc
  libtransmission/peer-io.cc
  libtransmission/peer-msgs.cc
  libtransmission/platform-quota.cc
  libtransmission/platform.cc
  libtransmission/rpc-server.cc
  libtransmission/session.cc
  libtransmission/session.h
  libtransmission/tr-dht.cc
  libtransmission/tr-lpd.cc
  libtransmission/tr-udp.cc
  libtransmission/tr-utp.cc
  libtransmission/utils.cc
  libtransmission/variant-json.cc
  libtransmission/variant.cc
  libtransmission/watchdir-inotify.cc
Labels: scope:core, type:build

#3841 refactor: cppcoreguidelines-avoid-goto
  libtransmission/.clang-tidy
  libtransmission/file-win32.cc
  libtransmission/peer-io.cc
  libtransmission/subprocess-posix.cc
  libtransmission/tr-udp.cc
Labels: scope:core, type:refactor

#3842 refactor: remove TR_PRIsv macros
  libtransmission/log.cc
  libtransmission/tr-macros.h
  tests/libtransmission/platform-test.cc
  utils/edit.cc
  utils/remote.cc
  utils/show.cc
Labels: scope:remote, scope:edit, scope:show, scope:core, type:refactor

#3848 fix: unnamed placeholders in create.cc
  utils/create.cc
Labels: scope:create

#3849 fix: #3847 crash on session close
  libtransmission/peer-msgs.cc
  libtransmission/session.cc
  libtransmission/session.h
  libtransmission/tr-dht.cc
  libtransmission/tr-dht.h
  libtransmission/tr-udp.cc
Labels: scope:core, type:fix

#3850 refactor: port forwarding
  Transmission.xcodeproj/project.pbxproj
  libtransmission/CMakeLists.txt
  libtransmission/port-forwarding-natpmp.cc
  libtransmission/port-forwarding-natpmp.h
  libtransmission/port-forwarding-upnp.cc
  libtransmission/port-forwarding-upnp.h
  libtransmission/port-forwarding.cc
  libtransmission/port-forwarding.h
  libtransmission/session.cc
  libtransmission/session.h
  libtransmission/transmission.h
  macosx/PrefsController.mm
Labels: scope:core, type:refactor

#3852 Fix TR_ASSERT equality
  libtransmission/tr-dht.cc
Labels: bug:regression

#3835 blocklist: Add IPv6 support
  libtransmission/blocklist.cc
  libtransmission/blocklist.h
  tests/libtransmission/blocklist-test.cc
Labels: enhancement, scope:core, type:feat

#3853 build: update dependency versions
  CMakeLists.txt
  gtk/Actions.cc
  gtk/FilterBar.cc
  gtk/IconCache.cc
  gtk/MessageLogWindow.cc
  gtk/Session.cc
  gtk/Utils.h
Labels: dependencies, type:build
