Repository transmission/transmission, pull requests merged in 2023-12, with the labels that each got.

#6320 feat: Only show .torrent files in the web UI
  web/src/open-dialog.js
Labels: scope:web, type:feat, type:ui

#6323 refactor: in tr_announce_list, replace port_and_str with aggregated parsed url
  libtransmission/announce-list.cc
  libtransmission/announce-list.h
  libtransmission/announcer-common.h
  libtransmission/announcer-udp.cc
  libtransmission/announcer.cc
  libtransmission/rpcimpl.cc
  libtransmission/transmission.h
  tests/libtransmission/announce-list-test.cc
Labels: scope:core, type:refactor, notes:none

#6325 perf: fewer temporary strings
  libtransmission/error.h
  libtransmission/peer-msgs.cc
  libtransmission/resume.cc
  libtransmission/rpcimpl.cc
Labels: scope:core, type:refactor, type:perf

#6328 refactor: constify the inout module
  libtransmission/cache.cc
  libtransmission/cache.h
  libtransmission/inout.cc
  libtransmission/inout.h
  libtransmission/open-files.cc
  libtransmission/open-files.h
  libtransmission/peer-msgs.cc
  libtransmission/session-settings.h
  libtransmission/session.cc
  libtransmission/session.h
  libtransmission/torrent.cc
  libtransmission/torrent.h
  libtransmission/transmission.h
  libtransmission/variant-converters.cc
  tests/libtransmission/open-files-test.cc
  tests/libtransmission/settings-test.cc
Labels: scope:core, type:refactor, notes:none

#6332 refactor: remove prefetch
  docs/Editing-Configuration-Files.md
  libtransmission/cache.cc
  libtransmission/cache.h
  libtransmission/file-posix.cc
  libtransmission/file-win32.cc
  libtransmission/file.h
  libtransmission/inout.cc
  libtransmission/inout.h
  libtransmission/peer-msgs.cc
  libtransmission/quark.cc
  libtransmission/quark.h
  libtransmission/session-settings.h
  libtransmission/session.h
  libtransmission/verify.cc
Labels: scope:core, type:refactor, notes:none

#6342 refactor: tr_block_info cleanup
  libtransmission/block-info.cc
  libtransmission/block-info.h
  libtransmission/file-piece-map.cc
  libtransmission/file-piece-map.h
  libtransmission/resume.cc
  libtransmission/torrent-metainfo.cc
  libtransmission/torrent.cc
  libtransmission/torrent.h
  tests/libtransmission/block-info-test.cc
  tests/libtransmission/file-piece-map-test.cc
Labels: scope:core, type:refactor, notes:none

#6340 documentation fix: create empty files on tr_torrent::start
  libtransmission/torrent.cc
Labels: type:docs, notes:none

#6337 fixup! fix: low priority not working (#6079)
  libtransmission/bandwidth.cc
  libtransmission/transmission.h
Labels: scope:core, type:refactor, notes:none

#6307 refactor: show 1.0 progress for zero-byte files
  qt/FileTreeItem.cc
  qt/FileTreeItem.h
Labels: scope:qt, type:refactor, type:ui, notes:none

#6347 chore: update webapp
  web/README
  web/public_html/index.html
  web/public_html/transmission-app.css
  web/public_html/transmission-app.js
  web/public_html/transmission-app.js.LEGAL.txt
Labels: scope:web, notes:none, type:chore

#6348 fix: crash after nullptr dereference in rpcimpl
  libtransmission/rpcimpl.cc
Labels: scope:core, type:fix, notes:none

#6346 docs: 4.0.5 release notes
  news/news-4.0.5.md
Labels: scope:docs, notes:none

#6350 fix: add check for `EWOULDBLOCK`
  libtransmission/peer-io.cc
Labels: scope:core, type:fix, notes:none

#6357 GTK: Add missing 4.0.4 and 4.0.5 releases to metainfo
  gtk/transmission-gtk.metainfo.xml.in
Labels: type:build

#6370 fix: remove unnecessary locking in global ip cache
  libtransmission/global-ip-cache.cc
  libtransmission/global-ip-cache.h
Labels: scope:core, type:fix, notes:none

#6364 fix: sometimes stuck magnet metadata transfer
  libtransmission/peer-msgs.cc
  libtransmission/torrent-magnet.cc
Labels: scope:core, type:fix, notes:none

#6321 Use screen.visibleFrame instead of screen.frame
  macosx/Controller.mm
  macosx/TorrentTableView.mm
Labels: scope:mac, type:fix

#3926 feat(qt): Add ETA to compact view
  qt/TorrentDelegate.cc
Labels: scope:qt, i18n, type:feat, semver:minor

#6379 Fill random buffer in chunks with mbedtls crypto backend
  libtransmission/crypto-utils-mbedtls.cc
  tests/libtransmission/crypto-test.cc
Labels: scope:core, type:fix, semver:patch

#6393 fix: build when compiling with GTKMM-4
  gtk/OptionsDialog.cc
Labels: scope:gtk, type:fix

#6395 fix: TeamCity `Illegal instructions` error
  libtransmission/variant-json.cc
Labels: scope:core, type:fix, notes:none

#6378 GTK: Add 4.0.4 and 4.0.5 releases to metainfo
  gtk/transmission-gtk.metainfo.xml.in
Labels: type:build

#6398 fix: allow aborting torrent verify mid-way again
  libtransmission/verify.cc
  libtransmission/verify.h
Labels: scope:core, type:fix, notes:none

#6400 fix: gcc 13 warnings, pt. 1
  libtransmission/rpcimpl.cc
  libtransmission/session.cc
  libtransmission/torrent.cc
  libtransmission/variant.cc
  qt/Application.h
  qt/MainWindow.cc
  qt/TorrentFilter.cc
  qt/VariantHelpers.cc
Labels: scope:qt, scope:core, scope:3rdparty, type:fix, notes:none

#6405 fix: mark torrent as changed when stopping
  libtransmission/torrent.cc
Labels: scope:core, type:fix, semver:patch

#6414 fix: use correct time to determine write buffer size
  libtransmission/peer-msgs.cc
Labels: scope:core, type:fix, notes:none

#6404 fix: gcc-13 warnings pt. 2
  gtk/FileList.cc
  gtk/OptionsDialog.cc
  libtransmission/net.h
  libtransmission/resume.cc
  libtransmission/subprocess-posix.cc
  libtransmission/transmission.h
  macosx/FilePriorityCell.mm
  tests/gtest/CMakeLists.txt
  tests/libtransmission/net-test.cc
Labels: scope:gtk, scope:mac, scope:core, type:fix, scope:test, notes:none

#6409 fix: esbuild load `svg` and `png` as `dataurl` type
  web/esbuild.mjs
Labels: scope:web, type:fix, semver:patch

#6394 fix: don't create all 0-byte files in `MakemetaTest::makeRandomFiles()`
  tests/libtransmission/makemeta-test.cc
Labels: type:fix, scope:test, notes:none

#6430 fix: update WebUI build instructions to use `dataurl` loader for images
  web/README.md
Labels: scope:web, type:docs, semver:patch

#6406 refactor: allow explicitly queuing functions in session thread
  libtransmission/rpc-server.cc
  libtransmission/session-thread.cc
  libtransmission/session-thread.h
  libtransmission/session.cc
  libtransmission/session.h
  libtransmission/torrent.cc
  libtransmission/webseed.cc
  tests/libtransmission/move-test.cc
Labels: scope:core, type:refactor, notes:none

#6432 refactor: remove tr_str_is_empty()
  libtransmission/subprocess-win32.cc
  libtransmission/torrent.cc
  libtransmission/utils.h
  utils/remote.cc
Labels: scope:remote, scope:core, type:refactor, notes:none

#6433 refactor: remove tr_strlcpy()
  Transmission.xcodeproj/project.pbxproj
  libtransmission/announcer.cc
  libtransmission/rpc-server.cc
  libtransmission/utils.cc
  libtransmission/utils.h
  tests/libtransmission/utils-test.cc
Labels: scope:core, type:refactor, notes:none

#6435 refactor: remove tr_parse_result enum
  gtk/Session.cc
  gtk/Session.h
  libtransmission/transmission.h
Labels: scope:gtk, scope:core, type:refactor, notes:none

#6428 Qt: Add labels feature from webclient
  qt/DetailsDialog.cc
  qt/DetailsDialog.h
  qt/DetailsDialog.ui
  qt/Session.cc
  qt/Torrent.cc
  qt/Torrent.h
Labels: needs UI review

#6450 Add sequentialDownload to list of rpc get response keys
  libtransmission/rpcimpl.cc
Labels: scope:core, type:fix

#6448 fix: exclude `(B/s)` from parameter names
  docs/rpc-spec.md
Labels: scope:docs, type:docs, notes:none, semver:patch

#6454 fix: `sequentialDownload` support in `transmission-remote`
  utils/remote.cc
Labels: scope:remote, type:fix

#6447 ui: unify percent done format in `transmission-remote`
  utils/remote.cc
Labels: scope:remote, type:ui, notes:none

#6463 Fix a couple of logging issues
  daemon/daemon-win32.cc
  libtransmission/rpc-server.cc
Labels: scope:daemon, scope:core, type:fix, semver:patch

#6466 Fix: Implicit conversion loses integer precision
  libtransmission/block-info.cc
  libtransmission/block-info.h
  libtransmission/variant.cc
  libtransmission/variant.h
  macosx/Controller.mm
  macosx/PrefsController.mm
  macosx/Torrent.mm
Labels: notes:none

#6452 perf: Don't poll every second for kevents
  macosx/VDKQueue/VDKQueue.h
  macosx/VDKQueue/VDKQueue.mm
Labels: scope:mac

#6462 webui: make torrent row colours more readable
  web/assets/css/transmission-app.scss
  web/src/torrent-row.js
Labels: scope:web, type:ui, notes:none
