Repository transmission/transmission, pull requests merged in 2023-09, with the labels that each got.

#5828 WebUI: Improved filterbar for narrowed viewports
  web/assets/css/transmission-app.scss
  web/public_html/index.html
Labels: scope:web, type:ui, semver:patch

#5945 refactor: tidy up announcer code
  libtransmission/announce-list.cc
  libtransmission/announcer-common.h
  libtransmission/announcer-http.cc
  libtransmission/announcer-udp.cc
  libtransmission/announcer.cc
  libtransmission/announcer.h
  tests/libtransmission/announcer-test.cc
  tests/libtransmission/announcer-udp-test.cc
Labels: scope:core, type:fix, type:refactor, notes:none

#5960 fix: transmission-remote -l regression
  libtransmission/variant.cc
Labels: scope:core, type:fix, semver:patch

#5947 WebUI: General responsive UI
  web/assets/css/transmission-app.scss
  web/src/inspector.js
  web/src/prefs-dialog.js
  web/src/transmission.js
  web/src/utils.js
Labels: scope:web, type:perf, type:feat, semver:minor

#5846 Refactor: torrent cell and small torrent cell
  macosx/Base.lproj/MainMenu.xib
  macosx/SmallTorrentCell.h
  macosx/SmallTorrentCell.mm
  macosx/TorrentCell.mm
  macosx/TorrentTableView.mm
Labels: scope:mac, type:refactor

#5969 fix: workaround HSTS upgrading HTTP trackers announces to HTTPS
  libtransmission/web.cc
Labels: scope:core, type:fix, semver:patch

#5957 fix: magnet data invalidates tracker IDs
  libtransmission/torrent.cc
Labels: scope:core, type:fix, semver:minor

#5897 feat: updated colors and label/button styles
  web/assets/css/transmission-app.scss
  web/src/file-row.js
  web/src/inspector.js
  web/src/torrent-row.js
Labels: scope:web, type:feat, semver:minor

#5983 refactor: public tr_session settings API now returns tr_variants
  cli/cli.cc
  daemon/daemon.cc
  gtk/Application.cc
  gtk/Prefs.cc
  gtk/Prefs.h
  libtransmission/rpc-server.cc
  libtransmission/rpc-server.h
  libtransmission/session-alt-speeds.cc
  libtransmission/session-alt-speeds.h
  libtransmission/session-settings.cc
  libtransmission/session-settings.h
  libtransmission/session.cc
  libtransmission/session.h
  libtransmission/transmission.h
  libtransmission/variant-converters.cc
  libtransmission/variant.h
  macosx/Controller.mm
  qt/Prefs.cc
  qt/Prefs.h
  qt/Session.cc
  tests/libtransmission/session-test.cc
  tests/libtransmission/settings-test.cc
Labels: scope:core, type:refactor, notes:none

#5941 fix: heap-use-after-free in peer communications
  libtransmission/peer-mgr.cc
Labels: scope:core, type:fix, notes:none

#5991 Fix selected torrents when moving rows
  macosx/Controller.mm
  macosx/TorrentTableView.h
  macosx/TorrentTableView.mm
Labels: scope:mac, bug:regression

#5980 docs: fix comment typos
  README.md
  libtransmission/peer-mgr.cc
Labels: type:docs, notes:none

#5994 perf: do not call `session-set` in `session-get` callback
  web/src/prefs-dialog.js
Labels: scope:web, type:perf, semver:patch

#5998 refactor: tr_variant API update
  libtransmission/variant.cc
  libtransmission/variant.h
Labels: scope:core, notes:none, semver:minor

#5939 feat: add `preferred-transport` to settings.json
  docs/Editing-Configuration-Files.md
  libtransmission/peer-io.cc
  libtransmission/peer-io.h
  libtransmission/peer-mgr.cc
  libtransmission/quark.cc
  libtransmission/quark.h
  libtransmission/session-settings.h
  libtransmission/session.h
  libtransmission/variant-converters.cc
  tests/libtransmission/settings-test.cc
Labels: scope:core, type:feat, semver:minor

#6006 refactor: use new tr_variant API in tr_session
  cli/cli.cc
  daemon/daemon.cc
  gtk/Application.cc
  gtk/Prefs.cc
  libtransmission/rpcimpl.cc
  libtransmission/session.cc
  libtransmission/session.h
  libtransmission/transmission.h
  libtransmission/utils.cc
  libtransmission/utils.h
  libtransmission/variant.h
  macosx/Controller.mm
  qt/Session.cc
  tests/libtransmission/session-test.cc
  tests/libtransmission/test-fixtures.h
Labels: scope:core, type:refactor, notes:none

#6034 fix: add seed progress percentage to compact rows
  web/assets/css/transmission-app.scss
Labels: scope:web, type:fix, semver:patch

#6036 fixup! refactor: tr_variant API update (#5998)
  libtransmission/rpcimpl.cc
  libtransmission/variant.h
Labels: type:fix, notes:none, semver:patch

#5895 feat: improved overflow menu for web client
  web/assets/css/transmission-app.scss
  web/src/about-dialog.js
  web/src/overflow-menu.js
Labels: scope:web, type:ui

#6016 Fix broken UI and windows on macOS Sonoma
  macosx/Base.lproj/InfoActivityView.xib
  macosx/Base.lproj/InfoGeneralView.xib
  macosx/Base.lproj/InfoOptionsView.xib
  macosx/CreatorWindowController.mm
  macosx/FilterBar.xib
  macosx/InfoFileView.xib
  macosx/InfoPeersView.xib
  macosx/InfoTrackersView.xib
  macosx/MessageWindowController.mm
  macosx/PrefsController.mm
  macosx/StatsWindowController.mm
  macosx/StatusBar.xib
Labels: bug, scope:mac, semver:patch

#5900 fix: remove redundant `tr_lpd::create()` call
  libtransmission/session.cc
Labels: scope:core, type:fix, notes:none

#6025 feat: BT and MSE handshake rework
  libtransmission/handshake.cc
  libtransmission/handshake.h
  libtransmission/peer-io.cc
  libtransmission/peer-io.h
  libtransmission/peer-mse.h
  libtransmission/tr-buffer.h
Labels: scope:core, type:feat, bep-compliance

#6028 fix: Fixed updating magnet link after selecting same torrent again
  web/src/inspector.js
  web/src/utils.js
Labels: scope:web, type:fix, semver:patch

#5928 feat: add touchscreen support for context menu
  web/assets/css/transmission-app.scss
  web/src/context-menu.js
  web/src/transmission.js
Labels: needs clarification, scope:web, type:ui

#5974 fix tr_sys_path_copy in file-posix.cc for some Synology Devices (#5966)
  libtransmission/file-posix.cc
Labels: scope:core, type:fix, semver:patch

#6049 fix: "Unrecognized colorspace number -1"
  macosx/ProgressBarView.mm
Labels: scope:mac, type:fix

#6048 fix: correct log output in `tr_torrent::recheck_completeness()`
  libtransmission/torrent.cc
Labels: scope:core, type:fix, notes:none

#6047 chore: bump minimum openssl version to 1.1.0
  CMakeLists.txt
Labels: scope:3rdparty, dependencies, type:build, needs code review

#6050 refactor: remove redundant code when adding announce lists to metainfo
  libtransmission/announce-list.cc
  libtransmission/announce-list.h
  libtransmission/makemeta.cc
  libtransmission/torrent-magnet.cc
Labels: type:refactor, notes:none

#6012 feat: support redirects to magnet
  macosx/Controller.mm
Labels: scope:mac, type:feat

#6051 Fix macOS 14 UI not clipping views and crashing on window restoration
  macosx/Base.lproj/InfoActivityView.xib
  macosx/Base.lproj/InfoGeneralView.xib
  macosx/Base.lproj/InfoOptionsView.xib
  macosx/CreatorWindowController.mm
  macosx/FilterBar.xib
  macosx/InfoFileView.xib
  macosx/InfoPeersView.xib
  macosx/InfoTrackersView.xib
  macosx/MessageWindowController.mm
  macosx/PrefsController.mm
  macosx/StatsWindowController.mm
  macosx/StatusBar.xib
Labels: scope:mac, type:fix, semver:patch
