Repository transmission/transmission, pull requests merged in 2023-08, with the labels that each got.

#5801 feat: split connectable and non-connectable pool
  libtransmission/global-ip-cache.cc
  libtransmission/net.h
  libtransmission/peer-common.h
  libtransmission/peer-io.h
  libtransmission/peer-mgr.cc
  libtransmission/peer-mgr.h
  libtransmission/peer-msgs.cc
  libtransmission/peer-msgs.h
  libtransmission/peer-socket.h
  libtransmission/rpc-server.cc
  libtransmission/webseed.cc
  libtransmission/webseed.h
Labels: scope:core, type:perf, type:feat, semver:minor

#5876 fix: incorrect pex flags merge logic
  libtransmission/peer-mgr.h
Labels: scope:core, type:fix, notes:none

#5858 Switch to list view for torrents list (GTK 4)
  .github/workflows/actions.yml
  CMakeLists.txt
  gtk/CMakeLists.txt
  gtk/DetailsDialog.cc
  gtk/DynamicPropertyStore.h
  gtk/FileList.cc
  gtk/FilterBar.cc
  gtk/GtkCompat.h
  gtk/MainWindow.cc
  gtk/MessageLogWindow.cc
  gtk/Percents.h
  gtk/PrefsDialog.cc
  gtk/Session.cc
  gtk/Torrent.cc
  gtk/Torrent.h
  gtk/TorrentCellRenderer.cc
  gtk/TorrentCellRenderer.h
  gtk/Utils.cc
  gtk/Utils.h
  gtk/transmission-ui.css
  gtk/ui/gtk4/MainWindow.ui
  gtk/ui/gtk4/TorrentListItemCompact.ui
  gtk/ui/gtk4/TorrentListItemFull.ui
  gtk/ui/gtk4/transmission-ui.gresource.xml
Labels: scope:gtk, type:ui, semver:minor

#5875 fix: announce LDP on listening interface
  libtransmission/session.h
  libtransmission/tr-lpd.cc
  libtransmission/tr-lpd.h
  tests/libtransmission/lpd-test.cc
Labels: scope:core, type:fix, bep-compliance, semver:patch

#5856 regression fix: missing priority icon in torrent cell
  macosx/Base.lproj/MainMenu.xib
  macosx/SmallTorrentCell.h
  macosx/SmallTorrentCell.mm
  macosx/TorrentCell.h
  macosx/TorrentCell.mm
Labels: scope:mac, type:fix, type:ui, bug:regression

#5871 fix: announce with query replace bug (fixes #5802)
  libtransmission/announce-list.cc
  libtransmission/announce-list.h
  tests/libtransmission/announce-list-test.cc
Labels: scope:core, type:fix, semver:patch

#5893 WebUI: Fix graying out inspector
  web/assets/css/transmission-app.scss
  web/public_html/index.html
Labels: scope:web, type:fix

#5807 fixup! perf: improve sorting performance in `tr_peerMgrGetPeers()`
  libtransmission/peer-mgr.cc
Labels: scope:core, type:fix, notes:none

#5863 add documentation for `session-id` rpc field
  docs/rpc-spec.md
Labels: scope:docs, type:docs, notes:none, semver:patch

#5806 fix: cover all pex disabled cases in `get_peer_candidate()`
  libtransmission/peer-mgr.cc
Labels: scope:core, type:fix, notes:none

#5859 add myself to AUTHORS
  AUTHORS
Labels: type:docs, notes:none

#5762 WebUI: Progress bar colour changes
  web/assets/css/transmission-app.scss
Labels: scope:web, type:ui, semver:minor

#5889 fix: do not mark peer as not connectable when we are currently connected
  libtransmission/peer-mgr.cc
  tests/libtransmission/CMakeLists.txt
  tests/libtransmission/tr-peer-info-test.cc
Labels: scope:core, type:fix, scope:test, notes:none

#5870 change some log-levels in global-ip-cache.cc from info to debug
  libtransmission/global-ip-cache.cc
Labels: scope:core, type:refactor, notes:none

#5903 refactor: add tr_variant_serde
  Transmission.xcodeproj/project.pbxproj
  daemon/daemon.cc
  gtk/Application.cc
  libtransmission/CMakeLists.txt
  libtransmission/announce-list.cc
  libtransmission/benc.h
  libtransmission/makemeta.cc
  libtransmission/peer-msgs.cc
  libtransmission/resume.cc
  libtransmission/rpc-server.cc
  libtransmission/session.cc
  libtransmission/stats.cc
  libtransmission/torrent-magnet.cc
  libtransmission/tr-dht.cc
  libtransmission/variant-benc.cc
  libtransmission/variant-common.h
  libtransmission/variant-json.cc
  libtransmission/variant.cc
  libtransmission/variant.h
  qt/Prefs.cc
  qt/RpcClient.cc
  tests/libtransmission/dht-test.cc
  tests/libtransmission/json-test.cc
  tests/libtransmission/makemeta-test.cc
  tests/libtransmission/variant-test.cc
  utils/edit.cc
  utils/remote.cc
  utils/show.cc
Labels: scope:core, type:refactor

#5878 refactor: re-organise `net.h` member functions
  libtransmission/announcer-http.cc
  libtransmission/announcer-udp.cc
  libtransmission/global-ip-cache.cc
  libtransmission/net.cc
  libtransmission/net.h
  libtransmission/peer-io.cc
  libtransmission/peer-mgr.cc
  libtransmission/peer-mgr.h
  libtransmission/peer-msgs.cc
  libtransmission/peer-socket.h
  libtransmission/port-forwarding-natpmp.cc
  libtransmission/rpc-server.cc
  libtransmission/rpc-server.h
  libtransmission/session-settings.h
  libtransmission/session.cc
  libtransmission/tr-dht.cc
  libtransmission/tr-lpd.cc
  libtransmission/tr-udp.cc
  libtransmission/tr-utp.cc
  libtransmission/variant-converters.cc
  tests/libtransmission/announcer-udp-test.cc
  tests/libtransmission/dht-test.cc
  tests/libtransmission/handshake-test.cc
  tests/libtransmission/lpd-test.cc
  tests/libtransmission/net-test.cc
  tests/libtransmission/settings-test.cc
Labels: scope:core, type:refactor, notes:none

#5827 WebUI: Fix overflow-menu and context-menu positioning for small viewports
  web/assets/css/transmission-app.scss
  web/src/transmission.js
  web/src/utils.js
Labels: scope:web, type:fix, type:ui

#5923 refactor: make tr_variant follow RAII
  cli/cli.cc
  daemon/daemon.cc
  daemon/daemon.h
  gtk/Application.cc
  gtk/DetailsDialog.cc
  gtk/Session.cc
  libtransmission/announce-list.cc
  libtransmission/makemeta.cc
  libtransmission/peer-msgs.cc
  libtransmission/resume.cc
  libtransmission/rpc-server.cc
  libtransmission/rpcimpl.cc
  libtransmission/session.cc
  libtransmission/stats.cc
  libtransmission/torrent-magnet.cc
  libtransmission/tr-dht.cc
  libtransmission/transmission.h
  libtransmission/variant-benc.cc
  libtransmission/variant-json.cc
  libtransmission/variant.cc
  libtransmission/variant.h
  macosx/Controller.mm
  qt/Prefs.cc
  qt/RpcClient.cc
  qt/Session.cc
  qt/VariantHelpers.h
  tests/libtransmission/dht-test.cc
  tests/libtransmission/json-test.cc
  tests/libtransmission/makemeta-test.cc
  tests/libtransmission/rpc-test.cc
  tests/libtransmission/session-test.cc
  tests/libtransmission/settings-test.cc
  tests/libtransmission/test-fixtures.h
  tests/libtransmission/variant-test.cc
  utils/edit.cc
  utils/remote.cc
  utils/show.cc
Labels: scope:core, type:refactor, notes:none

#5911 WebUI: Listen to K to edit labels
  web/src/action-manager.js
  web/src/transmission.js
Labels: scope:web, type:feat, semver:minor

#5930 refactor: replace tr_variant::is_T() with tr_variant::holds_alternative<T>()
  libtransmission/peer-msgs.cc
  libtransmission/resume.cc
  libtransmission/session.cc
  libtransmission/variant-benc.cc
  libtransmission/variant-json.cc
  libtransmission/variant.cc
  libtransmission/variant.h
  qt/TorrentModel.cc
  qt/VariantHelpers.h
  tests/libtransmission/json-test.cc
  tests/libtransmission/rpc-test.cc
  tests/libtransmission/variant-test.cc
  utils/remote.cc
Labels: scope:core, type:refactor, notes:none

#5916 fix: minor coverity warnings
  gtk/Application.cc
  gtk/FilterBar.cc
  gtk/Utils.h
  libtransmission/announcer.cc
  libtransmission/file-capacity.cc
  libtransmission/session.cc
  libtransmission/tr-udp.cc
  libtransmission/utils.h
  tests/libtransmission/announce-list-test.cc
  tests/libtransmission/file-test.cc
  utils/remote.cc
Labels: scope:remote, scope:gtk, scope:core, type:fix, notes:none

#5936 refactor: use std::variant in tr_variant
  libtransmission/variant-json.cc
  libtransmission/variant.cc
  libtransmission/variant.h
Labels: scope:core, type:refactor, notes:none, semver:minor

#5924 docs: add release notes for 4.0.4
  news/news-4.0.4.md
Labels: type:docs

#5949 refactor: prefer functions return std::string instead of tr_strbuf
  libtransmission/magnet-metainfo.cc
  libtransmission/magnet-metainfo.h
  libtransmission/torrent-magnet.cc
  libtransmission/torrent-metainfo.cc
  libtransmission/torrent-metainfo.h
  tests/libtransmission/torrent-metainfo-test.cc
Labels: scope:core, type:refactor, notes:none
