Repository transmission/transmission, pull requests merged in 2023-07, with the labels that each got.

#5709 Revert "perf: improve IPv4 `tr_address` comparison"
  libtransmission/net.cc
  tests/libtransmission/net-test.cc
Labels: type:fix, notes:none

#5711 fix: recent build warnings and errors
  libtransmission/inout.cc
  qt/FileTreeItem.cc
  qt/FileTreeView.cc
  qt/RpcQueue.cc
Labels: type:fix, notes:none

#5712 chore: update mime types
  libtransmission/mime-types.h
  libtransmission/mime-types.js
Labels: scope:core, dependencies, notes:none

#5715 perf: faster Cache::write_contiguous()
  libtransmission/cache.cc
Labels: scope:core, type:perf, semver:patch

#5720 perf: use small:set in tr_file_piece_map::reset()
  libtransmission/file-piece-map.cc
Labels: scope:core, type:perf

#5722 perf: use small::unordered_map in tr_torrent::primary_mime_type()
  libtransmission/torrent.cc
Labels: scope:core, type:perf, semver:minor

#5724 perf: use small::string in daemon::printMessage()
  daemon/daemon.cc
Labels: scope:daemon, type:perf, semver:minor

#5725 perf: avoid string allocations by using fixed-width hash strings
  libtransmission/crypto-utils.cc
  libtransmission/crypto-utils.h
  libtransmission/magnet-metainfo.h
  libtransmission/tr-strbuf.h
  qt/AddData.cc
  qt/Torrent.h
Labels: scope:core, type:perf

#5726 perf: move log strings instead of cloning them
  libtransmission/announcer-udp.cc
  libtransmission/announcer.cc
  libtransmission/file.cc
  libtransmission/inout.cc
  libtransmission/log.cc
  libtransmission/log.h
  libtransmission/torrent.cc
Labels: scope:core, type:perf

#5716 refactor: add lightweight observable / observer for decoupling
  libtransmission/CMakeLists.txt
  libtransmission/observable.h
  libtransmission/peer-mgr.cc
  libtransmission/peer-mgr.h
  libtransmission/session.cc
  libtransmission/session.h
  libtransmission/torrent.cc
  libtransmission/torrent.h
Labels: scope:core, type:refactor, notes:none

#5721 fix: assert failure when Transmission quit with pending IP queries
  libtransmission/global-ip-cache.cc
Labels: scope:core, type:fix, notes:none

#5728 perf: minor cleanups
  libtransmission/makemeta.h
  libtransmission/peer-mgr.cc
  libtransmission/torrent-metainfo.h
  libtransmission/torrent.h
Labels: scope:core, type:refactor, type:perf, notes:none

#5723 refactor: use `std::pair` to store socket addresses
  libtransmission/net.cc
  libtransmission/net.h
  libtransmission/peer-io.cc
  libtransmission/peer-io.h
  libtransmission/peer-mgr.cc
  libtransmission/peer-socket.cc
  libtransmission/peer-socket.h
  libtransmission/session.cc
  libtransmission/tr-utp.cc
  tests/libtransmission/handshake-test.cc
Labels: scope:core, type:refactor, notes:none

#5729 add constexpr to `peer_atom` methods
  libtransmission/peer-mgr.cc
Labels: scope:core, type:refactor, notes:none

#5730 refactor: add tr_socket_address typedef
  libtransmission/.clang-tidy
  libtransmission/handshake.h
  libtransmission/net.cc
  libtransmission/net.h
  libtransmission/peer-io.cc
  libtransmission/peer-io.h
  libtransmission/peer-mgr.cc
  libtransmission/peer-mgr.h
  libtransmission/peer-msgs.cc
  libtransmission/peer-msgs.h
  libtransmission/peer-socket.cc
  libtransmission/peer-socket.h
  libtransmission/tr-dht.cc
Labels: scope:core, type:refactor, notes:none

#5734 perf: faster get peer candidates
  libtransmission/peer-mgr.cc
Labels: scope:core, type:perf, semver:minor

#5738 chore: misc-include-cleaner (partial)
  libtransmission/announcer-http.cc
  libtransmission/announcer-udp.cc
  libtransmission/announcer.cc
  libtransmission/bitfield.cc
  libtransmission/cache.cc
  libtransmission/crypto-utils-fallback.cc
  libtransmission/crypto-utils.cc
  libtransmission/error.cc
  libtransmission/file.cc
  libtransmission/magnet-metainfo.cc
  libtransmission/makemeta.cc
  libtransmission/net.cc
  libtransmission/peer-mgr-wishlist.cc
  libtransmission/peer-mse.cc
  libtransmission/peer-msgs.cc
  libtransmission/platform.cc
  libtransmission/port-forwarding-natpmp.cc
  libtransmission/rpc-server.cc
  libtransmission/rpcimpl.cc
  libtransmission/session.cc
  libtransmission/torrent-ctor.cc
  libtransmission/torrent-metainfo.cc
  libtransmission/torrent.cc
  libtransmission/tr-assert.cc
  libtransmission/tr-udp.cc
  libtransmission/utils-ev.cc
  libtransmission/variant-benc.cc
  libtransmission/variant.cc
  libtransmission/watchdir-inotify.cc
  libtransmission/web-utils.cc
Labels: scope:core, notes:none, type:chore

#5742 refactor: add tr_compare_3way()
  libtransmission/announcer.cc
  libtransmission/net.cc
  libtransmission/peer-mgr-wishlist.cc
  libtransmission/peer-mgr.cc
  libtransmission/utils.h
  libtransmission/verify.cc
  tests/libtransmission/net-test.cc
Labels: scope:core, type:refactor, notes:none

#5737 Fix missing #include in DetailsDialog.cc
  gtk/DetailsDialog.cc
Labels: scope:gtk, notes:none

#5608 transmission-remote: for '-l', implement default sorting by addedDate
  utils/remote.cc
Labels: scope:remote, type:ui, semver:minor

#5695 fix: memory leak from signal handling event in daemon
  daemon/daemon-posix.cc
  daemon/daemon-win32.cc
  daemon/daemon.cc
  daemon/daemon.h
Labels: scope:daemon, type:fix

#5739 fix: spelling mistake in `net.h` function call
  libtransmission/net.h
  tests/libtransmission/net-test.cc
Labels: scope:core, type:fix, notes:none

#5748 fixup! refactor: remove libtransmission::Buffer (#5676)
  libtransmission/tr-buffer.h
Labels: scope:core, type:fix, notes:none

#5751 fixup! perf: faster get peer candidates (#5734)
  libtransmission/peer-mgr.cc
Labels: scope:core, type:fix, notes:none

#5688 `--init` added in `Building Transmission from Git (updating)` section
  README.md
Labels: scope:docs

#5755 perf: avoid copying/moving elements in peer candidate list
  libtransmission/peer-mgr.cc
Labels: scope:core, type:perf, notes:none

#5756 feat: do not auto-disconnect when seeding & a known seed handshakes
  libtransmission/handshake.cc
  libtransmission/handshake.h
  libtransmission/peer-mgr.cc
  tests/libtransmission/handshake-test.cc
Labels: scope:core, notes:none, semver:minor

#5769 fix: incorret log message in `global-ip-cache.cc`
  libtransmission/global-ip-cache.cc
Labels: scope:core, type:fix, notes:none

#5768 perf: use small::max_size_vector in tr_torrentGetMetadataPiece()
  libtransmission/peer-msgs.cc
  libtransmission/torrent-magnet.cc
  libtransmission/torrent-magnet.h
  libtransmission/variant.cc
  tests/libtransmission/torrent-magnet-test.cc
Labels: scope:core, type:perf, semver:minor

#5770 remove redundant seed limit check
  libtransmission/torrent.cc
Labels: scope:core, notes:none

#5772 refactor: make tr_socket_address a class
  libtransmission/global-ip-cache.cc
  libtransmission/net.cc
  libtransmission/net.h
  libtransmission/peer-mgr.cc
  libtransmission/peer-socket.cc
  libtransmission/peer-socket.h
  libtransmission/tr-dht.cc
  libtransmission/tr-udp.cc
  tests/libtransmission/dht-test.cc
  tests/libtransmission/handshake-test.cc
  tests/libtransmission/net-test.cc
Labels: scope:core, type:refactor, notes:none

#5771 Fix web ui start/pause icon size
  web/assets/css/transmission-app.scss
Labels: scope:web, type:fix, type:ui, semver:patch

#5760 chore: minor code cleanup
  libtransmission/bitfield.cc
  libtransmission/bitfield.h
  libtransmission/peer-mgr-wishlist.cc
  libtransmission/peer-mgr.cc
  libtransmission/resume.cc
Labels: scope:core, type:refactor, notes:none

#5773 refactor: replace `peer_atom` with `tr_peer_info`
  libtransmission/peer-common.h
  libtransmission/peer-mgr.cc
  libtransmission/peer-mgr.h
  libtransmission/peer-msgs.cc
  libtransmission/peer-msgs.h
  libtransmission/transmission.h
Labels: scope:core, type:refactor, notes:none

#5784 fix: formatting error in `Editing-Configuration-Files.md`
  docs/Editing-Configuration-Files.md
Labels: scope:docs, type:fix, type:docs

#5783 fix/cleanups to tr_peerMsgsImpl
  libtransmission/peer-msgs.cc
  libtransmission/rpcimpl.cc
  libtransmission/session.cc
  libtransmission/session.h
  libtransmission/torrent.h
Labels: scope:core, type:fix

#5787 fixup! docs: formatting error in `Editing-Configuration-Files.md`
  docs/Editing-Configuration-Files.md
Labels: scope:docs, type:fix, notes:none

#5777 fix: add missing tooltip for 'remove torrent' button
  gtk/ui/gtk3/MainWindow.ui
  gtk/ui/gtk4/MainWindow.ui
Labels: scope:gtk, type:fix, type:ui, semver:minor

#5788 perf: reuse the vector in receonnectPulse()
  libtransmission/peer-mgr.cc
Labels: scope:core, type:refactor

#5789 build: bump web client dev-dependencies
  web/assets/css/transmission-app.scss
  web/package-lock.json
  web/package.json
  web/public_html/index.html
  web/src/action-manager.js
  web/src/file-row.js
  web/src/inspector.js
  web/src/main.js
  web/src/notifications.js
  web/src/open-dialog.js
  web/src/overflow-menu.js
  web/src/prefs-dialog.js
  web/src/remote.js
  web/src/statistics-dialog.js
  web/src/torrent-row.js
  web/src/transmission.js
  web/src/utils.js
  web/stylelint.config.js
Labels: dependencies, type:build, notes:none, semver:minor

#5792 perf: improve sorting performance in `tr_peerMgrGetPeers()`
  libtransmission/peer-mgr.cc
Labels: scope:core, type:perf

#5791 refactor: `tr_torrent.incompleteMetadata` from raw pointer to `std::optional`
  libtransmission/torrent-magnet.cc
  libtransmission/torrent-magnet.h
  libtransmission/torrent.h
Labels: scope:core, type:refactor, notes:none

#5798 refactor: make a few more methods `constexpr`
  libtransmission/benc.h
  libtransmission/blocklist.h
  libtransmission/peer-io.h
Labels: scope:core, type:refactor, notes:none

#5799 refactor: tr_compare_3way()
  gtk/Torrent.cc
  gtk/TorrentSorter.cc
  gtk/Utils.h
  libtransmission/announcer.cc
  libtransmission/peer-mgr.h
  qt/FileTreeItem.cc
  qt/FileTreeItem.h
  qt/Torrent.cc
  qt/TorrentFilter.cc
Labels: scope:gtk, scope:qt, scope:core, type:refactor, notes:none

#5793 refactor: avoid code duplication
  libtransmission/global-ip-cache.cc
  libtransmission/net.cc
  libtransmission/net.h
  libtransmission/peer-mgr.cc
  libtransmission/peer-mgr.h
  libtransmission/peer-msgs.cc
  libtransmission/torrent-magnet.cc
  libtransmission/torrent-magnet.h
  tests/libtransmission/net-test.cc
Labels: scope:docs, needs update, type:refactor, notes:none

#5803 refactor: prefer direct-brace-initialization
  qt/Application.cc
  qt/Application.h
  qt/ColumnResizer.cc
  qt/DetailsDialog.cc
  qt/DetailsDialog.h
  qt/FileTreeDelegate.cc
  qt/FileTreeDelegate.h
  qt/FileTreeItem.h
  qt/FileTreeModel.cc
  qt/FileTreeView.cc
  qt/FilterBar.cc
  qt/FilterBarComboBox.cc
  qt/FreeSpaceLabel.cc
  qt/IconCache.cc
  qt/IconToolButton.cc
  qt/LicenseDialog.cc
  qt/MainWindow.cc
  qt/MakeDialog.cc
  qt/OptionsDialog.cc
  qt/PathButton.cc
  qt/Prefs.cc
  qt/PrefsDialog.cc
  qt/RelocateDialog.cc
  qt/RpcClient.cc
  qt/Session.cc
  qt/SessionDialog.cc
  qt/SqueezeLabel.cc
  qt/StatsDialog.cc
  qt/Torrent.cc
  qt/TorrentDelegate.cc
  qt/TorrentDelegateMin.cc
  qt/TorrentModel.cc
  qt/TorrentModel.h
  qt/TorrentView.cc
  qt/TrackerDelegate.cc
  qt/TrackerModel.cc
  qt/TrackerModel.h
  qt/Utils.cc
  qt/Utils.h
  qt/WatchDir.cc
Labels: scope:core, type:refactor

#5821 fix: clamp down harder for upload as well
  libtransmission/bandwidth.cc
Labels: scope:core, type:fix, notes:none, semver:patch

#5830 fixup! perf: use small::max_size_vector in tr_torrentGetMetadataPiece
  .github/workflows/actions.yml
  libtransmission/variant.cc
Labels: scope:core, type:fix

#5825 fix: disregard locale when building LDP announce message
  libtransmission/tr-lpd.cc
Labels: scope:core, type:fix, semver:patch

#5814 Add readme with light setup instructions; minor UI tweaks
  web/README
  web/assets/css/transmission-app.scss
  web/public_html/index.html
Labels: scope:web, type:fix, type:ui, semver:patch

#5832 refactor: use std::variant in tr_variant, pt 1: make tr_variant_string private
  libtransmission/variant.cc
  libtransmission/variant.h
Labels: scope:core, type:refactor

#5819 add documentation for `watch-dir-force-generic`
  docs/Editing-Configuration-Files.md
Labels: scope:docs, type:docs, notes:none, semver:patch

#5833 fix: CI: Do not use nproc on macOS hosts.
  .github/workflows/actions.yml
Labels: notes:none, type:ci

#5837 fixup! refactor: `tr_torrent.incompleteMetadata` from raw pointer to `std::optional`
  libtransmission/torrent-magnet.cc
Labels: scope:core, type:fix, notes:none

#5835 fix: fix ci web cmake option
  .github/workflows/actions.yml
Labels: type:build, notes:none, type:ci

#5632 fix -fobjc-arc with GCC
  libtransmission/CMakeLists.txt
  libtransmission/utils.cc
Labels: type:build, bug:regression

#5845 Use clang-format for qualifier alignment
  .clang-format
  code_style.sh
  libtransmission/tr-dht.h
  libtransmission/tr-strbuf.h
  macosx/Torrent.mm
  tests/libtransmission/dht-test.cc
Labels: scope:infra, notes:none, semver:minor, type:ci

#5844 Xcode cleanup of leftover reference
  Transmission.xcodeproj/project.pbxproj
Labels: scope:mac, type:build, notes:none
