Repository transmission/transmission, pull requests merged in 2023-03, with the labels that each got.

#5100 fix: max 4 significant digits for speed
  macosx/NSStringAdditions.mm
Labels: scope:mac, notes:none, semver:patch

#5106 fix: always add `announce` key even when including announce-list
  libtransmission/makemeta.cc
  tests/libtransmission/makemeta-test.cc
Labels: scope:core, type:fix, bep-compliance, semver:patch

#5099 docs: explain default-trackers param format in rpc-spec
  docs/rpc-spec.md
Labels: type:docs, notes:none, semver:patch

#5115 fix: 4981 open folder should open selected folder
  qt/MainWindow.cc
Labels: scope:qt, type:fix, type:ui, semver:patch

#5117 fix: 5053 old torrent files keep appearing
  libtransmission/resume.cc
  libtransmission/resume.h
  libtransmission/torrent-metainfo.cc
  libtransmission/torrent.cc
  tests/libtransmission/rename-test.cc
Labels: scope:core, type:fix, semver:patch

#5122 fix: correctly handle batch-adding trackers to multiple torrents
  qt/DetailsDialog.cc
  qt/RpcClient.cc
Labels: scope:qt, type:fix

#5096 fix: escaped representation of non-BMP characters when generating JSON
  libtransmission/variant-json.cc
  tests/libtransmission/json-test.cc
Labels: scope:core, type:fix, semver:patch

#5079 fix: complete copyWithZone for TorrentCell
  macosx/FilePriorityCell.mm
  macosx/TorrentCell.mm
Labels: scope:mac, semver:patch

#5126 Use bundled deps for GHA build from tarball on Mac
  .github/workflows/actions.yml
Labels: os:mac, type:ci

#5135 doc: How to find and open a CI build on macOS
  docs/Testing-Transmission.md
Labels: type:docs, semver:patch

#5097 fix: assertion failure in readBtPiece()
  libtransmission/peer-msgs.cc
  libtransmission/tr-buffer.h
Labels: scope:core, type:fix, semver:patch

#5152 fix: 7f9ef4730 use-after-free in peerMsgs::canRead
  libtransmission/peer-msgs.cc
Labels: scope:core, type:fix, notes:none, semver:patch

#5151 fix: selected torrent row color in dark mode
  web/assets/css/transmission-app.scss
Labels: scope:web, type:fix, type:ui, semver:patch

#5114 fix: regression (leech percentage) from earlier progress-indicator work
  web/assets/css/transmission-app.scss
Labels: scope:web, type:fix, type:ui, semver:patch

#5095 feat: Badge with arrow
  macosx/BadgeView.mm
Labels: scope:mac, type:fix, semver:patch

#5134 docs: add libssl-dev to Ubuntu dependencies
  docs/Building-Transmission.md
Labels: type:docs, notes:none, semver:patch

#5161 fix: crash in curl_easy_pause()
  libtransmission/web.cc
Labels: scope:core, type:fix, semver:patch

#5164 Only publish 'leechers' if it was actually returned during the announce
  libtransmission/announcer.cc
Labels: scope:core, type:fix, semver:patch

#4980 docs: improve build instructions
  README.md
Labels: needs update

#5167 fix: increase priority of first and last piece of each file
  libtransmission/file-piece-map.cc
  libtransmission/file-piece-map.h
  tests/libtransmission/file-piece-map-test.cc
Labels: type:fix, semver:patch

#5174 fix: display of ipv6 tracker URLs
  libtransmission/web-utils.cc
  tests/libtransmission/web-utils-test.cc
Labels: scope:core, type:fix, semver:patch

#5170 Revert "wanted" RPC field to integer, not bool
  docs/rpc-spec.md
  libtransmission/rpcimpl.cc
Labels: scope:core, bug:regression

#5175 Split current and initially requested minimized state
  gtk/Application.cc
  gtk/Application.h
  gtk/main.cc
Labels: scope:gtk, type:fix, semver:patch

#5168 Hardcoding BadgeView fontSize
  macosx/BadgeView.mm
  macosx/NSStringAdditions.mm
Labels: scope:mac, bug:regression

#5177 Download needs to be the "from-tarball" artefact
  docs/Testing-Transmission.md
Labels: type:docs

#5188 ci: check for clang tidy errors in libtransmission
  .github/workflows/actions.yml
  libtransmission/rpcimpl.cc
  libtransmission/torrent.cc
  libtransmission/torrent.h
Labels: notes:none, type:ci

#5184 fix: change badge font size, position and precision
  macosx/BadgeView.mm
  macosx/NSStringAdditions.h
  macosx/NSStringAdditions.mm
Labels: scope:mac, notes:none, semver:patch

#5176 fix: remove interest strategy code that could make dl speeds oscillate up & down
  libtransmission/peer-mgr.cc
Labels: scope:core, type:fix

#5197 Don't discover tests when cross-compiling w/o an emulator
  tests/libtransmission/CMakeLists.txt
Labels: type:build, scope:test, bug:regression, semver:patch

#5202 fix: check tr_ctorSetFoo() return values before adding torrent via RPC
  libtransmission/rpcimpl.cc
Labels: scope:core, type:fix, semver:patch

#5203 fix: std::clamp() assertion failure in maxAvailableReqs()
  libtransmission/peer-msgs.cc
Labels: scope:core, type:fix

#5214 Correct minor formatting errors in rpc-spec.md
  docs/rpc-spec.md
Labels: type:docs, semver:patch

#3454 Add back support for non-standard path.utf-8
  libtransmission/torrent-metainfo.cc
  tests/utils/CMakeLists.txt
  tests/utils/assets/bitcomet.utf-8.special.show
  tests/utils/assets/bitcomet.utf-8.special.torrent
  tests/utils/run_transmission_show.cmake
Labels: scope:core, type:fix, semver:patch

#5213 fix: precision in stringForSpeedCompact
  macosx/NSStringAdditions.mm
Labels: scope:mac, notes:none, semver:patch

#5217 fix: wrong error message when writing to incomplete dir
  libtransmission/inout.cc
Labels: scope:core, type:fix, semver:patch

#5219 fix: "Unrecognized colorspace number -1"
  macosx/TorrentCell.mm
Labels: scope:mac, type:fix

#5227 chore: remove unused header includes
  libtransmission/peer-msgs.cc
  libtransmission/torrent.cc
  libtransmission/tr-lpd.cc
  tests/libtransmission/move-test.cc
  utils/remote.cc
Labels: scope:remote, scope:core, scope:test, notes:none, type:chore

#5223 fix: remove extra checkboxes from webui peers preferences
  web/src/prefs-dialog.js
Labels: scope:web, type:fix, semver:patch

#5230 docs: add 4.0.2 release notes
  news/news-4.0.2.md
Labels: type:docs, notes:none

#5233 fix: generate peer-id on launch
  docs/Editing-Configuration-Files.md
  libtransmission/announcer.cc
  libtransmission/peer-mgr.cc
  libtransmission/quark.cc
  libtransmission/quark.h
  libtransmission/session-settings.h
  libtransmission/session.h
  libtransmission/torrent.cc
  libtransmission/torrent.h
Labels: scope:core, type:fix, semver:patch

#5238 fix: FTBFS in Ubuntu 20.04 / Qt 5.13
  .github/workflows/actions.yml
  qt/DetailsDialog.cc
Labels: scope:qt, type:fix, semver:patch

#5249 Check for E2BIG or NaN strings and replace with placeholders
  web/src/formatter.js
  web/src/inspector.js
Labels: scope:web, type:fix, type:ui, semver:patch

#5244 fix: crash when magnet dn isn't utf-8
  Transmission.xcodeproj/project.pbxproj
  libtransmission/CMakeLists.txt
  libtransmission/magnet-metainfo.h
  libtransmission/torrent-metainfo.cc
  libtransmission/utils.cc
  libtransmission/utils.h
  libtransmission/utils.mm
  tests/libtransmission/utils-test.cc
Labels: scope:mac, semver:patch

#5266 fix: 4.0.2 wishlist CPU perf regression pt. 1
  .github/workflows/actions.yml
  libtransmission/file-piece-map.cc
  libtransmission/file-piece-map.h
Labels: scope:core, type:fix, type:perf, bug:regression, semver:patch

#5274 fix: wrong tier value in torrent get tracker stat response
  libtransmission/announcer.cc
  qt/RpcClient.cc
Labels: scope:core, type:fix, semver:patch

#5276 fix: GTK client prefs window too large for small displays
  gtk/ui/gtk3/PrefsDialog.ui
  gtk/ui/gtk4/PrefsDialog.ui
Labels: scope:gtk, type:fix, type:ui, semver:patch

#5285 fix: The right operand of '<' is a garbage value
  libtransmission/completion.cc
Labels: scope:core, notes:none, semver:patch

#5288 Use locale-dependent decimal separators for user-visible numbers
  libtransmission/utils.cc
Labels: scope:gtk, scope:qt, scope:core, i18n, type:fix, semver:patch

#5280 fix crash on launch from tapping on a notification
  macosx/Controller.mm
Labels: scope:mac, bug:regression, semver:patch

#5289 fix: disable-deprecated by default for end users
  CMakeLists.txt
  gtk/CMakeLists.txt
Labels: scope:gtk, type:fix, type:build, semver:patch

#5286 docs: update AUTHORS
  AUTHORS
Labels: type:docs, notes:none

#5296 Intermediate fix for HTTP announce behaviour affected by `bind-address-ipv*`
  docs/Editing-Configuration-Files.md
  libtransmission/announcer-http.cc
  libtransmission/net.cc
Labels: scope:core, type:fix, semver:patch

#5312 Fix tr_net_hasIPv6()
  libtransmission/net.cc
Labels: scope:core, type:fix, semver:patch
