Repository transmission/transmission, pull requests merged in 2023-01, with the labels that each got.

#4504 feat: add `yourip` to extension protocol handshake
  libtransmission/net.h
  libtransmission/peer-msgs.cc
  libtransmission/quark.cc
  libtransmission/quark.h
Labels: enhancement, scope:core, type:feat, bep-compliance

#4506 fix(remote): Fix tr_strltime to output days correctly
  utils/remote.cc
Labels: scope:remote, type:fix

#4508 refactor: make announce key param unique per-torrent
  libtransmission/announcer-common.h
  libtransmission/announcer-udp.cc
  libtransmission/announcer.cc
  libtransmission/torrent.h
  libtransmission/tr-macros.h
Labels: scope:core, type:fix, bep-compliance

#4507 Modernize CMake code (ongoing refactoring)
  CMakeLists.txt
  cli/CMakeLists.txt
  cmake/FindAPPINDICATOR.cmake
  cmake/FindB64.cmake
  cmake/FindDEFLATE.cmake
  cmake/FindDHT.cmake
  cmake/FindEVENT2.cmake
  cmake/FindICONV.cmake
  cmake/FindMINIUPNPC.cmake
  cmake/FindMbedTLS.cmake
  cmake/FindNATPMP.cmake
  cmake/FindPSL.cmake
  cmake/FindSYSTEMD.cmake
  cmake/FindUTP.cmake
  cmake/FindWolfSSL.cmake
  cmake/LargeFileSupport.cmake
  cmake/TrMacros.cmake
  cmake/Transmission.tlb.rc.in
  daemon/CMakeLists.txt
  dist/msi/CMakeLists.txt
  dist/msi/UtilityFunctions.cmake
  gtk/CMakeLists.txt
  libtransmission/CMakeLists.txt
  macosx/CMakeLists.txt
  macosx/QuickLookPlugin/CMakeLists.txt
  macosx/VDKQueue/CMakeLists.txt
  po/CMakeLists.txt
  qt/CMakeLists.txt
  tests/CMakeLists.txt
  tests/gtest/CMakeLists.txt
  tests/libtransmission/CMakeLists.txt
  tests/utils/CMakeLists.txt
  tests/utils/run_transmission_show.cmake
  utils/CMakeLists.txt
  web/CMakeLists.txt
Labels: type:refactor, type:build

#4509 refactor: remove obsolete lightweight build option
  CMakeLists.txt
  docs/Editing-Configuration-Files.md
  libtransmission/CMakeLists.txt
  libtransmission/crypto-utils-openssl.cc
  libtransmission/utils.h
Labels: type:build

#4510 refactor: simplify tr_udp_core::sendto()
  libtransmission/tr-udp.cc
Labels: scope:core, type:refactor, notes:none

#4513 fix: use SO_REUSEADDR when binding UDP ports
  libtransmission/tr-udp.cc
Labels: scope:core, type:fix, notes:none

#4514 refactor: add constexpr
  libtransmission/announcer-udp.cc
  libtransmission/web.cc
  libtransmission/webseed.cc
Labels: scope:core, type:refactor, notes:none

#4518 refactor: more constexpr
  libtransmission/announce-list.h
  libtransmission/bitfield.h
  libtransmission/completion.h
  libtransmission/file-piece-map.h
  libtransmission/history.h
  libtransmission/inout.h
  libtransmission/torrent-files.h
  libtransmission/torrent.h
  libtransmission/web.h
Labels: scope:core, type:refactor, notes:none

#4519 perf: avoid vector temporary in announcer-udp
  libtransmission/announcer-udp.cc
  libtransmission/peer-socket.cc
Labels: scope:core, type:perf

#4520 Fix clang-tidy issue in `iconv` 2nd argument helper
  libtransmission/utils.cc
Labels: scope:core, type:refactor, notes:none

#4525 fix: clang-tidy-15 warnings
  CMakeLists.txt
  libtransmission/net.cc
  libtransmission/peer-mgr.cc
  libtransmission/web.cc
Labels: scope:core, type:fix, notes:none

#4526 fix: -Wredundant-decls warning when building with g++
  Transmission.xcodeproj/project.pbxproj
  libtransmission/CMakeLists.txt
  libtransmission/utils-ev.cc
  libtransmission/utils-ev.h
Labels: scope:core, type:refactor, notes:none

#4527 fix: Couldnt send to IPv6 address warnings
  libtransmission/tr-udp.cc
Labels: scope:core, type:fix, notes:none

#4529 refactor: fix readability-redundant-string-cstr clang-tidy-16 warnings
  libtransmission/platform-quota.cc
  libtransmission/rpc-server.cc
Labels: scope:core, type:fix, notes:none

#4531 chore: manually rebuild web client
  web/public_html/transmission-app.js
Labels: scope:web, notes:none, type:chore

#4536 chore: 4.0.0-beta.3
  CMakeLists.txt
  news/news-4.0.0-beta-3.md
Labels: type:chore

#4537 fixup! fix: Couldnt send to IPv6 address warnings (#4527)
  libtransmission/tr-udp.cc
Labels: scope:core, type:fixup, notes:none

#4538 refactor: misc-use-anonymous-namespace pt. 2
  CMakeLists.txt
  libtransmission/announcer-udp.cc
  libtransmission/file-posix.cc
  libtransmission/resume.cc
  libtransmission/torrent.cc
  libtransmission/tr-getopt.cc
  libtransmission/variant-benc.cc
  libtransmission/variant-json.cc
  libtransmission/variant.cc
Labels: scope:core, notes:none, type:chore

#4539 refactor: misc-use-anonymous-namespace pt. 3
  libtransmission/announcer-common.h
  libtransmission/announcer-udp.cc
  libtransmission/announcer.cc
  libtransmission/announcer.h
  libtransmission/completion.cc
  libtransmission/crypto-utils.cc
  libtransmission/log.cc
  libtransmission/log.h
  libtransmission/net.cc
  libtransmission/net.h
  libtransmission/open-files.cc
  libtransmission/peer-io.cc
  libtransmission/peer-mse.cc
  libtransmission/peer-mse.h
  libtransmission/peer-msgs.cc
  libtransmission/resume.cc
  libtransmission/rpc-server.cc
  libtransmission/rpcimpl.cc
  libtransmission/session-alt-speeds.cc
  libtransmission/session-thread.cc
  libtransmission/session.cc
  libtransmission/torrent-files.cc
  libtransmission/torrent.cc
  libtransmission/tr-macros.h
  libtransmission/tr-udp.cc
  libtransmission/utils.cc
  libtransmission/variant-benc.cc
  libtransmission/variant-converters.cc
  libtransmission/variant-json.cc
  libtransmission/variant.cc
  libtransmission/web-utils.cc
Labels: scope:core, notes:none, type:chore

#4550 refactor: misc-use-anonymous-namespace pt. 4
  libtransmission/announcer-http.cc
  libtransmission/announcer.cc
  libtransmission/crypto-utils-openssl.cc
  libtransmission/error.cc
  libtransmission/makelog
  libtransmission/peer-mgr.cc
  libtransmission/platform-quota.cc
  libtransmission/platform.cc
  libtransmission/port-forwarding-upnp.cc
  libtransmission/subprocess-posix.cc
  libtransmission/torrent.cc
  libtransmission/tr-utp.cc
Labels: scope:core, type:refactor, notes:none

#4552 refactor: misc-use-anonymous-namespace pt. 5
  libtransmission/bandwidth.cc
  libtransmission/bandwidth.h
  libtransmission/file-posix.cc
  libtransmission/peer-common.h
  libtransmission/peer-io.cc
  libtransmission/peer-mgr.cc
  libtransmission/peer-mgr.h
  libtransmission/peer-msgs.cc
  libtransmission/port-forwarding-natpmp.cc
  libtransmission/session.cc
  libtransmission/torrent-ctor.cc
  libtransmission/torrent-magnet.cc
  libtransmission/torrent.h
Labels: scope:core, type:refactor, notes:none

#4558 Refactor sorting and filtering compatibility code (GTK client)
  gtk/CMakeLists.txt
  gtk/FilterBar.cc
  gtk/FilterBase.h
  gtk/FilterBase.hh
  gtk/FilterListModel.h
  gtk/FilterListModel.hh
  gtk/Session.cc
  gtk/SortListModel.h
  gtk/SortListModel.hh
  gtk/SorterBase.h
  gtk/SorterBase.hh
  gtk/TorrentFilter.cc
  gtk/TorrentFilter.h
  gtk/TorrentSorter.cc
  gtk/TorrentSorter.h
Labels: scope:gtk, type:refactor, notes:none

#4561 Try to fix a couple of recurring CI flakes.
  tests/libtransmission/timer-test.cc
Labels: type:fix, type:test, notes:none

#4563 test: GH Action should only try pack-msi if making dist or qt
  .github/workflows/actions.yml
Labels: type:fix, type:build, notes:none

#4564 Fix GitHub CI actions warning for set-output
  .github/workflows/actions.yml
Labels: type:build, notes:none

#4565 build: remove explicit iconv dependency in libtransmission
  CMakeLists.txt
  Transmission.xcodeproj/project.pbxproj
  libtransmission/CMakeLists.txt
  libtransmission/torrent-metainfo.cc
  libtransmission/utils.cc
  libtransmission/utils.h
  tests/libtransmission/utils-test.cc
Labels: scope:core, dependencies, type:refactor, type:build

#4567 feat: change 403 error message
  libtransmission/rpc-server.cc
  libtransmission/utils.h
Labels: scope:core, type:fix, type:feat

#4571 fix: tr_torrentStat() acquires a session thread lock
  libtransmission/torrent.cc
Labels: scope:core, type:fix, notes:none

#4500 Fix two Help menus in macOS
  macosx/Controller.mm
Labels: scope:mac, type:feat, needs UI review, type:ui, needs code review

#4575 refactor: use std::function for announcer callback
  libtransmission/announcer.cc
  libtransmission/announcer.h
  libtransmission/torrent.cc
  libtransmission/torrent.h
Labels: scope:core, type:refactor, notes:none

#4601 fix: handle webseed servers that do not serve partial content
  libtransmission/web.cc
Labels: scope:core, type:fix

#4557 Increase font size in TorrentCell
  macosx/TorrentCell.mm
Labels: scope:mac, type:ui

#4587 refactor: pieces view
  macosx/PiecesView.mm
Labels: scope:mac, type:refactor, type:ui, needs code review

#4607 build: revert the minimum libdeflate version to 1.10
  CMakeLists.txt
Labels: type:build, notes:none

#4609 fix: when setting Accept-Encoding to identity, disable curl decoding.
  libtransmission/web.cc
Labels: scope:core, type:fix

#4611 feat: add setting to choose between lazy-verify or full verify
  docs/Editing-Configuration-Files.md
  libtransmission/quark.cc
  libtransmission/quark.h
  libtransmission/session-settings.h
  libtransmission/session.h
  libtransmission/torrent.cc
  libtransmission/transmission.h
  libtransmission/variant-converters.cc
  tests/libtransmission/settings-test.cc
Labels: scope:core, type:feat

#4612 daemon: check whether log file is regular and may be flushed
  daemon/daemon.cc
  daemon/daemon.h
  libtransmission/file-posix.cc
  libtransmission/file-win32.cc
  libtransmission/file.h
Labels: scope:daemon, type:fix

#4616 Add valid dtor, move ctor, and move operator= for tr_peer_socket
  libtransmission/peer-socket.h
Labels: scope:core, type:fix

#4623 Fix clang-tidy issues stemming from header files (GTK client)
  gtk/.clang-tidy
  gtk/DetailsDialog.cc
  gtk/FilterBase.h
  gtk/FilterListModel.hh
  gtk/Flags.h
  gtk/GtkCompat.h
  gtk/ListModelAdapter.h
  gtk/OptionsDialog.cc
  gtk/OptionsDialog.h
  gtk/Prefs.h
  gtk/SortListModel.hh
  gtk/SorterBase.h
  gtk/Utils.cc
  gtk/Utils.h
Labels: scope:gtk, type:refactor, notes:none

#4625 Destroy message dialog on error (#3805 regression)
  gtk/RelocateDialog.cc
Labels: scope:gtk, type:fix, bug:regression

#4627 fix: largefile support cmake tests
  cmake/LargeFileSupport.cmake
Labels: scope:core, type:fix, type:build

#4624 fix(remote): Don't draw "Yes" or "No" as an integer
  utils/remote.cc
Labels: scope:remote, type:fix, bug:regression

#4628 fix: clang-tidy warnings in libtransmission/transmission.h
  libtransmission/announcer.cc
  libtransmission/file-posix.cc
  libtransmission/session.cc
  libtransmission/torrent.cc
  libtransmission/transmission.h
Labels: scope:core, type:refactor, notes:none

#4610 fix: when comparing priority for rpc call, cast to string first
  web/assets/css/transmission-app.scss
  web/src/file-row.js
  web/src/inspector.js
  web/src/utils.js
Labels: scope:web, type:fix

#4630 refactor: remove unused declarations from tr-macros.h
  libtransmission/crypto-utils.cc
  libtransmission/tr-macros.h
  tests/libtransmission/session-test.cc
Labels: scope:core, type:refactor, notes:none

#4633 fix(remote): Crash caused by typo when displaying tracker info
  utils/remote.cc
Labels: scope:remote, type:fix, bug:regression

#4635 fix: announcer not updated after torrent announce list edited
  libtransmission/rpcimpl.cc
  libtransmission/session.h
  libtransmission/torrent.cc
  libtransmission/torrent.h
Labels: scope:core, type:fix, bug:regression

#4634 style: use the new paragraph comment style everywhere
  libtransmission/announcer-http.cc
  libtransmission/announcer.h
  libtransmission/bitfield.cc
  libtransmission/cache.cc
  libtransmission/crypto-utils-ccrypto.cc
  libtransmission/crypto-utils-fallback.cc
  libtransmission/crypto-utils-mbedtls.cc
  libtransmission/crypto-utils-wolfssl.cc
  libtransmission/crypto-utils.cc
  libtransmission/crypto-utils.h
  libtransmission/file-piece-map.cc
  libtransmission/handshake.cc
  libtransmission/inout.cc
  libtransmission/log.cc
  libtransmission/magnet-metainfo.cc
  libtransmission/net.cc
  libtransmission/net.h
  libtransmission/peer-common.h
  libtransmission/peer-mgr.cc
  libtransmission/peer-msgs.cc
  libtransmission/rpcimpl.h
  libtransmission/session.cc
  libtransmission/torrent.h
  libtransmission/tr-macros.h
  libtransmission/transmission.h
  libtransmission/utils.cc
  libtransmission/utils.h
  libtransmission/variant.h
  libtransmission/web.cc
  libtransmission/webseed.cc
Labels: scope:core, notes:none, type:chore

#4639 underscores in documentation comments should be code escaped
  libtransmission/announce-list.cc
  libtransmission/bandwidth.h
  libtransmission/history.h
  libtransmission/net.h
  libtransmission/peer-common.h
  libtransmission/peer-mgr.cc
  libtransmission/peer-msgs.h
  libtransmission/torrent-metainfo.h
  libtransmission/torrent.h
  libtransmission/tr-getopt.h
  libtransmission/tr-strbuf.h
  libtransmission/transmission.h
  libtransmission/utils.h
  libtransmission/variant.h
  libtransmission/web.h
Labels: scope:core, notes:none

#4640 chore: pin brew libpsl to 0.21.1
  .github/workflows/actions.yml
Labels: scope:infra, notes:none

#4644 build: downgrade web deps
  code_style.sh
  web/README.md
  web/package-lock.json
  web/package.json
  web/src/prefs.js
  web/src/utils.js
  web/stylelint.config.js
  web/webpack.config.js
Labels: scope:web, type:build, notes:none

#4641 fix: out-of-tree build
  .github/workflows/actions.yml
  CMakeLists.txt
  web/CMakeLists.txt
  web/src/transmission.js
Labels: scope:web, scope:infra, notes:none

#4651 fix: msvc warnings
  libtransmission/net.cc
  qt/Application.cc
  qt/FileTreeDelegate.cc
  tests/libtransmission/announcer-udp-test.cc
  utils/remote.cc
Labels: scope:qt, scope:core, type:fix, scope:test, notes:none

#4652 build: minor ci cleanup
  .github/workflows/actions.yml
  code_style.sh
  web/CMakeLists.txt
  web/package-lock.json
  web/package.json
Labels: scope:web, type:build, notes:none

#4656 Remove 'Message Log' item from Qt sys tray
  qt/MainWindow.cc
Labels: scope:qt, type:fix, type:ui, notes:none

#4662 refactor: add tr_error_set_from_errno()
  libtransmission/error.cc
  libtransmission/error.h
  libtransmission/file-posix.cc
  libtransmission/makemeta.cc
  libtransmission/makemeta.h
  libtransmission/peer-io.cc
  libtransmission/peer-socket.cc
  libtransmission/tr-buffer.h
Labels: scope:core, type:refactor, notes:none

#4658 build: add webapp github actions
  .github/workflows/webapp.yml
Labels: scope:web, scope:infra, type:build, notes:none

#4659 fix: ensure prefs window is centered the first time shown
  macosx/PrefsController.mm
Labels: scope:mac, type:fix, needs UI review, type:ui

#4663 chore: revert 5b14df51c, restore up-to-date web app devDependencies
  web/README.md
  web/package-lock.json
  web/package.json
  web/src/prefs.js
  web/stylelint.config.js
Labels: scope:web, type:build, notes:none

#4669 fix: detect NPM version for ENABLE_WEB in cmake
  .github/workflows/actions.yml
  CMakeLists.txt
Labels: type:build, notes:none

#4622 add remote HTTPS support to Qt GUI
  libtransmission/quark.cc
  libtransmission/quark.h
  qt/Prefs.cc
  qt/Prefs.h
  qt/Session.cc
Labels: scope:qt, notes:none

#4672 fix: bugprone-unchecked-optional-access warnings in tests
  tests/libtransmission/announcer-test.cc
  tests/libtransmission/announcer-udp-test.cc
  tests/libtransmission/crypto-test.cc
  tests/libtransmission/dht-test.cc
  tests/libtransmission/file-test.cc
  tests/libtransmission/handshake-test.cc
  tests/libtransmission/net-test.cc
  tests/libtransmission/open-files-test.cc
  tests/libtransmission/quark-test.cc
  tests/libtransmission/torrent-files-test.cc
  tests/libtransmission/variant-test.cc
Labels: type:fix, scope:test, notes:none

#4673 fix: remove CURL_VERSION_BITS macro
  libtransmission/announcer-http.cc
Labels: scope:core, type:fix, bug:regression

#4675 fix: omit curlopt options if curl is old
  libtransmission/web.cc
Labels: scope:core, type:fix, bug:regression

#4676 quick fix: changed order of some session prefs
  qt/Prefs.cc
  qt/Prefs.h
Labels: scope:qt, type:fixup, notes:none

#4677 fix: make torrent speed limit order consistent in prefs, details dialogs
  qt/DetailsDialog.ui
Labels: scope:qt, type:fix, type:ui

#4678 chore: don't warn on ECONNREFUSED to peer sockets.
  libtransmission/net.cc
Labels: scope:core, notes:none, type:chore

#4680 refactor: tidy libtransmission symbol visibility
  libtransmission/bandwidth.h
  libtransmission/bitfield.cc
  libtransmission/bitfield.h
  libtransmission/completion.cc
  libtransmission/completion.h
  libtransmission/net.cc
  libtransmission/peer-mgr.cc
  libtransmission/peer-mse.cc
  libtransmission/torrent-ctor.cc
  libtransmission/torrent-magnet.cc
  libtransmission/torrent-metainfo.cc
  libtransmission/torrent-metainfo.h
  libtransmission/tr-buffer.h
  libtransmission/web-utils.cc
  libtransmission/web.cc
Labels: scope:core, type:refactor, type:chore

#4682 refactor: buffer snake case
  libtransmission/announcer-udp.cc
  libtransmission/handshake.cc
  libtransmission/peer-common.h
  libtransmission/peer-io.cc
  libtransmission/peer-io.h
  libtransmission/peer-msgs.cc
  libtransmission/peer-socket.cc
  libtransmission/tr-buffer.h
  libtransmission/variant-benc.cc
  libtransmission/variant-common.h
  libtransmission/variant-json.cc
  tests/libtransmission/announcer-udp-test.cc
  tests/libtransmission/buffer-test.cc
Labels: scope:core, type:refactor

#4685 fix: cppcoreguidelines-pro-type-cstyle-cast
  libtransmission/.clang-tidy
  libtransmission/announcer.cc
  libtransmission/crypto-utils-openssl.cc
  libtransmission/file-posix.cc
  libtransmission/net.cc
  libtransmission/platform-quota.cc
  libtransmission/rpc-server.cc
  libtransmission/tr-dht.cc
  libtransmission/tr-lpd.cc
  libtransmission/tr-utp.cc
  libtransmission/transmission.h
  libtransmission/variant.cc
  libtransmission/watchdir.cc
  libtransmission/watchdir.h
  libtransmission/web.cc
Labels: scope:core, type:refactor, notes:none

#4686 fix: clang-tidy header warnings
  libtransmission/interned-string.h
  libtransmission/peer-mgr-wishlist.h
  libtransmission/peer-mgr.h
  libtransmission/peer-msgs.cc
  libtransmission/peer-msgs.h
  libtransmission/port-forwarding-upnp.h
  libtransmission/quark.h
  libtransmission/rpc-server.h
  libtransmission/session.h
  libtransmission/torrent-files.cc
  libtransmission/torrent-files.h
  libtransmission/torrent-metainfo.h
  libtransmission/torrent.h
  libtransmission/torrents.h
  libtransmission/tr-arc4.h
  libtransmission/utils.cc
  libtransmission/utils.h
  libtransmission/variant.cc
  libtransmission/variant.h
  libtransmission/web-utils.h
  libtransmission/web.h
Labels: scope:core, type:refactor, notes:none

#4687 fix: coverity warnings
  libtransmission/net.cc
  tests/libtransmission/file-test.cc
Labels: scope:core, type:fix, notes:none

#4688 Simplify progress bars coloring (GTK client)
  gtk/TorrentCellRenderer.cc
Labels: scope:gtk, type:fix, bug:regression

#4665 fix: call setHasPiece(piece, false) on checkPiece fail
  libtransmission/torrent.cc
Labels: scope:core, type:fix

#4689 #warning in header file should start with capital letter
  macosx/VDKQueue/VDKQueue.h
Labels: scope:mac, notes:none

#4694 Fix torrents count label update
  gtk/FilterBar.cc
  gtk/Flags.h
Labels: scope:gtk, type:fix
