Repository transmission/transmission, pull requests merged in 2023-06, with the labels that each got.

#5587 Avoid locale use in `tr_truncd()`
  libtransmission/utils.cc
Labels: scope:core, type:fix, semver:patch

#5600 fix: some labels not displayed in transmission-remote
  utils/remote.cc
Labels: scope:remote, type:fix, semver:patch

#5606 ci: add "brew upgrade" step
  .github/workflows/actions.yml
  libtransmission/platform.cc
Labels: notes:none, type:ci

#5510 Enable global IP query and fixes/refactorings
  libtransmission/global-ip-cache.cc
  libtransmission/global-ip-cache.h
  libtransmission/session.cc
  libtransmission/session.h
  tests/libtransmission/global-ip-cache-test.cc
Labels: scope:core

#5572 fix: transmission-remote only list every other label (fixes #5571)
  utils/remote.cc
Labels: scope:remote, type:fix, type:ui

#5221 refactor: replace NSMutableDictionary with constant attributes
  macosx/FileNameCell.h
  macosx/FileNameCell.mm
  macosx/TorrentCell.mm
Labels: scope:mac, type:refactor

#5633 fix 'setNeedsDisplay' is deprecated: first deprecated in macOS 10.14
  macosx/PiecesView.mm
  macosx/TorrentTableView.mm
Labels: scope:mac, semver:patch

#5624 Restore QT-Enable png
  docs/resources/QT-Enable-Web-Win-3.png
  macosx/Images/Images.xcassets/ActionHover.imageset/ActionHover@2x.png
Labels: type:docs, bug:regression, notes:none

#5563 fix: return error when renaming into existing file
  libtransmission/torrent.cc
  tests/libtransmission/rename-test.cc
Labels: scope:core, type:fix, semver:patch

#5523 fixup: dedup tr_rpc_address with tr_address
  libtransmission/rpc-server.cc
  libtransmission/rpc-server.h
Labels: scope:core, type:refactor, semver:minor

#5552 fix: Qt 6.5 deprecation warning
  qt/MainWindow.cc
Labels: scope:qt, type:fix, semver:patch

#5641 refactor: prefer std::map over QMap in transmission-qt
  qt/DetailsDialog.cc
  qt/DetailsDialog.h
  qt/FileTreeModel.cc
  qt/OptionsDialog.h
  qt/PrefsDialog.cc
  qt/PrefsDialog.h
Labels: scope:qt, type:refactor

#5643 Add support for sending the `ipv4` parameter during ltep handshake
  libtransmission/net.cc
  libtransmission/peer-msgs.cc
  libtransmission/session.cc
  libtransmission/session.h
  libtransmission/tr-udp.cc
Labels: scope:core, type:feat, bep-compliance, semver:minor

#5584 fix: add 'years' and 'Infinity' to ETA in transmission-remote
  utils/remote.cc
Labels: scope:remote, type:ui, semver:minor

#5644 fixup: refactor handshake objects to use socket address as key as well
  libtransmission/peer-mgr.cc
Labels: scope:core, type:refactor, notes:none

#5652 encode `&key=` as fixed-width 8-digit hex
  libtransmission/announcer-http.cc
Labels: scope:core, type:fix, semver:patch

#5650 perf: use small in libtransmission
  libtransmission/announcer-udp.cc
  libtransmission/handshake.cc
  libtransmission/peer-io.h
  libtransmission/peer-msgs.cc
  libtransmission/tr-buffer.h
  libtransmission/variant-benc.cc
  libtransmission/variant-json.cc
  libtransmission/web.h
  tests/libtransmission/announcer-udp-test.cc
  tests/libtransmission/buffer-test.cc
Labels: scope:core, type:perf

#5568 fix: apply i18n to percentage values
  macosx/NSStringAdditions.mm
Labels: scope:mac, type:fix, semver:patch

#5653 perf: use libsmall in libtransmission, pt 3
  libtransmission/peer-io.cc
  libtransmission/peer-io.h
  libtransmission/peer-mgr-active-requests.cc
  libtransmission/peer-mgr-wishlist.h
  libtransmission/peer-socket.cc
  libtransmission/peer-socket.h
  libtransmission/tr-buffer.h
  tests/libtransmission/announcer-udp-test.cc
  tests/libtransmission/buffer-test.cc
Labels: scope:core, type:perf, semver:minor

#5645 Use a map container to store peers in `tr_swarm`
  libtransmission/handshake.cc
  libtransmission/handshake.h
  libtransmission/peer-mgr.cc
  libtransmission/peer-mgr.h
  libtransmission/peer-msgs.cc
  tests/libtransmission/handshake-test.cc
Labels: scope:core, type:perf, semver:minor

#5656 refactor: replace some C idioms with C++ ones
  daemon/daemon-posix.cc
  daemon/daemon.cc
  gtk/Application.cc
  libtransmission/transmission.h
  libtransmission/utils.cc
  tests/libtransmission/json-test.cc
Labels: scope:daemon, scope:gtk, scope:core, type:refactor, scope:test, notes:none, semver:minor

#5654 chore: revert small buffer
  libtransmission/announcer-udp.cc
  libtransmission/handshake.cc
  libtransmission/peer-io.cc
  libtransmission/peer-io.h
  libtransmission/peer-mgr-active-requests.cc
  libtransmission/peer-mgr-wishlist.h
  libtransmission/peer-msgs.cc
  libtransmission/peer-socket.cc
  libtransmission/peer-socket.h
  libtransmission/tr-buffer.h
  libtransmission/variant-benc.cc
  libtransmission/variant-json.cc
  libtransmission/web.h
  tests/libtransmission/announcer-udp-test.cc
  tests/libtransmission/buffer-test.cc
Labels: scope:core, type:fix, notes:none

#5660 chore: update GTK client screenshot
  gtk/screenshots/a.png
Labels: scope:gtk, type:chore

#5655 refactor: global-ip-cache.cc nits
  libtransmission/global-ip-cache.cc
Labels: scope:core, type:refactor, notes:none

#5666 refactor: small again
  libtransmission/announcer-udp.cc
  libtransmission/peer-io.cc
  libtransmission/peer-io.h
  libtransmission/peer-mgr-active-requests.cc
  libtransmission/peer-mgr-wishlist.h
  libtransmission/peer-socket.cc
  libtransmission/peer-socket.h
  libtransmission/web.h
Labels: scope:core, type:refactor, type:perf

#5651 perf: improve IPv4 `tr_address` comparison
  libtransmission/net.cc
Labels: scope:core, type:perf

#5671 perf: in cache, flush biggest contiguous blocks
  libtransmission/cache.cc
  libtransmission/cache.h
Labels: scope:core, type:fix, type:perf

#5675 fix: do not write log if file handler is bad
  libtransmission/log.cc
Labels: scope:core, type:fix, semver:patch

#5676 refactor: remove libtransmission::Buffer
  libtransmission/announcer-udp.cc
  libtransmission/tr-buffer.h
  tests/libtransmission/announcer-udp-test.cc
  tests/libtransmission/buffer-test.cc
Labels: scope:core, type:refactor, semver:minor

#5668 Set `"cache-size-mb": 0` to bypass write cache
  docs/Editing-Configuration-Files.md
  libtransmission/cache.cc
  libtransmission/cache.h
Labels: scope:core, type:feat, semver:minor

#5678 refactor: share `CompareCacheBlockByKey` by constexpr static member
  libtransmission/cache.cc
  libtransmission/cache.h
Labels: scope:core, type:perf, notes:none, semver:patch

#5681 refactor: remove useless TR_DEBUG_FD env var
  docs/Environment-Variables.md
  libtransmission/log.cc
Labels: scope:core, type:refactor, notes:none

#5682 chore: remove unused function tr_env_get_int()
  libtransmission/utils.cc
  libtransmission/utils.h
  tests/libtransmission/utils-test.cc
Labels: scope:core, notes:none, type:chore

#5683 chore: remove tr_wait(); use std::this_thread::sleep_for() instead
  cli/cli.cc
  libtransmission/utils.h
  libtransmission/verify.cc
  libtransmission/web.cc
  tests/libtransmission/test-fixtures.h
Labels: type:refactor, notes:none, semver:minor

#5689 refactor: rename tr_dirSpace() to tr_sys_path_capacity()
  Transmission.xcodeproj/project.pbxproj
  gtk/FreeSpaceLabel.cc
  libtransmission/CMakeLists.txt
  libtransmission/file-capacity.cc
  libtransmission/file.h
  libtransmission/platform-quota.h
  libtransmission/rpcimpl.cc
  libtransmission/utils.cc
  libtransmission/utils.h
  tests/libtransmission/announcer-udp-test.cc
Labels: scope:core, type:refactor, semver:minor

#5691 refactor: remove unused function tr_peer.bandwidth()
  libtransmission/peer-common.h
  libtransmission/peer-msgs.cc
  libtransmission/webseed.cc
Labels: scope:core, type:refactor, notes:none

#5687 perf: convert comparator functors to static constexpr
  libtransmission/peer-mgr.cc
  libtransmission/rpcimpl.cc
  libtransmission/torrent.cc
  libtransmission/torrents.cc
Labels: scope:core, type:perf, notes:none

#5694 iwyu: remove, add std headers where used
  gtk/Session.cc
  gtk/Torrent.cc
  gtk/Torrent.h
  gtk/Utils.cc
  libtransmission/announce-list.h
  libtransmission/announcer-common.h
  libtransmission/announcer-http.cc
  libtransmission/announcer-udp.cc
  libtransmission/announcer.h
  libtransmission/bitfield.cc
  libtransmission/completion.cc
  libtransmission/crypto-utils.cc
  libtransmission/favicon-cache.h
  libtransmission/file-piece-map.cc
  libtransmission/file-posix.cc
  libtransmission/file-win32.cc
  libtransmission/file.cc
  libtransmission/file.h
  libtransmission/global-ip-cache.cc
  libtransmission/global-ip-cache.h
  libtransmission/handshake.cc
  libtransmission/inout.h
  libtransmission/log.h
  libtransmission/lru-cache.h
  libtransmission/magnet-metainfo.h
  libtransmission/net.cc
  libtransmission/open-files.cc
  libtransmission/peer-common.h
  libtransmission/peer-io.cc
  libtransmission/peer-mgr-active-requests.cc
  libtransmission/peer-mgr-wishlist.cc
  libtransmission/peer-mgr.cc
  libtransmission/peer-mse.h
  libtransmission/peer-msgs.h
  libtransmission/peer-socket.h
  libtransmission/port-forwarding-natpmp.cc
  libtransmission/port-forwarding-upnp.cc
  libtransmission/resume.cc
  libtransmission/rpc-server.h
  libtransmission/session-alt-speeds.h
  libtransmission/session-id.cc
  libtransmission/session.cc
  libtransmission/session.h
  libtransmission/torrent-metainfo.cc
  libtransmission/torrents.h
  libtransmission/tr-buffer.h
  libtransmission/tr-dht.cc
  libtransmission/tr-dht.h
  libtransmission/tr-getopt.cc
  libtransmission/transmission.h
  libtransmission/utils.cc
  libtransmission/variant.h
  libtransmission/verify.cc
  libtransmission/watchdir.cc
  libtransmission/web.h
  qt/Formatter.cc
  utils/remote.cc
Labels: scope:remote, scope:gtk, scope:qt, scope:core, notes:none, type:chore

#5696 refactor: utils naming
  daemon/daemon.cc
  gtk/DetailsDialog.cc
  gtk/FileList.cc
  gtk/Utils.cc
  libtransmission/announce-list.cc
  libtransmission/announcer-http.cc
  libtransmission/announcer.cc
  libtransmission/blocklist.cc
  libtransmission/clients.cc
  libtransmission/crypto-utils.cc
  libtransmission/favicon-cache.h
  libtransmission/file-win32.cc
  libtransmission/global-ip-cache.cc
  libtransmission/log.cc
  libtransmission/magnet-metainfo.cc
  libtransmission/makemeta.cc
  libtransmission/makemeta.h
  libtransmission/net.cc
  libtransmission/platform.cc
  libtransmission/resume.cc
  libtransmission/rpc-server.cc
  libtransmission/rpcimpl.cc
  libtransmission/session.cc
  libtransmission/subprocess-win32.cc
  libtransmission/torrent-ctor.cc
  libtransmission/torrent-files.cc
  libtransmission/torrent-magnet.cc
  libtransmission/torrent-metainfo.cc
  libtransmission/torrent.cc
  libtransmission/tr-getopt.cc
  libtransmission/tr-lpd.cc
  libtransmission/transmission.h
  libtransmission/utils.cc
  libtransmission/utils.h
  libtransmission/variant-benc.cc
  libtransmission/variant-converters.cc
  libtransmission/variant-json.cc
  libtransmission/variant.cc
  libtransmission/web-utils.cc
  libtransmission/webseed.cc
  macosx/CreatorWindowController.mm
  tests/libtransmission/announce-list-test.cc
  tests/libtransmission/copy-test.cc
  tests/libtransmission/makemeta-test.cc
  tests/libtransmission/platform-test.cc
  tests/libtransmission/rename-test.cc
  tests/libtransmission/subprocess-test.cc
  tests/libtransmission/torrent-metainfo-test.cc
  tests/libtransmission/utils-test.cc
  utils/edit.cc
  utils/remote.cc
  utils/show.cc
Labels: scope:core, type:refactor, notes:none

#5700 Updated logging levels in configuration documentation
  docs/Editing-Configuration-Files.md
Labels: type:fix, type:docs, semver:patch

#5701 refactor: prefer std::unordred_map over QHash
  qt/FileTreeItem.cc
  qt/FileTreeItem.h
  qt/RpcClient.cc
  qt/RpcClient.h
  qt/Utils.h
Labels: scope:qt, type:refactor, notes:none

#5704 refactor: prefer std::queue over QQueue
  qt/FileTreeView.cc
  qt/MainWindow.cc
  qt/RpcQueue.cc
  qt/RpcQueue.h
Labels: scope:qt, type:refactor, notes:none
