Repository transmission/transmission, pull requests merged in 2023-04, with the labels that each got.

#5345 Set log level before constructing tr_session for daemon
  libtransmission/session.cc
Labels: type:fix, semver:patch

#5360 Reduce GTK Prefs.ui size to 90
  gtk/ui/gtk3/PrefsDialog.ui
  gtk/ui/gtk4/PrefsDialog.ui
Labels: scope:gtk, type:ui

#5365 fix: silence torrent-metainfo warnings for cross_seed_entry, uid
  libtransmission/torrent-metainfo.cc
Labels: scope:core, type:fix, semver:patch

#5264 Fix Potential leak of an object of type 'NSString * _Nullable'
  Transmission.xcodeproj/project.pbxproj
  libtransmission/CMakeLists.txt
  libtransmission/utils.mm
  macosx/CMakeLists.txt
  macosx/QuickLookPlugin/CMakeLists.txt
Labels: scope:mac, type:build, bug:regression, semver:patch

#5371 ci: fix Sanity/Windows GitHub Actions
  .github/workflows/actions.yml
Labels: type:ci

#5376 Uninstall preinstalled OpenSSL on Windows GHA builder
  .github/workflows/actions.yml
Labels: type:build

#5378 fix: only torrent metainfo display-name as a fallback
  libtransmission/torrent-metainfo.cc
Labels: bug, scope:core, type:fix, semver:patch

#5318 fix: use a Verify keyboard shortcut that does not conflict with Paste
  web/src/action-manager.js
Labels: scope:web, type:fix, type:ui, semver:patch

#5381 fix: check for input focus before looking at keyboard shortcuts
  web/src/transmission.js
Labels: bug, scope:web, type:fix, type:ui, semver:patch

#5382 fix: show announce url origin in inspector tier list
  web/src/inspector.js
Labels: scope:web, type:fix, type:ui, semver:patch

#5389 docs: add 4.0.3 release notes
  news/news-4.0.3.md
Labels: type:docs, notes:none, semver:patch

#5392 chore: bump version to 4.1.0-dev
  CMakeLists.txt
Labels: notes:none, semver:minor

#5380 refactor: tr_sys_dir_open() takes a std::string_view
  libtransmission/blocklist.cc
  libtransmission/file-posix.cc
  libtransmission/file-win32.cc
  libtransmission/file.h
  libtransmission/makemeta.cc
  libtransmission/session.cc
  libtransmission/watchdir.cc
Labels: type:refactor, notes:none, semver:minor

#4931 cmake Xcode recommended build settings
  CMakeLists.txt
Labels: type:build, notes:none, semver:minor

#5108 Align tr_formatter_speed_KBps with `stringForSpeed: kb: mb: gb:`
  libtransmission/utils.cc
  libtransmission/utils.h
Labels: scope:core, feature disparity, semver:minor

#4795 feat: sequential download
  cli/cli.cc
  docs/rpc-spec.md
  libtransmission/peer-mgr-wishlist.cc
  libtransmission/peer-mgr-wishlist.h
  libtransmission/peer-mgr.cc
  libtransmission/quark.cc
  libtransmission/quark.h
  libtransmission/resume.cc
  libtransmission/rpcimpl.cc
  libtransmission/torrent.h
  qt/DetailsDialog.cc
  tests/libtransmission/peer-mgr-wishlist-test.cc
  utils/remote.cc
Labels: scope:core, type:feat, semver:minor

#4169 Add sort by ETA for macOS
  macosx/Base.lproj/MainMenu.xib
  macosx/Controller.mm
  macosx/Torrent.h
  macosx/Torrent.mm
Labels: scope:mac, feature disparity, i18n, semver:minor

#4419 feat: added support for displaying "Show Toolbar"
  macosx/Base.lproj/MainMenu.xib
  macosx/Controller.h
  macosx/Controller.mm
Labels: scope:mac, i18n, type:feat, type:ui, semver:minor

#5124 Add more complex formatting to a spinbox
  qt/DetailsDialog.cc
  qt/PrefsDialog.cc
  qt/Utils.cc
  qt/Utils.h
Labels: scope:qt, i18n, type:ui, semver:minor

#5282 Update MACOSX_DEPLOYMENT_TARGET to RECOMMENDED_MACOSX_DEPLOYMENT_TARGET
  CMakeLists.txt
  Transmission.xcodeproj/project.pbxproj
  macosx/Controller.h
  macosx/Controller.mm
  macosx/NSApplicationAdditions.mm
Labels: scope:mac, type:build

#5279 fix: crash in peer stats
  libtransmission/peer-common.h
  libtransmission/peer-mgr.cc
  libtransmission/peer-msgs.cc
  libtransmission/peer-msgs.h
Labels: scope:core, type:fix, semver:minor

#4876 perf: pass by reference
  libtransmission/announcer.cc
  libtransmission/cache.cc
  libtransmission/cache.h
  libtransmission/inout.cc
  libtransmission/inout.h
  libtransmission/torrent.cc
Labels: type:perf, semver:minor

#5154 feat: Add libtransmission::BufferWriter class
  libtransmission/tr-buffer.h
  tests/libtransmission/buffer-test.cc
Labels: type:perf, notes:none, semver:minor

#5155 feat: add tr_bitfield::intersects()
  libtransmission/bitfield.cc
  libtransmission/bitfield.h
  tests/libtransmission/bitfield-test.cc
Labels: type:perf, notes:none, semver:minor

#5394 perf: remove staging step for outbound peer msgs
  libtransmission/peer-msgs.cc
Labels: scope:core, type:perf

#5396 fix uninitialized session_id_t values
  libtransmission/session-id.h
Labels: scope:core, type:fix, semver:patch

#5082 feat: add drag-and-drop in web interface
  web/assets/css/transmission-app.scss
  web/public_html/index.html
  web/src/open-dialog.js
  web/src/transmission.js
Labels: scope:web, type:feat, semver:minor

#5090 refactor: use idiomatic enum names & types in objc
  macosx/BlocklistDownloader.h
  macosx/BlocklistDownloader.mm
  macosx/Controller.h
  macosx/Controller.mm
  macosx/FileOutlineController.mm
  macosx/InfoWindowController.mm
  macosx/PortChecker.h
  macosx/PortChecker.mm
  macosx/PrefsController.mm
  macosx/StatusBarController.mm
  macosx/Torrent.h
Labels: scope:mac, type:refactor, semver:minor

#5216 quicklook: alternate row background color
  macosx/QuickLookPlugin/GeneratePreviewForURL.mm
  macosx/QuickLookPlugin/style.css
Labels: scope:mac, needs UI review, type:ui, semver:minor

#5398 refactor: add tr_address::is_any()
  libtransmission/net.cc
  libtransmission/net.h
  libtransmission/peer-msgs.cc
  libtransmission/session.cc
  libtransmission/session.h
  libtransmission/tr-udp.cc
Labels: scope:core, type:refactor, notes:none, semver:minor

#5404 chore: prefer fmt/core.h over fmt/format.h
  cli/cli.cc
  daemon/daemon-posix.cc
  daemon/daemon-win32.cc
  gtk/DetailsDialog.cc
  gtk/Utils.h
  libtransmission/announcer-udp.cc
  libtransmission/clients.cc
  libtransmission/crypto-utils.cc
  libtransmission/error.cc
  libtransmission/file-posix.cc
  libtransmission/file-win32.cc
  libtransmission/handshake.cc
  libtransmission/interned-string.h
  libtransmission/log.cc
  libtransmission/magnet-metainfo.cc
  libtransmission/makemeta.cc
  libtransmission/peer-io.cc
  libtransmission/peer-mgr.cc
  libtransmission/peer-msgs.cc
  libtransmission/peer-socket.cc
  libtransmission/platform.cc
  libtransmission/port-forwarding-upnp.cc
  libtransmission/resume.cc
  libtransmission/session-id.cc
  libtransmission/session-settings.cc
  libtransmission/session.cc
  libtransmission/subprocess-posix.cc
  libtransmission/subprocess-win32.cc
  libtransmission/torrent-files.cc
  libtransmission/torrent-metainfo.cc
  libtransmission/tr-assert.mm
  libtransmission/tr-dht.cc
  libtransmission/tr-getopt.cc
  libtransmission/tr-lpd.cc
  libtransmission/tr-strbuf.h
  libtransmission/tr-utp.cc
  libtransmission/utils.cc
  libtransmission/variant-benc.cc
  libtransmission/variant-converters.cc
  libtransmission/variant-json.cc
  libtransmission/web-utils.cc
  libtransmission/web-utils.h
  libtransmission/web.cc
  libtransmission/webseed.cc
  qt/RpcClient.cc
  tests/libtransmission/announcer-udp-test.cc
  tests/libtransmission/benc-test.cc
  tests/libtransmission/makemeta-test.cc
  utils/create.cc
  utils/edit.cc
  utils/remote.cc
  utils/show.cc
Labels: notes:none

#5331 Removed modifiers for keyboard shortcuts
  web/src/action-manager.js
Labels: scope:web, type:ui

#5409 fix: minor warnings
  gtk/Session.cc
  libtransmission/peer-msgs.cc
  libtransmission/tr-buffer.h
  libtransmission/tr-dht.cc
  qt/DetailsDialog.cc
  qt/Filters.h
  qt/PrefsDialog.cc
  qt/Torrent.cc
  qt/Torrent.h
Labels: scope:gtk, scope:qt, scope:core, type:fix, notes:none, semver:patch

#5420 perf: in Buffer::Iterator, defer evbuffer API calls
  libtransmission/tr-buffer.h
Labels: scope:core, type:fix, type:perf, semver:minor

#5425 fix: 5422 use-after-free in peerMsgs::canRead
  libtransmission/peer-msgs.cc
Labels: scope:core, type:fix, semver:patch

#5426 fix: no such file or directory warning in transmission-cli
  cli/cli.cc
Labels: scope:cli, scope:core, type:fix, semver:patch

#5435 fix: Buffer::Buffer(Buffer&&) bug
  libtransmission/tr-buffer.h
  tests/libtransmission/buffer-test.cc
Labels: scope:core, type:fix, notes:none, semver:patch

#5437 fixup! feat: Add BufferWriter class (#5154)
  libtransmission/peer-io.cc
Labels: scope:core, type:fix, semver:patch

#5428 refactor: snake_case in libtransmission class methods
  libtransmission/announce-list.cc
  libtransmission/announcer.cc
  libtransmission/bandwidth.cc
  libtransmission/bandwidth.h
  libtransmission/bitfield.cc
  libtransmission/bitfield.h
  libtransmission/block-info.cc
  libtransmission/block-info.h
  libtransmission/cache.cc
  libtransmission/completion.cc
  libtransmission/completion.h
  libtransmission/file-piece-map.cc
  libtransmission/file-piece-map.h
  libtransmission/handshake.cc
  libtransmission/inout.cc
  libtransmission/magnet-metainfo.cc
  libtransmission/magnet-metainfo.h
  libtransmission/makemeta.cc
  libtransmission/makemeta.h
  libtransmission/peer-common.h
  libtransmission/peer-io.cc
  libtransmission/peer-io.h
  libtransmission/peer-mgr.cc
  libtransmission/peer-msgs.cc
  libtransmission/resume.cc
  libtransmission/rpcimpl.cc
  libtransmission/session.cc
  libtransmission/session.h
  libtransmission/torrent-ctor.cc
  libtransmission/torrent-magnet.cc
  libtransmission/torrent-metainfo.cc
  libtransmission/torrent-metainfo.h
  libtransmission/torrent.cc
  libtransmission/torrent.h
  libtransmission/torrents.cc
  libtransmission/torrents.h
  libtransmission/verify.cc
  libtransmission/webseed.cc
  macosx/Controller.mm
  macosx/DragOverlayWindow.mm
  macosx/QuickLookPlugin/GeneratePreviewForURL.mm
  qt/AddData.cc
  qt/OptionsDialog.cc
  qt/WatchDir.cc
  tests/libtransmission/announce-list-test.cc
  tests/libtransmission/bitfield-test.cc
  tests/libtransmission/block-info-test.cc
  tests/libtransmission/completion-test.cc
  tests/libtransmission/file-piece-map-test.cc
  tests/libtransmission/magnet-metainfo-test.cc
  tests/libtransmission/makemeta-test.cc
  tests/libtransmission/move-test.cc
  tests/libtransmission/peer-mgr-wishlist-test.cc
  tests/libtransmission/rename-test.cc
  tests/libtransmission/test-fixtures.h
  tests/libtransmission/torrent-magnet-test.cc
  tests/libtransmission/torrent-metainfo-test.cc
  tests/libtransmission/torrents-test.cc
  utils/show.cc
Labels: scope:core, type:refactor

#5294 feat: add generic favicon_cache class for reuse between Qt, GTK app
  gtk/CMakeLists.txt
  gtk/DetailsDialog.cc
  gtk/FaviconCache.cc
  gtk/FaviconCache.h
  gtk/FilterBar.cc
  gtk/Session.cc
  gtk/Session.h
  libtransmission/CMakeLists.txt
  libtransmission/favicon-cache.h
  libtransmission/web.h
  qt/Application.cc
  qt/Application.h
  qt/CMakeLists.txt
  qt/FaviconCache.cc
  qt/FaviconCache.h
  qt/FilterBar.cc
  qt/FilterBar.h
  qt/Torrent.cc
  qt/Torrent.h
  qt/TrackerDelegate.cc
  qt/VariantHelpers.cc
Labels: scope:gtk, feature disparity, type:feat, semver:minor

#5460 fix: bug that prevented providing the final metadata piece
  libtransmission/torrent-magnet.cc
Labels: scope:core, type:fix, bep-compliance, semver:patch

#5461 ci: do not install homebrew libnatpmp on macos 11
  .github/workflows/actions.yml
Labels: notes:none, type:ci

#5462 fix: null tier name in inspector list
  web/src/inspector.js
Labels: scope:web, type:fix, type:ui, semver:patch

#5444 fix: use user-preferred locale
  cli/cli.cc
  daemon/daemon.cc
  gtk/main.cc
  libtransmission/utils.cc
  libtransmission/utils.h
  macosx/main.mm
  qt/Application.cc
  tests/libtransmission/json-test.cc
  tests/utils/run_transmission_show.cmake
  utils/create.cc
  utils/edit.cc
  utils/remote.cc
  utils/show.cc
Labels: scope:cli, scope:daemon, scope:remote, scope:create, scope:edit, scope:show, scope:gtk, scope:qt, scope:mac, type:fix

#5456 fix: wrong case in AppKit.h
  macosx/BlocklistScheduler.h
Labels: scope:mac, needs code review

#5470 feat: high-contrast theme for web ui
  web/assets/css/transmission-app.scss
  web/src/action-manager.js
  web/src/overflow-menu.js
  web/src/prefs.js
  web/src/transmission.js
Labels: scope:web, type:feat, type:ui, semver:minor

#5475 Typos in macosx
  macosx/Controller.mm
  macosx/InfoTrackersViewController.mm
  macosx/Torrent.mm
Labels: scope:mac, type:fix, notes:none, semver:patch

#5473 Typos in libtransmission
  libtransmission/bitfield.cc
  libtransmission/net.cc
  libtransmission/session.cc
Labels: scope:core, type:fix, notes:none
