Repository transmission/transmission, pull requests merged in 2023-10, with the labels that each got.

#6053 fix 'setNeedsDisplay' is deprecated: first deprecated in macOS 10.14
  macosx/TorrentCellRevealButton.mm
  macosx/TorrentTableView.mm
  macosx/TrackerCell.mm
Labels: scope:mac, bug:regression, notes:none

#6029 chore: more specific peer error log
  libtransmission/peer-mgr.cc
Labels: scope:core, notes:none, type:chore

#6030 updating debian release
  docs/Building-Transmission.md
Labels: type:docs, semver:patch

#6054 chore: apply clang-format version 17.0.1
  libtransmission/net.cc
  macosx/FilterBarController.h
  macosx/TorrentTableView.h
  qt/DetailsDialog.cc
  qt/PrefsDialog.cc
  qt/RpcClient.cc
  tests/libtransmission/blocklist-test.cc
  tests/libtransmission/test-fixtures.h
Labels: notes:none, type:chore

#5978 feat: check if local files exist after setting location
  libtransmission/torrent.cc
Labels: scope:core, type:feat, semver:minor

#6061 fixup! refactor: remove redundant code when adding announce lists to metainfo (#6050)
  libtransmission/makemeta.cc
Labels: scope:core, type:fix, notes:none

#6062 fix: `assertion failed: port_empty` in `tr_swarm::remove_peer()`
  libtransmission/peer-mgr.cc
Labels: scope:core, type:fix, notes:none

#6066 refactor: remove tr_torrentStatCached()
  gtk/DetailsDialog.cc
  libtransmission/torrent.cc
  libtransmission/torrent.h
  libtransmission/transmission.h
Labels: scope:gtk, scope:core, type:refactor, notes:none

#6057 refactor: more tr_variant API
  libtransmission/rpcimpl.cc
  libtransmission/rpcimpl.h
  tests/libtransmission/rpc-test.cc
  tests/libtransmission/test-fixtures.h
  utils/remote.cc
Labels: scope:core, type:refactor, notes:none

#6008 feat: WebUI torrent tracker list style improvements
  web/assets/css/transmission-app.scss
  web/src/inspector.js
Labels: scope:web, type:ui, notes:none

#6070 refactor: make tr_torrent idle fields private
  libtransmission/resume.cc
  libtransmission/rpcimpl.cc
  libtransmission/torrent.cc
  libtransmission/torrent.h
  libtransmission/transmission.h
Labels: scope:core, type:refactor, notes:none

#6074 fixup! refactor: make tr_torrent idle fields private (#6070)
  libtransmission/torrent.cc
  libtransmission/torrent.h
Labels: scope:core, type:fix, notes:none

#6072 refactor: add a SimpleSmoothedSpeed helper class
  libtransmission/torrent.cc
  libtransmission/torrent.h
Labels: scope:core, type:refactor, notes:none

#6075 fix: reconstruct `utp_core_` when toggling utp
  libtransmission/session.cc
Labels: scope:core, type:fix, notes:none

#6073 perf: reduce unnecessary size overhead in tr_torrent struct
  libtransmission/observable.h
  libtransmission/torrent-magnet.cc
  libtransmission/torrent.h
Labels: scope:core, type:refactor, notes:none

#6083 Update peer-id documentation to account for post-3.00 changes
  docs/Peer-ID-and-User-Agent.md
Labels: scope:docs, type:docs

#6080 chore: minor housekeeping for bandwidth code
  libtransmission/bandwidth.cc
  libtransmission/bandwidth.h
  libtransmission/peer-io.cc
  libtransmission/rpcimpl.cc
  libtransmission/session.cc
  libtransmission/transmission.h
Labels: scope:core, notes:none, type:chore

#6081 feat: WebUI display full peer address in tooltip
  web/src/inspector.js
Labels: scope:web, type:feat, notes:none

#5981 feat: add option to force verify torrent in WebUI
  docs/rpc-spec.md
  libtransmission/rpcimpl.cc
  libtransmission/torrent.cc
  libtransmission/transmission.h
  web/src/action-manager.js
  web/src/context-menu.js
  web/src/force-verify-dialog.js
  web/src/remote.js
  web/src/transmission.js
Labels: scope:web, scope:core, type:feat, semver:minor

#6088 feat: better description for forced verify option
  web/src/force-verify-dialog.js
Labels: scope:web, type:feat, notes:none

#6077 refactor: add tr_torrent::Error helper class
  libtransmission/inout.cc
  libtransmission/peer-msgs.cc
  libtransmission/resume.cc
  libtransmission/torrent.cc
  libtransmission/torrent.h
Labels: scope:core, type:refactor, notes:none

#5857 feat: progress bar precision for web client
  web/src/torrent-row.js
Labels: scope:web, type:fix, notes:none

#6082 fix: only consider piece data in bandwidth limit
  libtransmission/bandwidth.cc
  libtransmission/bandwidth.h
Labels: scope:core, type:fix, semver:patch

#6091 feat: render file tree in legacy html-based QuickLook preview
  macosx/QuickLookPlugin/GeneratePreviewForURL.mm
Labels: scope:mac, type:feat

#6103 refactor: store outgoing handshake in `tr_peer_info` objects
  libtransmission/peer-mgr.cc
  libtransmission/peer-mgr.h
Labels: scope:core, type:refactor, type:perf

#6106 chore: fix warnings in CodeQL workflow
  .github/codeql/codeql-config-js.yml
  .github/workflows/codeql.yml
Labels: type:chore, type:ci

#6005 fix: json string serializer improperly escaping characters
  libtransmission/utils.cc
  libtransmission/utils.h
  libtransmission/variant-json.cc
  tests/libtransmission/json-test.cc
Labels: scope:core, type:fix

#6126 fix: encode `ip` in network byte order for udp announce
  libtransmission/announcer-udp.cc
  libtransmission/net.h
  libtransmission/tr-buffer.h
Labels: scope:core, type:fix, bep-compliance

#6128 fix: wrong target name in `FindSmall.cmake`
  cmake/FindSmall.cmake
Labels: scope:3rdparty, type:build, notes:none

#6111 perf: periodically purge inactive peer info objects from pool
  libtransmission/peer-mgr.cc
  libtransmission/peer-mgr.h
Labels: scope:core, type:perf, semver:minor

#6133 fix: json string serializer improperly escaping characters (#6005)
  libtransmission/utils.cc
  libtransmission/utils.h
  libtransmission/variant-json.cc
  tests/libtransmission/json-test.cc
Labels: scope:core, type:fix

#6134 fix: only consider piece data in bandwidth limit (#6082)
  libtransmission/bandwidth.cc
  libtransmission/bandwidth.h
Labels: scope:core, type:fix, semver:patch

#6132 fix: encode `ip` in network byte order for udp announce (#6126)
  libtransmission/announcer-udp.cc
  libtransmission/tr-buffer.h
Labels: scope:core, type:fix, semver:patch

#6104 UI fix: larger display group name
  macosx/Base.lproj/PrefsWindow.xib
Labels: scope:mac, type:fix, type:ui

#6139 chore: bump vulnerable web build deps
  web/babel.config.js
  web/package-lock.json
  web/package.json
Labels: scope:web, notes:none, type:chore

#6121 feat: directly open macOS notifications preferences for app
  macosx/PrefsController.mm
Labels: scope:mac, type:feat, semver:minor

#6131 fix: crash when selecting file from recently used in gtk file chooser
  gtk/OptionsDialog.cc
Labels: scope:gtk, type:fix

#6142 fix: crash when selecting file from recently used in gtk file chooser
  gtk/OptionsDialog.cc
Labels: scope:gtk, type:fix, semver:patch

#6144 fix: do not use get_files2 in 4.0.x branch
  gtk/OptionsDialog.cc
Labels: scope:gtk, notes:none, semver:patch

#6143 refactor: add tr_torrent::stat()
  libtransmission/torrent.cc
  libtransmission/torrent.h
Labels: scope:core, type:refactor, notes:none

#6145 refactor: make tr_torrent::unique_id_ private
  libtransmission/session.cc
  libtransmission/torrent.h
  tests/libtransmission/torrents-test.cc
Labels: type:refactor, notes:none, semver:minor

#6146 refactor: make tr_torrent::files_wanted_ private
  libtransmission/torrent.cc
  libtransmission/torrent.h
Labels: scope:core, type:refactor, notes:none

#6147 chore: remove unused progress arg from tr_torrentSetLocation()
  gtk/RelocateDialog.cc
  libtransmission/rpcimpl.cc
  libtransmission/torrent-files.cc
  libtransmission/torrent-files.h
  libtransmission/torrent.cc
  libtransmission/torrent.h
  libtransmission/transmission.h
  macosx/Torrent.mm
  tests/libtransmission/move-test.cc
Labels: scope:gtk, scope:mac, scope:core, notes:none, type:chore

#6148 refactor: make tr_torrent::any_date_ private
  libtransmission/rpcimpl.cc
  libtransmission/torrent.cc
  libtransmission/torrent.h
Labels: scope:core, type:refactor, notes:none

#6099 feat: add option to set macOS client as default for torrent files
  macosx/Base.lproj/PrefsWindow.xib
  macosx/PrefsController.mm
Labels: scope:mac, type:feat, semver:minor

#6151 refactor: reduce coupling between tr_session and tr_peerMgr
  libtransmission/peer-mgr.cc
  libtransmission/session.cc
  libtransmission/session.h
  libtransmission/torrent.cc
Labels: scope:core, type:refactor, notes:none

#6153 refactor: make tr_torrent::labels_ private
  libtransmission/resume.cc
  libtransmission/rpcimpl.cc
  libtransmission/torrent-ctor.cc
  libtransmission/torrent.cc
  libtransmission/torrent.h
Labels: scope:core, type:refactor, notes:none

#6102 chore: update build instructions
  README.md
  docs/Building-Transmission.md
Labels: scope:docs, type:docs, notes:none

#5953 feat: do separate IPv4 and IPv6 port checks in WebUI
  docs/rpc-spec.md
  libtransmission/quark.cc
  libtransmission/quark.h
  libtransmission/rpcimpl.cc
  web/src/prefs-dialog.js
  web/src/remote.js
Labels: scope:web, scope:core, type:feat, semver:minor

#6096 fix: URL cleanup in BlocklistDownloader on macOS
  macosx/BlocklistDownloader.mm
Labels: scope:mac, type:fix, semver:patch

#6159 refactor: remove quark support from tr_variant
  libtransmission/peer-msgs.cc
  libtransmission/resume.cc
  libtransmission/rpcimpl.cc
  libtransmission/variant-json.cc
  libtransmission/variant.cc
  libtransmission/variant.h
  utils/remote.cc
Labels: scope:core, type:refactor, notes:none

#6155 refactor: minor decoupling in peer-mgr
  libtransmission/peer-mgr.cc
  libtransmission/peer-socket.cc
  libtransmission/peer-socket.h
  libtransmission/torrent.cc
  libtransmission/torrent.h
  libtransmission/torrents.cc
  libtransmission/torrents.h
Labels: scope:core, type:refactor, notes:none

#5703 refactor: prefer std::set over QSet
  libtransmission/torrent.h
  qt/ColumnResizer.cc
  qt/ColumnResizer.h
  qt/DetailsDialog.cc
  qt/DetailsDialog.h
  qt/FileTreeItem.cc
  qt/FileTreeItem.h
  qt/FileTreeModel.cc
  qt/FileTreeModel.h
  qt/FileTreeView.cc
  qt/FileTreeView.h
  qt/OptionsDialog.cc
  qt/OptionsDialog.h
  qt/Prefs.cc
  qt/Prefs.h
  qt/Session.cc
  qt/Session.h
  qt/Typedefs.h
  qt/WatchDir.cc
  qt/WatchDir.h
Labels: scope:qt, type:refactor, notes:none

#5907 perf: cut down excess copying when downloading
  libtransmission/peer-msgs.cc
Labels: scope:core, type:perf, notes:none

#5933 fixup! refactor: re-organise net.h member functions (#5878)
  libtransmission/global-ip-cache.cc
  libtransmission/net.h
  libtransmission/session.h
Labels: scope:core, type:fix, notes:none

#5604 fix: in RPC, default to sort torrents by id
  libtransmission/rpcimpl.cc
  libtransmission/torrents.h
Labels: scope:core, type:fix, semver:patch

#5921 fix: fixed graying out buttons in dark mode for web client
  web/assets/css/transmission-app.scss
Labels: scope:web, type:fix, notes:none

#5918 feat: display date & time in torrent detail for web client
  web/src/formatter.js
  web/src/inspector.js
  web/src/torrent-row.js
Labels: scope:web, needs UI review, type:ui

#6161 refactor: extract the lambda method in tr_variant::Map::find()
  libtransmission/variant.h
Labels: scope:core, type:refactor, notes:none

#6166 refactor: remove tr_torrentTotalSize()
  gtk/Torrent.cc
  libtransmission/resume.cc
  libtransmission/torrent.cc
  libtransmission/transmission.h
  macosx/Torrent.mm
Labels: scope:core, type:refactor, notes:none

#6169 fixup! perf: cut down excess copying when downloading (#5907)
  libtransmission/peer-msgs.cc
Labels: scope:core, type:fix, notes:none

#6174 fix: formatting cmdline help message
  libtransmission/tr-getopt.cc
Labels: scope:core, type:fix, notes:none, semver:patch

#6180 Fix building on macOS Mojave
  Transmission.xcodeproj/project.pbxproj
Labels: scope:mac, bug:regression

#6181 refactor: make class methods private
  libtransmission/observable.h
  libtransmission/peer-mgr.cc
  libtransmission/torrent.h
Labels: scope:core, type:refactor, notes:none

#5840 refactor: unified shadow properties for web client
  web/assets/css/transmission-app.scss
  web/public_html/index.html
Labels: scope:web, needs UI review, type:ui

#6179 refactor: move tr_session::getAllTorrents to tr_torrents
  libtransmission/rpcimpl.cc
  libtransmission/session.cc
  libtransmission/session.h
  libtransmission/torrent.cc
  libtransmission/torrents.h
Labels: scope:core, type:fix, notes:none, semver:patch

#6120 refactor: move macOS default app logic to dedicated class
  Transmission.xcodeproj/project.pbxproj
  macosx/CMakeLists.txt
  macosx/DefaultAppHelper.h
  macosx/DefaultAppHelper.mm
  macosx/PrefsController.mm
Labels: scope:mac, type:refactor

#6189 refactor: blocklists
  libtransmission/blocklist.cc
  libtransmission/blocklist.h
  libtransmission/peer-mgr.cc
  libtransmission/peer-mgr.h
  libtransmission/rpcimpl.cc
  libtransmission/session.cc
  libtransmission/session.h
  tests/libtransmission/blocklist-test.cc
  tests/libtransmission/session-test.cc
Labels: scope:core, type:refactor, notes:none
