Repository transmission/transmission, pull requests merged in 2023-11, with the labels that each got.

#6192 Bump 3rd-party deps versions used on Windows
  .github/workflows/actions.yml
  release/windows/build-curl.ps1
  release/windows/build-dbus.ps1
  release/windows/build-openssl.ps1
  release/windows/build-qt5.ps1
  release/windows/build-qt6.ps1
  release/windows/build-zlib.ps1
Labels: scope:infra, type:build, notes:none

#3823 Sanitize torrent filenames depending on current OS
  libtransmission/torrent-files.cc
  tests/libtransmission/torrent-files-test.cc
Labels: semver:minor

#6197 refactor: work around C3779 error in MSVC 14.37.32822
  libtransmission/variant.h
Labels: type:refactor, notes:none

#6107 chore: replace deprecated NSNamePboardType with NSPasteboardTypeName
  macosx/Info.plist
  macosx/Info.plist.in
  macosx/TorrentTableView.mm
Labels: scope:mac, type:chore

#5118 refactor: remove unnecessary NSNotificationCenter observer removals
  macosx/AddMagnetWindowController.mm
  macosx/AddWindowController.mm
  macosx/DragOverlayWindow.mm
  macosx/FilterBarController.mm
  macosx/InfoActivityViewController.mm
  macosx/InfoOptionsViewController.mm
  macosx/InfoWindowController.mm
  macosx/MessageWindowController.mm
  macosx/PrefsController.mm
  macosx/StatusBarController.mm
  macosx/Torrent.mm
  macosx/TorrentTableView.mm
Labels: scope:mac, type:refactor, semver:minor

#6184 pbxproj refactor
  Transmission.xcodeproj/project.pbxproj
Labels: scope:mac, needs code review, notes:none

#5867 added open source reverse proxy guide on securing transmission
  docs/README.md
Labels: type:docs, notes:none

#6203 ci: bump macos-11 to macos-12 in github actions
  .github/workflows/actions.yml
  libtransmission/torrent.h
Labels: notes:none, type:ci

#5705 fix: only append '.added' suffix to watchdir files
  qt/AddData.cc
  qt/AddData.h
  qt/Application.cc
  qt/Application.h
  qt/MainWindow.cc
  qt/OptionsDialog.cc
  qt/Session.cc
  qt/Session.h
Labels: scope:qt, type:fix, semver:patch, needs testers

#6206 Update workflow to Qt 6 on macOS
  .github/workflows/actions.yml
Labels: notes:none, type:ci

#4919 fix: Implicit conversion loses integer precision
  macosx/Controller.mm
  macosx/PiecesView.mm
  macosx/ProgressBarView.mm
  macosx/Torrent.h
  macosx/Torrent.mm
Labels: scope:mac, type:refactor, notes:none

#6207 Fix: torrentTableView crash after superview.superview.superview
  macosx/AboutWindowController.mm
  macosx/AddMagnetWindowController.mm
  macosx/AddWindowController.mm
  macosx/Base.lproj/MainMenu.xib
  macosx/BlocklistDownloaderViewController.mm
  macosx/ColorTextField.mm
  macosx/Controller.mm
  macosx/CreatorWindowController.mm
  macosx/FileOutlineController.mm
  macosx/FileOutlineView.mm
  macosx/FilterBarController.mm
  macosx/FilterBarView.mm
  macosx/GlobalOptionsPopoverViewController.mm
  macosx/GroupsPrefsController.mm
  macosx/InfoActivityViewController.mm
  macosx/InfoFileViewController.mm
  macosx/InfoOptionsViewController.mm
  macosx/InfoPeersViewController.mm
  macosx/InfoTrackersViewController.mm
  macosx/InfoWindowController.mm
  macosx/MessageWindowController.mm
  macosx/PiecesView.mm
  macosx/PrefsController.mm
  macosx/StatsWindowController.mm
  macosx/StatusBarController.mm
  macosx/TorrentCellActionButton.mm
  macosx/TorrentCellControlButton.mm
  macosx/TorrentCellRevealButton.mm
  macosx/TorrentTableView.mm
  macosx/URLSheetWindowController.mm
Labels: scope:mac, bug:regression

#6223 fix: parse all http announce responses
  libtransmission/announcer-http.cc
Labels: scope:core, type:fix, semver:patch

#6224 feat: display full client name in tooltip [WebUI]
  web/src/inspector.js
Labels: scope:web, type:feat, notes:none

#4900 feat: add stats for known peers, not just connected ones
  libtransmission/peer-common.h
  libtransmission/peer-mgr.cc
  libtransmission/torrent.cc
  libtransmission/transmission.h
  macosx/InfoPeersViewController.mm
  macosx/Torrent.h
  macosx/Torrent.mm
Labels: scope:mac, scope:core, type:feat, needs UI review, semver:minor

#6215 refactor: add libtransmission::Values
  cli/cli.cc
  daemon/daemon.cc
  libtransmission/CMakeLists.txt
  libtransmission/utils.cc
  libtransmission/utils.h
  libtransmission/values.h
  tests/libtransmission/CMakeLists.txt
  tests/libtransmission/test-fixtures.h
  tests/libtransmission/values-test.cc
  tests/utils/assets/bitcomet.utf-8.special.show
  tests/utils/assets/bittorrent-v2-hybrid-test.show
  utils/create.cc
  utils/remote.cc
  utils/show.cc
  utils/units.h
Labels: scope:cli, scope:remote, scope:create, scope:show, scope:core, scope:test

#6233 fix: recent clang-tidy warnings
  libtransmission/peer-mgr.cc
  tests/libtransmission/file-piece-map-test.cc
Labels: scope:core, type:fix, type:test

#6236 fix: clang-analyzer-core.NullDereference warning in tr_variant_serde::parse_json()
  libtransmission/variant-json.cc
Labels: scope:core, type:refactor, notes:none

#6195 chore: automated copyright update with GitHub Actions
  .github/workflows/update-copyright.yml
Labels: needs code review, notes:none, type:ci

#6238 refactor: migrate variant api
  gtk/Session.cc
  libtransmission/resume.cc
  libtransmission/variant-benc.cc
  libtransmission/variant-json.cc
  libtransmission/variant.cc
  libtransmission/variant.h
  qt/VariantHelpers.cc
  tests/libtransmission/variant-test.cc
  utils/edit.cc
Labels: scope:core, type:refactor, notes:none

#6234 refactor: Values pt. 2 - use Speed in tr_bandwidth
  libtransmission/bandwidth.cc
  libtransmission/bandwidth.h
  libtransmission/peer-io.cc
  libtransmission/peer-io.h
  libtransmission/peer-msgs.cc
  libtransmission/resume.cc
  libtransmission/rpcimpl.cc
  libtransmission/session.cc
  libtransmission/session.h
  libtransmission/torrent.cc
  libtransmission/torrent.h
  libtransmission/transmission.h
  libtransmission/utils.cc
  libtransmission/webseed.cc
  tests/libtransmission/values-test.cc
Labels: scope:core, type:refactor, notes:none

#6230 refactor: thread-safe `lru-cache` and `tr_open_files`
  libtransmission/inout.cc
  libtransmission/lru-cache.h
  libtransmission/open-files.cc
  libtransmission/open-files.h
  tests/libtransmission/open-files-test.cc
Labels: scope:core, type:refactor, notes:none

#6242 Bumping pbxproj to C11/C++17 for all targets
  Transmission.xcodeproj/project.pbxproj
Labels: scope:mac, type:build

#6231 refactor: thread-safe `Cache`
  libtransmission/cache.cc
  libtransmission/cache.h
  libtransmission/torrents.cc
  libtransmission/torrents.h
Labels: scope:core, type:refactor, notes:none

#6235 refactor: Values pt. 3 - use Speed in tr_session
  libtransmission/peer-msgs.cc
  libtransmission/rpcimpl.cc
  libtransmission/session-alt-speeds.h
  libtransmission/session.cc
  libtransmission/session.h
  libtransmission/torrent.cc
  libtransmission/torrent.h
  libtransmission/transmission.h
Labels: scope:core, type:refactor, notes:none

#6241 refactor: Values pt. 4 - use Speed in peer_mgr, peer_msgs
  libtransmission/peer-common.h
  libtransmission/peer-mgr.cc
  libtransmission/peer-msgs.cc
  libtransmission/rpcimpl.cc
  libtransmission/transmission.h
  libtransmission/utils.cc
  libtransmission/utils.h
  libtransmission/webseed.cc
Labels: scope:core, type:refactor, notes:none

#6237 refactor: directly check if announcers are idle instead of using a stop counter
  libtransmission/announcer-udp.cc
  libtransmission/announcer.cc
  libtransmission/announcer.h
  libtransmission/session.cc
  libtransmission/session.h
  libtransmission/web.cc
  libtransmission/web.h
Labels: scope:core, type:fix, notes:none

#6254 fix: `assertion failed: is_connectable_.value_or(true) || !is_connected()`
  libtransmission/peer-mgr.cc
Labels: scope:core, type:fix, notes:none

#6259 refactor: make some tr_torrent fields private
  libtransmission/rpcimpl.cc
  libtransmission/torrent-magnet.cc
  libtransmission/torrent.cc
  libtransmission/torrent.h
  libtransmission/torrents.cc
Labels: scope:core, type:refactor, notes:none

#6260 refactor: add private helper class CumulativeCount
  libtransmission/peer-mgr.cc
  libtransmission/resume.cc
  libtransmission/session.cc
  libtransmission/torrent.cc
  libtransmission/torrent.h
Labels: scope:core, type:refactor, notes:none

#6258 refactor: Values pt. 7 - remove tr_formatter_init methods
  gtk/DetailsDialog.cc
  gtk/MainWindow.cc
  gtk/PrefsDialog.cc
  gtk/Torrent.cc
  gtk/Torrent.h
  gtk/Utils.cc
  gtk/Utils.h
  gtk/main.cc
  libtransmission/torrent.h
  libtransmission/utils.cc
  libtransmission/utils.h
  libtransmission/values.h
  macosx/Controller.mm
  qt/Application.cc
  qt/Application.h
  qt/DetailsDialog.cc
  qt/FileTreeItem.cc
  qt/FileTreeView.cc
  qt/Formatter.cc
  qt/Formatter.h
  qt/FreeSpaceLabel.cc
  qt/MainWindow.cc
  qt/MakeDialog.cc
  qt/PrefsDialog.cc
  qt/Speed.h
  qt/StatsDialog.cc
  qt/TorrentDelegate.cc
  qt/TrackerDelegate.cc
  tests/libtransmission/values-test.cc
Labels: scope:gtk, scope:qt, scope:mac, scope:core, type:refactor

#5906 feat: update GTK progress bar colours
  gtk/transmission-ui.css
Labels: scope:gtk, needs UI review, type:ui

#6263 refactor: add a tr_direction arg to tr_torrent::is_queued()
  libtransmission/session.cc
  libtransmission/torrent.h
Labels: scope:core, type:refactor, notes:none

#6274 refactor: RPC `port-test` improvements
  docs/rpc-spec.md
  libtransmission/announcer-http.cc
  libtransmission/rpcimpl.cc
  libtransmission/web.cc
  libtransmission/web.h
  libtransmission/webseed.cc
  tests/libtransmission/global-ip-cache-test.cc
Labels: scope:core, scope:docs, type:refactor, type:docs, notes:none

#6279 refactor: make tr_torrent::seconds_[seeding,downloading] private
  libtransmission/resume.cc
  libtransmission/resume.h
  libtransmission/session.cc
  libtransmission/torrent.cc
  libtransmission/torrent.h
  tests/libtransmission/rename-test.cc
Labels: scope:core, type:refactor, notes:none

#6281 refactor: make tr_torrent date fields private
  libtransmission/peer-mgr.cc
  libtransmission/resume.cc
  libtransmission/torrent.cc
  libtransmission/torrent.h
Labels: scope:core, type:refactor, notes:none

#6287 refactor: prefer css vars over sass
  .github/workflows/webapp.yml
  web/assets/css/transmission-app.scss
Labels: scope:web, type:refactor, notes:none

#6283 docs: remove dead link from Scripts.md
  docs/Scripts.md
Labels: type:docs, notes:none

#6277 refactor: pause torrent after verifying if files disappeared
  docs/rpc-spec.md
  libtransmission/rpcimpl.cc
  libtransmission/torrent.cc
  libtransmission/torrent.h
  libtransmission/transmission.h
  web/src/action-manager.js
  web/src/context-menu.js
  web/src/force-verify-dialog.js
  web/src/remote.js
  web/src/transmission.js
Labels: scope:core, type:refactor

#6293 refactor: make tr_torrent fields, methods private where possible
  libtransmission/announcer.cc
  libtransmission/cache.cc
  libtransmission/peer-mgr.cc
  libtransmission/resume.cc
  libtransmission/rpcimpl.cc
  libtransmission/session.cc
  libtransmission/torrent-magnet.cc
  libtransmission/torrent.cc
  libtransmission/torrent.h
  libtransmission/webseed.cc
  tests/libtransmission/move-test.cc
Labels: scope:core, type:refactor, notes:none

#6292 Compatibility to build with Xcode 11.3.1
  macosx/DefaultAppHelper.mm
Labels: scope:mac, type:build, bug:regression, notes:none

#6300 fix: Local variable 'pex' will be copied despite being returned by name
  libtransmission/tr-dht.cc
  libtransmission/variant.h
Labels: scope:core, notes:none

#6295 refactor: c++ify libtransmission's tr_ctor struct
  daemon/daemon.cc
  gtk/Session.cc
  libtransmission/CMakeLists.txt
  libtransmission/resume.cc
  libtransmission/resume.h
  libtransmission/rpcimpl.cc
  libtransmission/session.cc
  libtransmission/torrent-ctor.cc
  libtransmission/torrent-ctor.h
  libtransmission/torrent.cc
  libtransmission/torrent.h
  libtransmission/transmission.h
  tests/libtransmission/rename-test.cc
  tests/libtransmission/test-fixtures.h
  tests/libtransmission/torrent-metainfo-test.cc
Labels: scope:core, type:refactor, notes:none

#6299 Fix warning: "It's not legal to call -layoutSubtreeIfNeeded on a view which is already being laid out."
  macosx/TorrentTableView.mm
Labels: scope:mac, notes:none

#6302 docs: add description for torrent action requests
  docs/rpc-spec.md
Labels: scope:docs, type:docs, notes:none

#6301 refactor: make tr_torrent::queue_position_ private
  libtransmission/rpcimpl.cc
  libtransmission/session.cc
  libtransmission/torrent.cc
  libtransmission/torrent.h
Labels: scope:core, type:refactor, notes:none

#6304 refactor: make tr_torrent::on_announce_list_changed() private
  libtransmission/rpcimpl.cc
  libtransmission/torrent.cc
  libtransmission/torrent.h
Labels: scope:core, type:refactor, notes:none

#6280 build: migrate to esbuild from webpack
  .github/workflows/webapp.yml
  web/.eslintrc.js
  web/CMakeLists.txt
  web/README
  web/README.md
  web/babel.config.js
  web/esbuild.mjs
  web/package-lock.json
  web/package.json
  web/package.json.buildonly
  web/public_html/index.html
  web/public_html/transmission-app.css
  web/public_html/transmission-app.css.LEGAL.txt
  web/public_html/transmission-app.css.map
  web/public_html/transmission-app.js.LEGAL.txt
  web/webpack.config.js
Labels: scope:web, type:build

#6079 fix: low priority not working
  libtransmission/bandwidth.cc
  libtransmission/bandwidth.h
  libtransmission/peer-mgr.cc
  libtransmission/session.cc
  libtransmission/session.h
  libtransmission/transmission.h
Labels: scope:core, type:fix, semver:patch

#6305 refactor: make more tr_torrent fields private
  libtransmission/peer-mgr.cc
  libtransmission/resume.cc
  libtransmission/torrent.cc
  libtransmission/torrent.h
  libtransmission/transmission.h
Labels: scope:core, type:refactor, notes:none

#6306 chore: minor bandwidth code housekeeping
  libtransmission/bandwidth.cc
  libtransmission/bandwidth.h
  libtransmission/tr-buffer.h
Labels: scope:core, notes:none, type:chore

#6232 feat: support creating 0 byte files
  libtransmission/cache.cc
  libtransmission/cache.h
  libtransmission/file-piece-map.cc
  libtransmission/file-piece-map.h
  libtransmission/inout.cc
  libtransmission/lru-cache.h
  libtransmission/makemeta.cc
  libtransmission/open-files.cc
  libtransmission/open-files.h
  libtransmission/torrent-metainfo.cc
  libtransmission/torrent.cc
  libtransmission/torrent.h
  libtransmission/torrents.cc
  libtransmission/torrents.h
  libtransmission/verify.cc
  libtransmission/verify.h
  libtransmission/webseed.cc
  tests/libtransmission/file-piece-map-test.cc
  tests/libtransmission/makemeta-test.cc
  tests/libtransmission/open-files-test.cc
Labels: scope:core, type:feat, semver:minor

#6311 improve magnet metadata progress
  libtransmission/torrent-magnet.cc
Labels: scope:core, type:refactor, notes:none

#6290 VDKQueue: support deallocating the object
  macosx/VDKQueue/VDKQueue.h
  macosx/VDKQueue/VDKQueue.mm
Labels: scope:mac, type:refactor, notes:none
