Repository transmission/transmission, pull requests merged in 2023-02, with the labels that each got.

#4699 docs: deprecate trackerAdd, trackerRemove, trackerReplace RPC
  docs/rpc-spec.md
Labels: scope:docs

#4642 Fix WebUtilsTest.urlParse and psl_builtin for Xcode
  .gitignore
  Transmission.xcodeproj/project.pbxproj
  libtransmission/web-utils.cc
Labels: scope:mac, scope:core

#4705 fix: Add precheck for tar archive test.
  macosx/BlocklistDownloader.mm
Labels: scope:mac, type:fix

#4696 fix: remove abort() call from tr_assert_message()
  libtransmission/tr-assert.mm
Labels: scope:core, type:fix, needs code review, notes:none

#4528 fix magnet link start logic
  libtransmission/torrent-magnet.cc
  libtransmission/torrent.cc
  libtransmission/torrent.h
  libtransmission/transmission.h
  macosx/AddMagnetWindowController.mm
  macosx/Torrent.h
  macosx/Torrent.mm
Labels: scope:core, type:fix

#4684 Fix webui filter selection on mobile
  web/assets/css/transmission-app.scss
Labels: scope:web, type:fix

#4711 Fix issues reported by `hicpp` clang-tidy checks (GTK client)
  gtk/.clang-tidy
  gtk/Flags.h
  gtk/FreeSpaceLabel.h
  gtk/Torrent.cc
  gtk/Utils.cc
Labels: scope:gtk, type:refactor, notes:none

#4723 fix: ensure ipv4 for udp announces.
  libtransmission/announcer-udp.cc
Labels: type:fix

#4725 fix: race condition in RPC
  libtransmission/rpcimpl.cc
Labels: scope:qt, scope:core, type:fix

#4709 Workaround for CoreAutoLayout hang during runCustomizationPalette on macOS 13.2
  macosx/Controller.mm
  macosx/Toolbar.h
  macosx/Toolbar.mm
Labels: os:mac, needs UI review

#4706 docs: add 4.0.0 release notes
  news/news-4.0.0.md
Labels: type:docs, notes:none

#4730 chore: bump version to 4.0.0
  CMakeLists.txt
Labels: type:chore

#4760 build: renamed ENABLE_WEB build option for clarity
  CMakeLists.txt
  docs/Building-Transmission.md
Labels: type:build, notes:none

#4762 Include libb64 and libutp as subprojects
  .github/workflows/codeql.yml
  CMakeLists.txt
  cmake/TrMacros.cmake
Labels: scope:core, type:fix, type:build, bug:regression

#4799 fix: misleading error message when resume file is missing
  libtransmission/resume.cc
Labels: scope:core, type:fix, semver:patch

#4788 added padding to widgets in macOS client to avoid being hidden below scroller
  macosx/TorrentCell.mm
Labels: scope:mac, type:fix, type:ui, semver:patch

#4803 Doc: Python v3 required for Debian 11 Bullseye build
  docs/Building-Transmission.md
Labels: scope:docs, type:fix, semver:minor

#4808 chore: disable flaky unit tests
  tests/libtransmission/lpd-test.cc
  tests/libtransmission/timer-test.cc
  tests/libtransmission/watchdir-test.cc
Labels: type:build, notes:none, semver:patch

#4804 Fix: Prevent lengthy compilation workflows to run needlessly
  .github/workflows/codeql.yml
  .github/workflows/webapp.yml
Labels: type:perf, type:build, notes:none

#4809 Fix: Put "private" and "source" inside the metadata "info" key
  libtransmission/makemeta.cc
  tests/libtransmission/makemeta-test.cc
Labels: scope:core, type:fix, semver:patch

#4807 cmake: pass --no-warn-unused-cli to child cmake process
  cmake/TrMacros.cmake
Labels: type:build, notes:none, semver:patch

#4823 Speed up Appveyor builds with ccache
  CMakeLists.txt
  appveyor.yml
  release/windows/main.ps1
Labels: type:build

#4805 Fix: Protect against potential nullptr dereference
  libtransmission/announcer.cc
Labels: scope:core, type:fix, semver:patch

#4824 build: disable clang-tidy by default
  CMakeLists.txt
Labels: type:build

#4812 Doc: Add missing configuration file directives
  docs/Editing-Configuration-Files.md
Labels: type:docs

#4731 tests: expose libtransmission gtests to ctest
  .github/workflows/actions.yml
  tests/libtransmission/CMakeLists.txt
  tests/libtransmission/file-test.cc
  tests/libtransmission/platform-test.cc
Labels: type:build, scope:test, notes:none

#4839 fix: incorrect debounce arguments
  web/src/utils.js
Labels: scope:web, type:fix

#4826 fix: sometimes fails to detect when a uTP socket isn't writable & doesn't connect
  libtransmission/peer-io.cc
Labels: scope:core, type:fix

#4842 fix: port forwarding flag not saved between sessions
  libtransmission/session.cc
Labels: scope:core, type:fix

#4846 fix: display correct tracker port in qt torrent-details
  qt/TrackerDelegate.cc
Labels: scope:qt, type:fix, type:ui

#4813 style: dock badge colours follow Apple a11y colour guide
  macosx/Images/Images.xcassets/DownloadBadge.imageset/DownloadBadge.png
  macosx/Images/Images.xcassets/DownloadBadge.imageset/DownloadBadge@2x.png
  macosx/Images/Images.xcassets/UploadBadge.imageset/UploadBadge.png
  macosx/Images/Images.xcassets/UploadBadge.imageset/UploadBadge@2x.png
Labels: scope:mac

#4847 fix: tr_swarm order of destruction
  libtransmission/peer-mgr.cc
Labels: scope:core, type:fix

#4851 Revert "fix: remove abort() call from tr_assert_message() (#4696)"
  libtransmission/tr-assert.mm
Labels: notes:none

#4855 Build additional packages for Qt 5 on Appveyor
  appveyor.yml
  dist/msi/CMakeLists.txt
  dist/msi/Transmission.wxs
  release/windows/build-qt5.ps1
  release/windows/build-qt6.ps1
  release/windows/build-transmission.ps1
  release/windows/main.ps1
Labels: scope:qt, os:windows, type:build, bug:regression

#4840 fix: do not lose magnet links when upgrading from tr3 to 4
  libtransmission/torrent-metainfo.cc
  libtransmission/torrent-metainfo.h
  tests/libtransmission/assets/gimp-2.10.32-1-arm64.dmg.torrent
  tests/libtransmission/torrent-metainfo-test.cc
Labels: scope:core

#4860 chore: remove invalid assertion test
  libtransmission/peer-mse.h
Labels: scope:core, type:fix, notes:none

#4865 build: install rebuilt web if available
  CMakeLists.txt
  web/CMakeLists.txt
Labels: type:build, notes:none

#4863 fix: look for libquota and use it
  CMakeLists.txt
  libtransmission/CMakeLists.txt
Labels: type:fix, type:build

#4856 fix: magnet links paused when added
  libtransmission/peer-mgr.cc
  libtransmission/resume.cc
  libtransmission/torrent-magnet.cc
  libtransmission/torrent-magnet.h
  libtransmission/torrent.cc
  libtransmission/torrent.h
  libtransmission/transmission.h
  macosx/Torrent.mm
Labels: scope:core, type:fix, needs testers

#4879 fix: assertion failed leftUntilDone <= sizeWhenDone
  libtransmission/completion.cc
  libtransmission/completion.h
Labels: scope:core, type:fix

#4880 fix: checksum of pieces that don't align on block boundaries
  libtransmission/inout.cc
Labels: scope:core, type:fix

#4890 fix: handle block fragments that arrive from peers out-of-order
  libtransmission/cache.cc
  libtransmission/cache.h
  libtransmission/peer-msgs.cc
  libtransmission/torrent.cc
  libtransmission/webseed.cc
  tests/libtransmission/move-test.cc
Labels: scope:core, type:fix

#4884 macOS autolayout fixes in info activity view
  macosx/Base.lproj/InfoActivityView.xib
Labels: scope:mac, type:fix, type:ui

#4895 Don't autofetch metainfo at startup and new torrents.
  libtransmission/torrent.cc
  libtransmission/transmission.h
Labels: scope:core, notes:none, semver:patch

#4898 fix: awkward grammar in details dialog running-time display
  gtk/DetailsDialog.cc
Labels: scope:gtk, type:fix, type:ui, semver:patch

#4896 macOS fix selected Group text color
  macosx/GroupTextCell.h
  macosx/GroupTextCell.mm
  macosx/TorrentTableView.mm
Labels: scope:mac, type:fix

#4933 Store percents as integer, with 2 digits of precision
  .github/workflows/actions.yml
  gtk/CMakeLists.txt
  gtk/Percents.cc
  gtk/Percents.h
  gtk/Torrent.cc
  gtk/Torrent.h
  gtk/TorrentCellRenderer.cc
  gtk/TorrentSorter.cc
  gtk/Utils.h
Labels: scope:gtk, type:fix, type:ui, bug:regression

#4886 fix: Remove faulty `popcnt` features checks for MSVC [#4872]
  libtransmission/tr-popcount.h
Labels: scope:core, type:fix, bug:regression, semver:patch

#4897 fix: try utp connection first; fix utp timeout issues.
  libtransmission/handshake.cc
  libtransmission/peer-io.cc
  libtransmission/tr-utp.cc
Labels: type:fix

#4939 Only show/hide top-level windows on systray action
  gtk/Utils.cc
Labels: scope:gtk, type:fix, bug:regression

#4932 Allow searching labels with spaces and hyphens
  web/src/transmission.js
Labels: scope:web, bep-compliance, semver:patch

#4953 fix: blocklists allocate more memory than they need
  libtransmission/blocklist.cc
Labels: scope:core, type:fix

#4955 Support in-source builds
  .github/workflows/actions.yml
  cmake/TrMacros.cmake
Labels: type:build, semver:patch

#4963 fix: open-folder does not work in qt client
  qt/MainWindow.cc
Labels: scope:qt, type:fix

#4968 build: fix libdeflate find module never finding anything
  cmake/FindDEFLATE.cmake
Labels: scope:3rdparty, type:build

#4970 build: downgrade libdeflate to 1.7
  CMakeLists.txt
Labels: type:build, semver:patch

#4946 build: do not test utils if not building utils
  tests/CMakeLists.txt
Labels: type:fix, type:build, notes:none

#4978 fix: cannot build with clang on Windows
  libtransmission/open-files.cc
Labels: scope:core, type:fix, type:build

#4906 build: add option to disable installation of web assets
  CMakeLists.txt
  web/CMakeLists.txt
Labels: type:fix, type:build

#4984 fix: make context menu highlighted row readable in dark mode
  web/assets/css/transmission-app.scss
Labels: scope:web, type:fix, type:ui, semver:patch

#4998 docs: fix RPC documentation error
  docs/rpc-spec.md
Labels: type:fix, type:docs

#4956 docs: add 4.0.1 release notes
  news/news-4.0.1.md
Labels: type:docs, semver:patch

#5001 fix: padding in overflow menu
  web/assets/css/transmission-app.scss
  web/src/overflow-menu.js
Labels: scope:web, type:fix, type:ui

#5006 fix: TR_TIME_LOCALTIME contained garbage when calling a script
  libtransmission/torrent.cc
Labels: scope:core, type:fix

#5021 fix: Update Inspector window frame to fix AutoLayout warning.
  macosx/InfoWindow.xib
Labels: scope:mac, type:fix, type:ui, notes:none

#5018 fix: Adjust sizes to fix Call Script control cutoff.
  macosx/Base.lproj/PrefsWindow.xib
Labels: scope:mac, needs UI review, type:ui

#5029 Add "Unexpected argument" message (issue #4974)
  daemon/daemon.cc
Labels: scope:daemon, type:fix

#5033 fix: alt speed schedule not saved in web ui
  web/src/prefs-dialog.js
Labels: scope:web, type:fix

#5035 fix: Add tooltip explaining why auto adding for magnets is unavailable.
  macosx/PrefsController.mm
  macosx/en.lproj/Localizable.strings
Labels: scope:mac, type:fix, type:ui

#5039 Limit in-kernel file copying to 2 GiB blocks at a time
  libtransmission/file-posix.cc
Labels: scope:core, type:fix

#5025 fix: some torrents think they are magnets
  libtransmission/session.cc
  libtransmission/torrent-metainfo.cc
Labels: scope:core, type:fix

#5058 Workaround for Firefox downloads happening in two steps: first time being an empty file
  macosx/Controller.mm
Labels: scope:mac, type:fix, semver:patch

#5054 change alt to control for shortcuts
  web/src/action-manager.js
Labels: scope:web, type:fix

#5066 Set fPiecesControl segmentDistribution to fillProportionally
  macosx/Base.lproj/InfoActivityView.xib
Labels: scope:mac, type:fix, semver:patch

#5016 feat: Use updated minimal NSColorWell style for Groups.
  macosx/CocoaCompatibility.h
  macosx/GroupsPrefsController.mm
Labels: scope:mac

#5055 fix: don't include full source path in log messages
  libtransmission/log.cc
Labels: type:fix, semver:patch

#5080 fix: std::clamp() assertion failure in rechokeDownloads()
  libtransmission/peer-mgr.cc
Labels: scope:core, type:fix

#4971 docs: document new settings
  docs/Editing-Configuration-Files.md
  docs/rpc-spec.md
Labels: type:docs, semver:patch

#5086 fix: 4.0.0 regression that broke speed limits for utp peers
  libtransmission/peer-io.cc
Labels: scope:core, type:fix, semver:patch

#5088 fix: transmission-remote warning when adding magnet link
  utils/remote.cc
Labels: scope:remote, type:fix, semver:patch

#5083 fix: restore client-level progress indicators
  web/assets/css/transmission-app.scss
  web/src/torrent-row.js
Labels: scope:web, type:fix, type:ui, semver:patch

#5091 fix: 4.0.0 bookkeeping of protocol overhead when receiving peer messages
  libtransmission/peer-io.cc
Labels: scope:core, type:fix, semver:patch

#5060 recheckCompleteness on setDownloadDir
  libtransmission/torrent.cc
  libtransmission/torrent.h
Labels: scope:core, semver:patch
