Repository transmission/transmission, pull requests merged in 2023-05, with the labels that each got.

#5491 fix: show magnet name in compact mode
  qt/TorrentDelegateMin.cc
Labels: scope:qt, type:fix, type:ui, semver:patch

#5329 Fix UDP can't connect warnings and add IP cache on the way
  Transmission.xcodeproj/project.pbxproj
  docs/Editing-Configuration-Files.md
  libtransmission/CMakeLists.txt
  libtransmission/announcer.cc
  libtransmission/global-ip-cache.cc
  libtransmission/global-ip-cache.h
  libtransmission/net.cc
  libtransmission/net.h
  libtransmission/session.cc
  libtransmission/session.h
  libtransmission/tr-udp.cc
  tests/libtransmission/CMakeLists.txt
  tests/libtransmission/global-ip-cache-test.cc
  tests/libtransmission/net-test.cc
Labels: semver:minor

#5481 docs: update translation site names
  docs/Translating.md
Labels: type:fix, type:docs, semver:patch

#5490 refactor: save stats.json periodically and when closing session #5476
  libtransmission/session.cc
  libtransmission/stats.cc
  libtransmission/stats.h
Labels: scope:core, type:feat, semver:minor

#5498 Follow-up and clean-up of `tr_global_ip_cache` PR
  libtransmission/net.cc
  libtransmission/net.h
  libtransmission/session.cc
  libtransmission/session.h
  libtransmission/tr-udp.cc
Labels: scope:core, type:refactor, notes:none, semver:minor

#5407 GTK: Improve appstream metainfo
  gtk/transmission-gtk.metainfo.xml.in
Labels: scope:gtk, notes:none, type:chore

#5505 fix: does not trash added torrent files when asked
  qt/Session.cc
Labels: scope:qt, type:fix, semver:patch

#5506 fixup! feat: add global IP cache, fix UDP connection failure warnings
  tests/libtransmission/global-ip-cache-test.cc
Labels: scope:test, notes:none, type:chore

#5508 refactor: rename tr_tracker_view.host to .host_and_port for clarity
  gtk/DetailsDialog.cc
  gtk/FilterBar.cc
  libtransmission/announce-list.cc
  libtransmission/announce-list.h
  libtransmission/announcer.cc
  libtransmission/rpcimpl.cc
  libtransmission/torrent.cc
  libtransmission/transmission.h
  macosx/Torrent.mm
  macosx/TrackerNode.mm
  tests/libtransmission/announce-list-test.cc
Labels: type:refactor, notes:none, semver:minor

#5513 refactor: add BufferReader, BufferWriter::reserve_space()
  libtransmission/announcer-udp.cc
  libtransmission/peer-io.cc
  libtransmission/peer-io.h
  libtransmission/peer-mse.h
  libtransmission/peer-msgs.cc
  libtransmission/peer-socket.cc
  libtransmission/tr-buffer.h
  libtransmission/variant-benc.cc
  libtransmission/variant-json.cc
  tests/libtransmission/announcer-udp-test.cc
  tests/libtransmission/buffer-test.cc
Labels: scope:core, type:refactor, semver:minor

#5518 refactor: use BufferReader, BufferWriter as function args
  libtransmission/announcer-udp.cc
  libtransmission/peer-msgs.cc
  libtransmission/peer-socket.cc
  libtransmission/peer-socket.h
  libtransmission/variant-json.cc
  libtransmission/variant.cc
Labels: scope:core, type:refactor, notes:none

#5519 perf: use std::bitset instead of tr_bitfield in incoming_piece_data
  libtransmission/peer-msgs.cc
Labels: scope:core, type:perf, semver:patch

#5520 fix: avoid unintentional map insertions in ActiveRequests::count()
  libtransmission/peer-mgr-active-requests.cc
Labels: scope:core, type:fix, type:perf, notes:none, semver:patch

#5522 perf: avoid extra heap alloc in block cache
  libtransmission/cache.cc
  libtransmission/cache.h
  libtransmission/peer-msgs.cc
  libtransmission/webseed.cc
  tests/libtransmission/move-test.cc
Labels: scope:core, type:perf, notes:none

#5527 perf: avoid extra work in read_vc()
  libtransmission/handshake.cc
  libtransmission/handshake.h
Labels: scope:core, type:fix, type:perf, semver:patch

#5528 fix: revert buffer reserve space
  libtransmission/announcer-udp.cc
  libtransmission/peer-io.cc
  libtransmission/peer-io.h
  libtransmission/peer-mse.h
  libtransmission/peer-msgs.cc
  libtransmission/peer-socket.cc
  libtransmission/peer-socket.h
  libtransmission/tr-buffer.h
  libtransmission/variant-benc.cc
  libtransmission/variant-json.cc
  libtransmission/variant.cc
  tests/libtransmission/announcer-udp-test.cc
  tests/libtransmission/buffer-test.cc
Labels: scope:core, type:fix, notes:none

#5525 Only format JS if files in web/ change
  code_style.sh
Labels: type:build, notes:none

#5529 refactor: restore part of Buffer::reserve_space()
  libtransmission/peer-msgs.cc
  libtransmission/tr-buffer.h
  tests/libtransmission/buffer-test.cc
Labels: scope:core, type:refactor

#5532 refactor: use reserve_space() in peer-io
  libtransmission/handshake.cc
  libtransmission/peer-io.cc
  libtransmission/peer-io.h
  libtransmission/peer-mse.cc
  libtransmission/peer-mse.h
  libtransmission/tr-arc4.h
  tests/libtransmission/crypto-test.cc
Labels: scope:core, type:refactor, notes:none

#5533 refactor: migrate methods to buffer reader
  libtransmission/announcer-udp.cc
  libtransmission/peer-io.h
  libtransmission/peer-msgs.cc
  libtransmission/peer-socket.cc
  libtransmission/tr-buffer.h
  libtransmission/variant-benc.cc
  libtransmission/variant-json.cc
  tests/libtransmission/announcer-udp-test.cc
Labels: scope:core, type:refactor, notes:none

#5540 perf: avoid map insertion for complete blocks received
  libtransmission/peer-msgs.cc
Labels: scope:core, type:perf

#5543 refactor: move Buffer::add_socket() to BufferWriter::add_socket()
  libtransmission/tr-buffer.h
Labels: scope:core, notes:none

#5521 Fix building Xcode project
  Transmission.xcodeproj/project.pbxproj
  libtransmission/port-forwarding-natpmp.cc
Labels: type:build, bug:regression

#4452 Support localized punctuation for "Port:"
  macosx/InfoPeersViewController.mm
  macosx/da.lproj/Localizable.strings
  macosx/de.lproj/Localizable.strings
  macosx/en.lproj/Localizable.strings
  macosx/es.lproj/Localizable.strings
  macosx/fr.lproj/Localizable.strings
  macosx/it.lproj/Localizable.strings
  macosx/nl.lproj/Localizable.strings
  macosx/pt_PT.lproj/Localizable.strings
  macosx/ru.lproj/Localizable.strings
  macosx/tr.lproj/Localizable.strings
Labels: scope:mac, i18n
