Repository transmission/transmission, pull requests merged in 2024-07, with the labels that each got.

#6957 clarify MSE crypto algo usage
  libtransmission/handshake.cc
  libtransmission/handshake.h
Labels: scope:core, type:refactor, notes:none

#6918 fix: crash in `tr_torrent::VerifyMediator::on_verify_done()`
  libtransmission/torrent.cc
Labels: scope:core, type:fix, notes:none

#6937 fix: apply alt speed settings on load
  libtransmission/session-alt-speeds.cc
  libtransmission/session-alt-speeds.h
Labels: scope:core, type:fix

#6963 chore: clarify DhtPort specific usage
  libtransmission/peer-msgs.cc
Labels: scope:core, type:refactor, notes:none

#6927 chore: misc code cleanups
  Transmission.xcodeproj/project.pbxproj
  libtransmission/CMakeLists.txt
  libtransmission/announcer-udp.cc
  libtransmission/ip-cache.cc
  libtransmission/ip-cache.h
  libtransmission/session.cc
  libtransmission/session.h
  tests/libtransmission/CMakeLists.txt
  tests/libtransmission/ip-cache-test.cc
Labels: scope:core, notes:none, type:chore

#6896 fix: loading `2.20-3.00` progress from resume
  libtransmission/resume.cc
Labels: scope:core, type:fix

#6929 fix: misc µTP trace log fixes
  libtransmission/tr-udp.cc
  libtransmission/tr-utp.cc
Labels: scope:core, type:fix, notes:none

#6997 Add CI configuration for clang-tidy on Windows
  .github/actions/prepare-deps-win32/action.yml
  .github/workflows/actions.yml
  libtransmission/error-types.h
  libtransmission/file-capacity.cc
  libtransmission/file-win32.cc
  libtransmission/open-files.cc
  libtransmission/peer-mgr-active-requests.cc
  libtransmission/peer-msgs.cc
  libtransmission/platform.cc
  libtransmission/session-id.cc
  libtransmission/session-thread.cc
  libtransmission/session-thread.h
  libtransmission/subprocess-win32.cc
  libtransmission/tr-dht.cc
  libtransmission/utils.cc
  libtransmission/watchdir-win32.cc
  libtransmission/watchdir.cc
  libtransmission/web.cc
  release/windows/main.ps1
Labels: scope:infra, notes:none, type:ci

#6901 fix: `tr_variant_serde::parse_json()` bug fixes
  libtransmission/variant-json.cc
  tests/libtransmission/variant-test.cc
Labels: scope:core, type:fix, notes:none

#6683 fix: QT build missing an icon
  CMakeLists.txt
  dist/msi/CMakeLists.txt
  gtk/CMakeLists.txt
  gtk/icons/SOURCES.md
  gtk/transmission.gresource.xml
  gtk/transmission.rc
  icons/SOURCES.md
  icons/hamburger-menu.svg
  icons/hicolor_apps_scalable_transmission-devel.svg
  icons/hicolor_apps_scalable_transmission.svg
  icons/hicolor_apps_symbolic_transmission-symbolic.svg
  icons/lock.svg
  icons/options-symbolic.svg
  icons/ratio-symbolic.svg
  icons/transmission.ico
  icons/turtle-silhouette.svg
  icons/turtle.svg
  icons/yin-yang.svg
  qt/CMakeLists.txt
  qt/application.qrc
  qt/icons/lock.svg
  qt/icons/transmission.ico
  qt/icons/transmission.svg
  qt/icons/turtle-silhouette.svg
  qt/qtr.ico
Labels: scope:gtk, scope:qt, type:ui
