Repository transmission/transmission, pull requests merged in 2024-09, with the labels that each got.

#7086 fix: don't process http announce error if already succeeded
  libtransmission/announcer-http.cc
Labels: scope:core, type:fix, notes:highlight

#7096 Use "scale" cell renderer property to adjust file list font size
  gtk/FileList.cc
Labels: scope:gtk, semver:minor, type:a11y

#7097 Fix infinite loop when searching for missing torrents by id
  gtk/Session.cc
Labels: scope:gtk, type:fix, bug:regression, semver:patch

#6917 fix: various pex flag bugs and cleanup
  libtransmission/announcer.cc
  libtransmission/announcer.h
  libtransmission/peer-io.cc
  libtransmission/peer-io.h
  libtransmission/peer-mgr.cc
  libtransmission/peer-mgr.h
  libtransmission/peer-msgs.cc
  libtransmission/torrent.cc
  libtransmission/torrent.h
Labels: scope:core, type:fix, bep-compliance

#7113 chore: delete redundant `MainWindow.ui.full`
  gtk/ui/gtk4/MainWindow.ui.full
Labels: scope:gtk, notes:none, type:chore

#7116 fix: use correct quark for `Prefs::SHOW_TRACKER_SCRAPES`
  qt/Prefs.cc
Labels: scope:qt, type:fix, notes:none

#7117 chore: remove unused `TR_KEY_show_extra_peer_details` app default
  qt/Prefs.cc
Labels: scope:qt, notes:none, type:chore

#7119 GTK client accessibility improvements
  gtk/transmission-ui.css
  gtk/ui/gtk3/AddTrackerDialog.ui
  gtk/ui/gtk3/DetailsDialog.ui
  gtk/ui/gtk3/EditTrackersDialog.ui
  gtk/ui/gtk3/FilterBar.ui
  gtk/ui/gtk3/MainWindow.ui
  gtk/ui/gtk3/MakeDialog.ui
  gtk/ui/gtk3/MakeProgressDialog.ui
  gtk/ui/gtk3/MessageLogWindow.ui
  gtk/ui/gtk3/OptionsDialog.ui
  gtk/ui/gtk3/PrefsDialog.ui
  gtk/ui/gtk3/RelocateDialog.ui
  gtk/ui/gtk3/StatsDialog.ui
  gtk/ui/gtk3/TorrentUrlChooserDialog.ui
  gtk/ui/gtk4/AddTrackerDialog.ui
  gtk/ui/gtk4/DetailsDialog.ui
  gtk/ui/gtk4/EditTrackersDialog.ui
  gtk/ui/gtk4/MainWindow.ui
  gtk/ui/gtk4/MakeDialog.ui
  gtk/ui/gtk4/MessageLogWindow.ui
  gtk/ui/gtk4/OptionsDialog.ui
  gtk/ui/gtk4/PrefsDialog.ui
  gtk/ui/gtk4/RelocateDialog.ui
  gtk/ui/gtk4/StatsDialog.ui
  gtk/ui/gtk4/TorrentListItemFull.ui
  gtk/ui/gtk4/TorrentUrlChooserDialog.ui
Labels: scope:gtk, type:ui, semver:minor, type:a11y

#7115 fix: Use non-lib64 systemd system unit dir path
  daemon/CMakeLists.txt
Labels: os:linux, type:build, notes:none, semver:patch
