Repository transmission/transmission, pull requests merged in 2024-08, with the labels that each got.

#7049 chore: misc formatting updates and fixes
  .clang-format
  libtransmission/announcer-udp.cc
Labels: scope:infra, notes:none, type:chore

#7044 fix: `settings.json` default value and docs
  docs/Editing-Configuration-Files.md
  libtransmission/session.h
Labels: scope:core, scope:docs

#7020 Opt-in to secure coding explicitly
  macosx/Controller.mm
Labels: scope:mac

#7025 perf: avoid `std::advance` in cache.cc
  libtransmission/cache.cc
Labels: scope:core, type:perf, notes:none

#6990 fix: silence bugprone-unchecked-optional-access warnings
  libtransmission/file-posix.cc
Labels: notes:none

#6055 Fails with an error if data removal was not possible
  gtk/OptionsDialog.cc
  gtk/Session.cc
  libtransmission/rpcimpl.cc
  libtransmission/torrent-files.cc
  libtransmission/torrent-files.h
  libtransmission/torrent.cc
  libtransmission/torrent.h
  libtransmission/transmission.h
  libtransmission/utils.cc
  libtransmission/utils.h
  macosx/Torrent.mm
  tests/libtransmission/move-test.cc
  tests/libtransmission/rename-test.cc
  tests/libtransmission/rpc-test.cc
Labels: scope:gtk, scope:core, type:fix

#7059 Refactor async torrent removal logic
  gtk/Session.cc
  libtransmission/torrent-files.cc
  libtransmission/torrent.cc
  libtransmission/torrent.h
  libtransmission/transmission.h
  libtransmission/utils.cc
  libtransmission/utils.h
Labels: scope:gtk, scope:core, type:refactor

#7060 refactor: simplify addrinfo unique_ptr definition
  libtransmission/announcer-udp.cc
Labels: scope:core, type:refactor, notes:none

#7057 feat: log timestamps in local ISO8601 format
  libtransmission/log.cc
Labels: scope:core, type:feat

#7009 fix: accurate timestamp in daemon logs
  daemon/daemon.cc
  gtk/MessageLogWindow.cc
  libtransmission/log.cc
  libtransmission/log.h
  macosx/MessageWindowController.mm
Labels: scope:daemon, type:fix

#7040 docs: fix a link to send-email-when-torrent-done.sh script in Transmi…
  docs/Scripts.md
Labels: scope:docs, type:docs, notes:none

#6798 refactor: new `tr_variant` API in `transmission-remote` and other cleanup
  libtransmission/utils.cc
  libtransmission/utils.h
  libtransmission/variant.cc
  libtransmission/variant.h
  utils/remote.cc
Labels: scope:remote, scope:core, type:refactor, notes:none

#7014 fix: make name and hash readable
  web/assets/css/transmission-app.scss
  web/src/inspector.js
Labels: scope:web, type:ui

#7064 refactor: remove last byte special case in `tr_block_info::byte_loc()`
  libtransmission/block-info.h
  libtransmission/file-piece-map.cc
  libtransmission/torrent.cc
  tests/libtransmission/file-piece-map-test.cc
Labels: scope:core, type:refactor, notes:none

#7068 refactor: avoid `front()` prior to loop
  libtransmission/peer-mgr.cc
Labels: scope:core, type:refactor, notes:none

#7037 chore: misc WebUI fixes and cleanup
  web/src/open-dialog.js
  web/src/prefs-dialog.js
  web/src/transmission.js
Labels: scope:web, notes:none, type:chore

#6949 perf: lazy initialise Diffie-Hellman in handshake
  libtransmission/handshake.cc
  libtransmission/handshake.h
  libtransmission/peer-mse.cc
  libtransmission/peer-mse.h
  tests/libtransmission/crypto-test.cc
Labels: scope:core, type:perf, notes:none

#7030 feat: configurable client `reqq`
  docs/Editing-Configuration-Files.md
  docs/rpc-spec.md
  libtransmission/peer-mgr.cc
  libtransmission/peer-msgs.cc
  libtransmission/rpcimpl.cc
  libtransmission/session.h
  tests/libtransmission/rpc-test.cc
Labels: scope:core, type:feat, semver:minor

#6946 fix sort order of trackerStats keys within RPC doc
  docs/rpc-spec.md
Labels: closed:declined, scope:docs, type:docs, notes:none

#7076 Move Qt client's tr_main() into a separate file
  qt/Application.cc
  qt/Application.h
  qt/CMakeLists.txt
  qt/main.cc
Labels: scope:qt, type:refactor, semver:minor

#6875 fix: limit number of bad pieces to accept from a webseed
  libtransmission/peer-common.h
  libtransmission/peer-mgr.cc
  libtransmission/peer-msgs.cc
  libtransmission/peer-msgs.h
  libtransmission/webseed.cc
Labels: scope:core, type:fix

#6891 fix: add missing `write()` call in MSE handshake
  libtransmission/handshake.cc
Labels: scope:core, type:fix, notes:none

#6913 fix: process BT messages that immediately follows handshake
  libtransmission/handshake.cc
  libtransmission/handshake.h
  libtransmission/peer-io.cc
  libtransmission/peer-io.h
  libtransmission/peer-msgs.cc
Labels: scope:core, type:fix

#6989 build: enable clang-tidy by default (#4821)
  CMakeLists.txt
  android/build.gradle
Labels: type:build, needs notes
