Repository transmission/transmission, pull requests merged in 2024-05, with the labels that each got.

#6827 Avoiding &rarr; in UTF-8.
  docs/Why-is-my-port-closed.md
  macosx/TransmissionHelp/html/FAQ.html
  macosx/TransmissionHelp/html/check.html
  macosx/TransmissionHelp/html/gettingstarted.html
  macosx/TransmissionHelp/html/peers.html
  macosx/TransmissionHelp/html/pffirewall.html
  macosx/TransmissionHelp/html/pfrouter.html
  macosx/TransmissionHelp/html/portforward.html
  macosx/TransmissionHelp/html/remote.html
  macosx/TransmissionHelp/html/speed.html
  macosx/TransmissionHelp/html/tracker.html
  macosx/TransmissionHelp/html/usingt.html
Labels: scope:docs, type:docs

#6810 compatibility with libfmt v10.0.0
  gtk/Application.cc
  libtransmission/file-posix.cc
  libtransmission/variant-json.cc
Labels: type:build, notes:none

#6812 fix: missing #include in DetailsDialog.cc
  gtk/DetailsDialog.cc
Labels: scope:gtk, type:build

#6809 Expected white-space to come before width order/properties-alphabetical-order
  web/assets/css/transmission-app.scss
Labels: type:build, notes:none

#6819 Fix crash in printTorrentList
  libtransmission/variant.cc
Labels: scope:remote, type:fix

#6846 fix: escape single file torrent name
  libtransmission/torrent-metainfo.cc
Labels: scope:core, type:fix

#6823 [4.0.x] fix building with mbedtls 3.x
  libtransmission/crypto-utils-mbedtls.cc
Labels: type:build

#6779 chore: add Add <launchable> tag to GTK client metainfo (#6720)
  gtk/transmission-gtk.metainfo.xml.in
Labels: scope:gtk

#6844 fix: store seconds downloading/seeding when stopping torrent
  libtransmission/torrent.cc
Labels: scope:core, type:fix, semver:patch

#6802 removing temporary workaround for sanitizer crashes
  .github/workflows/actions.yml
Labels: notes:none, type:ci

#6761 chore: improved filterbar for narrowed viewports in web client
  web/assets/css/transmission-app.scss
  web/public_html/index.html
Labels: scope:web

#6784 Fix incorrect value for SortIncludes in .clang-format
  .clang-format
  third-party/.clang-format
Labels: notes:none, type:ci

#6791 Update outdated Doxygen params refs for tr_recentHistory
  libtransmission/history.h
Labels: scope:core, type:docs, notes:none

#6814 Building the QT app with CMake
  docs/Building-Transmission.md
Labels: type:docs

#6828 Avoiding "sec" as abbreviation
  macosx/TransmissionHelp/html/speed.html
  utils/transmission-remote.1
Labels: scope:docs, type:docs

#6815 fix: possible heap-use-after-free with magnet links
  libtransmission/torrent-magnet.cc
  libtransmission/torrent-magnet.h
  libtransmission/torrent.cc
  libtransmission/torrent.h
  tests/libtransmission/torrent-magnet-test.cc
Labels: scope:core, type:fix, scope:test, notes:none

#6789 Default initialize sleep callback duration in tr_verify_worker
  libtransmission/verify.h
Labels: scope:core

#6800 fir scripts, document usage of systemd overrides rather than changing…
  docs/Scripts.md
Labels: scope:docs

#6854 Support CMake 3.28+ in CI jobs on Windows
  .github/workflows/actions.yml
  release/windows/build-qt6.ps1
Labels: notes:none, type:ci

#6853 fix: restore portable file path check
  libtransmission/makemeta.cc
  libtransmission/makemeta.h
  libtransmission/resume.cc
  libtransmission/torrent-files.cc
  libtransmission/torrent-files.h
  libtransmission/torrent-metainfo.cc
  libtransmission/torrent-metainfo.h
  libtransmission/torrent.cc
  libtransmission/torrent.h
  macosx/QuickLookPlugin/GeneratePreviewForURL.mm
  tests/libtransmission/makemeta-test.cc
  tests/libtransmission/remove-test.cc
  tests/libtransmission/torrent-files-test.cc
  utils/create.cc
Labels: scope:core, type:fix, notes:none

#6781 add documentation key to systemd transmission-daemon.service
  daemon/transmission-daemon.service
Labels: scope:daemon, needs code review

#6822 fix building with mbedtls 3.X
  libtransmission/crypto-utils-mbedtls.cc
Labels: type:build

#6739 webui: fixed width for speed info
  web/assets/css/transmission-app.scss
  web/public_html/index.html
Labels: scope:web, type:ui, notes:none

#6786 Add virtual destructor to the polymorphic Settings class
  libtransmission/settings.h
Labels: scope:core, type:refactor, notes:none

#6858 build: temporarily disable macos-11 sanity checks
  .github/workflows/actions.yml
Labels: type:build, notes:none

#6845 fix: torrent details speed info unit
  utils/remote.cc
Labels: scope:remote, type:fix, notes:none

#6718 feat: allow port forwarding state to recover from error
  libtransmission/port-forwarding-natpmp.cc
  libtransmission/port-forwarding-upnp.cc
Labels: scope:core, type:feat, semver:minor

#6591 Recommended Project Settings
  Transmission.xcodeproj/project.pbxproj
  code_style.sh
Labels: scope:mac, type:build

#6613 rename "UpdateQueue" to "UpdateTorrentsState"
  macosx/Controller.mm
  macosx/FileOutlineController.mm
  macosx/PrefsController.mm
  macosx/Torrent.h
  macosx/Torrent.mm
Labels: scope:mac, type:refactor, notes:none

#6614 refactor: store peer info objects in shared pointers
  libtransmission/peer-mgr.cc
  libtransmission/peer-msgs.cc
  libtransmission/peer-msgs.h
Labels: scope:core, type:refactor, notes:none

#6700 feat: ipv6 lpd
  libtransmission/net.cc
  libtransmission/net.h
  libtransmission/tr-lpd.cc
  tests/libtransmission/lpd-test.cc
Labels: scope:core, type:feat, needs code review, bep-compliance

#6747 chore: resume file remove redundant `have` key and other cleanup
  libtransmission/resume.cc
Labels: scope:core, notes:none, type:chore

#6687 feat: dual stack udp tracker support
  libtransmission/announcer-common.h
  libtransmission/announcer-http.cc
  libtransmission/announcer-udp.cc
  libtransmission/announcer.cc
  libtransmission/announcer.h
  libtransmission/net.cc
  libtransmission/net.h
  libtransmission/tr-udp.cc
  libtransmission/web-utils.cc
  libtransmission/web-utils.h
  tests/libtransmission/announcer-udp-test.cc
Labels: scope:core, type:feat, scope:test, notes:highlight, bep-compliance, semver:minor

#6712 perf: restore 3.00 peer info (atom) pool pruning
  libtransmission/peer-mgr.cc
  libtransmission/peer-mgr.h
Labels: scope:core, type:perf, needs code review

#2947 remote: Implement idle seeding limits
  utils/remote.cc
  utils/transmission-remote.1
Labels: scope:remote, type:feat

#6869 fix: reset wishlist when stopping torrent
  libtransmission/peer-mgr.cc
Labels: scope:core, type:fix, notes:none
