Repository transmission/transmission, pull requests merged in 2024-02, with the labels that each got.

#6562 Fix clang-format const position
  gtk/MessageLogWindow.cc
Labels: notes:none

#6559 fix: base62 conversion in peer-id generation (#6486)
  update-version-h.sh
Labels: type:fix, type:build, notes:none

#6569 fix: various DHT bugs
  docs/Editing-Configuration-Files.md
  libtransmission/peer-msgs.cc
  libtransmission/session-settings.h
  libtransmission/session.h
  libtransmission/tr-dht.cc
  libtransmission/tr-dht.h
  tests/libtransmission/dht-test.cc
Labels: scope:core, type:fix, bep-compliance

#6549 perf: restore `3.00` wishlist with cached candidates
  libtransmission/peer-mgr-wishlist.cc
  libtransmission/peer-mgr-wishlist.h
  libtransmission/peer-mgr.cc
  libtransmission/torrent.cc
  libtransmission/torrent.h
  tests/libtransmission/peer-mgr-wishlist-test.cc
Labels: scope:core, type:perf, scope:test, needs code review

#6588 fix: right const
  libtransmission/settings.h
Labels: scope:core, notes:none

#6583 chore: crash report messages are now unsupported
  Transmission.xcodeproj/project.pbxproj
  libtransmission/CMakeLists.txt
  libtransmission/tr-assert.mm
Labels: os:mac, scope:core

#6465 Support multiple magnets on the same line
  macosx/Controller.mm
Labels: scope:mac

#6585 fix crash on empty filedescriptor after `accept`
  libtransmission/net.cc
Labels: scope:core, type:fix

#6589 perf: followup improvements to `3.00` Wishlist
  libtransmission/peer-mgr-wishlist.cc
  libtransmission/peer-mgr-wishlist.h
Labels: scope:core, type:perf

#6597 fix: clang-tidy-19 warnings
  libtransmission/announcer-http.cc
  libtransmission/announcer-udp.cc
  libtransmission/announcer.cc
  libtransmission/file-posix.cc
  libtransmission/global-ip-cache.cc
  libtransmission/open-files.cc
  libtransmission/peer-io.cc
  libtransmission/peer-mgr.cc
  libtransmission/peer-msgs.cc
  libtransmission/rpc-server.cc
  libtransmission/rpcimpl.cc
  libtransmission/session-id.cc
  libtransmission/session.cc
  libtransmission/torrent-ctor.cc
  libtransmission/torrent-metainfo.cc
  libtransmission/torrent.cc
  libtransmission/tr-assert.cc
  libtransmission/tr-dht.cc
  libtransmission/tr-lpd.cc
  libtransmission/tr-udp.cc
  libtransmission/utils.cc
  libtransmission/watchdir-inotify.cc
  libtransmission/web.cc
Labels: scope:core, type:fix, notes:none

#6592 refactor: libtransmission Settings
  Transmission.xcodeproj/project.pbxproj
  libtransmission/.clang-tidy
  libtransmission/CMakeLists.txt
  libtransmission/rpc-server.cc
  libtransmission/rpc-server.h
  libtransmission/session-alt-speeds.cc
  libtransmission/session-alt-speeds.h
  libtransmission/session-settings.cc
  libtransmission/session-settings.h
  libtransmission/session.cc
  libtransmission/session.h
  libtransmission/settings.cc
  libtransmission/settings.h
  libtransmission/variant-converters.cc
  libtransmission/variant.h
  tests/libtransmission/announce-list-test.cc
  tests/libtransmission/file-test.cc
  tests/libtransmission/settings-test.cc
Labels: scope:core, type:refactor, notes:none

#6601 add OS X 10.10 - macOS 10.12 compatibility to previous-releases
  docs/Previous-Releases.md
Labels: scope:mac, scope:docs

#6598 GTK: Add developer name (and screenshot caption) to metainfo
  gtk/transmission-gtk.metainfo.xml.in
Labels: scope:gtk

#6607 feat: WebUI add `Error` case in port test result
  web/src/prefs-dialog.js
Labels: scope:web, type:feat

#6604 fixup! perf: restore `3.00` wishlist with cached candidates (#6549)
  libtransmission/peer-mgr.cc
Labels: scope:core, type:fix, notes:none

#6611 remove old warning "doesn't like blank addresses"
  macosx/InfoTrackersViewController.mm
Labels: scope:mac, type:docs, notes:none

#6612 remove old warning: "subclass?"
  macosx/InfoPeersViewController.mm
Labels: scope:mac, type:docs, notes:none

#6608 fix: more clang-tidy warnings
  gtk/.clang-tidy
  gtk/DetailsDialog.cc
  gtk/DynamicPropertyStore.h
  gtk/FilterBar.cc
  gtk/FilterListModel.hh
  gtk/HigWorkarea.h
  gtk/MessageLogWindow.cc
  gtk/PrefsDialog.h
  gtk/Session.cc
  gtk/StatsDialog.cc
  gtk/Torrent.cc
  gtk/Utils.h
  qt/Application.cc
  qt/DetailsDialog.cc
  qt/FileTreeItem.cc
  qt/FileTreeView.cc
  qt/FilterBar.cc
  qt/InteropObject.cc
  qt/MakeDialog.cc
  qt/Prefs.cc
  qt/PrefsDialog.cc
  qt/Session.cc
  qt/Torrent.cc
  qt/TorrentFilter.cc
  qt/TrackerDelegate.cc
  qt/VariantHelpers.cc
  tests/libtransmission/handshake-test.cc
  tests/libtransmission/move-test.cc
  tests/libtransmission/torrent-magnet-test.cc
  tests/libtransmission/variant-test.cc
  tests/libtransmission/watchdir-test.cc
Labels: scope:gtk, scope:qt, type:fix, notes:none

#6616 fix clang-format
  qt/PrefsDialog.cc
Labels: scope:qt, notes:none

#6615 fix: sonarcloud warnings
  gtk/PrefsDialog.cc
  libtransmission/announcer-http.cc
  libtransmission/announcer.cc
  libtransmission/cache.h
  libtransmission/crypto-utils-mbedtls.cc
  libtransmission/crypto-utils-wolfssl.cc
  libtransmission/favicon-cache.h
  libtransmission/global-ip-cache.cc
  libtransmission/lru-cache.h
  libtransmission/peer-common.h
  libtransmission/peer-mgr-wishlist.cc
  libtransmission/rpc-server.h
  libtransmission/session-alt-speeds.h
  libtransmission/session.h
  libtransmission/verify.cc
  qt/PrefsDialog.cc
Labels: scope:gtk, scope:qt, scope:core

#6606 fix: don't consider peer info inactive if any of the time values is 0
  libtransmission/peer-mgr.h
Labels: scope:core, type:fix, notes:none

#6618 refactor: remove TR_PATH_DELIMITER
  libtransmission/session.h
  libtransmission/torrent.cc
  libtransmission/tr-macros.h
  tests/libtransmission/subprocess-test.cc
  tests/libtransmission/test-fixtures.h
  tests/libtransmission/watchdir-test.cc
Labels: scope:core, type:refactor, scope:test, notes:none

#6620 refactor: make tr_torrentReqIsValid() private
  libtransmission/peer-msgs.cc
  libtransmission/torrent.cc
  libtransmission/torrent.h
Labels: scope:core, type:refactor, notes:none

#6621 refactor: inline simple getters in qt client
  libtransmission/makelog
  qt/PathButton.cc
  qt/PathButton.h
  qt/RpcClient.cc
  qt/RpcClient.h
  qt/RpcQueue.h
  qt/Session.cc
  qt/Session.h
Labels: scope:qt, type:refactor, notes:none

#6622 chore: apply clang-format version 17.0.1 (#6054)
  libtransmission/net.cc
Labels: notes:none, type:chore

#6625 remove duplicate path: Transmission.xcodeproj
  .github/workflows/actions.yml
Labels: notes:none, type:ci

#6619 refactor: replace tr_sys_file_write_line() with fmt::print("...\n")
  daemon/daemon.cc
  daemon/daemon.h
  libtransmission/file-posix.cc
  libtransmission/file-win32.cc
  libtransmission/file.cc
  libtransmission/file.h
  libtransmission/log.cc
  tests/libtransmission/subprocess-test-program.cc
Labels: scope:daemon, scope:core, type:refactor, scope:test, needs code review, notes:none
