Repository transmission/transmission, pull requests merged in 2024-04, with the labels that each got.

#6599 qt: add dynamic RPC keys
  qt/Session.cc
  qt/Session.h
Labels: scope:qt, type:refactor, notes:none

#6610 feat(macos): added last known location
  macosx/Base.lproj/InfoGeneralView.xib
  macosx/InfoGeneralViewController.mm
  macosx/Torrent.h
  macosx/Torrent.mm
Labels: scope:mac, type:feat

#5102 Replace mac app default BindPort with a random port
  macosx/Controller.mm
  macosx/Defaults.plist
Labels: scope:mac, semver:minor

#6720 GTK: Add <launchable> tag to metainfo
  gtk/transmission-gtk.metainfo.xml.in
Labels: scope:gtk, notes:none

#6708 refactor: convert `tr_webseed` to C++ interface
  libtransmission/peer-mgr.cc
  libtransmission/webseed.cc
  libtransmission/webseed.h
Labels: scope:core, type:refactor, notes:none

#6788 Make std::hash specialization for tr_socket_address a struct
  libtransmission/net.h
Labels: scope:core, type:refactor, notes:none

#6787 Fix code style script path in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: type:docs, notes:none

#6790 doc: fix typo
  utils/transmission-remote.1
Labels: scope:docs, notes:none
