Repository transmission/transmission, pull requests merged in 2024-03, with the labels that each got.

#6656 refactor(web): Remove unused functions from utils.js
  web/src/utils.js
Labels: scope:web, notes:none, type:chore

#6657 fix(web): close connection failed alert on successful request
  web/src/remote.js
Labels: scope:web

#6647 refactor: remove tr_sys_file_flush()
  libtransmission/file-posix.cc
  libtransmission/file-win32.cc
  libtransmission/file.h
  tests/libtransmission/subprocess-test-program.cc
  tests/libtransmission/test-fixtures.h
Labels: scope:core, type:refactor, notes:none

#6666 ci: bump CI actions
  .github/workflows/actions.yml
  .github/workflows/codeql.yml
  .github/workflows/webapp.yml
Labels: scope:infra, notes:none, type:ci

#6664 refactor(web): extract mime icon creation to the helper
  web/src/torrent-row.js
Labels: scope:web, type:refactor, notes:none

#6662 refactor: aggregate crypto handles when computing digests
  Transmission.xcodeproj/project.pbxproj
  libtransmission/CMakeLists.txt
  libtransmission/crypto-utils-ccrypto.cc
  libtransmission/crypto-utils-mbedtls.cc
  libtransmission/crypto-utils-openssl.cc
  libtransmission/crypto-utils-wolfssl.cc
  libtransmission/crypto-utils.h
  libtransmission/handshake.cc
  libtransmission/inout.cc
  libtransmission/makemeta.cc
  libtransmission/verify.cc
  release/windows/build-openssl.ps1
  release/windows/build-qt6.ps1
  tests/libtransmission/CMakeLists.txt
  tests/libtransmission/crypto-test-ref.h
  tests/libtransmission/crypto-test.cc
Labels: scope:core, type:refactor, type:perf, notes:none

#6631 targeting clang-format version 17
  .github/workflows/actions.yml
  code_style.sh
Labels: type:chore, type:ci

#6649 refactor(web): use crypto.randomUUID for UUID if available
  web/src/utils.js
Labels: scope:web, type:refactor, notes:none

#6668 Support CMake 3.28+ in CI jobs on Windows
  .github/workflows/actions.yml
  release/windows/build-qt6.ps1
Labels: notes:none, type:ci

#6677 docs: fix `torrent-get` `fileStats` and `wanted` docs
  docs/rpc-spec.md
Labels: scope:docs, type:fix, type:docs

#6675 fix(web): do not close all popups on successful rpc requests
  web/src/remote.js
Labels: scope:web, type:fix, notes:none

#6590 build: fix building on macOS 10.14.6, 10.15.7 and 11.7
  libtransmission/block-info.h
  libtransmission/variant.h
Labels: scope:core, type:build

#6689 Support WiX toolset versions other than 3.11
  .github/workflows/actions.yml
  appveyor.yml
Labels: notes:none, semver:patch, type:ci

#5868 feat: webui use monochrome icons for play/pause buttons
  web/assets/img/pause-circle-active.svg
  web/assets/img/pause-circle-idle.svg
  web/assets/img/play-circle-active.svg
  web/assets/img/play-circle-idle.svg
Labels: scope:web, needs UI review, type:ui

#6698 fix multipleRatioLimits
  macosx/InfoOptionsViewController.mm
  macosx/Utils.h
Labels: scope:mac, bug:regression, notes:none

#5992 run peerMgrPeerStats in session thread
  libtransmission/peer-mgr.cc
Labels: scope:core, type:fix

#6580 refactor: convert `tr_peerMsgsImpl` helper functions to class methods
  libtransmission/handshake.cc
  libtransmission/magnet-metainfo.cc
  libtransmission/net.cc
  libtransmission/net.h
  libtransmission/peer-common.h
  libtransmission/peer-mgr-active-requests.cc
  libtransmission/peer-mgr-active-requests.h
  libtransmission/peer-mgr.cc
  libtransmission/peer-mgr.h
  libtransmission/peer-msgs.cc
  libtransmission/peer-msgs.h
  libtransmission/torrent-metainfo.cc
  libtransmission/torrent-metainfo.h
  libtransmission/webseed.cc
  libtransmission/webseed.h
  tests/libtransmission/completion-test.cc
Labels: scope:core, type:refactor, notes:none

#6667 refactor: allow Settings to register custom serializers / deserializers
  libtransmission/session-alt-speeds.h
  libtransmission/settings.cc
  libtransmission/settings.h
Labels: scope:core, type:refactor, notes:none

#6699 fix compatibility with clang-format 18 (#6690)
  qt/RpcClient.cc
  tests/libtransmission/dht-test.cc
  tests/libtransmission/timer-test.cc
Labels: notes:none

#6688 ci: trigger CI when changing CI definitions
  .github/workflows/actions.yml
Labels: scope:infra, notes:none, type:ci

#5263 fix: Sparkle Version Comparator
  CMakeLists.txt
  Transmission.xcodeproj/project.pbxproj
  libtransmission/version.h.in
  macosx/Base.lproj/PrefsWindow.xib
  macosx/CMakeLists.txt
  macosx/Controller.mm
  macosx/Info.plist.in
  macosx/PrefsController.mm
  macosx/VersionComparator.h
  macosx/VersionComparator.mm
  update-version-h.sh
Labels: scope:mac, needs code review, semver:patch

#6695 feat: periodically refresh dht node id
  libtransmission/quark.cc
  libtransmission/quark.h
  libtransmission/tr-dht.cc
  tests/libtransmission/dht-test.cc
Labels: scope:core, type:feat, scope:test

#6629 Add torrent priority to completion script environment variables
  docs/Scripts.md
  libtransmission/torrent.cc
Labels: scope:core

#6726 KeepEmptyLinesAtTheStartOfBlocks: false
  .clang-format
  gtk/OptionsDialog.cc
  libtransmission/peer-mgr.cc
  libtransmission/tr-dht.cc
Labels: type:refactor, notes:none

#6717 fix: misc net.cc and blocklist.cc fixes
  libtransmission/announcer-http.cc
  libtransmission/blocklist.cc
  libtransmission/net.cc
  libtransmission/net.h
  libtransmission/peer-io.cc
  libtransmission/peer-mgr.cc
  libtransmission/peer-mgr.h
Labels: scope:core, type:fix, notes:none

#6586 feat: µTP delayed ack
  libtransmission/session.cc
  libtransmission/tr-udp.cc
  libtransmission/tr-utp.cc
  libtransmission/tr-utp.h
Labels: scope:core, type:feat

#6722 Disable a long-lived and recurrent flaky test
  tests/libtransmission/lpd-test.cc
  tests/libtransmission/timer-test.cc
  tests/libtransmission/watchdir-test.cc
Labels: scope:test

#6725 fix: mismatched `class` forward declaration for `struct tr_peer`
  tests/libtransmission/peer-mgr-active-requests-test.cc
Labels: type:fix, scope:test, notes:none

#6617 add macos-11 to actions.yml
  .github/workflows/actions.yml
Labels: scope:mac, type:ci

#6735 fix: more misc `net.cc` fixes
  libtransmission/net.cc
  libtransmission/tr-udp.cc
  libtransmission/web-utils.cc
  tests/libtransmission/announcer-test.cc
  tests/libtransmission/net-test.cc
  tests/libtransmission/web-utils-test.cc
Labels: scope:core, type:fix, scope:test, notes:none

#6743 Win32 compatibility for get_peer_stats
  libtransmission/peer-mgr.cc
Labels: bug:regression, notes:none

#6759 fix shadowed declaration warnings [-Wshadow]
  libtransmission/settings.h
Labels: scope:core, notes:none, type:chore

#6751 fix: assert failure when moving torrents to bottom of the queue
  libtransmission/torrent.cc
Labels: scope:core, type:fix, notes:none

#6738 refactor: remove torrent_view virtual class
  libtransmission/completion.cc
  libtransmission/completion.h
  libtransmission/torrent.h
  tests/libtransmission/completion-test.cc
  tests/libtransmission/lpd-test.cc
  tests/libtransmission/watchdir-test.cc
Labels: scope:core, type:refactor, notes:none

#6750 fix: invalid socket address in `tr_peerIo::reconnect()`
  libtransmission/handshake.cc
  libtransmission/peer-io.cc
Labels: scope:core, type:fix, notes:none

#6728 Add start_paused to settings file and daemon
  daemon/daemon.cc
  daemon/daemon.h
  docs/Editing-Configuration-Files.md
  libtransmission/quark.cc
  libtransmission/quark.h
Labels: scope:daemon

#6623 fix: Sparkle Version Comparator (#5263)
  CMakeLists.txt
  Transmission.xcodeproj/project.pbxproj
  libtransmission/version.h.in
  macosx/Base.lproj/PrefsWindow.xib
  macosx/CMakeLists.txt
  macosx/Controller.mm
  macosx/Info.plist.in
  macosx/PrefsController.mm
  macosx/VersionComparator.h
  macosx/VersionComparator.mm
  update-version-h.sh
Labels: scope:mac, semver:patch

#6570 fix(web): don't use 2 rows for upload/download speed info
  web/assets/css/transmission-app.scss
Labels: scope:web

#6723 fix: restore loose data type parsing in RPC and `settings.json`
  libtransmission/rpcimpl.cc
  libtransmission/session.cc
  libtransmission/settings.cc
  libtransmission/variant.cc
  libtransmission/variant.h
Labels: scope:core, type:fix, notes:none

#6745 Disable restartWithDifferentInterval for all platforms
  tests/libtransmission/timer-test.cc
Labels: scope:test, notes:none

#6746 fix: save sequential download across sessions
  libtransmission/resume.cc
  libtransmission/resume.h
  libtransmission/torrent.h
Labels: scope:core, type:fix, notes:none

#6715 re-enabling ubuntu tests
  .github/workflows/actions.yml
Labels: type:ci

#6626 support macos-14 universal builds in CI
  .github/workflows/actions.yml
Labels: scope:mac, type:ci

#6600 doc: no need to adopt an alternative to VDKQueue
  macosx/VDKQueue/VDKQueue.h
  macosx/VDKQueue/VDKQueue.mm
Labels: scope:mac, type:docs, notes:none

#6578 feat: support "torrent" in Spotlight indexation
  macosx/en.lproj/InfoPlist.strings
Labels: scope:mac, needs notes

#6672 feat: support different internal and external port for UPnP
  libtransmission/port-forwarding-upnp.cc
  libtransmission/port-forwarding-upnp.h
  libtransmission/port-forwarding.cc
  libtransmission/port-forwarding.h
  libtransmission/session.h
Labels: scope:core, type:feat, notes:none
