Repository transmission/transmission, pull requests merged in 2024-10, with the labels that each got.

#7110 Clarify that torrent ids are not stable
  docs/rpc-spec.md
Labels: scope:docs, type:docs, notes:none

#7120 Clarify file order and indexes
  docs/rpc-spec.md
Labels: type:docs

#7136 fix: calculate size of one hash line in lpd correctly
  libtransmission/tr-lpd.cc
Labels: scope:core, type:fix, notes:none

#6753 feat: save queue order between sessions
  libtransmission/quark.cc
  libtransmission/quark.h
  libtransmission/resume.cc
  libtransmission/resume.h
  libtransmission/torrent.cc
  libtransmission/torrent.h
Labels: scope:core, type:feat, semver:minor

#6922 refactor: improve criteria for choosing peers to save to resume
  libtransmission/peer-mgr.cc
Labels: scope:core, type:refactor, notes:none

#7018 remove TR_ASSERT(now >= latest)
  libtransmission/torrent.h
Labels: scope:core

#7159 Delete web/public_html/transmission-app.css
  web/public_html/index.html
  web/public_html/transmission-app.css
Labels: scope:web, type:fix

#7143 fix: update torrent progress when verifying partially completed pieces
  libtransmission/torrent.cc
Labels: scope:core, type:fix

#7089 perf: don't open torrent file descriptors with `TR_SYS_FILE_SEQUENTIAL`
  libtransmission/open-files.cc
Labels: scope:core, type:perf, semver:patch

#7072 fixup! fix: update partial file suffix after verifying torrent (#6871)
  libtransmission/torrent.h
Labels: scope:core, type:fix, notes:none

#7184 fix: code should be clang-formatted
  gtk/FilterBase.h
  gtk/SorterBase.h
  qt/DetailsDialog.cc
Labels: notes:none

#7181 fix: check `tr_num_parse` result in daemon
  daemon/daemon.cc
Labels: scope:daemon, type:fix, notes:none

#6950 fix: properly reconnect on handshake error
  libtransmission/handshake.cc
  libtransmission/peer-io.cc
  libtransmission/peer-io.h
Labels: scope:core, type:fix

#6992 fix: `date done` and `recently-active` not updated on state change
  libtransmission/torrent.cc
  libtransmission/torrent.h
Labels: scope:core, type:fix

#7036 fix(web): pressing the enter key now submits dialogs
  web/src/open-dialog.js
  web/src/utils.js
Labels: scope:web, type:fix, needs notes

#6872 correct "Queue for download" last activity
  qt/DetailsDialog.cc
Labels: scope:qt, type:fix, needs code review, needs notes

#7187 fix: clang-tidy-20 warnings
  libtransmission/announcer.cc
  libtransmission/bandwidth.cc
  libtransmission/bitfield.cc
  libtransmission/crypto-utils.cc
  libtransmission/handshake.cc
  libtransmission/peer-mgr-active-requests.cc
  libtransmission/peer-mgr.cc
  libtransmission/peer-mse.cc
  libtransmission/session-alt-speeds.cc
  libtransmission/session.cc
  libtransmission/torrent-ctor.cc
Labels: scope:core, semver:patch

#7088 feat: clear the badge when quitting app
  macosx/Controller.mm
Labels: scope:mac, type:feat, type:ui

#7192 fix: clang-tidy-20 warnings in transmission-qt
  qt/FileTreeModel.cc
  qt/FileTreeView.cc
  qt/PathButton.cc
  qt/SqueezeLabel.cc
  qt/Torrent.h
  qt/TorrentDelegate.cc
  qt/TorrentDelegateMin.cc
  qt/TrackerDelegate.cc
  qt/VariantHelpers.cc
Labels: scope:qt, type:fix, notes:none

#7028 fix: count webseeds when calculating piece replication
  libtransmission/peer-mgr.cc
Labels: scope:core, type:fix, notes:none

#7141 fix: clear tracker error if tracker is removed
  libtransmission/torrent.cc
Labels: scope:core, type:fix, semver:patch

#7203 refactor: warn peer incompliant behaviour in ltep
  libtransmission/peer-msgs.cc
Labels: scope:core, type:refactor, notes:none

#7199 fix: always sort peer candidates by score
  libtransmission/peer-mgr.cc
Labels: scope:core, type:fix, notes:none

#7198 ci: automatically regenerate `package.json.buildonly`
  .github/workflows/webapp.yml
  web/generate-buildonly.js
  web/package.json
Labels: scope:web, notes:none, type:ci

#7207 refactor: remove unused TR_SYS_FILE_LOCK_UN
  libtransmission/file-posix.cc
  libtransmission/file-win32.cc
  libtransmission/file.h
Labels: scope:core, type:refactor, notes:none

#7206 refactor: remove unused TR_SYS_FILE_APPEND
  libtransmission/file-posix.cc
  libtransmission/file-win32.cc
  libtransmission/file.h
  tests/libtransmission/file-test.cc
Labels: scope:core, type:refactor, notes:none

#5937 feat: display percent in progress bar for web client
  web/assets/css/transmission-app.scss
  web/src/file-row.js
  web/src/formatter.js
  web/src/inspector.js
  web/src/torrent-row.js
  web/src/torrent.js
Labels: scope:web, type:feat

#7209 chore: convert `transmission-web` to ES module
  web/.eslintrc.cjs
  web/package.json
  web/prettier.config.cjs
  web/stylelint.config.cjs
Labels: scope:web, notes:none

#7210 build: fail if clang-tidy is not found when `-DRUN_CLANG_TIDY=ON`
  CMakeLists.txt
Labels: scope:infra, type:build, notes:none
