Repository transmission/transmission, pull requests merged in 2024-11, with the labels that each got.

#7218 fix: add missing `settings.json` docs and app defaults
  daemon/daemon.cc
  docs/Editing-Configuration-Files.md
Labels: scope:daemon, type:fix, notes:none

#7214 fix: support nodejs below v20.11 for `generate_buildonly.js`
  web/generate-buildonly.js
Labels: scope:web, type:fix, notes:none

#7216 fix: save resume when shutting down
  libtransmission/torrent.cc
Labels: scope:core, type:fix

#7226 Crash fix: "Invalid parameter not satisfying: aString != nil"
  macosx/InfoGeneralViewController.mm
Labels: scope:mac, type:fix, notes:none

#7219 build: accept false constant other than `OFF` for `REBUILD_WEB`
  CMakeLists.txt
Labels: scope:infra, type:build, notes:none

#7235 fix: don't double count webseed download data rate
  libtransmission/session.cc
  libtransmission/session.h
  libtransmission/web.cc
  libtransmission/web.h
Labels: scope:core, type:fix

#7233 refactor: set `CURLOPT_MAXREDIRS` once
  libtransmission/web.cc
Labels: scope:core, type:refactor, notes:none

#7238 fix: don't increment failure count when stopping torrent
  libtransmission/peer-mgr.h
  libtransmission/peer-msgs.cc
Labels: scope:core, type:fix, notes:none

#6975 fix: allow unreachable peers to be retried
  libtransmission/peer-mgr.cc
Labels: scope:core, type:fix, notes:none

#7027 refactor: faster wishlist
  Transmission.xcodeproj/project.pbxproj
  libtransmission/CMakeLists.txt
  libtransmission/peer-common.h
  libtransmission/peer-io.cc
  libtransmission/peer-io.h
  libtransmission/peer-mgr-active-requests.cc
  libtransmission/peer-mgr-active-requests.h
  libtransmission/peer-mgr-wishlist.cc
  libtransmission/peer-mgr-wishlist.h
  libtransmission/peer-mgr.cc
  libtransmission/peer-mgr.h
  libtransmission/peer-msgs.cc
  libtransmission/torrent.h
  libtransmission/webseed.cc
  tests/libtransmission/CMakeLists.txt
  tests/libtransmission/peer-mgr-active-requests-test.cc
  tests/libtransmission/peer-mgr-wishlist-test.cc
Labels: scope:core, type:refactor, type:perf

#7228 fix: clang-tidy header warnings, pt. 1
  libtransmission/bandwidth.h
  libtransmission/cache.h
  libtransmission/error-types.h
  libtransmission/file.h
  libtransmission/handshake.h
  libtransmission/log.h
  libtransmission/open-files.h
  libtransmission/peer-common.h
  libtransmission/peer-io.h
  libtransmission/peer-mse.h
  libtransmission/port-forwarding-natpmp.h
  libtransmission/session-alt-speeds.h
  libtransmission/torrent-ctor.h
  libtransmission/torrent-metainfo.h
  libtransmission/torrent.h
  libtransmission/tr-popcount.h
  libtransmission/utils.h
  libtransmission/values.h
  libtransmission/variant.h
  libtransmission/watchdir-base.h
  libtransmission/web.h
Labels: scope:qt, scope:core, type:fix, notes:none

#7242 ci: test `REBUILD_WEB=ON`
  .github/workflows/actions.yml
Labels: scope:infra, notes:none, type:ci

#7254 fix: macOS CI
  .github/workflows/actions.yml
Labels: type:ci

#7252 fix: CI errors related to `REBUILD_WEB`
  .github/workflows/actions.yml
  CMakeLists.txt
Labels: scope:infra, type:build, notes:none, type:ci

#7266 refactor: use string_view literals instead of C string literals
  libtransmission/variant.cc
Labels: scope:core, type:refactor, notes:none
