Repository transmission/transmission, pull requests merged in 2024-12, with the labels that each got.

#7282 chore: add 4.0.5 and 4.0.6 release notes to main branch
  README.md
  news/news-4.0.5.md
  news/news-4.0.6.md
Labels: scope:docs, type:docs, notes:none

#7279 fix: utilize gigabyte per second to conserve space and upload arrow clipping fix
  web/assets/css/transmission-app.scss
  web/src/formatter.js
Labels: scope:web, type:ui

#7275 CI: updrading deprecated macOS 12 to macOS 13
  .github/workflows/actions.yml
Labels: notes:none, type:ci

#7271 refactor: remove `tr_torrent::do_magnet_idle_work()`
  libtransmission/torrent-magnet.cc
  libtransmission/torrent-magnet.h
  libtransmission/torrent.cc
  libtransmission/torrent.h
  tests/libtransmission/torrent-magnet-test.cc
Labels: scope:core, type:refactor, notes:none

#7258 fix: handle nullptr in json serde
  libtransmission/variant-json.cc
  tests/libtransmission/json-test.cc
Labels: scope:core, type:fix, notes:none

#7273 ci: remove macos pkgconf workaround
  .github/workflows/actions.yml
Labels: scope:infra, notes:none, type:ci

#7268 test: use new `tr_variant` API
  libtransmission/variant.h
  tests/libtransmission/dht-test.cc
  tests/libtransmission/json-test.cc
  tests/libtransmission/makemeta-test.cc
  tests/libtransmission/move-test.cc
  tests/libtransmission/rpc-test.cc
  tests/libtransmission/session-test.cc
  tests/libtransmission/settings-test.cc
  tests/libtransmission/test-fixtures.h
  tests/libtransmission/variant-test.cc
Labels: type:refactor, scope:test, notes:none

#7001 refactor: parse cookie pref values as their default values types
  web/src/prefs.js
  web/src/transmission.js
Labels: scope:web, type:refactor, notes:none

#7204 fix: send ltep handshake if received ltep handshake
  libtransmission/peer-msgs.cc
Labels: scope:core, type:fix, notes:none

#7114 feat: log when RPC server reject requests
  libtransmission/rpc-server.cc
Labels: scope:core, type:feat, semver:minor

#7102 Feature/default focus
  gtk/DetailsDialog.cc
  gtk/OptionsDialog.cc
  gtk/ui/gtk3/AddTrackerDialog.ui
  gtk/ui/gtk3/TorrentUrlChooserDialog.ui
  gtk/ui/gtk4/AddTrackerDialog.ui
  gtk/ui/gtk4/TorrentUrlChooserDialog.ui
Labels: scope:gtk, type:fix, semver:patch

#7251 Adjust slider limits in GTK
  gtk/MakeDialog.cc
Labels: scope:gtk, feature disparity, type:feat, type:ui

#7288 docs: add 4.1.0-beta.1 notes
  CMakeLists.txt
  news/news-4.1.0-beta.1.md
Labels: type:docs, notes:none

#7289 Fix MacStadium opensource URL
  README.md
Labels: type:docs

#7112 refactor: use evhttp public accessors in rpc server
  libtransmission/rpc-server.cc
Labels: scope:core, type:refactor, notes:none

#6893 feat: download first and last piece first in sequential mode
  libtransmission/peer-mgr-wishlist.cc
  tests/libtransmission/peer-mgr-wishlist-test.cc
Labels: scope:core, type:feat

#6966 handshake: add fire_timer() explicitly instead of overloading fire_done()
  libtransmission/handshake.cc
  libtransmission/handshake.h
Labels: scope:core, type:refactor, notes:none

#7255 feat: support the JSON `null` type in `tr_variant`
  libtransmission/variant-benc.cc
  libtransmission/variant-json.cc
  libtransmission/variant.cc
  libtransmission/variant.h
  tests/libtransmission/json-test.cc
Labels: scope:core, type:feat, notes:none

#7092 qt: refactor Application
  qt/Application.cc
  qt/Application.h
Labels: scope:qt, type:refactor

#7051 feat: contract main area for inspector for large viewports
  web/assets/css/transmission-app.scss
  web/src/inspector.js
Labels: scope:web, type:ui

#7313 fix: Take into account only the private that is inside info.
  libtransmission/torrent-metainfo.cc
Labels: scope:core, type:fix, bep-compliance, semver:patch, needs notes

#7305 fix: shadowed variable warning in `tr_torrentVerify()`
  libtransmission/torrent.cc
Labels: scope:core, type:fix, notes:none

#7326 fix: check full path when parsing http tracker responses
  libtransmission/announcer-http.cc
  libtransmission/benc.h
  libtransmission/torrent-metainfo.cc
Labels: scope:core, type:fix, bep-compliance

#7247 Fixing bug in new torrent options dialog
  gtk/OptionsDialog.cc
Labels: scope:gtk, type:fix, semver:patch

#7310 refactor: multiple popups code refinement
  web/src/transmission.js
Labels: scope:web, type:refactor, notes:none

#7195 fix: use process umask for new files.
  libtransmission/utils.cc
Labels: scope:core, type:fix

#7340 fix(webui): dispatch `close` events when closing popups
  web/src/prefs-dialog.js
  web/src/statistics-dialog.js
Labels: scope:web, type:fix, notes:none

#7339 fix: speed limits did not work below 16KiB/s
  libtransmission/bandwidth.cc
  libtransmission/bandwidth.h
  libtransmission/peer-io.cc
  libtransmission/peer-io.h
  libtransmission/peer-socket.h
  libtransmission/webseed.cc
Labels: scope:core, type:fix

#6945 refactor: alternative x/y coords to account for zoomed in browser
  web/src/transmission.js
Labels: scope:web, type:ui, notes:none

#6914 refactor: convert `tr_net_init_mgr` to singleton
  cli/cli.cc
  daemon/daemon.cc
  gtk/main.cc
  libtransmission/utils.cc
  libtransmission/utils.h
  macosx/main.mm
  qt/main.cc
  tests/libtransmission/announcer-udp-test.cc
  tests/libtransmission/dht-test.cc
  tests/libtransmission/test-fixtures.h
  tests/libtransmission/watchdir-test.cc
  utils/remote.cc
  utils/show.cc
Labels: scope:cli, scope:daemon, scope:remote, scope:show, scope:gtk, scope:qt, scope:mac, scope:core, type:refactor, scope:test, notes:none

#7345 fix: cert-oop54-cpp warnings about self-assignment in strbuf
  libtransmission/tr-strbuf.h
Labels: scope:core, type:refactor, notes:none

#7311 refactor: pointer device listener code refinement
  web/src/transmission.js
Labels: scope:web

#7336 fix: use `grid` CSS to resolve the inflating rows by long torrent names in compact view
  web/assets/css/transmission-app.scss
Labels: scope:web, type:fix, type:ui

#7346 fix(web): enable/disable textbox when session changed
  web/src/prefs-dialog.js
Labels: scope:web, type:fix, type:ui
