Repository transmission/transmission, pull requests merged in 2024-06, with the labels that each got.

#6861 fix: cert-err58 warning in GTK client
  gtk/SystemTrayIcon.cc
Labels: scope:gtk, type:fix, notes:none

#6874 libtransmission: fix copyright header generation
  libtransmission/mime-types.h
  libtransmission/mime-types.js
Labels: type:docs, notes:none

#6881 fix: don't call `tr_logAddTraceIo` before `tr_peerIo::set_socket()`
  libtransmission/net.cc
  libtransmission/peer-io.cc
Labels: scope:core, type:fix, notes:none

#6665 refactor: cleanup build for miniupnp
  CMakeLists.txt
  Transmission.xcodeproj/project.pbxproj
  cmake/FindMINIUPNPC.cmake
  libtransmission/CMakeLists.txt
  libtransmission/port-forwarding-upnp.cc
Labels: scope:core, type:build

#6834 refactor: harden idle_seconds
  libtransmission/torrent.cc
  libtransmission/torrent.h
Labels: scope:core, type:refactor, notes:none

#6871 fix: update partial file suffix after verifying torrent
  libtransmission/torrent.cc
  libtransmission/torrent.h
  tests/libtransmission/move-test.cc
  tests/libtransmission/rename-test.cc
Labels: scope:core, type:fix

#6890 Remove warning "don't cut off end"
  macosx/MessageWindowController.mm
Labels: scope:mac, type:chore

#6774 build with -latomic on platforms that need it
  cmake/CheckAtomic.cmake
  libtransmission/CMakeLists.txt
Labels: type:build

#6908 fix compile error: no matching function for call to ‘flock::flock‘
  libtransmission/file-posix.cc
Labels: scope:core, type:fix, semver:patch

#6923 ci: bump `clang-tidy` from 14 to 18
  .github/workflows/actions.yml
  libtransmission/announcer-udp.cc
Labels: scope:infra, notes:none, type:ci

#6919 docs: fix default value in docs
  docs/Editing-Configuration-Files.md
Labels: scope:docs, type:docs, notes:none

#6920 fix: restore tr_optind in all getConfigDir branches
  cli/cli.cc
Labels: scope:cli, type:fix, bug:regression, semver:patch
