Repository transmission/transmission, pull requests merged in 2025-05, with the labels that each got.

#7555 Google-Glasnost was shut down in 2017
  docs/Why-Are-My-Speeds-So-Slow.md
Labels: type:docs

#7549 docs: use Qt6 in Windows build instructions
  docs/Building-Transmission.md
Labels: os:windows, scope:docs, type:docs, notes:none

#7571 build: support different install prefixes for daemon service file
  daemon/CMakeLists.txt
  daemon/transmission-daemon.service.in
Labels: scope:daemon, type:build

#7486 feat: make `proxy_url` nullable
  docs/Editing-Configuration-Files.md
  libtransmission/session.cc
  libtransmission/session.h
  libtransmission/settings.cc
  libtransmission/web.cc
  libtransmission/web.h
  tests/libtransmission/settings-test.cc
Labels: scope:core, type:feat

#7496 refactor: announcer code housekeeping
  libtransmission/announcer-common.h
  libtransmission/announcer-http.cc
  libtransmission/announcer-udp.cc
  libtransmission/announcer.cc
  tests/libtransmission/announcer-test.cc
  tests/libtransmission/announcer-udp-test.cc
Labels: scope:core, type:refactor, notes:none

#7582 Simplify logic around gettext/libintl use
  .github/workflows/actions.yml
  libtransmission/CMakeLists.txt
  libtransmission/utils.h
Labels: scope:core, i18n, type:build

#7586 chore: silence clang-tidy warnings
  libtransmission/cache.cc
  libtransmission/cache.h
  libtransmission/peer-mgr-wishlist.cc
Labels: scope:core, notes:none, type:chore

#7519 docs: recommend to keep the cache small
  docs/Editing-Configuration-Files.md
Labels: scope:docs, type:docs, notes:none

#7529 build: tell clang-tidy to suggest uppercase literal suffixes
  gtk/.clang-tidy
  libtransmission/.clang-tidy
  qt/.clang-tidy
  tests/libtransmission/.clang-tidy
Labels: scope:infra, type:build, notes:none

#7535 fix(remote): print label separators correctly
  utils/remote.cc
Labels: scope:remote, type:fix, notes:none

#7588 chore: move `.gitattributes` to root of repository
  .gitattributes
  web/.gitattributes
Labels: notes:none, type:chore

#7590 fix: remove duplicated mime types and prefer iana source
  libtransmission/mime-types.h
  libtransmission/mime-types.js
Labels: scope:core, type:fix, notes:none
