Repository transmission/transmission, pull requests merged in 2025-03, with the labels that each got.

#7457 feat: warn about problematic curl versions
  libtransmission/web.cc
Labels: scope:core, type:feat, notes:none

#7447 fix: not correctly sending UA to trackers related to curl gh6312
  libtransmission/web.cc
Labels: scope:core, type:fix, needs notes

#7355 refactor: set peer io socket in constructor
  libtransmission/net.cc
  libtransmission/net.h
  libtransmission/peer-io.cc
  libtransmission/peer-io.h
  libtransmission/peer-socket.h
  libtransmission/session.h
  libtransmission/settings.cc
  tests/libtransmission/handshake-test.cc
  tests/libtransmission/settings-test.cc
Labels: scope:core, type:refactor

#7461 perf: cache curl version
  libtransmission/web.cc
Labels: scope:core, type:perf, notes:none

#7443 refactor: remove builtin and asm popcount implementation
  libtransmission/tr-popcount.h
Labels: scope:core, type:fix

#7354 refactor: drop className `.full` in favor of `:not(.compact)`
  web/assets/css/transmission-app.scss
  web/src/torrent-row.js
Labels: scope:web, type:refactor, notes:none

#7351 refactor: fix modernize-use-nodiscard warnings by adding [[nodiscard]]
  libtransmission/benc.h
  qt/AddData.h
  qt/DBusInteropHelper.h
  qt/FileTreeDelegate.h
  qt/FileTreeModel.h
  qt/FileTreeView.h
  qt/FilterBarComboBox.h
  qt/FilterBarComboBoxDelegate.h
  qt/Filters.h
  qt/IconToolButton.h
  qt/InteropHelper.h
  qt/InteropObject.h
  qt/MainWindow.h
  qt/MakeDialog.h
  qt/PathButton.h
  qt/Torrent.h
  qt/TorrentFilter.h
  qt/TrackerDelegate.h
  qt/TrackerModel.h
  qt/TrackerModelFilter.h
  qt/WatchDir.h
  tests/libtransmission/test-fixtures.h
Labels: scope:qt, scope:core, type:refactor, scope:test, notes:none

#7466 fix: bugprone-exception-escape warning in `Variant::make_map()`
  libtransmission/variant.h
Labels: scope:core, type:fix, notes:none

#7177 fix: use message id to check for pex and metadata xfer support
  libtransmission/peer-msgs.cc
Labels: scope:core, type:fix, notes:none

#7468 refactor: remove `TR_ARG_TUPLE()` macro
  cli/cli.cc
  libtransmission/tr-macros.h
  qt/Prefs.cc
Labels: scope:core, type:refactor, notes:none

#7394 feat: error rename alert message
  web/src/rename-dialog.js
Labels: scope:web, type:feat

#7469 refactor: remove `TR_LIKELY` and `TR_UNLIKELY` macros
  libtransmission/tr-assert.h
  libtransmission/tr-macros.h
Labels: scope:core, type:refactor, notes:none

#7470 refactor: remove unused macro `TR_UNREACHABLE`
  libtransmission/tr-assert.h
Labels: scope:core, type:refactor, notes:none

#7471 refactor: simplify TR_CONSTEXPR20 macro
  libtransmission/tr-macros.h
Labels: scope:core, type:refactor, notes:none

#7462 refactor: remove the test to see if curl is at least 7.15.6
  libtransmission/web.cc
Labels: scope:core, type:refactor, notes:none

#6892 refactor: store peers as benc in resume file
  libtransmission/peer-mgr.cc
  libtransmission/peer-mgr.h
  libtransmission/quark.cc
  libtransmission/quark.h
  libtransmission/resume.cc
Labels: scope:core, type:refactor, notes:none

#7167 feat: disconnect blocklisted peers on blocklist update
  libtransmission/peer-mgr.cc
Labels: scope:core, type:fix

#7332 refactor: dedicated class for torrent queue
  Transmission.xcodeproj/project.pbxproj
  libtransmission/CMakeLists.txt
  libtransmission/quark.cc
  libtransmission/quark.h
  libtransmission/resume.cc
  libtransmission/resume.h
  libtransmission/session.cc
  libtransmission/session.h
  libtransmission/torrent-metainfo.cc
  libtransmission/torrent-metainfo.h
  libtransmission/torrent-queue.cc
  libtransmission/torrent-queue.h
  libtransmission/torrent.cc
  libtransmission/torrent.h
  tests/libtransmission/CMakeLists.txt
  tests/libtransmission/torrent-queue-test.cc
Labels: scope:core, type:refactor, semver:minor

#7029 refactor: respond immediately to block requests from peer
  libtransmission/peer-msgs.cc
Labels: scope:core, type:refactor

#7034 fix(remote): failure reason should be printed
  utils/remote.cc
Labels: scope:remote, type:fix, needs notes

#6947 fix: abort handshake if the torrent is stopped
  libtransmission/handshake.cc
  libtransmission/handshake.h
  libtransmission/peer-mgr.cc
  tests/libtransmission/handshake-test.cc
Labels: scope:core, type:fix, notes:none

#6973 refactor: save outgoing `len(PadA)`, `len(PadB)` and `len(IA)`
  libtransmission/handshake.cc
  libtransmission/handshake.h
Labels: scope:core, type:refactor, notes:none

#7047 feat: sequential download in `settings.json` `torrent-add` and `sesssion-*` RPC methods
  docs/Editing-Configuration-Files.md
  docs/rpc-spec.md
  libtransmission/resume.cc
  libtransmission/rpcimpl.cc
  libtransmission/session.h
  libtransmission/torrent-ctor.h
  libtransmission/torrent.cc
  tests/libtransmission/rpc-test.cc
Labels: scope:core, type:feat, semver:minor

#6832 Fix building transmission with C++23
  .github/workflows/actions.yml
  CMakeLists.txt
  daemon/daemon.cc
  gtk/Application.cc
  gtk/DetailsDialog.cc
  gtk/Dialogs.cc
  gtk/FileList.cc
  gtk/FilterBar.cc
  gtk/FreeSpaceLabel.cc
  gtk/MainWindow.cc
  gtk/MakeDialog.cc
  gtk/MessageLogWindow.cc
  gtk/Notify.cc
  gtk/PrefsDialog.cc
  gtk/RelocateDialog.cc
  gtk/Session.cc
  gtk/StatsDialog.cc
  gtk/SystemTrayIcon.cc
  gtk/Torrent.cc
  gtk/Utils.cc
  gtk/main.cc
  libtransmission/announcer-http.cc
  libtransmission/announcer-udp.cc
  libtransmission/announcer.cc
  libtransmission/blocklist.cc
  libtransmission/blocklist.h
  libtransmission/crypto-utils-ccrypto.cc
  libtransmission/crypto-utils-mbedtls.cc
  libtransmission/crypto-utils-openssl.cc
  libtransmission/crypto-utils-wolfssl.cc
  libtransmission/inout.cc
  libtransmission/ip-cache.cc
  libtransmission/makemeta.cc
  libtransmission/net.cc
  libtransmission/open-files.cc
  libtransmission/peer-io.cc
  libtransmission/port-forwarding-natpmp.cc
  libtransmission/port-forwarding-upnp.cc
  libtransmission/port-forwarding.cc
  libtransmission/rpc-server.cc
  libtransmission/rpcimpl.cc
  libtransmission/session-id.cc
  libtransmission/session.cc
  libtransmission/torrent-metainfo.cc
  libtransmission/torrent.cc
  libtransmission/tr-dht.cc
  libtransmission/tr-lpd.cc
  libtransmission/tr-strbuf.h
  libtransmission/tr-udp.cc
  libtransmission/utils.cc
  libtransmission/variant-json.cc
  libtransmission/variant.cc
  libtransmission/watchdir-inotify.cc
  libtransmission/watchdir-kqueue.cc
  libtransmission/watchdir.cc
  libtransmission/web.cc
  utils/create.cc
  utils/remote.cc
Labels: type:refactor, notes:none

#7479 fix: clang-tidy-20 warnings
  libtransmission/file-posix.cc
  qt/.clang-tidy
  qt/Application.cc
  tests/libtransmission/.clang-tidy
  tests/libtransmission/block-info-test.cc
  tests/libtransmission/completion-test.cc
  tests/libtransmission/dht-test.cc
  tests/libtransmission/file-piece-map-test.cc
  tests/libtransmission/ip-cache-test.cc
  tests/libtransmission/session-test.cc
  tests/libtransmission/subprocess-test.cc
  tests/libtransmission/timer-test.cc
Labels: scope:qt, scope:core, type:fix, scope:test, notes:none

#7048 feat: sequential download cmdline options in remote and daemon
  daemon/daemon.cc
  utils/remote.cc
Labels: scope:daemon, scope:remote, type:feat, semver:minor

#7069 refactor: use new `tr_variant` API for resume
  libtransmission/resume.cc
Labels: scope:core, type:refactor, notes:none

#7483 refactor: rename unreleased quarks to snake_case
  cli/cli.cc
  daemon/daemon.cc
  docs/Editing-Configuration-Files.md
  docs/rpc-spec.md
  gtk/Session.cc
  libtransmission/quark.cc
  libtransmission/quark.h
  libtransmission/resume.cc
  libtransmission/rpcimpl.cc
  libtransmission/session.h
  qt/Session.cc
  tests/libtransmission/rpc-test.cc
  utils/remote.cc
  web/src/prefs-dialog.js
  web/src/remote.js
Labels: scope:core, type:refactor, notes:none

#5038 feat: proxy support for web-connections
  docs/Editing-Configuration-Files.md
  libtransmission/quark.cc
  libtransmission/quark.h
  libtransmission/session.cc
  libtransmission/session.h
  libtransmission/web.cc
  libtransmission/web.h
Labels: scope:core, type:feat, semver:minor
